### PR TITLE
Update WL_example_3.sh to use NETCDF driver

### PR DESCRIPTION
**Pull request by PaulWessel**
Still does not work but at least it opens the file correctly.  More work needed, @joa-quim.

### CODE REVIEW

**Comment by joa-quim** [comment]
The failing case is not our fault at all. If, in `gmt_gdalread`, we change the two occurrences to
```
switch (GDALGetRasterDataType(hBand)) {
	case GDT_Byte:
	case 14:
```

than it works.

I wonder if we should not add this ugly hack since we do not have code to read complex grids from GDAL.

**Review by joa-quim — APPROVED** [review]

**Comment by PaulWessel** [comment]
So the data are complex in this case? Or do you worry we will crash on such a grid (which not that many would have, no)?

**Comment by joa-quim** [comment]
No, data is not complex but is misinterpreted to be so. The worry, is if we pass in a true complex layer and that change will make it seem as if it is a char. But that case would fail anyway because we don't (?) deal with complex grids read by GDAL:

**Comment by PaulWessel** [comment]
Yes, more important that a published WL_example_3 (presumably both .m and .sh) works again

**Comment by joa-quim** [comment]
The may work but result is wrong. Mirone is using an older GDAL and can read that layer just fine.

**Pull request merged**
