### PR TITLE
Merge README.CMake with README.md

### PR DESCRIPTION
**Pull request by remkos**
This addressed issue #45

### CODE REVIEW

**Comment by remkos** [comment]
Hi @joa-quim. Here's another approach: leaving README.md more or less the same and replacing README.CMake with Building_GMT_with_CMake.md linked from the former.

**Comment by remkos** [comment]
@joa-quim : You can see the rendered version here: https://github.com/GenericMappingTools/gmt/blob/master/Building_GMT_with_CMake.md

**Comment by joa-quim** [comment]
Yes, now that it is merged I can but before it seemed to be in a branch of yours that I could not find in the main page branches list. Probably just ignorance.

**Comment by leouieda** [comment]
> This welcome bot sometimes is a bit dumb. So now it's my first PR merge!

@joa-quim it's Remko's first PR. Note: the texts that the bot uses can be configured in the file `gmt/.github/config.yml` so we could have it say whatever we want (in case there is any GMT humor that you might want to introduce).

**Pull request merged**
