### PR TITLE
Recommendations for package maintainers

### LINKED ISSUE #1791: Migrate the packaging recommendations
Add the packaging recommendations (http://gmt.soest.hawaii.edu/projects/gmt/wiki/PackagingGMT) to BUILDING.md.

### PR DESCRIPTION
**Pull request by seisman**
I've copied the packaging recommendations from http://gmt.soest.hawaii.edu/projects/gmt/wiki/PackagingGMT. 

It definitely needs more improvements.

Close #1791

### CODE REVIEW

**Comment by seisman** [comment]
The idea of the packaging recommendations is to have a consistent package names and description among different package managers.

For the DCW data, most package managers use `dcw-gmt`, consistent with the tarball names `dcw-gmt-1.1.4.tar.gz`. However, Ubuntu uses `gmt-dcw`. 

For the GSHHG data, the package name is more diverse:

- `gshhg-gmt`, used by conda-forge, macports, also consistent with the tarball names `gshhg-gmt-2.3.7.tar.gz`
- `gshhg-gmt-nc4`, by Fedora/RHEL/CentOS
- `gmt-gshhg`, by Ubuntu/Debian
- `gshhg`, by fink

I think `dcw-gmt` and `gshhg-gmt` are the best names for these packages. Agree?

**Comment by PaulWessel** [comment]
Yes I agree.  These are data first (hence leading with dcw or gshhg) but formatted for GMT (hence the -gmt part).  These data area also packaged for other use (Shapefiles) that have nothing to do with GMT.

**Comment by seisman** [comment]
OK, this PR is almost done. Can you update the  description of the DCW data (the link is broken) and then review it?

**Comment by seisman** [comment]
> DCW-GMT is an enhancement to the original 1:1,000,000 scale vector
  basemap of the world available from the Princeton University Digital Map and Geospatial
  Information Center and from GeoCommunity at http://data.geocomm.com/readme/dcw/dcw.html.
  This data is for use by GMT, the Generic Mapping Tools.

I mean the link to Geocommunity. It's gone.

**Comment by PaulWessel** [comment]
OK, maybe just say "Information about DCW can be found on Wikipedia [https://en.wikipedia.org/wiki/Digital_Chart_of_the_World]

It is pointless to try to find a specific URL since nobody seems to maintain things for very long.

**Comment by PaulWessel** [comment]
I updated my DCW page to list the Wikipedia entry.

**Pull request merged**
