### PR TITLE
Fixes issues when plotting full moment tensor with big isotropic components

### LINKED ISSUE #661: psmeca plotting full moment tensors
Thank you for the sustained support of GMT. I have made some input files for testing plotting routines for full moment tensors. Examples, including figures and input files, can be found here:
https://github.com/carltape/compearth/blob/master/momenttensor/plot/gmt/beachball_plots/
This includes the test script lune_beachballs_min.csh

```
gmtset PAPER_MEDIA Custom_3.2ix7.7i PAGE_ORIENTATION portrait MEASURE_UNIT inch BASEMAP_TYPE plain TICK_LENGTH 0.0c FRAME_PEN 2p TICK_PEN 2p
psbasemap -JXi/6.72i -R-30/30/-90/90 -Ba10f5g10:" ":/a10f5g10:" ":wesn -G200 -K -V -X0.5 -Y0.5 > lune_ngeo_iplot2_lplot1_kplot1_min.ps
psmeca beachballs_ipts1_iref1_lune_psmeca -JXi/6.72i -R-30/30/-90/90 -Sm0.45/8p -L0.5p/0/0/0 -G255/0/0 -N -O -V >> lune_ngeo_iplot2_lplot1_kplot1_min.ps
```

which was run using GMT 4.5.3 and using a modified version of utilmeca.c. The output figure is included, and it is also attached here as
[lune_ngeo_iplot2_lplot1_kplot1_min_psmeca_custom.pdf](https://github.com/GenericMappingTools/gmt/files/3115880/lune_ngeo_iplot2_lplot1_kplot1_min_psmeca_custom.pdf)

The example, partially converted for GMT 5, is:

```
gmt gmtset PS_MEDIA Custom_3.2ix7.7i PS_PAGE_ORIENTATION portrait PROJ_LENGTH_UNIT inch MAP_FRAME_TYPE plain MAP_TICK_LENGTH 0.0c MAP_FRAME_PEN 2p MAP_TICK_PEN 2p
gmt psbasemap -JXi/6.72i -R-30/30/-90/90 -Ba10f5g10:" ":/a10f5g10:" ":wesn -G200 -K -V -X0.5 -Y0.5 > test.ps
gmt psmeca beachballs_ipts1_iref1_lune_psmeca -JXi/6.72i -R-30/30/-90/90 -Sm0.45/8p -L0.5p,0/0/0 -W0.5p,0/0/0 -G255/0/0 -N -O -V >> test.ps
```

This generates the file test.ps, which I have renamed and attached as 
[lune_ngeo_iplot2_lplot1_kplot1_min_psmeca_gmt5.4.5.pdf](https://github.com/GenericMappingTools/gmt/files/3115882/lune_ngeo_iplot2_lplot1_kplot1_min_psmeca_gmt5.4.5.pdf)

Comparison between the two pdf files reveals two main differences.
1. 14 beachballs are plotted incorrectly in GMT 5.4.5:
6 are all-white and should be all-red (top).
6 are all-red and should be all-white (bottom).
1 is all-white and should have some red (upper middle).
1 has its colors flipped (lower middle).

For the all-red and all-white beachballs, this means that the eigenvalues of the moment tensors are either all positive (red) or all negative (white). This would seem to be a straightforward check. I'm not sure what fix is needed for the other two beachballs.

2. For the beachballs plotted in GMT 5.4.5, the nodal lines are not plotted with the pen specification. (Except for the one double couple, at center.) This issue is much less significant compared with the first issue. It's possible that I need to fix the syntax, but I did not see how. (Plus, I don't see why the nodal lines would appear for one beachball but not the others.)

The correct plot was generated using a modified version of utilmeca.c, which can be found at the link at the top. It seems like this would be a better starting point than the current version of utilmeca.c. I have not tried to compile GMT 5.4.5 with the modified utilmeca.c to see how it works. Finally, in the repository above I have provided five additional sets of beachballs that would be useful for more comprehensive testing.

**System information**
* Operating system: Mac OS 10.13.6
* Version of GMT: 5.4.5

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

1. Fixes plotting full moment tensors with big isotropic component (see #661 for details) 
2. Add the example script in #661 
3. Fix -S syntax in code and documentations

As @carltape mentioned in #661,
> For the beachballs plotted in GMT 5.4.5, the nodal lines are not plotted with the pen specification. 

This PR fixes the nodal lines issue, but breaks some meca tests. 

If I understand it correctly, -L controls the plotting of nodal lines. If -L is not used, nodal lines are not plotted. In the original codes, L.active is set to true by default, but its value isn't used in meca_ps_tensor. In the revised codes, L.active is set to false by default.

@PaulWessel Can you help verify if this PR breaks the meca tests in a good way?

Closes #661.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Sure, just finished my run.  There seems to be several cases where the outside circle is not plotted, e.g., meca_09.sh right plot.  Neither module call uses **-W**_pen_ (which I read in the docs to control the outline of symbols), yet the ball on the left seems to have an outline?  Maybe **-Sm** sets the outline but **-Sa** does not?

BTW, maybe you can fix this thing in the psmeca.rst.  For **-W** it says

> This setting applies to -C, -L, -T, -p, -t, and -Fz, unless overruled by options to those arguments

but that should be

> This setting applies to -C, -L, -T, -Fp, -Ft, and -Fz, unless overruled by options to those arguments

**Comment by seisman** [comment]
In my mind, the expected behavior is:

- If none of -W, -L or -T is used, only the outside circle is plotted, using the default pen;
- If -W is used, only the outside circle is plotted, using the pen specified by -W;
- If -L is used, both outside circle and nodal lines are plotted, using the pen specified by -L
- If -T is used, the nodal lines for nodal planes are plotted, using the pen specified by -T. 

Is it correct?

**Comment by PaulWessel** [comment]
I think this makes since, speaking as someone who does not use the meca supplement.  I think you have the power to make those decisions as our only seismologist!

**Comment by seisman** [comment]
> * If none of -W, -L or -T is used, only the outside circle is plotted, using the default pen;
> * If -W is used, only the outside circle is plotted, using the pen specified by -W;
> * If -L is used, both outside circle and nodal lines are plotted, using the pen specified by -L
> * If -T is used, the nodal lines for nodal planes are plotted, using the pen specified by -T.

I tested psmeca in GMT 4.5.18 and found this is exactly what psmeca does in 4.5.18. Obviously, GMT 5 does it in a wrong way, and it's time to make it right.

The script below shows how psmeca works in this PR.

```bash
gmt begin psmeca-new png
gmt subplot begin 2x2 -Fs4i/2i -M0p -JX4i/2i -R-1/6/0/4 -B0
for option in "" "-W2p,black" "-L1p,blue -W2p,black" "-L1p,blue -T0/1p,gray"; do
    echo "1 2 0  4.319 37.28 145.8  6 0 0 -Sa ${option}" | gmt psmeca -Sa4c -M -Gred -Elightblue ${option} -c
    echo "4 2 0 0.961 0.204 -0.895 1.045 -0.307 0.716 2 0 0 -Sm ${option}" | gmt psmeca -Sm4c -M -Gred -Elightblue ${option}
done
gmt subplot end
gmt end
```

The generated plot is:

image

The double couple beachball (-Sa) in the lower right panel looks weird at first sight, but it's consistent with the GMT4 behavior. I don't know why it was designed this way, but it's acceptable to me. So I prefer not to change it.

**Known bug**:

If you zoom in the beachball in the upper right panel, you'll see that it's not perfect for thick outlines.
This is because a beachball is usually plotted in three steps (see figure below):
image

Do you have any idea to fix it?

**Comment by PaulWessel** [comment]
I agree with this - it is most likely I broke something when porting to GMT 5 since I had to undo a lot of rouge lower-case options (**-t -r -s** etc.) that infringed on GMT common options.  As for the thick line etc.  There are only two ways I think:

1. You want to fat outline, so draw that at the end instead of at the beginning
2. You reduce the symbol radius after step 1 by half the pen width and then it should match up.

Perhaps number two is easier to do.

**Comment by seisman** [comment]
I fix the fat line issue by plotting the step 1 circle twice (fill-only at the beginning, and outline-only at the end).

**Comment by PaulWessel** [comment]
I want to build and run tests but need to leave now for errands etc.  I will try later tonight (it is a holiday in Hawaii today).

**Comment by PaulWessel** [comment]
The tests looks pretty good, just tiny changes to outlines that show up magenta.  Is that all you see as well? Let me know and I can approve in1 hour or we can get @joa-quim to approve.

**Comment by seisman** [comment]
Yes, tiny changes only.

This PR breaks several tests. How can I regenerate the PS files as the new baseline for future testing? Is `gmt set -Du` enough?

**Comment by PaulWessel** [comment]
I usually run make check and then copy the nes ps files from the build tree
to the place they should go

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Pull request merged**
