### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR updates the ex32 baseline image and increases the tolerance for cartellipse.sh.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
@PaulWessel, could you please check out this branch, run `dvc pull`, and test if those two failures now pass for you?

**Comment by PaulWessel** [comment]
Hm, no.  I am on the test_updates branch and have built and run the test (after dvc pull) and it still reports the old limit?

/opt/local/bin/gm compare: image difference exceeds limit (0.00352256 > 0.003).

**Comment by PaulWessel** [comment]
It is clip_ellipse.sh that is failing, not cartellipse.

**Comment by meghanrjones** [comment]
> It is clip_ellipse.sh that is failing, not cartellipse.

Oops, fixed now.

**Comment by PaulWessel** [comment]
Yep works, I only have testsuite and my gspline?5 now.

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
