### PR TITLE
Fix sharedir path

### PR DESCRIPTION
**Pull request by PaulWessel**
Work in progrress on this.

### CODE REVIEW

**Comment by seisman** [comment]
@leouieda Can you check if this commit works in conda builds.

**Comment by leouieda** [comment]
Running at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=43123 I'll post here when it finishes building

**Comment by leouieda** [comment]
OK, all checks pass on all 3 OSs. This is good to go on the conda side.

**Comment by seisman** [comment]
This PR is OK to me. The only tiny issue is that the bundle will still try to search Paul's path first. Of course, Paul's path doesn't exist in users' computer, then the bundle skip it to the correct path.

**Comment by PaulWessel** [comment]
Maybe we can make this better after rc1 is done.

**Comment by leouieda** [comment]
:+1: I'm in favor of that

**Comment by seisman** [comment]
Yes, I agree. I also don't think my PR is good enough.

**Pull request merged**
