### PR TITLE
Improve gmtmath -Q behavior

### PR DESCRIPTION
**Pull request by PaulWessel**
See #5348 for background and explanations.  This PR implements those suggestions to make it simpler to select the output unit or have no unit conversion on output, as well as improved documentation as to what is happening.  Closes $5348.

### CODE REVIEW

**Comment by Esteban82** [comment]
With the division it works. however, when I try MUL all the result were 1/2.54 or 1/2.54<sup>2</sup>

```
gmt math -Qi 1c 1c MUL = 0.155
gmt math -Qn 1c 1c MUL = 0.155
gmt math -Qc 1c 1c MUL = 0.3937
gmt math -Q  1c 1c MUL = 0.3937
```

Only when the units are in inches I get 1

`gmt math -Qi 1i 1i MUL = ` 1
`gmt math -Qn 1i 1i MUL = `1

**Comment by PaulWessel** [comment]
Yes, and can't help that.  If you specify units then GMT will convert them to inches.  Now you have 1/2.54 inside.  If you dont want that conversion, dont give units.

**Comment by Esteban82** [comment]
So, should I approve this feature, right? And then avoid using units? Maybe a warning message could be add in the docs.

**Comment by PaulWessel** [comment]
Give me a minute to update the docs and if you think they are clear then you can approve.

**Comment by PaulWessel** [comment]
Should now make it clear that using units on input gives internal INCHES, and if that is not desired then do not use units.  See new section in man page called _Scalar math with units_.

**Review by Esteban82 — APPROVED** [review]

**Pull request merged**
