### PR TITLE
Update gmt.conf.rst

### PR DESCRIPTION
**Pull request by Esteban82**
Fix typos and replace pi for π.

### CODE REVIEW

**Comment by Esteban82** [comment]
Should `[default is %.12g].` be deleted in the descripition of FORMAT_FLOAT_MAP and FORMAT_FLOAT_OUT?

**Review by PaulWessel — APPROVED** [review]
Thanks.  I guess pi works like that - great.  I thought we needed :math: etc but apparently not.

**Comment by PaulWessel** [comment]
Hm, I think not.  The see FORMAT_GEO_OUT is for ddd:mm etc and not floating points.  However, for FORMAT_FLOAT_OUT it lists the default twice - perhaps the first one should be removed.

**Comment by Esteban82** [comment]
I have a doubt. 

For example in `FORMAT_FLOAT_MAP` when it says `see FORMAT_GEO_OUT. [default is %.12g].` 

The default value is for FORMAT_FLOAT_MAP or FORMAT_GEO_OUT?

The first time I read it I thought that was for GEO_OUT but now I think it is for FLOAT_MAP.

**Comment by PaulWessel** [comment]
Yes, it is for float_out - sorry it is bit unclear.

**Comment by Esteban82** [comment]
> Yes, it is for float_out - sorry it is bit unclear.

Ok, so I will edit the text to make it clear.

**Review by PaulWessel — APPROVED** [review]

**Comment by Esteban82** [comment]
I can't merge it (because there is a failing check).

**Pull request merged**
