### PR TITLE
Let movie open and play movie if gmt end show is used

### LINKED ISSUE #7455: Let movie main.sh handle show to open the movie
In modern mode script we can end with

`gmt end show`

and then the plot opens up in the default viewer.I learned today via @Esteban82 that **ffmpeg** is one of many ff tools; the full list is

`ffmpeg	ffprobe		ffplay`

So a proposal would be if main.sh ends with `gmt end show` then once movie assembles the mp4 movie it would call **ffplay**, or perhaps just "open" like we do for images? Open movie.mp4 works fine on macOS (opens QuickTime player) - how about Windows and Linux?

### PR DESCRIPTION
**Pull request by PaulWessel**
If the _mainscript_ ends with

`gmt end show`

we will use **gmt docs** to open and play the movie after it has been assembled.  Closes #7455.

### CODE REVIEW

**Comment by Esteban82** [comment]
It works but I got a lot of messagges related to vlc on the terminal including bold and red letters (see screen capture below) that might looks scary for some users. Is it possible to avoid that?

```
movie [NOTICE]: Running: ffmpeg -loglevel warning -f image2 -framerate 12 -y -i "/home/federico/Github/Esteban82/Pruebas_Privadas/Bug_Movie_Title/1/1_%03d.png" -vcodec libx264  -pix_fmt yuv420p 1.mp4
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
federico@loki:~/Github/Esteban82/Pruebas_Privadas/Bug_Movie_Title$ [0000564a7e271820] main libvlc: Ejecutar vlc con la interfaz predeterminada. Use «cvlc» para usar vlc sin interfaz.
[00007f920c004900] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
[00007f920c004900] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007f9214046790] main video output error: video output creation failed
[00007f9228c022f0] main decoder error: failed to create video output
[00007f920c02b4d0] gl gl: Initialized libplacebo v4.192.1 (API v192)
[00007f9228c022f0] avcodec decoder: Using G3DVL VDPAU Driver Shared Library version 1.0 for hardware decoding
[h264 @ 0x7f9228c42fc0] Failed setup for format vdpau: hwaccel initialisation returned error.
[00007f9228c022f0] avcodec decoder error: existing hardware acceleration cannot be reused
[00007f920c02b4d0] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
[00007f920c02b4d0] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007f925c001b70] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
[00007f925c001b70] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007f92140b6ff0] main video output error: video output creation failed
[00007f9228c022f0] main decoder error: failed to create video output
[00007f925c017580] gl gl: Initialized libplacebo v4.192.1 (API v192)
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
```

Screencapture:

image

**Comment by Esteban82** [comment]
Also, if I asked for a a master frame (`-Ml,png`),  GMT tries and fails to open it.

image


Full script

```
#!/usr/bin/env bash

cat << EOF > main.sh
gmt begin
	echo \${MOVIE_FRAME} | gmt text -R0/1/0/1 -JX10c -F+f200p+cCM -B0 -X0 -Y0
gmt end show
EOF
gmt movie main.sh -N1 -T100 -C480p -Fmp4 -Zs -D12 -Ml,png
```

**Comment by Esteban82** [comment]
> Is it possible to avoid that?

Yes, with this:

`open 1.mp4 2> /dev/null
`

**Comment by PaulWessel** [comment]
@Esteban82, see if this works now for opening both master frame and the movie.  I have fixed the path and now explicitly call gmt docs on the master png.  Before, I relied on just the gmt end show in the script taking care of it, but there is the issue of moving the plot up one directory.

Let me know about your warnings after this commit.

**Comment by Esteban82** [comment]
> @Esteban82, see if this works now for opening both master frame and the movie. I have fixed the path and now explicitly call gmt docs on the master png. Before, I relied on just the gmt end show in the script taking care of it, but there is the issue of moving the plot up one directory.

@PaulWessel it worked. Both files were open.

I wonder if it is a good idea to open both files. I think it might be a bit annoying. I wonder if it would be better to open only the mp4 only. And only open the master frame when a video is not requested.

**Comment by PaulWessel** [comment]
Might also be annoying to some if we _don't_ open both...
Maybe some modifier somewhere? E.g., **-F**.....[**+v**] for view movie.  That way we could use a **gmt end show** presence to view master and **+**v to view movie, even if manuscript does to have show.  Cleaner I think, and accommodates both schemes.

**Comment by PaulWessel** [comment]
I think this is the better solution and I will implement it.

**Comment by PaulWessel** [comment]
Try this @Esteban82 - works for me and the +v is a better solution for the video.

**Comment by PaulWessel** [comment]
Got me thinking that having to add/remove show from a script is not a very clean way to do this.  Thus **+v** is good.  But we could also add **+v** as modifier to **-M** and then we have full control from the command line with no need to modify scripts.  What you think?

**-M**[_frame_|**f**|**m**|**l,**][**+v**]

? I can even make it backwards compatible if **show** is in the script.

**Comment by PaulWessel** [comment]
Sorry, not sure what I copied.  -M is

[-M][frame],[format][+rdpu][+v]

**Comment by Esteban82** [comment]
Yes, I think it is better to have a modifier in the **gmt movie** command (to open both files).

**Comment by PaulWessel** [comment]
OK, +v in -M as well as backwards gmt end show check both works. Give it a try and then we can wrap this up.

**Comment by Esteban82** [comment]
I am getting an error

```
NULL @ 0x55a54486da80] Unable to find a suitable output format for ',png'
,png: Invalid argument
movie [ERROR]: Running FFmpeg conversion to MP4 returned error 256 - exiting.
free(): invalid pointer
play.sh: línea 8: 35611 Abortado                (`core' generado) gmt movie main.sh -Ntitle -T10 -C480p -Zs -D12 -Ml,png -Fmp4
```

I think that you it was in the last commit (Add +v to -M)

**Comment by PaulWessel** [comment]
Strange, I do

`gmt movie main.sh -N1 -T100 -C480p -Fmp4+v -Zs -D12 -Ml,png+v`

and it works fine for me.  Please double-check.  Those are error messages from **ffmpeg** and not **movie**.  I only get the notice:

`movie [NOTICE]: Running: ffmpeg -loglevel warning -f image2 -framerate 12 -y -i "/Users/pwessel/1/1_%03d.png" -vcodec libx264  -pix_fmt yuv420p 1.mp4`

and there are no ,png strings anywhere.

**Comment by Esteban82** [comment]
> gmt movie main.sh -N1 -T100 -C480p -Fmp4+v -Zs -D12 -Ml,png+v

This works for me.

**Comment by Esteban82** [comment]
I run this script. The movie command works. 

The second doesn't. It tries to run the below command. I think that the **,png** is wrong. I try without it and I got the movie.

ffmpeg -loglevel warning -f image2 -framerate 10 -y -i "/home/federico/Github/Esteban82/Pruebas_Privadas/Branch_movie-play/movie-play1/movie-play1_%01d.png" -vcodec libx264 **,png** -pix_fmt yuv420p movie-play1.mp4


### Full script
```
#!/usr/bin/env bash

cat << EOF > main.sh
gmt begin
	echo \${MOVIE_FRAME} | gmt text -R0/1/0/1 -JX10c -F+f200p+cCM -B0 -X0 -Y0
gmt end
EOF
gmt movie main.sh -Nmovie-play1 -T5 -C480p -Z  -D10 -Ml,png -Fmp4 
gmt movie main.sh -Nmovie-play2 -T5 -C480p -Zs -D10 -Fmp4 -Ml,png  
```

### Terminal output
```
bash movie-play.sh 
movie [NOTICE]: Running: ffmpeg -loglevel warning -f image2 -framerate 10 -y -i "/home/federico/Github/Esteban82/Pruebas_Privadas/Branch_movie-play/movie-play1/movie-play1_%01d.png" -vcodec libx264 ,png -pix_fmt yuv420p movie-play1.mp4
[NULL @ 0x559d3f07f000] Unable to find a suitable output format for ',png'
,png: Invalid argument
movie [ERROR]: Running FFmpeg conversion to MP4 returned error 256 - exiting.
free(): invalid pointer
movie-play.sh: línea 8: 56700 Abortado                (`core' generado) gmt movie main.sh -Nmovie-play1 -T5 -C480p -Z -D10 -Ml,png -Fmp4
movie [NOTICE]: Running: ffmpeg -loglevel warning -f image2 -framerate 10 -y -i "/home/federico/Github/Esteban82/Pruebas_Privadas/Branch_movie-play/movie-play2/movie-play2_%01d.png" -vcodec libx264  -pix_fmt yuv420p movie-play2.mp4
```

**Comment by PaulWessel** [comment]
Ok think I get it; work on that after dinner

**Comment by PaulWessel** [comment]
OK, I had made a mistake by switching some pointers and that cam to bite me in parsing -F.  Now should work - I was able to wee the same error you had and now it is gone.

**Comment by Esteban82** [comment]
Now it works. 

But I am still getting a lot of scary messagges in the terminal.

**Comment by PaulWessel** [comment]
OK, can you

1. run it with -Vd and see what gmt docs actually runs (the "open" command it selects)
2. paste in those messages here
3.

**Comment by PaulWessel** [comment]
I am suspecting it picks ffplay and it has a nasty extensive verbose setting, so then we will need to fix that.

**Comment by PaulWessel** [comment]
Hm, could you post your movie-play.sh again.  It says line 18

`movie-play.sh: línea 18: dev/null: No existe el archivo o el directorio`

but there is no dev/null, only /dev/null, so something funny is happening but there is no GMT error?

**Comment by PaulWessel** [comment]
```
docs [DEBUG]: Opening file:///home/federico/Github/Esteban82/Pruebas_Privadas/Branch_movie-play/1.mp4 via xdg-open
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
```

This seems to indicate that xdc-open is not fully configured somewhere (there should be a hidden file with file type pointing to a suitable application).  I found this [link](https://bugs.kde.org/show_bug.cgi?id=442721) about KDE.

**Comment by Esteban82** [comment]
> Hm, could you post your movie-play.sh again. It says line 18
> 
> `movie-play.sh: línea 18: dev/null: No existe el archivo o el directorio`
> 
> but there is no dev/null, only /dev/null, so something funny is happening but there is no GMT error?

Sorry, I had an extra command on my script. Nothing related to GMT. Forget about this.

**Comment by PaulWessel** [comment]
Does that mean you can approve this PR?

**Comment by Esteban82** [comment]
Sorry, I couldn't test again.

**Review by Esteban82 — APPROVED** [review]

**Comment by Esteban82** [comment]
> ```
> docs [DEBUG]: Opening file:///home/federico/Github/Esteban82/Pruebas_Privadas/Branch_movie-play/1.mp4 via xdg-open
> kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
> kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
> VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
> ```
> 
> This seems to indicate that xdc-open is not fully configured somewhere (there should be a hidden file with file type pointing to a suitable application). I found this [link](https://bugs.kde.org/show_bug.cgi?id=442721) about KDE.

Thanks. This fix the warning messages.

**Pull request merged**
