### PR TITLE
Add AUTHORSmd file draft

### PR DESCRIPTION
**Pull request by PaulWessel**
List of who is who and various acknowledgements.

### CODE REVIEW

**Comment by abanbj** [comment]
I see an 'Andreas B.' in there. Could you please give an example of one of his bug reports?

**Comment by PaulWessel** [comment]
E.g., http://gmt.soest.hawaii.edu/boards/1/topics/8203?r=8208#message-8208

**Comment by abanbj** [comment]
Alright!

**Comment by seisman** [comment]
http://gmt.soest.hawaii.edu/projects/gmt/wiki/Volunteers 

Who are these volunteers? Do you need to add them to the list?

**Comment by PaulWessel** [comment]
They would go into the last section of AUTHORS.md; in fact, most of them are there already but I will add a few more.

**Pull request merged**
