### PR TITLE
Need to read GSHHGS nodes if -A modifiers +l or +r are used

### PR DESCRIPTION
**Pull request by PaulWessel**
This addresses issue #231.

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel Also commit this change to 5.4 branch?

**Comment by PaulWessel** [comment]
Please do as I don't know how...

**Comment by seisman** [comment]
@PaulWessel I have cherry-picked this commit and applied it to 5.4 branch.

**Comment by PaulWessel** [comment]
Mahalo!

**Pull request merged**
