### PR TITLE
New -B modifier +i for internal annotations

### PR DESCRIPTION
**Pull request by PaulWessel**
For some projections, such as azimuthal or polar with 360 longitude range or global projections with 180 latitude range and where the poles are points, selected annotations may be excluded since the required axis along which to plot them do not exist.  This new modifier will force additional annotations inside the map frame along the specified parallel of meridian.

### CODE REVIEW

**Comment by PaulWessel** [comment]
So far I have implemented the case for azimuthal/polar internal annotations.  First case is a polar (r-theta) map (`gmt basemap -R0/360/0/10 -JP6i -Bxafg30 -Byafg -B+i90 -png map1`):

map1

Next up is a S polar map (`gmt basemap -R0/360/-90/-30 -JA0/-90/6i -Bxafg30 -Bya15g15+f -B+i-60 -png map2`): 

map2

And finally a N polar maps (`gmt basemap -R0/360/30/90 -JA0/90/6i -Bxafg -Bya15g30+f -B+i60 -png map3`):

map3

Given this, time to ask some questions of @joa-quim and @seisman before I move along:

1. The annotations are offset from the exact location by MAP_ANNOT_OFFSET.  This seems reasonable to me; what you you think?
2. There are no tick marks or other symbols being placed at the exact (lon/lat) spots. Is it important to mark the spots? Since there is no axis drawn, it seems odd to draw ticks. Could place a small grid cross there?
3. There is no painting to white out gridlines that go through the annotations.  One possibility is to say if **+g**_fill_ was used in the frame **-B** (to paint the inside of the map) then perhaps it makes sense to paint the bounding box for each label that way.  This means you could use **+g**_white_ to get the effect as well.
4. I have included the central annotation (r = 0) but excluded the perimeter annotation.  OK with this?

**Comment by joa-quim** [comment]
1 - I would rather not have the MAP_ANNOT_OFFSET but perhaps have it with respect to the theta circles. See [this Matlab plot](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/e5ac47b2-4a80-11e4-9553-005056977bd0/ccdd7449-1c32-43a8-a5a2-f833b3906d9d/images/screenshot.jpg)

2 - Not sure what's better. Perhaps no ticks.

3 - Crossing annotations with lines is not pretty but we cannot paint to avoid it because it would also be painting everything else that is bellow.

4 - Perhaps only annotate r_min if r_min is not zero (donuts)?

**Comment by PaulWessel** [comment]
One thought is that if you do draw the gridlines then having a corner justification and annotation offset would allow the annotations to miss the gridlines for most cases.

**Comment by PaulWessel** [comment]
By using corner justification we avoid the problem with gridline overprinting the annotations:

map3

I think this beats the other arrangement above, no? I like it and I am coding it (!).

**Comment by PaulWessel** [comment]
Work that remains to be done:

1. Make it also work for the polar r-theta when **+f**, **+x**, **+a**, or **+t** are used, and add the azim_radial.sh test
2. Implement for parallel as well and add test global_parallel.sh.

**Comment by seisman** [comment]
It seems **+i** is a modifier for frame settings, why is that?
In your first example, `gmt basemap -R0/360/0/10 -JP6i -Bxafg30 -Byafg+i90 -png map1`, does this one make more sense? **a** in **-By** controls the annotation intervals, and **+i90** controls the locations.

**Comment by PaulWessel** [comment]
The new feature is an _internal axis_ separate from the axes specified via -BWSNEZ.  That is why it should go with the frame settings.  It is not an axis setting.

**Comment by seisman** [comment]
OK, I take your point.

**Comment by PaulWessel** [comment]
Wrapped up radial annotations for polar r-theta projection, with new test azim_radial.sh. Thus only the longitude annotations for global projections remain. However, two new failures show up: GMT_App_F_stand+_iso+.sh I have seen before and fixed but cannot recall what the hell it is again - must rediscover.  The other is GMT_eckert4.sh which makes no sense.  It runs fine by itself but does not produce anything when run via ctest.  All the new code is under an if-test that is not triggered by that script so a mystery.  If anyone has any hints please let me know.

azim_radial

**Comment by joa-quim** [comment]
Just noticing one thing. For the azimuthal example the annotations are above the line they are annotating but for the r-theta they are below the line.

Question. Being **-i** a new axis can we draw only de annotations but not the axis (like in the Matlab example)?

**Comment by seisman** [comment]
`GMT_eckert4.sh` fails because I used `-pdf` for the one-liner command. I've fixed it and committed directly to the master branch.

**Comment by PaulWessel** [comment]
Answering @joa-quim:

1. I have fixed the azimuthal so it is the same layout as the r-theta cases
2. No axis is drawn, just annotations, and if gridlines are not activated or goes through the selected meridian then I draw small grid crosses.

**Comment by PaulWessel** [comment]
OK, the longitude annotations are much easier and looks like below.  Let me know if you think I should skip the first annotation as well (I am skipping the last).

azim_global

**Comment by PaulWessel** [comment]
BTW, here is the updated azim_polar.sh output:

azim_polar

**Comment by PaulWessel** [comment]
I have removed the WIP and opening this for review.

**Comment by seisman** [comment]
The *internal* annotations don't use minus symbols correctly.
image

**Comment by joa-quim** [comment]
:scissors: to long minus. They waste valuable space.

**Comment by PaulWessel** [comment]
Seriously!?  There is minus and there is hyphen.  We have spent lots of time getting the character sets stuff working correctly.  Not changing that.

**Comment by joa-quim** [comment]
I know we won't be changing it but you may remember I never liked the original change. Those math minus are just too long. The hyphen char looks much better. But not arguing we should go back.

**Comment by seisman** [comment]
Something wrong with the CI. No need to wait for it.

**Pull request merged**
