### PR TITLE
Add example in xyz2grd

### PR DESCRIPTION
**Pull request by abanbj**
Add man page example in ``xyz2grd.rst``. I see that my old commit also is included in this PR.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Could you remove your old commit from this one since those changes are already in master?

**Comment by abanbj** [comment]
Will try - not fluent in github yet.

**Comment by PaulWessel** [comment]
Likewise...

**Comment by seisman** [comment]
@abanbj You need to rebase your add-example-in-xyz2grd with gmt's master branch.

Assuming that you have a local copy and have added the gmt official repo as a remote repo and named it as upstream. You can follow these steps to rebase your branch:

```
git fetch upstream master   # fetch the latest master branch from upstream
git checkout add-example-in-xyz2grd  # switch to your branch
git rebase upstream/master   # rebase your branch with gmt's master branch
# push your local branch to your github repo
# you need -f option to force pushing, since rebasing changed the commit history of the branch
git push -f                   
```

**Comment by abanbj** [comment]
Thank you for helping me out @seisman. Made a new PR!

**Pull request closed without merging**
