### PR TITLE
pswiggle longopts adjustments

### LINKED ISSUE #6991: pswiggle longopts adjustments
**Description of the desired feature**
Adjust pswiggle longopts to better match GMT.jl

**Are you willing to help implement and maintain this feature?** Yes

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**
Adjust pswiggle longopts to better match GMT.jl

Fixes #6991

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
-F is to set a frame (filled, outlined, shaded, etc) behind the scale.  Joaquim's framepen makes no sense since it has nothing to do specifically with pen.  I would think _scalepanel_ is better since pen and fill etc are all modifiers.  Or perhaps just --panel is even better.

**Comment by rbdavis** [comment]
> -F is to set a frame (filled, outlined, shaded, etc) behind the scale. Joaquim's framepen makes no sense since it has nothing to do specifically with pen. I would think _scalepanel_ is better since pen and fill etc are all modifiers. Or perhaps just --panel is even better.

Actually, framepen was my string, not Joaquim's. I chose it because of the man page's reference to MAP_FRAME_PEN. If you want --panel instead just LMK and I will change it. This occurs in at least one other module as well as I recall.

**Comment by PaulWessel** [comment]
Yes in basemap as well.

**Comment by rbdavis** [comment]
basemap has not been longopted yet. I just double-checked, turns out I was 
referring to pscoast.

Do you want me to change --framepen to --panel in both pscoast and 
pswiggle?

**Comment by PaulWessel** [comment]
Yes please, that is what -F does (sets a panel which has lots of attributes given by modifiers)

**Comment by joa-quim** [comment]
GMT.jl uses ``box`` for the several modules that have -F

**Comment by PaulWessel** [comment]
> GMT.jl uses `box` for the several modules that have -F

Yes, but panel is a better word for what it is.

**Comment by joa-quim** [comment]
I knew there had to be a reason to have choose ``box`` instead of ``panel``.
``panel`` is already taken by **-c**

**Comment by PaulWessel** [comment]
thanks, We will give this a think.

**Pull request merged**
