### PR TITLE
Better check for earthtide and block* grid output selections

### PR DESCRIPTION
**Pull request by PaulWessel**
This should allow externals to use -Gfile to write directly to file.  Hopefully, @joa-quim can check if this works as expected now.

### CODE REVIEW

**Comment by joa-quim** [comment]
Nope, this doesn't work;
```
earthtide(G="lixo.grd")
```
still returns the Grid object to Julia and doesn't write it to disk.

**Comment by PaulWessel** [comment]
Can you tell me what exactly is the command passed to GMT_Call_Module in this case?

**Comment by joa-quim** [comment]
earthtide  -Cz -Glixo.grd

**Comment by PaulWessel** [comment]
Think this will fix it though.  In your case k remained 1 so it added -G?.

**Comment by joa-quim** [comment]
No, it doesn't. You can check it with Matlab too. This  returns instead of writing
```
gmtmex('earthtide -Cx -Glixo.grd')
```
It does work though if no **-C** is specified

**Comment by PaulWessel** [comment]
OK, and now fell into your typical trap (cooking).  So tomorrow.

**Comment by PaulWessel** [comment]
Working on this now - see the problem and will fix shortly.

**Comment by PaulWessel** [comment]
Problem was that the -C check mean the -G was not done (else if).  Now we do -C, and then we do -G etc.  Now, k ends up being zero and it works for me.  Please give it a spin, @joa-quim.

**Comment by PaulWessel** [comment]
I think we should have **earthtide** fill out the z unit info correctly . Right now it says 

```
lixo.grd: Remark: 
lixo.grd: z_min: -0.0772267207503 z_max: 0.0775824487209 name: z
```

i.e., no information on what the units are (meters?) and no remark that this is x-component of deformation (only inferred via command -Cx) and name probably should be "x/east tie"?  I can do this if you can confirm the units.

**Comment by joa-quim** [comment]
Yes, units are meters.

**Review by joa-quim — APPROVED** [review]
OK, my tests pass now. Also for the blocks

**Pull request merged**
