### PR TITLE
pssac longopts implementation

### LINKED ISSUE #7000: pssac longopts
**Description of the desired feature**
Add longopts to pssac

**Are you willing to help implement and maintain this feature?** Yes

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**
Add pssac longopts support. Note there was no GMT.jl module for comparison AFAIK.

Fixes #7000

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Fine with me but since this is DongDong's baby you may want to see if pyGMT has wrapped it and if so what words they chose.

**Comment by rbdavis** [comment]
> Fine with me but since this is DongDong's baby you may want to see if pyGMT has wrapped it and if so what words they chose.

How do I do that, i.e., check pyGMT? I tried before (several weeks ago) but could not find anything. I'm sure I was looking in the wrong places, but will most likely have no better luck this time without some guidance.

**Comment by joa-quim** [comment]
I don't think ``pssac`` has been wrapped but you can see the wrapped modules in https://www.pygmt.org/v0.6.0/api/ 
Each man page tells the longoption names for the wrapped options.

**Comment by rbdavis** [comment]
Thanks Joaquim.

I'm probably being stupid here. I see an API Reference, but nothing that 
looks like a manual page section. And in any case, I see nothing anywhere 
that looks like it relates to pssac (or sac). Can you give me a specific 
link to a page showing the pssac (or sac) strings?

**Comment by joa-quim** [comment]
I don't see a wrap of ``pssac`` either but that page (the should be https://www.pygmt.org/v0.7.0/api/) has links to man pages in first column of each table.

**Pull request closed without merging**
