### PR TITLE
Long-options support for movie/grdinterpolate/psevents/seismodules.

### LINKED ISSUE #6965: long-options support for movie/grdinterpolate/psevents/seis
**Description of the desired feature**

long-options support for movie/grdinterpolate/psevents/seis

**Are you willing to help implement and maintain this feature?** Yes

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**

Long-options support for movie/grdinterpolate/psevents/seismodules.

Sorry this is another multi-module PR, it should be the last one. (It was already in progress and I would have made more of a mess if I'd tried to split it up.) I will try to keep future long-option PRs to a single module where possible.

Note that there are interdependencies between psevents.c and psmeca.c/pscoupe.c, as the former requires specific knowledge of the latter's option strings.

There is also one unexplained change in movie.c (lines 1784 against line 1830, see below) that seems to have crept in somehow due to some git mis-synchronization, I suppose. Please correct as appropriate.

Fixes #6965

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
local static variables are not thread safe.  Please move ZSlongopt into the struct CTRL_PSEVENTS Ctrl so it is allocated with the rest, and you will have to pass it of the pointer to the struct to any function that needs access.

**Comment by PaulWessel** [comment]
Oh I forgot: The change in movie was done ~1 week ago so remember you should always merge master into your branch to pick up any changes since you started working on the branch, otherwise we end up reverting things unintentionally.  That line 1784 should have the -1 in it - that was a bug fix.  Please add taht back in to your branch before merging.

**Comment by joa-quim** [comment]
I note also that there barely any longoption name that is common to the those in GMT.jl. This is not *sustainable*

**Comment by rbdavis** [comment]
> local static variables are not thread safe. Please move ZSlongopt ...

Will do, was not aware of this issue.

**Comment by rbdavis** [comment]
> Oh I forgot: The change in movie was done ~1 week ago so remember you should always merge master into your branch to pick up any changes since you started working on the branch, otherwise we end up reverting things unintentionally. That line 1784 should have the -1 in it - that was a bug fix. Please add taht back in to your branch before merging.

Will restore as directed, sorry about that. I did do a pull on master right before beginning work on movie (about a week ago as you said). If you can explain to me how to do a merge on my system (which branch, which git command, etc.) I'll be happy to do that.

**Comment by rbdavis** [comment]
> I note also that there are barely any longoption names common to the those in GMT.jl. This is not _sustainable_

This is the first I've heard of GMT.jl. I'm happy to make these new strings conform to others where possible, but I need to know what those pre-existing strings are. Also, this file does not appear to be part of what I've downloaded from the master branch onto my system. Where is GMT.jl? And is there anything else I should be looking at?

**Comment by PaulWessel** [comment]
I thought I had mentioned this, but anyway.  GMT/Julia is at https://github.com/GenericMappingTools/GMT.jl and PyGMT is at https://github.com/GenericMappingTools/pygmt.

**Comment by joa-quim** [comment]
Some more background. GMT.jl exists since ~2014-2015 and started to expand to use long options around 2016. PyGMT came later and also started to use long options but it doesn't yet wrap all GMT modules nor all the options in a given module. There is no full compliance between GMT.jl and PyGMT but in large most of the options names are the same (I've not done a full comparison though). Another difference between the two is that PyGMT is more strict but admitting only one name whilst GMT.jl accepts some aliases for the same option.

Knowing what GMT.jl uses as longoptions is easy. Just type ``gmthelp(module_name)`` or ``? module_name`` in the Julia REPL. The info between these two is not exactly the same because the ``gmthelp(...)`` intends to show all supported names (even the non-documented ones) but fails some times.

**Comment by rbdavis** [comment]
> Some more background. GMT.jl exists since ~2014-2015 and started to expand to use long options around 2016. PyGMT came later and also started to use long options but it doesn't yet wrap all GMT modules nor all the options in a given module. There is no full compliance between GMT.jl and PyGMT but in large most of the options names are the same (I've not done a full comparison though). Another difference between the two is that PyGMT is more strict but admitting only one name whilst GMT.jl accepts some aliases for the same option.
> 
> Knowing what GMT.jl uses as longoptions is easy. Just type `gmthelp(module_name)` or `? module_name` in the Julia REPL. The info between these two is not exactly the same because the `gmthelp(...)` intends to show all supported names (even the non-documented ones) but fails some times.

Thanks Joaquim. Stupidity factor here, though, as I have no idea what is Julia REPL, nor how to obtain or run it. Any further hints?

**Comment by joa-quim** [comment]
``REPL`` (Read Evaluate Print Loop) is a new slang for ``shell``. As for installing GMT.jl and its docs, see the link Paul posted above (same for PyGMT).

**Comment by joa-quim** [comment]
And for installing Julia in other than Windows I recommend https://github.com/JuliaLang/juliaup

**Comment by rbdavis** [comment]
> And for installing Julia in other than Windows I recommend https://github.com/JuliaLang/juliaup

Thanks. Any reason not to just use MacPorts to install Julia? (Monterey on M1)

**Comment by joa-quim** [comment]
Don't know. If it works ... It's not uncommon to see comments on how Homebrew has screwed.
There is also https://julialang.org/downloads/ but ``juliaup`` takes care of adding to the path and knows how to update.

**Comment by rbdavis** [comment]
> Don't know. If it works ... It's not uncommon to see comments on how Homebrew has screwed. There is also https://julialang.org/downloads/ but `juliaup` takes care of adding to the path and knows how to update.

OK, thanks. I'll try MacPorts first as I get many other external packages from there, easier to just add this to my list of must-have packages. If it makes a mess I'll throw it out and go the other route. I've never used Homebrew -- started with MP before it was around and never heard of a good enough reason to switch.

**Comment by joa-quim** [comment]
Another thing. I'm blocked to release new versions because Conda screw by using the latest GCC and libstdc++ is incompatible with the one that Julia uses. Because of it my many changes are still waiting for that shit to be solved and leave only in the master version. Those changes includes some aliases renaming/adding and that's why I'm mentioning it.

All of this to say, when installing GMT.jl, please do (in the Julia shell/REPL) ``] add GMT#master`` and that will install the master version. After this, updating (later, when needed) it's done by only typing ``] up``

**Review by PaulWessel — APPROVED** [review]

**Comment by rbdavis** [comment]
> Another thing. I'm blocked to release new versions because Conda screw by using the latest GCC and libstdc++ is incompatible with the one that Julia uses. Because of it my many changes are still waiting for that shit to be solved and live only in the master version. Those changes includes some aliases renaming/adding and that's why I'm mentioning it.
> 
> All of this to say, when installing GMT.jl, please do (in the Julia shell/REPL) `] add GMT#master` and that will install the master version. After this, updating (later, when needed) it's done by only typing `] up`

OK, some progress here, but not all the way there yet:

(1) MacPorts julia is apparently no better than Homebrew. The package installed with no errors but when julia is run it immediately exits with the message `Killed: 9`. I uninstalled, went to https://github.com/JuliaLang/juliaup as recommended by Joaquim and used the curl installation instruction for macOS. That worked fine, and the julia interpreter now starts properly.

(2)` ] GMT#master` installation of GMT under Julia also worked fine.

(3) gmthelp(modulename) does nothing useful for me:

> julia> gmthelp(blockmean)
> ERROR: UndefVarError: gmthelp not defined
> Stacktrace:
>  [1] top-level scope
>    @ REPL[4]:1

I expect there's a trivial environmental fix for this but it's not going to be figured out by me.

**Comment by PaulWessel** [comment]
You have to also say
`using GMT`

**Comment by rbdavis** [comment]
`using GMT`

That did it, thanks!

**Comment by joa-quim** [comment]
Sorry, forgot to tell that. All packages in Julia need to be loaded first with “using”. 
Remember that you can also do

? modulename

**Comment by rbdavis** [comment]
Thanks, Joaquim, no worries. All working now.

**Pull request merged**
