### PR TITLE
Add -Fe to GMT_splines.sh

### PR DESCRIPTION
**Pull request by Esteban82**
Update script to add the new method to interpolate (#7488).

I make the figure taller so the legend doesn't cover the curves.

### CODE REVIEW

**Comment by Esteban82** [comment]
Should update something else? Like [doc/scripts/images.dvc](https://github.com/GenericMappingTools/gmt/commit/5c8cc24c1307e5e48d126e1760caa6456b5a2a34#diff-285fc9f11ec224c783c3de8fb59be4b9e6aca41ffb430fd563515f993f25e09b) ?

I add WIP until -Fe works well.

**Comment by PaulWessel** [comment]
Hi @Esteban82 please remind we where we are on this one.

**Comment by Esteban82** [comment]
This just add the new type of line to the figure. And it makes it a bit higher for the legend. 
I think we could approve this.

**Comment by Esteban82** [comment]
No, wait. The docs says "-Fe requires momotonically increasing data" and the input file of the script is NOT.

```
cat << EOF > t.txt
0	0
1	1
2	1.5
3	1.25
4	1.5
4.5	3
5	2
6	2.5
```

**Comment by Esteban82** [comment]
I think it would be good to add that curve to figure but it doesn't work for that input file,

**Comment by PaulWessel** [comment]
Hm, either we pick some other points that are monotonic and still allows the other splines to do some wiggling, or we just mention Fe in the caption but no line.  You can decide.

**Comment by Esteban82** [comment]
Also, it seems that the curve can only go upwards. Bug?

GMT_splines

**Comment by Esteban82** [comment]
If not, them I will leave the figure without that line (i.e. closing this issue without merge).

**Comment by PaulWessel** [comment]
Note sure what **-Fe** is supposed to do but if it is called step-_up_ then it is not unreasonable that it cannot go down, no?

**Comment by Esteban82** [comment]
> Note sure what **-Fe** is supposed to do but if it is called step-_up_ then it is not unreasonable that it cannot go down, no?

I use it to interpolate the cumulative sum of goals score by Messi. So it is working fine. But in my case the data was always increasing. This is NOT the case for the plot. 

` gmt math Messi_Goals.txt -C3 SUM -o0,3 = | gmt sample1d $(gmt info Messi_Goals.txt -T3d) -Fe -fT > dates_vs_goals.txt`

So, about this PR, I think it would be good to show this curve in the figure. But I don't see how. Except to make another figure (but I don't like this idea).

**Review by PaulWessel — APPROVED** [review]

**Comment by seisman** [comment]
> or should I update also doc/scripts/images.dvc ?

Yes, you should do it, otherwise the tests will be broken.

**Comment by PaulWessel** [comment]
Do a dvc pull since I just updated 42 PS files, and git pull in master.

**Comment by Esteban82** [comment]
Ok, I will have to study how to do it.

**Comment by PaulWessel** [comment]
See teh Contribution guide for documentation.  You will need dvc of course and ability to push to the DVC server.  If this was never set up for you by Max then I can ask them and I can then do this PS.  Let me know.  If DVC is set up for you then good for you to git this a try.  Usually:

1. Run the test that has been updated
2. Verify the plot is as expected
3. Place it (in your case) in doc/scripts/images (see that the old one is there first)
4. Update index via dvc add doc/scripts/images
5. Push new plots sto cloud with dvc push

**Comment by Esteban82** [comment]
> See teh Contribution guide for documentation. You will need dvc of course and ability to push to the DVC server. If this was never set up for you by Max then I can ask them and I can then do this PS. Let me know. If DVC is set up for you then good for you to git this a try. Usually:
> 
> 1. Run the test that has been updated
> 2. Verify the plot is as expected
> 3. Place it (in your case) in doc/scripts/images (see that the old one is there first)
> 4. Update index via dvc add doc/scripts/images
> 5. Push new plots sto cloud with dvc push


I have to do this within this branch? Should I update it? Or dvc  has nothing to do with git?

**Comment by joa-quim** [comment]
I think yes. `dvc` has nothing to do with `git`

**Comment by Esteban82** [comment]
I don't how to do this. I run the test and I got almost 1000 fails.

and them I got this error with 4.:

```
dvc add doc/scripts/images
ERROR: bad DVC file name 'doc/scripts/images.dvc' is git-ignored.  
```

**Comment by PaulWessel** [comment]
The only way to get 1000 failures is if you have a gmt.conf file in your home directory. We throw an immediate error on that.

Did Max set up up for write access via dvc push? Cannot put stuff up in dvc cloud without being registered.

I just now merged from master into GMT_Splines_add_Fe.

**Comment by PaulWessel** [comment]
Did you run dvc add doc/scripts/images after updating the PostScript file of that test and placed it in that dir? But if you dont have permission yet then you cannot push it.  Did you have communication with Max about this?  If you want I can add the PS and push it and then that test will pass?

**Comment by Esteban82** [comment]
> Did Max set up up for write access via dvc push? Cannot put stuff up in dvc cloud without being registered.

I think so. You can see me here "https://dagshub.com/GenericMappingTools/gmt" as a collaborator. Is it ok?

**Comment by joa-quim** [comment]
I can see that you have wright permissions.

**Comment by Esteban82** [comment]
> The only way to get 1000 failures is if you have a gmt.conf file in your home directory.

Is it possible that I have to uncomment `set (GMT_DATA_SERVER "static") on `ConfigUserAdvanced.cmake`? 

If so, them I would need to clarify it here https://docs.generic-mapping-tools.org/dev/devdocs/contributing.html#setting-up-your-environment, right?
`

**Comment by PaulWessel** [comment]
I've done that but the problem is that one is not always running the tests and in between one might want to plot Pluto.  Does not exist on static.  What I do is I defined four aliases in my .bashrc file:

```
alias set-static='export GMT_DATA_SERVER=static'
alias set-candidate='export GMT_DATA_SERVER=candidate'
alias set-oceania='export GMT_DATA_SERVER=oceania'
alias wipe-server='unset GMT_DATA_SERVER'
```

To run the test I just write set-static in the terminal and then ctr to run the tests (see admin/bashrc_for_gmt for the GMT bash aliases).

If I need to make that pluto map i do set-candidate.  Once we release everything it would be set-oceania for work and set-static for tests.

**Comment by PaulWessel** [comment]
I'll update the ex15.ps file now.

**Comment by PaulWessel** [comment]
@seisman, I am guessing this is more DVC stuff.  @Esteban82 improved the GMT_splines.sh script and I merged it.  I then ran all tests and this one failed due to the changes.  I then placed the PS made by the test (which is the right plot) into doc/scripts/images and got

```
dvc add doc/scripts/images
'./doc/examples/images.dvc' validation failed.

extra keys not allowed, in outs -> 0 -> hash, line 2, column 3
  1 outs:                                                                                                                                                                                             
  2 - md5: 4dd0ad31844cb0b0b451648cda314e2a.dir                                                                                                                                                       
  3   size: 37295153      
```                                         

The full images.dvc file is

```
outs:
- md5: 4dd0ad31844cb0b0b451648cda314e2a.dir
  size: 37295153
  nfiles: 53
  path: images
  hash: md5
```

**Comment by seisman** [comment]
When I worked in PR https://github.com/GenericMappingTools/gmt/pull/7978, running `dvc` automatically add the `hash: md5` line into this file. 
Maybe this is something new in the latest dvc versions (I'm using dvc 3.27.0).

Please try either remove this line manually or upgrade your dvc.

**Comment by PaulWessel** [comment]
OK, my dvc is 2.56.0...

**Pull request merged**
