### PR TITLE
Free the longoptions from the #ifdefs jail

### PR DESCRIPTION
**Pull request by joa-quim**
Roger Davis has finish the implementation and he is no longer contributing, so do not let the longoptions code rotten under the #ifdefs curtain. Nothing that I detected is broken by this release. What, and that is a big WHAT, is left to do is to document their use.

### CODE REVIEW

**Comment by rbdavis** [comment]
Just to clarify, longoptification of the core modules is complete. Many
supplemental modules remain undone.

Ron

**Review by Esteban82 — APPROVED** [review]
Blind approve.

**Comment by seisman** [comment]
also need to remove it from cmake settings

**Comment by joa-quim** [comment]
Done.

**Review by seisman — APPROVED** [review]

**Pull request merged**
