### PR TITLE
Improve the GMT landing page using sphinx-panels

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

As mentioned in #4743, this PR adds the `sphinx-panels` extension to redesign the GMT documentation landing page.

|  Old | New |
|---|---|
| image | image |

- Old landing page: https://docs.generic-mapping-tools.org/6.1/
- Preview the new landing page: https://gmt-35efcu8gq-gmt.vercel.app/

**NOTE:** As mentioned in #4743, the `sphinx-panel` extension is not included in the repository. Anyone who wants to build the documentation locally must install it manually.

The command is:

```
pip install sphinx sphinx-panels
```

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Very nice to have it tighter like that.

**Review by meghanrjones — COMMENTED** [review]
This is nice! I think it would look better to have the 'Quick links' section in a full width panel above the others, rather than not in a panel.

Also, does sphinx-panels need to be added to BUILDING.md for the documentation dependencies?

**Comment by seisman** [comment]
> This is nice! I think it would look better to have the 'Quick links' section in a full width panel above the others, rather than not in a panel.

Done in 0070f05fc5ed8616d8c4f39844db24b3e83f9ffd, although the panel headers are slightly different.

> Also, does sphinx-panels need to be added to BUILDING.md for the documentation dependencies?

Yes, I see you're working in #4905. It would be better if you can add sphinx-panels to BUILDING.md

**Comment by meghanrjones** [comment]
> > This is nice! I think it would look better to have the 'Quick links' section in a full width panel above the others, rather than not in a panel.
> 
> Done in [0070f05](https://github.com/GenericMappingTools/gmt/commit/0070f05fc5ed8616d8c4f39844db24b3e83f9ffd), although the panel headers are slightly different.

Sorry (I didn't realize what it would look like before making the suggestion), but I think it's worth reverting this change because the header difference draws attention away from the quick links, which are probably the most important part of landing page since the other links can be reached from the TOC and it's also useful to have a direct link to the quick links. 

> > Also, does sphinx-panels need to be added to BUILDING.md for the documentation dependencies?
> 
> Yes, I see you're working in #4905. It would be better if you can add sphinx-panels to BUILDING.md

I will add in #4905.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
