### PR TITLE
Add the day/night image documentation to GMT

### PR DESCRIPTION
**Pull request by PaulWessel**
Adds another chapter to the dataset documentation.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Might you have that URL handy?

**Comment by PaulWessel** [comment]
I think for Blue Marble [2002] we can use this:
https://visibleearth.nasa.gov/images/57752/blue-marble-land-surface-shallow-water-and-shaded-topography

And for Black Marble I think this:
https://earthobservatory.nasa.gov/features/NightLights/page3.php

**Comment by PaulWessel** [comment]
And it is the 2012 that is color. 2016 is just grayscale.

**Comment by seisman** [comment]
This PR looks good, but the daynight.jpg is a little too large. Do you have a smaller figure?

**Comment by PaulWessel** [comment]
OK, now 149 kb

**Pull request merged**
