### PR TITLE
gmt.conf.rst: make table for listing terms

### PR DESCRIPTION
**Pull request by anbj**
gmt.conf.rst: make table for listing terms

### CODE REVIEW

**Comment by seisman** [comment]
@anbj Thanks for making it look better.

You're using a "grid table" syntax to list the terms. It's OK, but we (at least myself) usually find it difficult to maintain/update/change a grid table. Thus we (again, at least myself) prefer to use a much simpler table syntax.

Please see https://docs.generic-mapping-tools.org/latest/rst-cheatsheet.html#simple-table for an example of the "simple table" syntax (right column for the raw code, left column for preview).

**Comment by anbj** [comment]
@seisman Great, thanks for the tip! I’ll do it that way (if not anyone beats me to me) when I get back from vacation.

**Comment by seisman** [comment]
Hi @anbj, we know that it's frustrating to switch between master and 6.1 branches when submitting a PR. After [some discussion](https://github.com/GenericMappingTools/gmt/issues/3612), we have improved our workflow to make it more friendly to contributors (and also to us). 

All new branches should be created from the master branch, and PRs should be merged into master branch, too. If the changes are critical for GMT 6.1.x release, then we will backport the changes into 6.1 branch, and the fix will be available in the next patch release.

So I've changed the base branch of this PR to master branch. It doesn't affect your branch and this PR.

**Comment by anbj** [comment]
Great @seisman, thanks for the info. I’ll close this PR and make a new one with the simple table syntax when I have the opportunity.

**Pull request closed without merging**
