### PR TITLE
Add grdcontour option for grd2kml

### LINKED ISSUE #142: Add grdcontour option for grd2kml
**Description of the desired feature**

Add an option (e.g. -W) for overlaying contours in grd2kml using either:

1. a constant sample spacing and pen attributes (e.g. spacing=500 pen=1p,black)

gmt grd2kml input.grd -I+a340 -Ctable.cpt -W500+w1p,black -Nkml_output

or 

2. an input text file that contains the contour levels and corresponding pen attributes

gmt grd2kml input.grd -I+a340 -Ctable.cpt -Wcontours.txt -Nkml_output

contours.txt =
-4000 1p,grey
-3000 1p,grey
-2000 3p,black
-1000 1p,grey

"Under the hood" - Call grdcontour after grdimage and before psconvert

**Are you willing to help implement and maintain this feature?** Yes/No

4464c7b

### PR DESCRIPTION
**Pull request by btozer**
**Description of proposed changes**

This branch is a work in progress to add a grdcontour option for grd2kml. This is required for producing final Google Earth products for our global grids (e.g. SRTM15+ bathymetry and gravity). 

Creating the contours as a separate vector file and then overlying these on the raster grid isn't an option as Google Earth crashes when importing vectors that exceed a certain size.  

So far, the code has only been edited with some basic groundwork (this may need reviewing and fixing).  But the idea is to add an option flag (e.g. -W) for overlaying contours using either:

a constant sample spacing and pen attributes (e.g. spacing=500m pen=1p,black)
gmt grd2kml input.grd -I+a340 -Ctable.cpt -W500+w1p,black -Noutput.kml

or

an input text file that contains the contour levels and corresponding pen attributes
gmt grd2kml input.grd -I+a340 -Ctable.cpt -Wcontours.txt -Noutput.kml

contours.txt =
-4000 1p,grey
-3000 1p,grey
-2000 3p,black
-1000 1p,grey

"Under the hood" - grdcontour will need to be called after grdimage and before psconvert.

Fixes #142 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by leouieda** [comment]
@btozer thanks for opening the PR! :1st_place_medal:  Could you please fill out the description with what you did/will do? See #230 and #321 for examples of good PR descriptions. This will help us write the commit message when the PR is merged.

**Comment by leouieda** [comment]
@btozer looks like you have a conflict with the current master branch. I'll fix this through the web interface. Please `git pull` before making any more commits.

**Comment by btozer** [comment]
Hey @leouieda - yep my clone was wayyy behind. Have git pulled and updated the description.

**Comment by PaulWessel** [comment]
Hi @btozer, sorry this has lingered so long.  Need to ask a few things:

1. You only want to draw these contours as indicated and not add any labeling, right? Labeling would not work well, I think.
2. I would let the pen entry be optional and default to the contour pen 0.25p,black,
3. We could allow **-W**_singlecontour_**+p**_pen_ as well,

Thanks.

**Comment by btozer** [comment]
Hi @PaulWessel, No problem! 

1. Yes, just the contour lines. No Labels.
2. Sounds good.
3. Sounds good.

**Comment by PaulWessel** [comment]
I am closing this PR since handled separately now.

**Pull request closed without merging**
