### PR TITLE
Add -H to plot for symbol and pen attribute scaling

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See #4866 for background.  This PR adds **-H** to **plot** which can be used to scale the symbol size _as well as_ the symbol pen outline attributes (width, style) by the provided scales in the data file.  Documentation has been updated with a **Data Column Order** explanatory note (as was done for **meca**, **coupe**, and **velo**), and a simple test _scalesymb.sh_ was added to demonstrate that it works with both a fixed symbol size or a variable one (i.e., size read from file, then multiplied by scale read from file).

This feature is required for properly scaled animations via **events** but the feature can also be used for other **plot** purposes.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Decided to combine both psxy and psxyz in the same PR since similar.

**Comment by meghanrjones** [comment]
Does **-H** scale just the pen or the pen and the size? I think it would be more flexible to have **-H** only scale the pen and leave the size scaling to **-S**, but the documentation for **-H** says it scales both the size and the pen.

**Comment by meghanrjones** [comment]
> Does **-H** scale just the pen or the pen and the size? I think it would be more flexible to have **-H** only scale the pen and leave the size scaling to **-S**, but the documentation for **-H** says it scales both the size and the pen.

Second comment - if it only scales the pen, could this be done as a modifier to **-W** rather than a new flag. It seems like a small feature for one of the three remaining upper case letters for psxy.

**Comment by joa-quim** [comment]
I got more convinced by your example than the feature description. Even so that I wonder if that should not be a command line flag to reproduce this effect. After all, if it's possible to achieve via file it should also be possible via command option.

**Comment by PaulWessel** [comment]
Remember that plot can accept a fixed _size_ (**-Sc**1c) as well as variable _size_ (**-Sc**); in the latter case we read actual dimensions (including units if appended) from the next column after the optional z-column (**-C**).  This is a separate thing from an overall _scale_ which is nondimensional and scales the current symbol size (which is either fixed or variable, as above) and also adjusts pen attributes related to dimension (i..e, width and gap/dash lengths). To do this effect requires the _scale_ column which is not the same as a _size_ column and both may be needed for some applications.  So no, it cannot just be a modifier to **-W** since it does affect the symbol size.
I am not sure what @joa-quim is saying since this is a command flag and is doable via command option - as the test scripts do.

**Comment by PaulWessel** [comment]
I chose **-H** since available across the 5 modules that need this effect.

**Comment by joa-quim** [comment]
Yes, I got that but what I'm saying is that we could as well want to do ``-Sc1c -W2p -H5`` and have that same symbol be  scaled differently on different plot calls for example. It's an extension of the ``-S<symb><size>``, ``-S<symb>`` case.

**Comment by PaulWessel** [comment]
So **-H**_scale_ would imply a constant scale and no scale column, whereas **-H** would read the scale from file?  I can implement that very easily.

**Comment by joa-quim** [comment]
Yes, exactly.

**Comment by PaulWessel** [comment]
OK, **-H**_scale_ implemented, tests still pass and the new feature works fine, e.g.

`echo 0 0 | gmt plot -R-2/2/-2/2 -JX4i -B -Sc1i -W1p -Gred -H3 -pdf t`

**Review by joa-quim — APPROVED** [review]

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
