### PR TITLE
Soften error message when docs cannot be opened automatically.

### PR DESCRIPTION
**Pull request by joa-quim**
Address issue #498

### CODE REVIEW

**Comment by joa-quim** [comment]
I was just trying to avoid that ugly ``docs [ERROR]: `` since this not really a user error. Looked into the code but without stepping though it's really hard to tell if Report is writing to stderr or stdout. Is there a way (without fprintf) to write the text to stderror and not printing the ``docs [ERROR]: `` bit?

**Comment by PaulWessel** [comment]
I think we should check the system return and if xdg-open is not found then it _is_ an error and we do as before.  However, if it is not that type of error then we can do a soft GMT_Message and then just do a printf of the URL.

**Comment by joa-quim** [comment]
But this only about ``xdg-open``? And what other type of error would merit a soft message whilst this get the harsh one?
This issue is getting more complicated than it worth.

**Comment by PaulWessel** [comment]
yes, I think open and cmd start will always be available.  I think only "not found" is an error.  Reasons for other failures would be considered soft and have to do with X11 tunneling etc.  Given that we are addressing an issue affecting 1% of users I think handling this 1st order error is more than we need to worry about.

**Pull request closed without merging**
