### PR TITLE
Fid bad CID fix that broke the r,g,b grids case

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel just made some fixes in #4280, which causes some conflicts with this PR.

**Comment by joa-quim** [comment]
In your PR, delete the line around 7964, the one with ``gmt_M_str_free (input);`` and I can delete this PR

**Comment by PaulWessel** [comment]
I am correctly freeing the input string and not correctly passing infile to the function that returns, so I think master has this covered as is?

**Comment by joa-quim** [comment]
Yes, looks good. So I'll close this PR, right?

**Comment by PaulWessel** [comment]
Yes, think so.  Sorry, did not notice you were working on that

**Pull request closed without merging**
