### PR TITLE
Add longoptions support for greenspline.

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**

Python differences:

  No Python module.

Julia differences:

  Used ncdata instead of mode for -D. mode seems unrelated to
    manual page description. (-Z specs distance mode.)

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — COMMENTED** [review]
Note that grdedit also has -D and there you chose

	{ 0, 'D', "netcdf|netCDF|ncheader",

I think all those **-D** options should be identical (grdinterpolate, xyz2grd, greenspline) as well

**Comment by rbdavis** [comment]
Just changed -D as requested.

**Comment by rbdavis** [comment]
Just submitted PR #8298 to make grdinterpolate/xyz2grd compliant per Paul's request.

**Comment by PaulWessel** [comment]
Been too long for me to remember all of this, but I also wonder what netCDF etc as to do with -D.  It was intended for --information and at best --metadata and should not involved netCDF if we can help it.  Did Python of Julia et stuck with netCDF?  Why not metadata?

**Comment by PaulWessel** [comment]
Sam thing, why not --metadata?

**Review by PaulWessel — APPROVED** [review]

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
