### PR TITLE
Improve option checks and docs for grdgradient

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR fixes a docs mixup in which the direction (-D) and magnitude (-S) were switched.

### CODE REVIEW

**Comment by meghanrjones** [comment]
I'm opening this as a PR to have a discussion related to this section - the docs say that grdgradient computes the directional derivative or the magnitude/direction of the vector gradient. But there doesn't seem to be anything in the code that makes these options (-A versus -D|-S) mutually exclusive (e.g., https://github.com/GenericMappingTools/pygmt/pull/1679). Is this intentional?

**Review by PaulWessel — APPROVED** [review]

**Comment by meghanrjones** [comment]
> I'm opening this as a PR to have a discussion related to this section - the docs say that grdgradient computes the directional derivative or the magnitude/direction of the vector gradient. But there doesn't seem to be anything in the code that makes these options (-A versus -D|-S) mutually exclusive (e.g., https://github.com/GenericMappingTools/pygmt/pull/1679). Is this intentional?

Sorry, I forgot to ping @PaulWessel on this comment for feedback.

**Comment by PaulWessel** [comment]
I think **-A** and **-D** are mutually exclusive since both write to the **-G** output grid.  So you cannot get both the directional derivatives in the chosen direction (via **-A**) _and_ output gradient directions by asking for **-D** as well.  Likewise, **-S** can _only_ be used with **-D** to save the magnitude to the separate file.  So I think these changes are needed:

1. Parse needs to give error if both **-A** and **-D** are set
2. Parse needs to give error if **-S** is set but not **-D**
3. Documentation for **-D** should start with "Instead of finding the gradient in a given direction (-A), find ..."

Note that if **-S** is given and **-G** is not then no gradient direction grid is written.

**Comment by PaulWessel** [comment]
Also, while at it.  I think the equations with words look bad.  I suggest you change this to use variable names.  Just introduce variables o (offset) and \sigma (sigma) [which you already have], amplitude (a), and then it will look more like real equations.

**Comment by meghanrjones** [comment]
Sounds good. I'm going to convert this to a WIP and add the changes here rather than opening a different PR, since this already contains the relevant discussion.

**Review by PaulWessel — APPROVED** [review]
There is a :math: run-in in the -A section that is not set as math.
-Nt last equation, is the parenthesis around a needed?
Otherwise looks great!

**Pull request merged**
