### PR TITLE
Update links to grid file formats explanations

### LINKED ISSUE #4615: Fix missing links in some man pages
There are several man pages that writes things like in the entry for an input grid.  This is from grd2cpt:

*grid*
	Names of one or more grid files used to derive the color palette
	table. All grids need to have the same size and dimensions. (See
	**GRID FILE FORMATS** below).

However, there is nothing below.  What is meant I think is a link to _explain_grd_inout.rst__.  I think this used to be a section and the above was a reference to a section (that include file starts with the subtitle **Grid File Format**s).  The **GRID FILE FORMATS** string appears in these rst files:

```
./grd2cpt.rst
./grd2kml.rst
./grdcontour_common.rst_
./grdedit.rst
./grdfft.rst
./grdfilter.rst
./grdgradient.rst
./grdhisteq.rst
./grdimage_common.rst_
./grdinfo.rst
./grdlandmask.rst
./grdmask.rst
./grdmath.rst
./grdproject.rst
./grdvector_common.rst_
./supplements/potential/gravfft.rst
./supplements/potential/grdflexure.rst
./supplements/potential/grdseamount.rst
./supplements/potential/grdslice.rst
./supplements/potential/talwani3d.rst
```

while explain_grd_inout.rst_  only appears in ./gmt.rst.

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

Many documentation pages for modules that input or output *grid* files stated "See GRID FILE FORMATS below" in the explanation (e.g., [grd2cpt](https://docs.generic-mapping-tools.org/dev/grd2cpt.html)). This section was occasionally missing (e.g., [grd2kml](https://docs.generic-mapping-tools.org/dev/grd2kml.html)) or included a short, unlinked version of the grid file formats explanation (e.g., https://docs.generic-mapping-tools.org/dev/grd2cpt.html#grid-file-formats). This pull request directly links to the [full grid file format section](https://docs.generic-mapping-tools.org/dev/gmt.html#grd-inout-full) from the arguments that reference *grid* files. In addition, it consolidates the grid file format explanation for input and export versus just export into one section to remove duplication of text.

Fixes #4615

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Looks great!

**Comment by meghanrjones** [comment]
@PaulWessel or @seisman, do you know what to make of the failed check? I am not sure why it could not download gmt-cache.zip.

**Comment by PaulWessel** [comment]
Usually when I ask @seisman of these things he says just go ahead and merge as administrator since it passes on the other checks and the cache download is unrelated to your PR.

**Comment by seisman** [comment]
Yes, OK to merge.

**Pull request merged**
