### PR TITLE
Consolidate source text for cookbook and manpage -B docs

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR consolidates the source documentation for **-B** for the cookbook and reference docs (similar to -R in #4996). 

Addresses #4969

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by PaulWessel** [comment]
I never know when or not to except a Vercel links in these - is it only for the originator of the PR?

**Comment by meghanrjones** [comment]
I'm not sure about the notifications - but for any PR you can view them here:
image
By clicking 'Show environment' and then by clicking on the view deployment button:
image

**Review by PaulWessel — APPROVED** [review]
Looks nice.  The only odd thing I found was for the 3-D axis annotation using those 1-4 codes,  It says <axes><code>, but this is only for Z, so maybe Z|z<code>?

**Comment by meghanrjones** [comment]
> Looks nice. The only odd thing I found was for the 3-D axis annotation using those 1-4 codes, It says `` , but this is only for Z, so maybe Z|z`?` ``

The 'it says' part of your comment got cut off, so I am not sure exactly what should be changed. Does this look better?

image

**Comment by PaulWessel** [comment]
Thanks, yes.  Sorry, I forgot if I do stuff like` <test>` it cuts out unless I format it.

**Comment by meghanrjones** [comment]
I made a last change by including the preamble explaining that -B can be called multiple times in both the cookbook and gmt.rst. The links in both go to the cookbook 'Frame settings'  and 'Axes settings' sections, but that seems better than not having the links.

**Comment by PaulWessel** [comment]
Yes, that should be OK though.

**Pull request merged**
