### PR TITLE
Generate docs dependent figures in PNG and PDF formats separately

### PR DESCRIPTION
**Pull request by seisman**
Address #805

### CODE REVIEW

**Comment by joa-quim** [comment]
So, how do I run this?
```
cmake --build . --target docs_html_depends;
ninja: error: unknown target 'docs_html_depends'
```

**Comment by seisman** [comment]
Did you run `cmake ..` again or remove the build directory and re-run `cmake ..`?

You can also run `cmake --build . --target docs_html` to generate HTML documentations and HTML-only dependents.

**Comment by joa-quim** [comment]
I use ninja, so build is
```
ninja install
```
and docs
```
ninja docs_html
```
which still builds the PDF

**Comment by seisman** [comment]
```
mkdir build
cd build
cmake .. -G Ninja
ninja
ninja docs_html
```

I don't see any pdf in the build directory or any subdirectories.

**Comment by joa-quim** [comment]
Well, I have all the examples and scripts built in PDF as well.

**Pull request merged**
