### PR TITLE
Fixed strsignal(3) usage

### PR DESCRIPTION
**Pull request by uleysky**
Fixed compilation on a systems with strsignal(3) function

### CODE REVIEW

**Comment by PaulWessel** [comment]
Thanks for checking and fixing!

**Comment by seisman** [comment]
We tests GMT on different Ubuntu and Debian versions, but the latest glibc version on these Linux distros are 2.31. That's why we don't catch the bug in our CI.

BTW, this PR should be backported to 6.1 branch. I will do it manually after merging.

**Comment by seisman** [comment]
Merging this PR gives following warnings when compilation:
```
../src/gmt_common_sighandler.c:198:73: warning: implicit declaration of function ‘strsignal’; did you mean ‘ssignal’? [-Wimplicit-function-declaration]
   fprintf (stderr, "ERROR: Caught signal number %d (%s) at\n", sig_num, strsignal(sig_num));
                                                                         ^~~~~~~~~
                                                                         ssignal
../src/gmt_common_sighandler.c:198:54: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
   fprintf (stderr, "ERROR: Caught signal number %d (%s) at\n", sig_num, strsignal(sig_num));
```
Need `string.h`?

**Comment by PaulWessel** [comment]
Yes, I think so.  It is in signal.h on macos but googling suggest string.h

**Pull request merged**
