### PR TITLE
Safeguard against rogue GMT_DATADIR settings

### LINKED ISSUE #2971: Seg faults of gmt installed on Mac through home-brew
We are having problems with homebrew installs on High Sierra and Mojave machines after upgrades to gmt-6.0.0_4.high_sierra.bottle.tar.gz or gmt-6.0.0_4.mojave.bottle.tar.gz

The problem is that gmt simply seg faults, regardless of arguments. Just running "gmt" results in something like:

ERROR: Caught signal number 11 (Segmentation fault) at
0   libgmt.6.dylib                      0x00000001046388de gmt_replace_backslash_in_path + 12
1   ???                                 0x0000000000000000 0x0 + 0
Stack backtrace:
0   libgmt.6.dylib                      0x00000001045d42b1 sig_handler + 561
1   libsystem_platform.dylib            0x00007fff62645f5a _sigtramp + 26
2   ???                                 0x0000000061c398e6 0x0 + 1640208614
3   libgmt.6.dylib                      0x00000001046c9bf4 gmt_begin + 1819
4   libgmt.6.dylib                      0x00000001045e2394 GMT_Create_Session + 728
5   gmt                                 0x00000001045c77bc main + 288
6   libdyld.dylib                       0x00007fff62337015 start + 1
7   ???                                 0x0000000000000001 0x0 + 1

I have gone through the exercise of completely deleting my homebrew installation and reinstalling everything from scratch. The result is the same.

A couple weeks back we started having failures of the test MacOs build in our Travis-CI testing of MB-System commits , apparently due to this problem. I seemed to fix this by moving the target from High Sierra to Mojave and then requiring that all formula be fully updated. However, today a coworker reports this same failure on her Mac Pro running Mojave.

### PR DESCRIPTION
**Pull request by PaulWessel**
As per #2971, if a non-existant path is given via the environmental variable **GMT_DATADIR** we get a SEGV crash (when accessing a NULL pointer later on).  This PR tests all such directories.  Only lists of directories are not checked since these are used later to look for specific files and will only cause file not found run-time errors.  Closes #2971.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Please try this branch, @dwcaress.

**Comment by dwcaress** [comment]
@PaulWessel , Your fix works for me with no GMT_DATADIR set, with valid GMT_DATADIR set, and invalid GMT_DATADIR set. Looks good - thanks!

**Comment by PaulWessel** [comment]
Great, those should be all the cases, apart form the list of directories which as a separate handling.

**Comment by PaulWessel** [comment]
Any concerns from @seisman - just double-checking in case something subtle was left out (I know @seisman keen eye will spot it!)

**Pull request merged**
