### PR TITLE
WIP [ DO NOT MERGE]: Rebuild CI caches in a PR

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

DO NOT MERGE!

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
This is the relevant error message from the logs:
```
 CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:70 (message):
  Couldn't find tool "testepsg":

      "C:/vcpkg/packages/gdal_x64-windows/bin/testepsg.exe" does not exist
```

The[ vcpkg portfile](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake) includes `testepsg`, but that was removed from the default build for gdal in https://github.com/OSGeo/gdal/commit/0272378cc7b16975e3a85585e175ec8b8fffcaa1. Do you think this should be reported to vcpkg or gdal?

**Comment by seisman** [comment]
I think it's a vcpkg issue.

**Comment by meghanrjones** [comment]
> I think it's a vcpkg portfile issue.

OK, I will open an issue there.

**Comment by meghanrjones** [comment]
We're no longer seeing failures on all the Windows build checks, so I think you can close this now. Thanks for working on fixing the caches.

**Pull request closed without merging**
