### PR TITLE
Update gmtmath.rst

### PR DESCRIPTION
**Pull request by Esteban82**
Update the table operator as discused on #6778.

### CODE REVIEW

**Comment by seisman** [comment]
I don't check any changes in this PR, but I think perhaps we should use the "Simple Table" syntax (https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#simple-tables) or the "List Table" syntax (https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table).

**Comment by seisman** [comment]
I think "Simple Table" is better in this case.

**Comment by Esteban82** [comment]
I think it is better to close this PR and open a new one with a "Simple Table".

**Comment by PaulWessel** [comment]
Fine with me - whatever you think looks better.

**Comment by seisman** [comment]
> I think it is better to close this PR and open a new one with a "Simple Table".

Fine with me.

**Pull request closed without merging**
