### PR TITLE
gmtbinstats documents the **-n** option but was not accepting it.

### PR DESCRIPTION
**Pull request by joa-quim**
gmtbinstats [ERROR]: Unrecognized option -n

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Please also remove it from the docs.

**Comment by joa-quim** [comment]
I didn't remove it. I added it. But is it supported or not?

**Comment by PaulWessel** [comment]
No, there is no 2-D interpolation going on here at all.

**Comment by PaulWessel** [comment]
Sorry I read your thing backwards.  The C code was fine - the docs had copy/paste

**Pull request merged**
