### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR fixes a typo.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
FYI, when I find something super-trivial like that I do a direct master commit (no tell Dongdong).

**Comment by seisman** [comment]
I also commit to master branch directly for typos like this 😄

**Comment by PaulWessel** [comment]
> I also commit to master branch directly for typos like this 😄

Blasfemi!

**Comment by meghanrjones** [comment]
Understood

**Pull request merged**
