### PR TITLE
Fix logic on how to detect a -L deprecated syntax.

### PR DESCRIPTION
**Pull request by joa-quim**
This fixes a bug where -L was not usable in modern mode.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
I think you may want to use **GMT_LEN_UNITS** instead of all those individual checks, e.g

isoldL = strchr (GMT_LEN_UNITS, *pch) != NULL;

**Comment by joa-quim** [comment]
I knew something like that had to exist. But does it include 'c' and 'C'?

**Comment by PaulWessel** [comment]
You can do stuff line strchr (GMT_LEN_UNITS "cC", *pch) since string constants concatenate

**Comment by joa-quim** [comment]
OK, but that's much less readable.

**Comment by PaulWessel** [comment]
Well, standard C so not that unreadable I think.

**Pull request merged**
