### PR TITLE
Initialize var. Otherwise it crashes from Win debug builds.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by PaulWessel** [comment]
Please also merge from 6.0 into master.

**Comment by joa-quim** [comment]
Do you do that here (Github)? Where?

**Comment by PaulWessel** [comment]
Hm, I use GitHub Desktop tool and it lets me merge from X into master, and if no conflict it will do so.  I don't know how to do it on the website but perhaps @seisman or @leouieda do.  Since all 6rc1 fixes are bugs that also are in master we must remember to do those merges from time to time.

**Comment by seisman** [comment]
We can't merge 6.0 into master on the GitHub website, unless opening a new PR. I usually do the merge using command-line.

**Comment by joa-quim** [comment]
Will have to confirm next time. Did it from Tortoise and can see it master. Except that Github says the change was done > 15 min ago and I just did it.

**Comment by seisman** [comment]
The commit 9264c062e73be6c85ef88c1d9120fac655f73f38 (this PR) was merged into the 6.0 branch >15 min ago. 

Merging 6.0 into master just reuses the commit, so even on master branch, you still see that the commit was done > 15 min ago.

**Comment by leouieda** [comment]
To keep from forgetting to push bug fixes to master, I would suggest always doing this as soon as a bug fix is merged in 6.0. Might be useful to start using the issue and PR labels to indicate if things are bug fixes or new features so we can easily parse them. Labels can be customized with whatever name we want if we don't like the existing ones.

**Pull request merged**
