### PR TITLE
Update to -JP new syntax

### PR DESCRIPTION
**Pull request by seisman**
All tests still pass.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Check if the polarpanels.sh works.

**Comment by seisman** [comment]
That's weird. I got different output, but the ctest run passed.

**Comment by seisman** [comment]
`-JPa?+o45` mixes old and new syntaxes. It shouldn't work, but it works.

I've updated it to the new syntax `-JP?+a+o45`.

**Comment by PaulWessel** [comment]
It works because checking for the leading 'a' does not set up a separate branch if found.  Perhaps it should so such things would be errors.

**Comment by seisman** [comment]
Yes, it should report an error.

**Pull request merged**
