### PR TITLE
Ignore PS_MEDIA unless classic mode or PostScript format

### PR DESCRIPTION
**Pull request by PaulWessel**
Unless we are making a PostScript plot we must ignore any **PS_MEDIA** settings. Closes issue #2099.

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel This PR may break animations. Below is the movie_frame.sh of anim02.
```
#!/usr/bin/env bash
# Main frame loop script
export GMT_SESSION_NAME=$$
export GMT_END_SHOW=off
# Include static and frame-specific parameters
source movie_init.sh
source movie_params_$1.sh
mkdir ${MOVIE_NAME}
cd ${MOVIE_NAME}
gmt begin
# 	Set output PNG name and plot conversion parameters
	gmt figure ${MOVIE_NAME} png E${MOVIE_DPU},A+n+r
	gmt set PS_MEDIA 3.5ix4.167i DIR_DATA /Users/seisman/Gits/gmt/gmt/doc/examples/anim02,/Users/seisman/Gits/gmt/gmt/doc/examples/anim02/anim_02
	width=`gmt math -Q ${MOVIE_WIDTH} 0.5i SUB =`
	gmt grdimage @tut_relief.nc -I+a${MOVIE_COL0}+nt2 -JM${width} -Cmain.cpt 		-BWSne -B1 -X0.35i -Y0.3i --FONT_ANNOT_PRIMARY=9p
	gmt plot -Sc0.8i -Gwhite -Wthin <<< "256.25 35.6"
	gmt plot -Sv0.1i+e -Gred -Wthick <<< "256.25 35.6 ${MOVIE_COL1} 0.37i"
gmt end
# Move PNG file up to parent directory and cd up one level
mv -f ${MOVIE_NAME}.png ..
cd ..
# Remove frame directory and frame parameter file
rm -rf ${MOVIE_NAME}
rm -f movie_params_$1.sh

```

**Comment by PaulWessel** [comment]
OK, will look later today - full day here.  movie may be an exception to that rule.

**Comment by PaulWessel** [comment]
Let's review this issue.  It started because a bad PS_MEDIA setting ended up cropping a plot which seemed very unseemly for modern mode.  However, we did not particularly discuss the pros/cons on this.  Given modern mode is meant to be simple, we don't want to crop valid plots and confuse the user.  Also, if the user wants space around  a plot there is the PS_CONVERT and gmt begin and figure settings you can use.  If the user wants an A4 plot however, then right now the option is to do a PS plot with PS_MEDIA=a4 then convert that manually to PDF, for instance.  Then, there is the case of movie making where we definitively need to specify a page size.  So what do you think? If we revert #2100 then we are back to rouge PS_MEDIA settings.  Or are we? Do we not start a sessions with a clean slate? If someone sets PS_MEDIA in a modern mode, should we really disallow that?

**Comment by seisman** [comment]
There are some related discussions in issues #106 and #497.

> If the user wants an A4 plot however, then right now the option is to do a PS plot with PS_MEDIA=a4 then convert that manually to PDF, for instance. 

Currently it's the only way to have an A4 plot. In #106, I thought I could have an A4 plot by setting PS_MEDIA to A4 and disable the cropping by setting PS_CONVERT to an empty string. However, it gave me a wrong figure, because the plot origin in modern mode is 5 inch by 5 inch away from the lower-left corner of the paper. 

> Do we not start a sessions with a clean slate? 

I don't think it's a good idea. Users may have their own gmt.conf files for specific purposes. 

> If someone sets PS_MEDIA in a modern mode, should we really disallow that?

Are there any technical difficulties allowing PS_MEDIA in modern mode? If PS_MEDIA is set in modern mode, can we just move the plot origin 1 inch by 1 inch (i.e. the origin for classic mode) and disable auto-cropping?

**Comment by PaulWessel** [comment]
We could try to do that, i.e., use PS_MEDIA if set and undo the 5 inch slop.  Since we committed #2100 perhaps you know how to revert that - a bit easier than to redo stuff.

**Comment by joa-quim** [comment]
Agree. If, for unknown reason, user sets the paper size then we should try to cope with it. Fear is that setting is from GMT < 6 habits.

**Comment by PaulWessel** [comment]
We can better explain in what situations PS_MEDIA is useful.  Hi @seisman, could you help with the reverting?

**Comment by seisman** [comment]
#2113 reverts #2100 by `git revert commit-hash`.

#2101 is kept and we can modify it later.

**Pull request merged**
