### PR TITLE
Allow -Vd to debug modern usage

### PR DESCRIPTION
**Pull request by PaulWessel**
Commands like `gmt plot -? -Vd` would refuse to show the moderm mode syntax since the **-Vd** messed up the option count.  I now deal with this so that developers can run the synopsis cases with full debug.  However, I cannot get `gmt plot -Vd `to not complain, but this is not a likely command; developers can run `gmt plot -? -Vd` to test that case.

### CODE REVIEW

**Comment by seisman** [comment]
`gmt plot -+ -Vd` still doesn't work.

**Comment by PaulWessel** [comment]
Works for me in Xcode debugger but not on command line (yet) because macOS seems to have a long memory of what is in a shared library (?).

**Comment by seisman** [comment]
It doesn't work for me, too.

**Comment by PaulWessel** [comment]
It has happened before that I make certain changes to the API and it works when running Xcode but still fails when running command line.  Not sure what to do but reboot.  I will do that as a test.

**Comment by PaulWessel** [comment]
Try now.  I had a ~/.gmt/sessions/gmt6.1 directory so it already thought it was a modern mode session...

**Pull request merged**
