### PR TITLE
Clean up julia scripts

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by joa-quim** [comment]
Deleting these scripts here it's trowing them away for good.

**Comment by seisman** [comment]
@joa-quim Probably you can move these scripts to GMT.jl since they are never tested in the main GMT repository.

**Comment by joa-quim** [comment]
If I wanted them in GMT.jl they would there already. Those scripts were written because I needed them (troubles with bash on Win). 

Let me be clear. I'm against deleting them.

**Comment by seisman** [comment]
OK. Let's keep them.

**Pull request closed without merging**
