### PR TITLE
Enable documentation deployment in Azure Pipelines Linux CI

### PR DESCRIPTION
**Pull request by seisman**
I made some changes to the document deployment script from https://github.com/fatiando/continuous-integration/blob/master/travis/deploy-gh-pages.sh.

I tested it with another repository and it worked well. 

@leouieda Can you review it?

### CODE REVIEW

**Comment by leouieda** [comment]
@seisman thanks for doing this! Did you add the token through the web interface? Also, did you check if it's not being leaked anywhere in the log? This token gives full access to all of your repositories (including the GMT ones). 

Should we enable building this branch temporarily as if it were 6.0 to test that it works? Otherwise we'll have to wait for the scheduled build.

**Comment by seisman** [comment]
@leouieda I added a fake token through the web interface. The log looks secure to me.

```
bash ci/deploy-gh-pages.sh
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/1cce2eed-949b-493a-be46-9dffe13dbca9.sh
Not in master or 6.x branches. Deployment skipped.
+ REPO=GenericMappingTools/gmt
+ BRANCH=gh-pages
+ CLONE_DIR=deploy
+ CLONE_ARGS='--quiet --branch=gh-pages --single-branch'
+ REPO_URL=https://***@github.com/GenericMappingTools/gmt.git
+ HTML_SRC=/home/vsts/work/1/s/build/doc/rst/html
+ [[ azure-deploy-docs =~ ^6\.[0-9]+$ ]]
+ [[ azure-deploy-docs == \m\a\s\t\e\r ]]
+ echo -e 'Not in master or 6.x branches. Deployment skipped.'
+ exit 0
```

**Comment by seisman** [comment]
> Be sure to turn it off in Travis so we don't deploy twice

Travis CI is only used to deploy documentations. So now it's OK to fully drop Travis CI in https://github.com/GenericMappingTools/gmt/pull/1337/commits/2975450737efe1d8cfffb770f3398c896d599973.

> Make sure the job runs on tag builds, not just scheduled builds of master/6.0

Currently, we do nothing for a new tag, even don't trigger any builds for a new tag. I think we can leave it to another PR. BTW, we will update/deploy the documentations nightly, so building documentations on tag builds won't make many differences.

**Comment by leouieda** [comment]
> we will update/deploy the documentations nightly, so building documentations on tag builds won't make many differences.

That's true. Are all version branches updated nightly?

**Comment by seisman** [comment]
Yes, both master and 6.0 are updated nightly.

**Comment by leouieda** [comment]
Alright, this is fine by me then. Merge when you're ready.

**Pull request merged**
