### PR TITLE
Windbarbs supplement

### PR DESCRIPTION
**Pull request by joa-quim**
This PR contains the code to plot `windbarbs` either from table data as well as two grids, ``à lá grdvector``.

The code was a little reworked from that of https://sites.google.com/site/masahigaki/gmt/gmt-windbarb?authuser=0 with changes to make it compile with GMT master version and drop the complicated plugin recipe.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Things to do:

Compare with **psxy** and note there needs to be changes to:

1. How the usage function is not using the new way with the GMT_Usage function (to handle variable terminal widths)
2. Probably something related to -C if no argument (modern mode stuff)
3. Maybe KEYS - did not look very carefully.
4. Perhaps RST stuff using our SYN-* macros.
5. ???

**Comment by joa-quim** [comment]
> How the usage function is not using the new way with the GMT_Usage function (to handle variable terminal widths)

It does

> Perhaps RST stuff using our SYN-* macros

It does, and I made several changes too.

**Comment by PaulWessel** [comment]
Ok I just browsed the code on GitHub and that used GMT_Message. Will try tomorrow

**Comment by joa-quim** [comment]
When you try, change the mode to +x of the two sh examples to stop that `Code Validator` failure. It ignores what I do on Windows.

**Comment by PaulWessel** [comment]
Done, but unless you have uncommitted changes, there is no use of GMT_Usage in these codes etc.

**Comment by PaulWessel** [comment]
And since this is a branch: Given how all the other supplements are (all "required" together) you should places those tests and rst in their final places now, i.e, test/windbarb/yourwtoscripts and in rst/source/supplements/windbarg and so on.  It is OK to not have PS files from the test so far so no worries about dvc.

**Comment by joa-quim** [comment]
> test/windbarb/yourwtoscripts

I just copy his shell examples. They are not tests.

> rst/source/supplements/windbarg

They are already in ``doc\rst\source\supplements\windbarbs``

**Comment by joa-quim** [comment]
>  there is no use of GMT_Usage in these codes etc.

I don't even know how to use them. I find it to much pain for no gain.

**Comment by masahigaki** [comment]
Dear all,
It would be my great pleasure if the windbarb extension would be included in the GMT Supplement.

> you should places those tests and rst in their final places now, i.e, test/windbarb/yourwtoscripts

Regarding test scripts, I rewrite the example scripts *barb_example.sh, and put them into test/windbarbs/ subdirectory on my private repository masahigaki/gmt@e6cb3f6
The shbang of the scripts is fixed to "#!/usr/bin/env bash" to pass the code validator.

I would appreciate if you could examine the changes.
Masakazu

**Comment by masahigaki** [comment]
Dear Joaquim,

Thank you for the clarification and I am sorry for my delayed response.
I chose four scripts for windbarbs test, removed data files in the test directory, and updated the scripts to generate data.
Please look at masahigaki/gmt@9e9133aa

**Comment by masahigaki** [comment]
I have rewrited {grd,ps,wind}barb.c to use GMT_Usage instead of GMT_Message at masahigaki/gmt@7519afbf .
Your confirmation would be appreciated.

**Comment by joa-quim** [comment]
@PaulWessel I think this is good for merging.

**Comment by PaulWessel** [comment]
I made the scripts executable.  How about PS rigs for DVC and in test/baseline/* etc?

**Comment by joa-quim** [comment]
I have not add the PS's to DVC because every time I touch it that _porcelain_ thing breaks.

**Comment by PaulWessel** [comment]
Getting there. I can do the DVC once all is ready. Need a few more things:

1. Module listing shows _psbarb_ which is a classic name.  Need to add _barb.rst_. See _psxy.rst_ vs _plot.rst_ for what to do.
2. **barb** and **grdbarg** man pages need to be stripped of classic-only options like **-O -K -P**
3. Note there is a classic-module RST listing (_modules-classic.rst_) where **psbarb** and **grdbarb** also need to go and here the **-O -K -P** are listed.
4. The individual modules under the WIndbarbs header does try to access **barb** but no such file.
5. The two man pages has failed link about purpose on top. Run _gmt_make_module_purpose.sh_ first.

**Comment by PaulWessel** [comment]
I am working on the docs formatting now.

**Comment by PaulWessel** [comment]
Think it is ready now.

**Review by PaulWessel — APPROVED** [review]
Tests work, docs look good, -T gone from sight, C-fixes seems fine.  Have a look too.

**Comment by joa-quim** [comment]
I see that the ``psbarb.rst`` includes ``barb.rst`` but no manual is included. The page has synopsis and jumps to Examples.

**Comment by PaulWessel** [comment]
I forgot - will look in < 1 hour

**Comment by PaulWessel** [comment]
Had forgotten to do what is also done for psmeca.rst and meca.rst.

**Comment by PaulWessel** [comment]
psbarb is fixed

**Comment by joa-quim** [comment]
Ok, let's give this light.

**Comment by masahigaki** [comment]
Thank you very much for fixing the windbarbs code and merging it into master.

**Comment by joa-quim** [comment]
Hi Masakazu, If you have a nice windbarbs map, kind of official looking with meteorological agency logos and so, it would be a nice post in the Forum [Showcase](https://forum.generic-mapping-tools.org/c/Show-your-nice-example-script/10)

**Comment by masahigaki** [comment]
Paul-san,
Thank you again for adding the windbarbs code into GMT Supplement.

I think "2-D" should be added to
https://github.com/GenericMappingTools/gmt/blob/74a5caa8baa0eb5b8ca71bfaea6ae3fe5a7ccaa0/doc/rst/source/supplements/module_supplements_purpose.rst_#L103
as well as 
https://github.com/GenericMappingTools/gmt/blob/74a5caa8baa0eb5b8ca71bfaea6ae3fe5a7ccaa0/src/windbarbs/psbarb.c#L33

Regards,
Masakazu

**Comment by PaulWessel** [comment]
Yes, I had already done the update (it is a define statement in the C code) but forgot to run the script that builds those rst includes.  Thanks, now updated in master

**Pull request merged**
