### PR TITLE
Resolve merge conflict for gmt-themes

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

Resolve merge conflicts due to auto-colors branch

### CODE REVIEW

**Comment by meghanrjones** [comment]
I'm not sure how well this would work given the squash and merge requirement. I could just describe the merge conflict solution if that's easier

**Comment by seisman** [comment]
From the original PR #3344, it seems there is only a tiny conflict.
image

**Comment by meghanrjones** [comment]
I think it's showing all the diffs since the last time that master was merged into the gmt-themes branch, so all changes since Nov. 28. I wasn't expecting that, which is why I suggested that it might be easier/clearer for Paul to just resolve the merge conflict rather than using this PR.

**Comment by meghanrjones** [comment]
The current changes in gmt_themes can be accepted while updating line ~2671
``` fprintf (fpo, "%-30s = %s\n", GMT5_keywords[k].name, gmtlib_getparameter (GMT, GMT5_keywords[k].name));```
to
```fprintf (fpo, "%-30s = %s\n", GMT_keyword_active[k].name, gmtlib_getparameter (GMT, GMT_keyword_active[k].name)); ``` 
and updating the four instances of ```GMT_keywords_updated``` to ```GMT_keyword_updated``` in ```gmtinit_conf_classic_US```. Indeed a tiny conflict, was just hoping to save a small amount of time.

**Review by PaulWessel — APPROVED** [review]
Sorry so slow - missed the email

**Comment by seisman** [comment]
It looks a little dangerous to merge this PR with so many changes. 

BTW, why do we need this PR?

**Comment by meghanrjones** [comment]
Thanks, I was actually just writing a message to ask your opinion about this method.

**Comment by PaulWessel** [comment]
Yes, we need your help.  Perhaps @meghanrjones just needs to merge master into her branch to avoid the numerous commits?

**Comment by meghanrjones** [comment]
I'll close the PR. For background, there wasn't really anything involved in this except merging master into my branch. These were the specific steps:
```
git checkout -b themes origin/gmt-themes
git checkout master
git pull
git checkout themes
git merge master
```
I fixed the gmt_init.c and the gmt.conf.rst (new) merge conflicts
```
git commit
git push meghanrjones themes
```
Then creating the pull request because I did not want to push directly to Paul's branch. I'll just wait for Paul to merge master into gmt-themes.

**Comment by seisman** [comment]
I agree that it would be easier for @PaulWessel to click the "Resolve conflicts" button directly in PR #3344.

**Comment by PaulWessel** [comment]
Will be busy with AGU next 2 hours then EXCOM meeting so if @seisman could do it then better.  if not I can do later today.

**Comment by seisman** [comment]
I'm not fully confident about merging these conflicts, so I'll leave it to you.

**Comment by PaulWessel** [comment]
OK, not to be too slow, but #3344 is  WIP so I need to remove that first, then merge and deal with the conflict discussed here:

> The current changes in gmt_themes can be accepted while updating line ~2671
> fprintf (fpo, "%-30s = %s\n", GMT5_keywords[k].name, gmtlib_getparameter (GMT, GMT5_keywords[k].name));
> to
> fprintf (fpo, "%-30s = %s\n", GMT_keyword_active[k].name, gmtlib_getparameter (GMT, GMT_keyword_active[k].name)); 
> and updating the four instances of GMT_keywords_updated to GMT_keyword_updated in gmtinit_conf_classic_US. Indeed a tiny conflict, was just hoping to save a small amount of time.

Correct?

**Comment by seisman** [comment]
There is another conflict near line 5425:
image

I'm not sure what to do with this conflict.

**Comment by meghanrjones** [comment]
What worked for me was to reject those incoming changes (L6433 - 6457 in the screenshot) and manually change the four instances of ```GMT_keywords_updated``` in the same block of code inside ```gmtinit_conf_classic_US``` to ```GMT_keyword_updated```

**Comment by meghanrjones** [comment]
The conflict occured because the gmt-themes branch moved that block of code to a separate function (gmtinit_conf_classic_us) and a recent merge into master updated ```GMT_keywords_updated``` to ```GMT_keyword_updated```

**Comment by meghanrjones** [comment]
At least, that was my interpretation

**Pull request closed without merging**
