### PR TITLE
Let each session work dir be gmt_session.#####

### PR DESCRIPTION
**Pull request by PaulWessel**
This makes session subdirs more unique and avoids using the current GMT version number as part of the name

### CODE REVIEW

**Comment by seisman** [comment]
There are more placed to be updated:
```
$ ack gmt%d.%s
src/inset.c
284:		sprintf (ffile, "%s/gmt%d.%s/gmt.frame", API->session_dir, GMT_MAJOR_VERSION, API->session_name);
343:				sprintf (ffile, "%s/gmt%d.%s/gmt.frame", API->session_dir, GMT_MAJOR_VERSION, API->session_name);

src/gmt_init.c
17557:	snprintf (file, PATH_MAX, "%s/gmt%d.%s/gmt.frame", GMT->parent->session_dir, GMT_MAJOR_VERSION, GMT->parent->session_name);

src/gmt_parse.c
282:		snprintf (file, PATH_MAX, "%s/gmt%d.%s/gmt.frame", GMT->parent->session_dir, GMT_MAJOR_VERSION, GMT->parent->session_name);
```

and Line 125 in doc/rst/source/begin.rst.

**Comment by PaulWessel** [comment]
Shit, that is a a bad system.  OK, will fix those.

**Comment by PaulWessel** [comment]
Hi @seisman, can you think of any reason why those places dont use the API->gwf_dir? It is set in gmt_begin called by GMT_Create_Session so it surely is already set when those other places are doing this?  I will go with that assumption.  gmt inset surely has already called Create_Session.

**Comment by PaulWessel** [comment]
I ran all the test with these changes and they all pass (minus the two known gdal_nn and grdimage_img_tif.sh).

**Comment by PaulWessel** [comment]
if @seisman want to run all tests in the CI to be very sure than that is fine with me.

**Comment by seisman** [comment]
@PaulWessel I just triggered the tests in the CI.

**Comment by PaulWessel** [comment]
I dont understand what is failing here, @seisman ?

**Comment by joa-quim** [comment]
It's ``grdimage_img_tif.sh`` It fails on the Windows CI too but not for me locally. However, my threshold is 0.005 while for the CI it's 0.003

```
6/9 Test #391: grdimage/grdimage_img_tif.sh .....***Failed   19.11 sec
C:\Program Files\GraphicsMagick-1.3.32-Q8\gm.exe compare: image difference exceeds limit (0.00448453 > 0.003).
grdimage/grdimage_img_tif.ps: RMS Error = 0.0045 [FAIL]
```

**Comment by seisman** [comment]
yes, everything is good. The only failure is `grdimage_img_tif.sh`.

**Pull request merged**
