### PR TITLE
Only check for -A or -S if events is not just plotting labels

### PR DESCRIPTION
**Pull request by PaulWessel**
See #4742  for details.  The failing error check predates the **-A** addition so the check did not consider a user just plotting labels.  Now we only give that error if the user also set **-Es**. Let me know if this works for you too, @Esteban82.

### CODE REVIEW

**Review by joa-quim — APPROVED** [review]

**Comment by Esteban82** [comment]
Is this to suppose to fix the bug? Because a installed the branch 'events-labels-only' (I suppose I did it well) and I still get the same error.

**Comment by PaulWessel** [comment]
Well, yes, and it works for me:

**this branch:**

`gmt events -Rg MOR_names.txt -L100 -Et+r6+f6 -T200 -F+f12p,Helvetica-Bold,yellow -JH6i -B -pdf t`

**master:**
```
gmt events -Rg MOR_names.txt -L100 -Et+r6+f6 -T200 -F+f12p,Helvetica-Bold,yellow -JH6i -B -pdf t
events [ERROR]: Must specify either -A or -S.
```

Sure you built and run the branch code?

**Comment by seisman** [comment]
> Is this to suppose to fix the bug? Because a installed the branch 'events-labels-only' (I suppose I did it well) and I still get the same error.

You can run `gmt --version` to check if you're using the correct version.

**Comment by Esteban82** [comment]
> Sure you built and run the branch code?

No, I am not. I have Version 6.2.0_b7eaa8f_2021.01.29. I think that it is from a week ago. I will check what it happening.

**Comment by PaulWessel** [comment]
Hi @Esteban82, let me know if I can merge this PR.  I think is is correct since it works for me.

**Comment by Esteban82** [comment]
Hi @PaulWessel. I think that there is still a a problem. I had a problem with the path. I fix it and I managed to install the branch (Version 6.2.0_398d1c1_2021.02.03). 

Now I have NOT any error message. I run the animation 09 (with a lower resolution grid) for the frame 15 and I get this image: 


anim09

**Comment by PaulWessel** [comment]
Thanks, I will look at this.  This is a different issues than the -A -S error, but there must be some regression somewhere since those values are the frame appearances and should be used but not plotted.

**Comment by PaulWessel** [comment]
Hi @Esteban82, there was one more place where I had an if-test that needed some work to do this right.  With this fix I get those labels again.  Please refresh the branch, build, and let me know.

**Comment by Esteban82** [comment]
Done. Now the figure is fine.

**Comment by PaulWessel** [comment]
Thanks, merging and closing.

**Pull request merged**
