### PR TITLE
Must close file before delete it

### PR DESCRIPTION
**Pull request by joa-quim**
Fix broken situation on Windows with the lock files where files cannot be deleted if they were not closed,

### CODE REVIEW

**Comment by PaulWessel** [comment]
THink this need backport, no? @seisman ?

**Comment by seisman** [comment]
No bakport. The whole file lock feature is not backported.

**Comment by joa-quim** [comment]
Hmm, why not?

**Comment by seisman** [comment]
Perhaps because it's not a big issue? Of course, we can backport them (https://github.com/GenericMappingTools/gmt/pull/3735, https://github.com/GenericMappingTools/gmt/pull/3768, https://github.com/GenericMappingTools/gmt/pull/3780, https://github.com/GenericMappingTools/gmt/pull/3785) if you want.

**Comment by seisman** [comment]
This PR can't be backported to 6.1 branch automatically. If you still want to backport it, we need to backport these PRs (#3735, #3768, #3780, #3785) first.

**Comment by PaulWessel** [comment]
Given the number of bugs we are finding I think we need a 6.1.1 soon.  So perhaps porting the lockfile stuff is a good decision.

**Comment by joa-quim** [comment]
Then must be next only. 

Sent from my iDedo

**Pull request merged**
