### PR TITLE
Missed one check on format strings

### LINKED ISSUE #3620: gmt convert crashes if FORMAT_GEO_OUT is blank
Obscure stuff, but still. If you forget to tell GMT what template to use you get a crash:

```
$ echo 2.79334970 79.16202276 | gmt convert --FORMAT_GEO_OUT=
ERROR: Caught signal number 11 (Segmentation fault) at
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f2da1431e20]
/lib/x86_64-linux-gnu/libnssutil3.so(+0x2a000)[0x7f2d9a3ec000]
Stack backtrace:
/usr/local/lib/libgmt.so.6(sig_handler+0x2ab)[0x7f2da13c89ab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f2da136a3c0]
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f2da1431e20]
/usr/local/lib/libgmt.so.6(gmtlib_geo_C_format+0x43)[0x7f2da143c183]
/usr/local/lib/libgmt.so.6(gmtlib_setparameter+0x187d)[0x7f2da14eb00d]
/usr/local/lib/libgmt.so.6(gmt_parse_common_options+0xc05)[0x7f2da1502955]
/usr/local/lib/libgmt.so.6(GMT_Parse_Common+0x542)[0x7f2da14c8dc2]
/usr/local/lib/libgmt.so.6(GMT_gmtconvert+0x17a)[0x7f2da15ab7ea]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x3d5)[0x7f2da13e6295]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x634)[0x7f2da13e64f4]
gmt(main+0xb84)[0x564033d6cee4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f2da118a0b3]
gmt(_start+0x2e)[0x564033d6d60e]
```

Using bleeding edge master.

### PR DESCRIPTION
**Pull request by PaulWessel**
Closes #3620.

### CODE REVIEW

**Comment by PaulWessel** [comment]
If @anbj is on vacation (what is that, my US dictionary has no hits) then I think @joa-quim or @seisman have to stop up to the plate and approve.

**Comment by seisman** [comment]
Again, 6.1 or master?

**Comment by PaulWessel** [comment]
Clearly not critical so lets do master.

**Comment by seisman** [comment]
FYI, I'm exploring this application (https://mergify.io/features/backports). It looks a good way to do the backports automatically.

**Pull request merged**
