### PR TITLE
cmake: Simplify CMake scripts for supplemental packages

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Each supplemental package must provide its own CMakeLists.txt.
Currently, each CMakeLists.txt file has to define some CMake variables,
install module symbolic links, install example data and header files.

An example cmake file from `seis` is shown below:
```
set (SUPPL_NAME seis)

# source files
set (SUPPL_HEADERS meca.h utilmeca.h sacio.h)
set (SUPPL_LIB_SRCS utilmeca.c sacio.c)
set (SUPPL_PROGS_SRCS psmeca.c pspolar.c pscoupe.c pssac.c)

# example files
set (SUPPL_EXAMPLE_FILES README.seis)

# lib sources
set (LIB_SRCS ${SUPPL_LIB_SRCS} ${SUPPL_PROGS_SRCS})

# create build targets
string (REPLACE ".c" "" _gmt_modules "${SUPPL_PROGS_SRCS}")
install_module_symlink (${_gmt_modules})

# install example data
install (FILES ${SUPPL_EXAMPLE_FILES}
	DESTINATION ${GMT_DOCDIR}/supplements/${SUPPL_NAME}
	COMPONENT Documentation)

# install headers
if (BUILD_DEVELOPER)
	install (FILES ${SUPPL_HEADERS}
		DESTINATION ${GMT_INCLUDEDIR}/${SUPPL_NAME}
		COMPONENT Runtime)
endif (BUILD_DEVELOPER)
```

This PR simplify the CMakeLists.txt file of supplemental packages by moving
all the cmake install commands to the top `src/CMakeLists.txt`.
Now we only need to provide a few variables in `seis/CMakeLists.txt`.

```
set (SUPPL_NAME seis)

# source files
set (SUPPL_HEADERS meca.h utilmeca.h sacio.h)
set (SUPPL_LIB_SRCS utilmeca.c sacio.c)
set (SUPPL_PROGS_SRCS psmeca.c pspolar.c pscoupe.c pssac.c)

# example files
set (SUPPL_EXAMPLE_FILES README.seis)

# lib sources
set (LIB_SRCS ${SUPPL_LIB_SRCS} ${SUPPL_PROGS_SRCS})
```

---

**Still work in process. I'll improve it if you think it's good.**

### CODE REVIEW

**Comment by joa-quim** [comment]
Look good and life simplifier but I don't have much time to test this, specially on adapting it for the MB build.

**Comment by seisman** [comment]
It now only works for GMT's supplemental packages. Further work is needed for third-party plugins.

**Comment by joa-quim** [comment]
OK, (but I know how it works, one thing leads to the other and I'll be tempted to update my MB scripts).

**Comment by seisman** [comment]
This PR is ready for review.

**Pull request merged**
