### PR TITLE
Let GMT examine if the DCW file has a minimum version requirement

### PR DESCRIPTION
**Pull request by PaulWessel**
Since DCW 1.2.0 is not compatible with GMT 6.1.0 or earlier, we have added a check in the latest GMT to see if a minimum gmt version string exists in DCW (it does from 1.2.0 onwareds) and if so determine if this GMT version passes the test.

dcw-gmt-1.2.0.tar.gz and zip are available for testing purposes in the usual pwessel/release ftp folder.

### CODE REVIEW

**Comment by joa-quim** [comment]
As I said in the other thread, the version name must be 2.0 because it breaks compatibility.

**Comment by seisman** [comment]
Yes, it should be 2.0.0 if we follow semantic versions strictly.

**Comment by PaulWessel** [comment]
You guys make me do so much work on Wednesdays...OK, will rebuild.

**Comment by PaulWessel** [comment]
OK, files on the ftp is now 2.0.0.

ftp.soest.hawaii.edu/pwessel/release/dcw-gmt-2.0.0.tar.gz
ftp.soest.hawaii.edu/pwessel/release/dcw-gmt-2.0.0.zip

**Comment by PaulWessel** [comment]
Please install DCW 2.0.0, edut your cmake settings and rebuild master and give it a spin.  Apart from generally working, you can try these

```
gmt coast -RZA -EZA+gred -Ggray -B -png ZAmap
gmt coast -RIT -EIT+gred -Ggray -B -pdf ITmap
```

If you zoom in on the ITmap you should clearly see the San Marino hole and if you zoom all in you will see a tiny hole in Rome for the Vatican.

**Comment by PaulWessel** [comment]
And right now I cannot make it work for me... I think all I did was to change the version number. And building this branch, but let me try to figure this out first [middle of GMTSAR short course...]

**Comment by joa-quim** [comment]
Yep, not working for me neither.

**Comment by PaulWessel** [comment]
Very odd, worked fine last night... So yet another debug effort.

**Comment by PaulWessel** [comment]
I ahve too many noncommitted branches.  This one adds the check but it is not the one that makes plots.

**Comment by PaulWessel** [comment]
OK, so this branch only adds the checking so makes no difference since the test passes.  This is just for future checking of minimum GMT version required to use a particular DCW version.

**Comment by PaulWessel** [comment]
And after merging the other branch now this one works as advertised.

**Comment by joa-quim** [comment]
OM, it works for me too but you need to set the backports

**Comment by PaulWessel** [comment]
Hm, did not set backport on the first one. @seisman how do we handle this if I backport this one?

**Comment by PaulWessel** [comment]
Ok the first has now been safely backported and this one has been labeled.

**Pull request merged**
