### PR TITLE
Set curl user agent to meet some data servers' requirements

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

I'm unsure if you can reproduce it, but I can't use the China data server recently.

Here is the command to reproduce the issue:
```
$ gmt clear data
$ gmt set GMT_DATA_SERVER https://mirrors.ustc.edu.cn/gmtdata
$ gmt grdinfo @earth_relief_01d_g                            
grdinfo [NOTICE]: Remote data courtesy of GMT data server https://mirrors.ustc.edu.cn/gmtdata [https://mirrors.ustc.edu.cn/gmtdata]

grdinfo [NOTICE]: SRTM15 Earth Relief v2.5.5 at 1x1 arc degrees reduced by Gaussian Cartesian filtering (111.2 km fullwidth) [Tozer et al., 2019].
grdinfo [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_g.grd
grdinfo [ERROR]: Libcurl Error: HTTP response code said error
grdinfo [ERROR]: Probably means @earth_relief_01d_g.grd does not exist on the remote server
grdinfo [ERROR]: Unable to obtain remote file @earth_relief_01d_g.grd
grdinfo [ERROR]: Must specify one or more input files
```

After trial and error, I find that the China server (and maybe also others) requires the curl user agent (https://everything.curl.dev/http/requests/user-agent) to be set. The user agent can be any string but it must be set. 

This PR sets the curl user agent to a string like "GMT/6.4.0". After the patch, I can download data files from the China server successfully.

### CODE REVIEW

**Comment by seisman** [comment]
I just tried this branch with all data server mirrors. They all work well, so changes in this branch has no side-effects.
```
for mirror in oceania brasil australia china sdsc-opentopography noaa portugal singapore south-africa; do
	gmt clear data
	gmt set GMT_DATA_SERVER $mirror
	gmt grdinfo @earth_relief_01d -C
done
```

**Comment by seisman** [comment]
I use the following script to the all GMT server mirrors:
```
for mirror in oceania brasil australia china sdsc-opentopography noaa portugal singapore south-africa; do
	echo "### $mirror ###"
	gmt clear data
	gmt set GMT_DATA_SERVER $mirror
	gmt grdinfo @earth_relief_01d_g -C
done
```
- With the GMT master branch, china/noaa/singapore mirrors don't work. 
- With this branch, china mirror work, and noaa/singapore mirrors still don't work.

It seems NOAA and Singapore mirrors are offline.

**Comment by seisman** [comment]
ping @PaulWessel

**Comment by WalterHFSmith** [comment]
Happy to ping, but what exactly am I looking for?

**Comment by PaulWessel** [comment]
Sorry, this is the list of [mirrors](https://www.generic-mapping-tools.org/mirrors/) and while only Singapore is clearly down (red circle), NOAA does not respond either.

**Comment by seisman** [comment]
@PaulWessel The offline NOAA and Singapore mirrors are not related to this PR, so this PR can be reviewed and approved, right?

**Review by PaulWessel — APPROVED** [review]
Sorry, forgot

**Pull request merged**
