### PR TITLE
Update in the docs to netcdf 1.7

### PR DESCRIPTION
**Pull request by Esteban82**
I create a grid and I saw with grdinfo that the files formats are CF-1.7 (not CF-1.5).

I made this PR to update this.

Approve ONLY if it is correct

### CODE REVIEW

**Review by seisman — APPROVED** [review]
Looks correct to me.

**Comment by joa-quim** [comment]
But why are we doing this? Nothing changed in the netCDF usage. What is the difference between CF 1.5 and CF 1.7 that affects anything we use in GMT?

**Comment by seisman** [comment]
Just make the documentation consistent with the GMT output.

**Comment by joa-quim** [comment]
OK. Still think useless CI Joules burning, but OK.

**Comment by Esteban82** [comment]
> But why are we doing this? Nothing changed in the netCDF usage. What is the difference between CF 1.5 and CF 1.7 that affects anything we use in GMT?

I agree, nothing major. But I'm going to teach a class on GMT grid formats and I want the documentation to say the same thing as the terminal information. If I was sure, I would have modified it directly on master.

**Comment by joa-quim** [comment]
Than the most correct thing to do is to remove that CF info from the grdinfo print. The thing is that the ndetCDF grids are **not** a GMT format and can, and actually are, be produced by many different programs. They are all reported to conform with CF1.7, but we have no idea if that is even true.

**Pull request merged**
