### PR TITLE
Fix the lack of precision in -Ib

### PR DESCRIPTION
**Pull request by PaulWessel**
The **-Ib** option outputs the bounding box of the grid.  But it failed to do so at the increment resolution and instead only output the 5 corner points.  That meant that projecting this polygon would fail to outline the polygon in an oblique projection. This PR corrects this bug by sampling the perimeter at the grid spacing.  Because pixel and gridline-registered grids have the save w/e/s/n but different node coordinates we make sure both types give the correct outer box and that the polygon is closed.

### CODE REVIEW

**Comment by PaulWessel** [comment]
## Basic checks

_Pixel grid:_
```
gmt grdmath -R-3000/2600/-800/800 -I100 -r 0 = p.grd
gmt grdinfo -Ib p.grd > pix_perim.txt
```

_Gridline grid_
```
gmt grdmath -R-3000/2600/-800/800 -I100  0 = g.grd
gmt grdinfo -Ib g.grd > grid_perim.txt

```

**Comment by meghanrjones** [comment]
There are a few grdblend failures on this branch:
```
The following tests FAILED:
	392 - test/grdblend/center_bf_p.sh (Failed)
	394 - test/grdblend/center_cf_p.sh (Failed)
	396 - test/grdblend/center_nf_p.sh (Failed)
```

**Comment by PaulWessel** [comment]
I had those before I made my update using the new gmt_grid_perimeter function and then I got no failures... I suppose they are tiny differences between the 5-point polygon and the detailed outline?

**Review by meghanrjones — APPROVED** [review]

**Comment by meghanrjones** [comment]
> I had those before I made my update using the new gmt_grid_perimeter function and then I got no failures... I suppose they are tiny differences between the 5-point polygon and the detailed outline?

I was on a commit from before the update. Works fine with the latest changes.

**Comment by PaulWessel** [comment]
Puh!

**Comment by PaulWessel** [comment]
Let me add a non-plot test just in case.  Will take me a few minutes.

**Pull request merged**
