### PR TITLE
CPT to plot magnetic anomaly maps.

### PR DESCRIPTION
**Pull request by joa-quim**
It's the one used in IPGP for decades

### CODE REVIEW

**Comment by joa-quim** [comment]
The ``GMT_App_M_1?`` are complicated and the three pages are full. What you mean _do it in the cache_

**Comment by joa-quim** [comment]
And speaking of new CPT's. Shouldn't we add the [new rainbow](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html?m=1) from Google that I mentioned you?

**Comment by PaulWessel** [comment]
There is room for adding a pair of CPTs so if you get the google one too.  However, that one has no hinge and should be normalized to 0-1 in z (see others).  I think the mag has a hinge (zero mag) but no zero entry in the CPT.  It would probably be best to split that -50 to 50 up in to -50 to 0 and 0 to 50 for that reason, and add the HINGE flag.
I can help with App M.

**Comment by PaulWessel** [comment]
OK, what do we call the google cut? google? spectrum?  Once you add it I can go to work on App M.

**Comment by joa-quim** [comment]
Well, they called it _turbo_. It's a stupid name but that's how it's going to be known.
Still trying to see how to reformat it.

**Comment by PaulWessel** [comment]
OK, turbo is fine since it is not already used.

**Comment by PaulWessel** [comment]
Need entry in gmt_cpt_masters.h for turbo.

**Comment by joa-quim** [comment]
Done. I think this turbo is a candidate to a new default CPT (if that is still on the table)

**Comment by PaulWessel** [comment]
So some difficulty with App. We have 71 CPTs in gmt_cpt_masters.h, but one we skip (srtm which is same as dem4 on land only).  So 70 minus the 24 from Fabio = 46.  To split into two pages with two columns that number needs to be divisible by 4.  So we actually need 48.  Are we able to come up with 2 more CPTs.

**Comment by PaulWessel** [comment]
How about cequal [http://soliton.vm.bytemark.co.uk/pub/cpt-city/imagej/tn/cequal.png.index.html] and columbia [http://soliton.vm.bytemark.co.uk/pub/cpt-city/wkp/shadowxfox/index.html]?

**Comment by joa-quim** [comment]
And what about dropping 2? We already have more than enough generic ones.

**Comment by PaulWessel** [comment]
Would give backwards compatibility headaches.  Better to add two.  OK, could remove two from the table but leave in share - that is backwards compatible since the gmt_cpt_masters.h is only used for listing (and by App M).  What to remove?

**Comment by PaulWessel** [comment]
Maybe seafloor and wysiwyg?

**Comment by joa-quim** [comment]
wysiwyg is a good candidate. And the _acton_? We only break some compat if remove old ones. New ones were technically never really released.

**Comment by PaulWessel** [comment]
acton is part of Fabio so does not help with the 24 problem.

**Comment by PaulWessel** [comment]
I think seafloor is pretty useless and there is ibcao, bathy, abyss already.

**Comment by joa-quim** [comment]
Yes, we have several seaflors. Panoply seems pretty useless too.

**Comment by PaulWessel** [comment]
I'll remove seafloor and wysiwyg.  Remko loves panoply...

**Comment by seisman** [comment]
Why do we have to remove two CPT? Can we list all 70 cpts in one long paper? Or can we have 24, 22, and 24 cpts in three pages?

**Comment by PaulWessel** [comment]
OK, done and updated M 1b PS.  Now for discussion of turbo vs rainbow.  I would think we agree that turbo is a much improved rainbow without being washed out as in Fabio, no?  Maybe @seisman might agree as well?

**Comment by PaulWessel** [comment]
Words of wisdom from @seisman. We don't have to make 3 separate M plots.  We could keep the Fabio stuff separate and then do everything else as a longer page.  We are no longer dealing with page plotting.  I will see what I can do - the App M script is messy...

**Comment by seisman** [comment]
I once tried to rewrite the three App M scripts with subplot. It's more readable but much slower.

**Comment by PaulWessel** [comment]
I got things to fit as @seisman suggested with 24, 22, 24 on three pages.
Opinions on making turbo the new rainbow default CPT in GMT 6?

**Comment by PaulWessel** [comment]
Changing to turbo will probably affect some of our PS origs.

**Comment by seisman** [comment]
I have no objection.

**Comment by joa-quim** [comment]
I'm very favorable. It's not only the perceptual thing but also that it drops the violet, which always felt wrong on topography maps.

**Comment by PaulWessel** [comment]
Running all tests but having trouble:

psxy [ERROR]: Unable to down file http://oceania.generic-mapping-tools.org/gmt_md5_server.txt

Not sure why this is happening but I have seen it before.  So lots of failures obviously if we cannot get the cache files.

**Comment by PaulWessel** [comment]
We are finding out that possibly due to a UH firewall change, nodes INSIDE the UH network cannot access oceania but nodes on the outside can. The SOEST IT staff says it has nothing to do with the SOEST firewall, but there seems to be some infinite loop being set up when we try within UH.

**Comment by seisman** [comment]
I'm back now. Should I push the updated PS files to this branch?

**Comment by PaulWessel** [comment]
Yes please, I am unable to access the cache since I am inside the UH network...

**Comment by PaulWessel** [comment]
So if tests pass for you then I guess we can merge this PR?

**Comment by PaulWessel** [comment]
Implemented.

**Pull request merged**
