### PR TITLE
No remote, no refresh

### LINKED ISSUE #4497: White lines and white MAP_FRAME_PEN don't go along.
```
printf "0.0 0\n1.1 1" | gmt plot -JX12c/8c -Baf -BWSen+tBLA -R-0.04/1.12/-0.04/1.04  --MAP_FRAME_PEN=thicker,white --PS_PAGE_COLOR=gray -W1,white -png lixo
```

lixo

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

Only call _gmt_refresh_server_ when we know a remote file is being requested.  This should conclude and close #4497.

### CODE REVIEW

**Comment by PaulWessel** [comment]
BTW, cannot see where **gmt begin** enters into this, but perhaps you can point to it.

**Comment by joa-quim** [comment]
I was looking at the gmt-themes branch and there gmt_begin() calls ``gmtlib_refresh_server()``

**Review by joa-quim — APPROVED** [review]

**Comment by PaulWessel** [comment]
Hm, I will look at gmt-themes - it is hard to keep up those now old branches as master moves forward.  I have merged a thousand times but there were some conflicts and perhaps I messed up one.

**Comment by PaulWessel** [comment]
Cannot find any call to _gmtlib_refresh_server_ in the gmt-themes branch and the function does not exist.  After #4499 there is still a call to _gmt_refresh_server_ but that only happens if it finds a file on the command line that starts with @ (not counting memory files).

**Comment by joa-quim** [comment]
I was not dreaming
image

but missed a ``git pull`` after switching to the branch (thought the *master* update also updated the branches).

**Comment by PaulWessel** [comment]
Yes, it is gone now and for some time I think.

**Pull request merged**
