### PR TITLE
gmtspatial.rst: fix typo

### PR DESCRIPTION
**Pull request by anbj**
Fix link to `-W`.
Please review the `*distf*\[*unit*]/*distl*\[*unit*]` part.
Not completely sure about this one.

### CODE REVIEW

**Comment by PaulWessel** [comment]
OK, will have to build the docs to know I think . Did you build the docs locally and verified it looks corect?

**Comment by anbj** [comment]
I did not. I could, but will have to wait until tomorrow. 'distf' and 'distl' should be slanted, right=

**Comment by PaulWessel** [comment]
Yes, all italics.  I am not sure how to build from a branch that is not in the regular repo...

**Comment by meghanrjones** [comment]
> Yes, all italics. I am not sure how to build from a branch that is not in the regular repo...

```
git fetch origin pull/6808/head:fix-typo
git checkout fix-typo
```

**Comment by anbj** [comment]
I've had this problem before, but I don't remember how to fix it - any help?

```
$ cmake --build . --target docs_html
[  0%] Copying doc/rst/source ...
[  0%] Built target _docs_copy_rst_tree_source
[  0%] Built target _docs_rst_mkdir_verbatim
[  0%] Built target script2verbatim
[ 15%] Built target _docs_examples_verbatim
[ 16%] Copying doc/rst/_extensions ...
[ 16%] Built target _docs_copy_rst_tree__extensions
[ 16%] Copying doc/rst/themes ...
[ 16%] Built target _docs_copy_rst_tree_themes
[ 16%] Copying doc/rst/_templates ...
[ 16%] Built target _docs_copy_rst_tree__templates
[ 16%] Built target _docs_rst_src
[ 16%] Copying doc/rst/_static ...
[ 16%] Built target _docs_copy_rst_tree__static
[ 16%] Built target _docs_rst_mkdir_images
[ 20%] Built target _docs_copy_fig
[ 20%] Built target gen_gmt_headers
[ 21%] Built target pslib
[ 52%] Built target gmtlib
[ 54%] Built target gmt
[ 54%] Built target gmt_for_img_convert
gmake[3]: *** No rule to make target 'doc/scripts/images/GMT_RGBchart.ps', needed by 'doc/rst/source/_images/images/GMT_RGBchart.pdf'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:1355: doc/scripts/CMakeFiles/_docs_html_scripts_fig.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1307: doc/rst/CMakeFiles/docs_html.dir/rule] Error 2
gmake: *** [Makefile:569: docs_html] Error 2
```

**Comment by PaulWessel** [comment]
I cannot recall if you installed dvc etc and did a 
dvc pull
at the top GMT directory before running those commands, but that is needed to get the latest PS files used by the docs.

**Comment by anbj** [comment]
> I cannot recall if you installed dvc etc and did a dvc pull at the top GMT directory before running those commands, but that is needed to get the latest PS files used by the docs.

Sorry; Yes, I did.

**Comment by anbj** [comment]
```
 $ dvc pull
Everything is up to date.

$ cmake --build . --target docs_html --parallel $(nproc)
[  1%] Copying doc/rst/source ...
[  1%] Copying doc/rst/themes ...
[  1%] Copying doc/rst/_templates ...
[  1%] Copying doc/rst/_static ...
[  1%] Built target script2verbatim
[  1%] Built target _docs_html_examples_fig
[  1%] Copying doc/rst/_extensions ...
[  1%] Built target gen_gmt_headers
[  1%] Built target _docs_copy_rst_tree_themes
[  1%] Built target _docs_copy_rst_tree__templates
[  1%] Built target _docs_copy_rst_tree__static
[  2%] Built target pslib
[  2%] Built target _docs_copy_rst_tree__extensions
[  2%] Built target _docs_copy_rst_tree_source
[  2%] Built target _docs_rst_src
[  2%] Built target _docs_rst_mkdir_images
[  2%] Built target _docs_rst_mkdir_verbatim
[ 17%] Built target _docs_examples_verbatim
[ 49%] Built target gmtlib
[ 94%] Built target _docs_scripts_verbatim
[ 97%] Built target gmt
[ 98%] Built target _docs_copy_fig
[ 98%] Built target gmt_for_img_convert
gmake[3]: *** No rule to make target 'doc/scripts/images/GMT_RGBchart.ps', needed by 'doc/rst/source/_images/images/GMT_RGBchart.pdf'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:1355: doc/scripts/CMakeFiles/_docs_html_scripts_fig.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1307: doc/rst/CMakeFiles/docs_html.dir/rule] Error 2
gmake: *** [Makefile:569: docs_html] Error 2
```

**Comment by PaulWessel** [comment]
Sorry, need smarter people like @seisman or @meghanrjones to help with this...

**Comment by anbj** [comment]
Very interesting. When did this power flow to me?

See #6811 for new and fresh PR.

**Comment by anbj** [comment]
Don't spend more time on the PR - I'll close it, but I would like to get the problems with builing the docs sorted out please.

**Comment by PaulWessel** [comment]
Not sure and perhaps we forgot to tell you...but you are now a trusted entity!

**Comment by anbj** [comment]
I feel blessed!

**Comment by anbj** [comment]
Shit.

**Comment by anbj** [comment]
Thanks for the info @meghanrjones!

And, my mistake regarding problems building the docs. See #6812. Closing.

**Pull request closed without merging**
