### PR TITLE
Add a API test for checking passing vectors and strings to pstext

### PR DESCRIPTION
**Pull request by seisman**
Here is a C code which passes *x, y, angle, justify, text* to pstext. It should be equivalent to the following bash script:
```
gmt text -JX10c -R0/10/0/10 -Baf -F+a+j -Vd > testapi_vector_strings.ps << EOF
5.0 3.0 30.0 ML First Label
5.0 8.0 60.0 MR Second Label
EOF
```

However, it seems the *angle* is not correctly passed. 

**Output of the C code**

image

**Output of the bash script:**

image

Anything wrong?

### CODE REVIEW

**Comment by PaulWessel** [comment]
Problem was your dim[0] = 2 but you have three columns.  And _GMT_Put_Vector_ returns an error but not checked by main.  It does not print a message.  We have lots of places where we don't print a message but return error code.  Maybe we should always print an error?

**Comment by seisman** [comment]
> Problem was your dim[0] = 2 but you have three columns.

Yes, changing it to 3 works!

> We have lots of places where we don't print a message but return error code. Maybe we should always print an error?

Not sure whether it's necessary, but at least PyGMT checks the return error code carefully.

**Comment by PaulWessel** [comment]
OK, maybe commit your dim edit and I can approve this merge?

**Comment by seisman** [comment]
Will do it later and also add a test.

**Comment by seisman** [comment]
@PaulWessel Done.

**Pull request merged**
