### PR TITLE
movie.rst: create table for preset video formats

### PR DESCRIPTION
**Pull request by anbj**
Create table of preset video formats. Easier to read. Consider removing the descriptions in the paragraph.

### CODE REVIEW

**Comment by Esteban82** [comment]
Great idea @anbj. 

I have my own table where I add columns with pixel density (px/cm and px/inch). I wonder if it is worth including it.

**Comment by anbj** [comment]
Please do if you think it’s useful. 

My git expertise is not good enough; can you do commits to this branch in any way? Or maybe you can add it later.

**Comment by Esteban82** [comment]
I think I can commit but I am not really sure if it is useful. We can always add it later.

**Review by meghanrjones — APPROVED** [review]
Great, thanks!

I agree with removing the descriptions from the paragraph above, do you mind if I commit that change to this branch before merging?

**Comment by anbj** [comment]
Not at all - please do. Thanks!

**Pull request merged**
