### PR TITLE
coast.rst: only use abbreviations when specifying continent

### LINKED ISSUE #6444: Can't specify continent with full name in -E
From [coast man](https://docs.generic-mapping-tools.org/dev/pscoast.html#e):

*Append =continent to specify a continent, using either the full names or the abbreviations AG (Africa), AF (Africa), AN (Antarctica), AS (Asia), EU (Europe), OC (Oceania), NA (North America), or SA (South America).*

Abbreviations works:

```
gmt coast -E=EU+gblack -png test
```

Full name does not:
```
gmt coast -E=Europe+gblack -png test
coast [WARNING]: Continent code =Europe unrecognized
coast [ERROR]: South is outside -90 to +90 degree range
coast [ERROR]: General map projection error
```

### PR DESCRIPTION
**Pull request by anbj**
* This ~~makes~~ closes #6444 ~~go away~~, by removing the part in the docs that says continents may be specified by using full names or abbreviations.
* Ideally, one should be able to use full names, but it's not:

```
$ gmt pscoast -E=Europe
pscoast [WARNING]: Continent code =Europe unrecognized
-R0/0/9999/-9999
```

### CODE REVIEW

**Comment by PaulWessel** [comment]
Checking with @Esteban82 if this is what is expected.

**Comment by Esteban82** [comment]
> * Ideally, one should be able to use full names, but it's not:

These work:

```
 gmt pscoast -EEurope
-R-10.4842/66.9097/34.802/71.1838    # This is from the DCW-Collections

gmt pscoast -E=EU
-R-73.263466/40.218071/27.638819/83.627419    # This is a region that include all the european countries
```

The list of european countries are here: https://github.com/GenericMappingTools/dcw-gmt/tree/master/orig/EU

**Comment by anbj** [comment]
Ok, so ``-E=<code`` and ``-E<full name>``?

**Comment by Esteban82** [comment]
> Ok, so `-E=<code>`

"Continent" code.

**Comment by Esteban82** [comment]
> - Append =\ *continent* to specify a continent, using the abbreviations AF (Africa),
>       AN (Antarctica), AS (Asia), EU (Europe), OC (Oceania), NA (North America), or SA (South America).


I think this is obsolete. People should use DCW-Collections instead. Then I think we should:

1) Clarify in the text that it is not a continent but a list of countries (which fits as much as possible to the continent but is not ideal). It is suggested to use the DCW-Collections for a better definition, or: 
2) Remove it from the documentation.

**Comment by PaulWessel** [comment]
Guys, were are we with this? Close or action?

**Comment by anbj** [comment]
I need to read up on this again, but if @Esteban82 has any thoughts (which he remembers), I'll wait for his response.

**Comment by Esteban82** [comment]
> I need to read up on this again, but if @Esteban82 has any thoughts (which he remembers), I'll wait for his response.

Yes, see my last post. 
So, basically replace "continent" by " list of countries (which fits as much as possible to the continent but is not ideal)". 
Or, just remove that line. Is too confusing. People should use the DCW collections.

**Comment by anbj** [comment]
Good, I'll look at it tomorrow.

**Comment by anbj** [comment]
Oh, I see you made a change. Good to go?

**Comment by Esteban82** [comment]
It was another thing. 

But, I can make the change. What option do you prefer me to do?

**Comment by anbj** [comment]
I'm talking about DCW proper here, not the collection.

The [coast docs](https://docs.generic-mapping-tools.org/dev/coast.html#e) says *Append =continent to specify a continent, using either the full names or the abbreviations AF (Africa), AN (Antarctica), AS (Asia), EU (Europe), OC (Oceania), NA (North America), or SA (South America).*

Abbrev. works:
```
$ gmt pscoast -E=EU
-R-73.263466/40.218071/27.638819/83.627419
```

Full name does not:
``` 
$ gmt pscoast -E=Europe
pscoast [WARNING]: Continent code =Europe unrecognized
-R0/0/9999/-9999
```

Therefore, I propose that the line *..using either the full names or the abbreviations..* is changed to *..using the abbreviations..*

And when writing this, I try all in CAPS, and suddenly, full name *does work*::

```
 $ gmt pscoast -E=EUROPE
-R-73.263466/40.218071/27.638819/83.627419
```

What's the logic here?

**Comment by joa-quim** [comment]
> What's the logic here? Case sensitive?

Programmers logic. Search only the min chars necessary

```
C:\v>gmt pscoast -E=EUrope
-R-73.263466/40.218071/27.638819/83.627419
```

**Comment by anbj** [comment]
Ah, so it catches EU and thinks I mean the abbreviation. Thanks.

Then my post above applies; full name is not understood, so it should be removed from the docs.

**Review by Esteban82 — APPROVED** [review]

**Comment by PaulWessel** [comment]
Works with full names:

gmt pscoast -EAfrica,Europe
-R-17.5338/66.9097/-34.8304/71.1838

**Comment by Esteban82** [comment]
> Works with full names:
> 
> gmt pscoast -EAfrica,Europe -R-17.5338/66.9097/-34.8304/71.1838

Yes, becuase you are using the DCW-Collections.

**Comment by PaulWessel** [comment]
Well, since it cost nothing for people to upgrade their DCW and get the collections, do we really worry about older setups?

**Comment by Esteban82** [comment]
Sí, estoy de acuerdo. La sugerencia de anbj es correcta. Pero creo que debemos ir más allá y eliminar esa frase para animar a los usuarios a utilizar directamente las colecciones DCW.

**Comment by anbj** [comment]
Muchas gracias @Esteban82 !

I know I'm being a pain here.
My point is just to make the docs reflect what is actually possible.
P.t. you cannot give a full name to ``-E``, e.g. ``-E=Europe`` - it does not work -> delete the part of the sentence saying so; hence this PR. The best would of course be to make it work.

**Comment by Esteban82** [comment]
I think that this can be merge. I can't do it myself (I don't have permission). And the missing checks will never be executed (as far as I know) because the code was not modified (only the documentation).

**Comment by seisman** [comment]
Aslo need to update the classic pscoast.rst.

**Comment by anbj** [comment]
> Aslo need to update the classic pscoast.rst.

I cant see that this is mentioned in pscoast.rst?

**Comment by seisman** [comment]
Sorry, my bad. Then this PR should be good to merge.

**Pull request merged**
