### PR TITLE
Add test for passing text dataset to legend

### PR DESCRIPTION
**Pull request by PaulWessel**
Basically replicates the situation in #6336.

@joa-quim, might you be able to try this branch and build all and then run the` testapi_text_legend > junk.ps `command? It should crash as well since it is basically doing your case - but perhaps things are easier to see.

### CODE REVIEW

**Comment by joa-quim** [comment]
Can't right now. Poor computer is melting with all cores working.

**Comment by meghanrjones** [comment]
Can you provide more guidance about how I can help as a reviewer on this PR? On windows, I added -Vd to the module arguments, added `testapi_text_legend` to gmtest.in, and added a shell script in `test/api` to confirm that it crashes. The only suspicious message in the logs is `GMT_Destroy_data: Skipped due to wrong level for object 1`. The last two messages are:
```
VirtualFile name created: <virtualfile>
RUNNING: PAR: gmt pstext -R0/12/0/12 -Jx1i -O -K -N -M -F+a+f+j <virtualfile> --GMT_HISTORY=readonly
```
I could try setting up debugging for this case on Windows, but I am not sure if I would get further than Joaquim did.

**Comment by PaulWessel** [comment]
Maybe we could learn where it crashes?

**Comment by meghanrjones** [comment]
I am still working on getting my windows setup working again, but will let you know when I get more information about the crash.

**Comment by joa-quim** [comment]
But I said where it crashes. When freeing a corrupted memory.

**Comment by PaulWessel** [comment]
Yes you did, sorry.  So looking at what that commit did that is related to the dataset D[PAR], it is this only:

`+                       D[PAR]->table[0]->n_segments = n_para;`

So before n_segments (probably) was not set but now it is, and that is why 

`for (seg = 0; seg < table->n_segments; seg++) gmt_free_segment (GMT, &(table->segment[seg]));`

is now actually calling that statement while before the loop would not execute.  I will see if I can learn anything in Xcode even though it does not crash.

**Comment by PaulWessel** [comment]
It gets to that point twice:

1. First it cleans up the input to **pslegend**.  That is the dataset you create in Julia via your _text_record_, maybe using _GMT_Create_Data_? I cannot see that part.  But it says all the memory is allocated internally by GMT hence it frees things as we do with all GMT-created memory.  Now, if this memory was _not_ created by GMT then I can understand the crash, but then you need to set the alloc_modes to **GMT_ALLOC_EXTERNALLY**, etc.
2. The second time it is to free the dataset created in **pslegend** that is passed to **pstext -M**.  I see nothing unusual there (and since nothing crashes I cannot tell anyway).

Perhaps you are able to tell me which of these two places is crashing, i.e., trying to free the **pslegend** input or the **pstext** input?

**Comment by joa-quim** [comment]
1. Could not be. It's the same function that reads all datasets

The problem is that when it goes to line 8704 it tries to free a NULL memory.
image

**Comment by joa-quim** [comment]
But even if I add

if (table->segment != NULL) gmt_M_free (GMT, table->segment);

it still crashes with the corrupted heap message so, some bad allocation happened before.

**Comment by PaulWessel** [comment]
If I understand you there are other places where you create such program text strings and that works fine (for pstext I assume but not in pslegend).  So you think it is the internally generated D[PAR] dataset that fails upon freeing, yes?

**Comment by PaulWessel** [comment]
Yes, no need to check if something is non-NULL or NULL since gmt_M_free checks and does not try to free a NULL pointer.

**Comment by joa-quim** [comment]
This was with the testapi_text_legend.exe. No Julia.

**Comment by PaulWessel** [comment]
OK. No julia, but still need to pin you down that when you see the crashing free you are witnesses the destruction of the dataset that was created in pslegend (D[PAR]) and passed into pstext? Yes or no.

**Comment by joa-quim** [comment]
I think I found it. In ``pslegend``
```
	if (D[PAR]) {
		n_para++;
		if (n_para >= 0) {	/* End of last paragraph for sure */
			S[PAR]->n_rows = krow[PAR];
			D[PAR]->table[0]->n_segments = D[PAR]->n_segments = n_para;
			D[PAR]->table[0]->n_records += S[PAR]->n_rows;
			D[PAR]->n_records = D[PAR]->table[0]->n_records;
			S[PAR] = D[PAR]->table[0]->segment[n_para] = GMT_Alloc_Segment (GMT->parent, GMT_WITH_STRINGS, krow[PAR], 0U, NULL, S[PAR]);
		}
```
The last line allocates ``segment[n_para]`` which is already ``segment[1]`` so ``segment[0]`` is never allocated. Changing it to ``segment[n_para-1]`` and the tests runs fine.

**Comment by PaulWessel** [comment]
Yes, that must be it.  I will make a PR (will reorder a few things).

**Comment by PaulWessel** [comment]
Actually, might as well do exactly as you suggested.  Give this a spin and approve if no crash under Windows, @joa-quim

**Review by joa-quim — APPROVED** [review]
No more crashes in Julia and the silly test works again.

**Pull request merged**
