### PR TITLE
Specify grid registration in example scripts

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Address https://github.com/GenericMappingTools/gmt/issues/7227

### CODE REVIEW

**Review by PaulWessel — COMMENTED** [review]
Agree with the non-plotting modules (grdcut, edit etc) but grdimage? It defaults to pixel registration if now given so I dont think we want to complicate the users most likely interaction which is to make plots.  People who need to cut and process should know what they are doing.

**Comment by joa-quim** [comment]
I go even further. What we should have is that annoying warning about *since you didn't specify registration I'm defaulting to ...* moved into the ``info`` verbose level. Most people don't know, or don't care (and the truth is, do we as users?) what we are talking about. If that's ok for them just let go and don't complicate the system.

**Comment by PaulWessel** [comment]
I am OK with muting that annoying warning.  If you dont know what you are doing then adding -V is a reasonable thing to be optional.  I will take care of it.

**Comment by PaulWessel** [comment]
So we have this:

```
is_PS = gmtinit_is_PS_module (API, mod_name, keys, options);	/* true if module will produce PS */
if (!is_PS) {	/* Override API default since module is a data processor */
	API->use_gridline_registration = true;
	API->use_gridline_registration_warn = (strcmp (mod_name, "grd2cpt") && strcmp (mod_name, "grd2kml"));	/* Give warning unless it is these two clowns */
}
```

so that warning only comes when you are doing data processing, in which case we felt the user need to know what they are doing and actually specify the registration.  This is different from making just a map.  Have you changed your mind? Don't you care if you get p or g when you do stuff with non-plotters?

**Comment by joa-quim** [comment]
My stanza on it is *if you care than be explicit*. But note that many data processing steps are nothing but previous steps for making an image. I GMT.jl I had to add this condition to be able to read ``@earth_`` files without having to remember every time that I had to add that ``-g``.
https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmtreadwrite.jl#L125

**Comment by PaulWessel** [comment]
OK, find I will make it INFORMATION. Not bothered either way.

**Comment by PaulWessel** [comment]
Now in master

**Comment by joa-quim** [comment]
Nice, and I now go catch a train.

**Comment by seisman** [comment]
I think we can close this PR now.

**Pull request closed without merging**
