### PR TITLE
WIP: Enable GLIB in Windows CI

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by seisman** [comment]
After enabling GLIB, most tests still pass. However, if a test fails, it reports some weird errors:
```

gmt.exe [ERROR]: Error closing GMT glib-2 shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT zlib1 shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT netcdf shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT pcre shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT glib-2 shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT zlib1 shared library: Error <193>: 
Set GMT_SESSION_NAME = 2625
blockmedian [ERROR]: Mismatch between actual (2) and expected (3) fields near line 15653 in file tut_ship.xyz
gmt.exe [ERROR]: Error closing GMT netcdf shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT pcre shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT glib-2 shared library: Error <126>: The specified module could not be found.

gmt.exe [ERROR]: Error closing GMT zlib1 shared library: Error <126>: The specified module could not be found.

ERROR: gmtest:56
memtrack errors: 0
exit status: 1
```

**Comment by PaulWessel** [comment]
Sorry, I know nothing about glib2.

**Comment by seisman** [comment]
@joa-quim Any thoughts on the errors?

**Comment by joa-quim** [comment]
When one gets ``The specified module could not be found`` it means a dependency missing/conflict. I am using ``glib-2.38.2`` and works fine for me. What version are you trying in these tests?

**Comment by seisman** [comment]
vcpkg provides glib 2.52.3-14-3.

**Comment by joa-quim** [comment]
Yeap, mine is a bit old. Only way to debug this is to build locally and use a dependency analyzer to see what's screwing.

**Comment by PaulWessel** [comment]
we could to as for bin and lib and add

GMT_DOCDIR_RELATIVE
and keep
GMT_DOC_DIR as it was.

**Pull request closed without merging**
