### PR TITLE
Fix wrong entries in OpenMP pragmas

### PR DESCRIPTION
**Pull request by PaulWessel**
Hoping this is the cause of failures in Linux and Windows since they presumably are running with OpenMP.  Also rename badly named local functions...  let me know if this does the trick, @seisman.

### CODE REVIEW

**Comment by seisman** [comment]
Still fails.

**Comment by PaulWessel** [comment]
OK, but is it true the CI uses OpenMP?

**Comment by seisman** [comment]
I think yes. It says:
```
*  OpenMP support             : enabled
```

**Comment by PaulWessel** [comment]
So I think the mistake is to set `V[GMT_Z] = cube->z[layer]` outside the OpenMP loop since _V_ is private and thus duplicated for each thread but I doubt this also magically sets `V[GMT_Z] = cube->z[layer]`.  So _V[GMT_Z]_ is probably zero always which matches the fact that all levels give the same wrong result.  Please try this one, @seisman .

**Comment by seisman** [comment]
Great! The test now passes on all platforms.

**Review by seisman — APPROVED** [review]

**Comment by PaulWessel** [comment]
Make a mental note that when a module fails on a platform with OpenMP and passes on macOS we should suspect bad pragmas...not the first time.

**Pull request merged**
