### PR TITLE
Use https for URL to GMT data server

### PR DESCRIPTION
**Pull request by PaulWessel**
Run the encrypted service.  Please test from outside hawaii.edu to make sure there are no side-effects since I cannot do it.

### CODE REVIEW

**Comment by seisman** [comment]
Does it work for you? This is what I got:
```
$ gmt which -Gl @AFR.nc
gmtwhich [ERROR]: Unable to down file https://oceania.generic-mapping-tools.org/gmt_md5_server.txt
gmtwhich [ERROR]: Libcurl Error: Couldn't connect to server
gmtwhich [ERROR]: Libcurl Error: Couldn't connect to server
gmtwhich [ERROR]: File AFR.nc not found!
```

**Comment by PaulWessel** [comment]
I cannot test until I go home.  The libcurl function may need an extra setting to do this, perhaps?

**Comment by seisman** [comment]
I don't think it's libcurl settings. You can try visit the URL via you browser. http://oceania.generic-mapping-tools.org is redirected to http://www.soest.hawaii.edu/gmt/data/, with a 403 forbidden code. But https://oceania.generic-mapping-tools.org cannot be reached. Maybe https isn't enabled by the DNS provider?

**Comment by PaulWessel** [comment]
Try in a few minutes.  The DNS services forwards

oceania.generic-mapping-tools.org to https://www.soest.hawaii.edu/gmt/data

now (it was http).  So not sure what happens if you try http.  I guess rc4 will have http so it may break?  But from the entry above there is no left-side http or https I can set.

**Comment by seisman** [comment]
Not working for me now. I'll test it later. I believe it's possible to have both http and https. Just like https://www.generic-mapping-tools.org and http://www.generic-mapping-tools.org.

**Comment by seisman** [comment]
I still cannot visit the https URL now.

**Comment by PaulWessel** [comment]
I just now changed it back to http:

**Comment by PaulWessel** [comment]
So the GMT server supports either one of course (I remove the local rays_11.txt between each try):

```
gmt set GMT_DATA_SERVER http://www.soest.hawaii.edu/gmt/data
gmt which -Gc @rays_11.txt -Vd
gmt set GMT_DATA_SERVER https://www.soest.hawaii.edu/gmt/data
gmt which -Gc @rays_11.txt -Vd
```
But doing the same with oceania fails, only http works.

**Comment by PaulWessel** [comment]
Any thoughts on this @leouieda?

**Comment by PaulWessel** [comment]
Closing this since does not work for https.

**Comment by leouieda** [comment]
@PaulWessel I think it's a good idea to do https whenever possible. I'm sure SOEST IT can setup SSL for the data server.

**Pull request closed without merging**
