### PR TITLE
Layout of docs under PSL "Justification" improved - whitespaces were not maintained

### PR DESCRIPTION
**Pull request by KristofKoch**
**Description of proposed changes**

In the documentation for PostScriptLight there is some ASCII Art to visualize the options for justification. However the font used was not monospaced and whitespaces were not maintained. Changed the paragraph to reformatted text and did some cosmetic changes to the text.

### CODE REVIEW

**Comment by seisman** [comment]
It seems your branch is created from the master branch, instead of the 6.0 branch.

**Comment by PaulWessel** [comment]
Any magic that can be applied to make the branch work with 6.0?

**Comment by seisman** [comment]
Have to do a rebase locally. I can help but not now.

**Comment by seisman** [comment]
It seems I'm not authorized to edit @KristofKoch's branch.

**Comment by KristofKoch** [comment]
Uh, it looks like I have screwed it up. Big time. My apologies for the trouble. To be honest, this are my first steps with GitHub and I thought I figured it out all by myself. 

So the right way would be to fork the _6.0_ branch and make a pull request on _6.0_? And cancel this pull request? 

Again, my apologies for causing more work for you while trying to be helpful.

**Comment by PaulWessel** [comment]
Hi @KristofKoch, sorry to make it complicated, and perhaps we need to write this down somewhere, but we make all bug/typo fixes to the 6.0 branch and then we merge 6 into master from time to time.  Any new feature is only implemented in master (to become 6.1 or something eventually).

**Comment by KristofKoch** [comment]
Ok @PaulWessel , I think I understand it now. So I cancel this pull request and try again in the _6.0_ branch. Correct?

**Comment by PaulWessel** [comment]
Yes, if you do it all form 6.0 then it should be much easier, but lets hear from an expert like @seisman before we send you down that road!

**Comment by seisman** [comment]
I can do the rebase operations if you check the checkbox "allow edits from maintainers" at the right side of the issue page. 

Otherwise, you have to close this PR, go to the 6.0 branch (https://github.com/GenericMappingTools/gmt/blob/6.0/doc/rst/source/postscriptlight.rst), click the edit icon to edit the file, then open another PR.

**Comment by KristofKoch** [comment]
@seisman the box is checked without me changing anything? 
Bildschirmfoto 2019-09-09 um 22 58 13

**Comment by seisman** [comment]
@KristofKoch I may did something wrong before. Now it works. I just edited your branch, and now it's ready to go. 

We're working on the redesign of our documentations in #1308, and plan to have a "Edit on Github" button/link at the top-right corner of each page of the documentations. I believe it will simplify the contributing process to the documentations.

**Pull request merged**
