### PR TITLE
Anim03 improve

### PR DESCRIPTION
**Pull request by Esteban82**
See #5720 for details.

I modified the script, the rst and other files following what seisman did when we upgrade anim02. 

I think only lacks the youtube video and link, and the processing info.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
After removing in as a test script in the CMakeLists.txt file, don't we also remove the PS file from the repo?

**Comment by Esteban82** [comment]
Mm

> After removing in as a test script in the CMakeLists.txt file, don't we also remove the PS file from the repo?

Mmm, I don't know.

**Comment by PaulWessel** [comment]
OK, leave for now.  We can remove later,  Good to merge.

**Comment by PaulWessel** [comment]
I will try it (build the anim03.mp4) and upload to YouTube and add correct link in a new PR.

**Pull request merged**
