### PR TITLE
Fix regression on Windows when trying to find if name is a SUBDATASET.

### LINKED ISSUE #3657: Reading @ with GDAL is broken on Windows
```
grdinfo @warning.png
ERROR 4: `c:c:/j/.gmt/cache//j/.gmt/cache/warning.png' does not exist in the file system, and is not recognized as a supported dataset name.
grdinfo (gmtapi_import_grid): Not a supported grid format [c:/j/.gmt/cache/warning.png]
```

The problem is in 
```
GMT_LOCAL GDALDatasetH gdal_open (struct GMT_CTRL *GMT, char *gdal_filename) {
	char *file = NULL, path[PATH_MAX] = {""}, *c = NULL;
	if (gmtlib_found_url_for_gdal (gdal_filename))	/* A vis*** URL, pass to GDAL as is */
		strncpy (path, gdal_filename, PATH_MAX-1);
	else if ((c = strchr(gdal_filename, ':'))) {		/* Assume it is a SUBDATASET */
```
``:`` is not a SUBDATASET separator it's the ``c:``

I knew that test was not good to have. So we still need a 6.1.1 soon.

### PR DESCRIPTION
**Pull request by joa-quim**
Closes #3657

### CODE REVIEW

**Comment by joa-quim** [comment]
Well, broken is what it was.

**Comment by PaulWessel** [comment]
Need to add a test since clearly no test checked this part.  COuld you do that?

**Comment by seisman** [comment]
We have many failures recently (https://github.com/GenericMappingTools/gmt/issues/3642), possibly due to this bug.

**Comment by PaulWessel** [comment]
Does this raise to the level of a 6.1.1 before the workshop next week?

**Comment by seisman** [comment]
> Does this raise to the level of a 6.1.1 before the workshop next week?

It looks a new bug introduced after 6.1.0 release. The reasons are:

1. There are no related failures when we release 6.1.0
2. You made some changes in PR #3596, after releasing 6.1.0. Perhaps the bug were introduced in your PR #3596?

**Comment by joa-quim** [comment]
Yes, #3596 introduced the bug but lucky of us that it was hold to after 6.1, so we don't need to release a 6.1.1. Just fix it

**Pull request merged**
