### PR TITLE
Update gmtspatial.rst

### PR DESCRIPTION
**Pull request by jidanni**
Mention also truncates lines.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Code actually reads the input as a polygon, so I assume if a line it will connect first/last and make a bad polygon.  So I cannot accept this one - would require testing and working with lines....

**Comment by jidanni** [comment]
All I know is it works fine with lines.

**Review by PaulWessel — APPROVED** [review]
Taking your word on it.

**Comment by joa-quim** [comment]
I remind that each of these absolutetely needless changes have launched a VM somewhere that worked full steam during some half an hour.

**Pull request merged**
