### PR TITLE
Fix catlabels and update PS

### PR DESCRIPTION
**Pull request by PaulWessel**
Various changes needed due to improved categorical handling in #7831.

### CODE REVIEW

**Review by Esteban82 — APPROVED** [review]
Blind approved.

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
The "Code Validator" failure is unrelated to this PR. So OK to merge.

**Comment by seisman** [comment]
@PaulWessel Did you forget to run `dvc push`?

**Comment by PaulWessel** [comment]
Yes, did it just now.

**Comment by seisman** [comment]
Now the DVC diff report in https://github.com/GenericMappingTools/gmt/pull/7883#issuecomment-1751749178 looks good.

**Review by seisman — APPROVED** [review]

**Pull request merged**
