### PR TITLE
Ensure geographic projection in pscoast (backport #74)

### PR DESCRIPTION
**Pull request by leouieda**
Backported #74 from master to 5.4

### CODE REVIEW

**Comment by PaulWessel** [comment]
Travis seems to be taking a long time on this one.  is it running a 5.4 check and is getting stuck? Something seems different.

**Comment by leouieda** [comment]
@PaulWessel and @joa-quim I don't think there is an easy way to backport this automatically. So many things changed in `pscoast.c` that git can't do it automatically. I tried to isolate the changes here but there are some problems:

f1530a4 removes the lines: 

```
    if (gmt_M_is_cartesian (GMT, GMT_IN)) {
		GMT_Report (API, GMT_MSG_NORMAL, "You must use a map projection or -Jx|X...d[/...d] for geographic data\n");
		Return (GMT_RUNTIME_ERROR);
    }
```

But 5.4 doesn't have that. It has this instead:

```
if (!gmt_M_is_geographic (GMT, GMT_IN)) {
 		GMT_Report (API, GMT_MSG_NORMAL, "Error: You must use a map projection or -Jx|X...d[/...d] for geographic data\n");
 		Return (GMT_RUNTIME_ERROR);
}
```

I have no idea the `if(... is_geographic` should be removed from 5.4 or not. 

All in all, in this case it's easier to make the change manually in the `5.4` branch. This kind of fix involving code that changed so much between versions is tricky to make.

If making it manually, you'd have to:

```
git checkout 5.4
# Create a new branch from 5.4
git checkout -b backport-pscoast
# ... make changes to this branch and commit
git push -u origin backport-pscoast
```

Then open a PR on Github but select `5.4` as the "base" instead of `master`.

**Comment by leouieda** [comment]
> Travis seems to be taking a long time on this one. is it running a 5.4 check and is getting stuck? Something seems different.

It'll stay like that forever I guess since there is no Travis configuration on 5.4. We can just ignore it.

**Comment by leouieda** [comment]
I removed it as a merge requirement so now it's gone.

**Comment by PaulWessel** [comment]
The !geographic and cartesian tests are the same - I must have switched it in trunk to make more sense.  So in both cases we delete that test once the new section looks like

	if (Ctrl->Q.active && !GMT->common.J.active) {	/* Set fake area and linear projection */
		gmt_parse_common_options (GMT, "J", 'J', "x1d");
		GMT->common.R.wesn[XLO] = GMT->common.R.wesn[YLO] = 0.0;
		GMT->common.R.wesn[XHI] = GMT->common.R.wesn[YHI] = 1.0;
	}
	else if (Ctrl->M.active && !GMT->common.J.active)	/* Set fake linear projection */
		gmt_parse_common_options (GMT, "J", 'J', "x1d");
	else if (GMT->common.J.active && gmt_M_is_cartesian (GMT, GMT_IN)) {	/* Gave -J but forgot the "d" */
		gmt_set_geographic (GMT, GMT_IN);
		GMT_Report (API, GMT_MSG_LONG_VERBOSE, "Switching to -Jx|X...d[/...d] for geographic data\n");
	}

**Comment by leouieda** [comment]
OK, so I'll delete that part and update this PR.

**Comment by leouieda** [comment]
OK, I removed the `if` block. Just pending a guru review to merge.

**Comment by leouieda** [comment]
For the record, this is how I fixed things on 5.4 and made this backport:

1. Delete the 3 commits that shouldn't have been in 5.4:

```
git checkout 5.4
# Undo the last 3 commits
git reset HEAD~2
# Discard changes left after undoing commits
git checkout -- .
# Force push to Github to overwrite the 5.4 branch
git push -f origin 5.4
```

2. Create a new branch from 5.4 that I'll use to backport and open this PR and copy commit f1530a4 from `master` into my new branch:

```
git checkout 5.4
# Create a new branch starting from 5.4 instead of master
git checkout -b backport-pscoast
# Copy a single commit from `master` into `backport-pscoast`
git cherry-pick f1530a4fe39d04776c5bfb1993b83d6036544ad0
```

3. Git can't port the commit automatically because a lot changed in `pscoast.c` between 5.4 and master (mainly modern mode). So the `cherry-pick` will cause conflicts. I used a merge tool to resolve the conflicts by only taking the lines that should be included:

```
# Open the merge tool and make changes in the GUI
git mergetool
# Save commit the cherry picked changes
git commit
```

4. Push the new branch to Github and make a pull request with `5.4` as the "base".


The merge conflict tool I use is [Meld](http://meldmerge.org/). I configured git to use it by adding the following to my `~/.gitconfig`:

```
[merge]
    tool = meld
```

**Comment by joa-quim** [comment]
Hi, sorry for the hassle I caused. But I still don't understand what happened. I did the PR from 5.4, not from master. After all, this is no different to what we used to do in SVN. Right, I did not create a branch because 5.4 is already a branch. I can be mistaken when I think I did it from 5.4 branch and was actually on master, but I did it from Tortoise and if I was on master it would have anted to commit on master too.

The other thing is that I did not try to commit the master pscoast.c but did the (same) changes directly on the 5.4 pscoast.

Lastly, you removed 3 commits previously on 5.4 (though you say HEAD-2, which lets think that only 2 were removed) but I think you should not have done so. At least without checking what they were. I remember clearly to have made one commit in 5.4 to fix the ``grdinfo -I-`` issue that surfaced on the GMTSAR workshop.

**Comment by joa-quim** [comment]
Continuing the non-understanding. Looking at the commit messages in 5.4 directly on the Github site I can see that grdinfo says: `` Backport fix to -I- option (#25) ``, so my fix is still there. But in that case what could have been my other commits that you removed since I deleted the PR (the pscoast one) without merging anything?

**Pull request merged**
