### PR TITLE
Exempt URL queries from having lock files

### PR DESCRIPTION
**Pull request by PaulWessel**
Since the URL of a quiery is not a good file name, we do not create an advisory lock file for such downloads.  Addresses #3765 hopefully.

### CODE REVIEW

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/pull/3735 is not backported to 6.1. Are you sure you want to backport this pr?

**Comment by PaulWessel** [comment]
Oops, I thought it was.  No, in that case.

**Comment by PaulWessel** [comment]
Network outage suddenly, please merge after tests

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Comment by PaulWessel** [comment]
Back on, fortunately. Marginally high wind on Oahu tends to mean short blackouts, and even though I am well UPS-ed up at home now, I have no defense against external network outages other than my cellphone plan...

**Pull request merged**
