### PR TITLE
Handle general URL files

### PR DESCRIPTION
**Pull request by PaulWessel**
URLs need to be checked if they exist locally.

### CODE REVIEW

**Comment by PaulWessel** [comment]
This PR lets URL files be downloaded to current directory, but the failure in mfilter.sh has to do with header records that GMT cannot recognized.  I dont understand how this worked earlier.

**Comment by PaulWessel** [comment]
A question would be if GMT should know that records starting with quotes must be headers.  Currently only records starting with # are headers unless **-hi**_n_ is used.

**Comment by PaulWessel** [comment]
What do you think @joa-quim ?

**Comment by seisman** [comment]
The command below only plots one circle. Possibly all invalid records are ignored.
```
gmt plot -R0/10/0/10 -JX10c -Baf -Sc0.5c -Gred -Vd -pdf map << EOF
" 1 1
" 2 2
' 3 3
$ 4 4
5 5
( 6 6
EOF
```

**Comment by PaulWessel** [comment]
Problem is there is no **-f0T** in filter1d call so it does not know that those 1958-* text strings are time stamps when it finally gets there.  It could learn that by examining one of those records but it never gets there since the header record is scanned as the first data record and has no time data to learn from.

**Comment by PaulWessel** [comment]
I am hesitant to skip records starting with " since there are gmt modules that can read just trailing text, so this would skip such record entirely.  If we know there must be numerical portions then we could do that.  Clearly, filter1d is such a case but the decision needs to be known deep in the io function.

**Comment by joa-quim** [comment]
Hmm, dangerous ground. I agree that we should not consider comments lines starting with ". Specially not at this point of time-line. If CSV was a reliable extension/format/whatever then we could dare more but unfortunately global ignorance reign and it so often is used just to mean a text file. Current case could perhaps  be solved if we could analyze a couple of lines at the END of file to know the number of columns (using ',' as separator) and then restart from beginning and skip all lines that have a different number of columns. But, as I said above, this is guess-work on dangerous  land.

**Comment by PaulWessel** [comment]
Yes.  And reading the end is tricky with pipes.  Would have to save to temp file, etc.

**Pull request merged**
