### PR TITLE
Remove obsolete syntax -E+r|R<inc> for DCW data

### LINKED ISSUE #2177: coast -E+r|R is not explained in the manpage

### PR DESCRIPTION
**Pull request by seisman**
Closes #2177.

### CODE REVIEW

**Comment by seisman** [comment]
pscoast is the only module which uses DCW data directly. I also don't have a solution.

**Comment by PaulWessel** [comment]
The **-R** parser (parse_R_option) also deals with DCW data since **-R**FR**+r**2 means reading the France polygon and rounding to multiples of 2.  But with **-R** being a common option I am not sure what module could be given the duty of reporting **-R**.  But there is this simple solution:

Since every module that accepts **-R** can do what pscoast **-E**... does, it is probably no longer important to get a **-R** string via pscoast to pass to another module.  The only reason is backwards compatibility and we can do that by accepting this PR.  Most users will rather do

`grd grdimage -RFR+r2 ...`

than

```
R=`gmt pscoast -EFR+2`
gmt grdimage $R ...
```

So shall I just accept your patch and we move on?  Are there any circumstances where we must give the user a **-R** string like that? I think the only other modules that return **-R** strings are gmtinfo and grdinfo.

**Comment by PaulWessel** [comment]
I've just implemented **+r|+R**_incs_ in gmtinfo and one issue comes up.  I would like to declare a bug in **+r**.  The rounding to nearest multiple of _dx_ is nice, but in the case that John brought up, the min is zero, and no **+r** will change that to less than zero.  **+R** will, but then we don't get nice rounded values.  I currently do stuff like this (e.g., for west):

`west  = floor (west  / Ctrl->I.delta[XLO]) * Ctrl->I.delta[XLO];`

I think it should instead be something like this:

```
new_west  = floor (west  / Ctrl->I.delta[XLO]) * Ctrl->I.delta[XLO];
west = (west == new_west) ? new_west - Ctrl->I.delta[XLO] : new_west;
```
I.e., the rounded region can never equal the given region if it already is an exact multiple.
Alternatively, this is a new feature and we need another modifier letter that is unique in both -I and -R.  They don't use many modifiers so something like +e for extend could be used.  So that would mean

**+r**_incs_: Convert region to multiples of given incs, rounded outward.
**+e**_incs_: Same, but any limit already a multiple of inc gets shifted by one more inc
**+R**_incs_: Simply add the incs to the determined limits.

Thoughts?

**Comment by seisman** [comment]
In the worst case, users can use `gmt coast -EFR -M | gmt info -Ie` to have the -R string.

**Comment by PaulWessel** [comment]
True, but isn't OK to just leave the capability there quietly and remove any trace of it from the documentation? We can even add a compatibility check around it so if 7 then complain.

**Comment by seisman** [comment]
Yes, I agree.

**Comment by PaulWessel** [comment]
OK, I will accept your change, but do you also agree with +r has a bug or should we add +e? I can see the usefulness of all three ways so perhaps adding new +e is the best solution (in master)?

**Comment by seisman** [comment]
I missed that comment. I think +e is necessary.

**Comment by seisman** [comment]
Give @joa-quim more time before merging this PR.

**Comment by PaulWessel** [comment]
OK, will wait for @joa-quim but starting a new feature request for **+e**.  There are some questions to discuss there as well.

**Comment by joa-quim** [comment]
I think it's OK to merge this. This syntax is documented in GMT5.4.5 bu the ``DCW_OPT`` define is only used in pscoast, so if deprecated it should not be documented.

**Comment by seisman** [comment]
OK, merging.

**Pull request merged**
