### PR TITLE
Add a modifier to -S to let polygon counting in headers start at 1 instead of 0

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Review by PaulWessel — CHANGES_REQUESTED** [review]
No, I dont like it, hardwired to 1.  Just do the same as for -N: +p<start> with default = 0.

**Comment by joa-quim** [comment]
It's nor hardwired to 1. Ctrls->S.onebased defaults to 0

**Comment by PaulWessel** [comment]
I mean, I cannot make it start at 100 if I wanted to.  So why not use a variable argument via +p.

**Comment by joa-quim** [comment]
Ok, changed it to -S[<n>].

**Review by PaulWessel — APPROVED** [review]
Good, yes no need for +p in this case, just n.

**Pull request merged**
