### PR TITLE
WIP: Trigger daily builds on master branch

### PR DESCRIPTION
**Pull request by seisman**
**DO NOT MERGE THIS PR!**

Azure Pipelines currently doesn't run our scheduled jobs due to some unknown issues (See #1088). This PR triggers CI jobs to run the full tests on the master branch. I'll manually merge the master branch into this PR to run the full tests.

### CODE REVIEW

**Comment by seisman** [comment]
Some tests fail on the master branch, but pass on the 6.0 branch. 
```
 38/839 Test  #26: GMT_App_O_9.sh ..........................***Failed    7.28 sec
Set GMT_SESSION_NAME = 5978
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
/usr/local/bin/gm compare: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r200x200" "-g1700x2200" "-sOutputFile=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gmuEYafD" "--" "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gmuocV66" "-c" "quit".
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
/usr/local/bin/gm compare: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r200x200" "-g1700x2200" "-sOutputFile=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gmuEYafD" "--" "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gmuocV66" "-c" "quit".
/usr/local/bin/gm compare: Request did not return an image.
ERROR: gmtest:88
memtrack errors: 0
exit status: 1
GMT_App_O_9.ps: RMS Error = NA [FAIL]
Error: /limitcheck in (-7.48e+240 -5.18e+245 -1.16e+265 C 7.58226e+298 /Normal PSL_transp [0] 0 B)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2029   1   3   %oparray_pop   2028   1   3   %oparray_pop   2009   1   3   %oparray_pop   1868   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   168   1   176   --nostringval--   %for_pos_int_continue   --nostringval--
Dictionary stack:
   --dict:957/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--   --dict:255/375(L)--
Current allocation mode is local
Current file position is 1254342
psconvert [ERROR]: System call [gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true 'GMT_App_O_9.ps' 2> './psconvert_6391c.bb'] returned error 256.
memtrack errors: 0
exit status: 3
```

**Comment by PaulWessel** [comment]
Could you post one of the failing PS file?  Are they all related to transparency?

**Comment by seisman** [comment]
> Could you post one of the failing PS file? Are they all related to transparency?

Currently, I can't access the PS files generated by the CI builds. And these failing tests pass locally on my mac machine.

This is a list of failing tests on macOS CI builds:
```
	 26 - GMT_App_O_9.sh (Failed)
	139 - GMT_tut_13.sh (Failed)
	180 - ex23/example_23.sh (Failed)
	340 - grdcontour/grdtime.sh (Failed)
	388 - grdgradient/illum_var.sh (Failed)
	421 - grdmath/ldist.sh (Failed)
	426 - grdpaste/paste_gridreg_underlap.sh (Failed)
	428 - grdpaste/paste_pixreg.sh (Failed)
	429 - grdpaste/paste_pixreg_overlap.sh (Failed)
	808 - spotter/spotter_04.sh (Failed)
	825 - time/time_testing_6.sh (Failed)
```
Failing tests on Linux CI builds:
```
        26 - GMT_App_O_9.sh (Failed)
	180 - ex23/example_23.sh (Failed)
	340 - grdcontour/grdtime.sh (Failed)
	362 - grdcut/origin.sh (Failed)
	388 - grdgradient/illum_var.sh (Failed)
	421 - grdmath/ldist.sh (Failed)
	808 - spotter/spotter_04.sh (Failed)
```

All these failing tests use `grdcontour`.

**Comment by joa-quim** [comment]
Here's an example (pssolar\shading) of a failing PS on Win. It's related to transparency. I can clearly see gray horizontal lines in PS, which disappear in pdf.

[shading.zip](https://github.com/GenericMappingTools/gmt/files/3369953/shading.zip)

**Comment by PaulWessel** [comment]
I zoomed in to 10x and see no gray horizontal lines (?) and the PDF looks the same (apart from the transparency), with no artifact.  Perhaps your gsview32 is acting up?

I am more concerned with @seisman reported:

Error: /limitcheck in (-7.48e+240 -5.18e+245 -1.16e+265 C 7.58226e+298 /Normal PSL_transp [0] 0 B)

which are crazy values that does not look like uninitiated number but not sure.  There are no @_transparency_ or **-t**_transp_ in GMT_App_O_9.sh.

**Comment by joa-quim** [comment]
This the _failure.png_. The violets correspond to gray lines I see in ghostview. But there is no ghostview involved in this. Only ghostscript.
Capture

And this is another view of the same file with another previewer. Not ghostview, but also use the ghostscript dll. One can see the transparency here.

Capture

**Comment by PaulWessel** [comment]
Well, I don't know.  I ran shading.sh again but this time only drawling a line instead of fill and I do not see any of those excursions which should be tiny line segments going back and forth.  Also, when I look at your PS file in the editor I see no x excursions in the PS code.  There would have to be some to draw such lines, as there always were when we had those real and annoying lines zipping across a periodic basemap.  I see none.  Since I cannot see any problem with your file, is it not possible that there is something odd with your viewer still?

**Comment by joa-quim** [comment]
It has to be ghostscript itself. No viewer involved in the creation of the .png file. Only gm and the ghost.

**Comment by seisman** [comment]
@PaulWessel  Attached is the build directory which contains the failing tests.
[macOSBuildDirectory.zip](https://github.com/GenericMappingTools/gmt/files/3370442/macOSBuildDirectory.zip)

**Comment by PaulWessel** [comment]
Looks crazy, here is a snippet of one file:

> (î1 W -3.1e-132 -5.23e-21 -5.61e+95 C 6.54834e+211 /Normal PSL_transp \[0\] 0 B)
> 	(î1 W -3.1e-132 -5.23e-21 -5.61e+95 C 6.54834e+211 /Normal PSL_transp \[0\] 0 B)
> 	(î1 W -3.1e-132 -5.23e-21 -5.61e+95 C 6.54834e+211 /Normal PSL_transp \[0\] 0 B)
> 	(î1 W -3.1e-132 -5.23e-21 -5.61e+95 C 6.54834e+211 /Normal PSL_transp \[0\] 0 B)
> 	(0 W -1.65e+115 -0.147 -1.32e-117 C \[0\] 0 B)
> 	(0 W -1.65e+115 -0.147 -1.32e-117 C \[0\] 0 B)
> 	(0 W -1.65e+115 -0.147 -1.32e-117 C \[0\] 0 B)
> 	(0 W -1.65e+115 -0.147 -1.32e-117 C \[0\] 0 B)
> 	(0 W 0 A \[0 0\] 0 B)
> 	(0 W 0 A \[0 0\] 0 B)
> 	(0 W 0 A \[0 0\] 0 B)
> 	(0 W 0 A \[0 0\] 0 B)

So the r g b values are out of wack, andI dont understand the escaping of the bracket for the setdash (B) commands...  So not just transparency stuff but that too.  There must be something else going on since we both run macOS just fine.  Some wrong library linked in?

**Comment by seisman** [comment]
It's weird. I run all the tests locally. The tests on 6.0 branch all pass, but 6 tests fail on master branch.
```
	 26 - GMT_App_O_9.sh (Failed)
	180 - ex23/example_23.sh (Failed)
	421 - grdmath/ldist.sh (Failed)
	426 - grdpaste/paste_gridreg_underlap.sh (Failed)
	428 - grdpaste/paste_pixreg.sh (Failed)
	808 - spotter/spotter_04.sh (Failed)
```

I then rerun the failing tests again and again, some of them pass, and I still have 3 failing tests.
```
	426 - grdpaste/paste_gridreg_underlap.sh (Failed)
	428 - grdpaste/paste_pixreg.sh (Failed)
	808 - spotter/spotter_04.sh (Failed)
```

**Comment by seisman** [comment]
I tried to revert 6fb324d2a774f43fb6bb364e7dc55122ecc2f5ea, and the failing tests pass again.

**Comment by PaulWessel** [comment]
OK, I admit not testing that feature particularly well so perhaps I should try a few things.  But cannot right now, probably tomorrow morning.

**Comment by PaulWessel** [comment]
Sorry, made the mistake of committing directly to master, but it does fix the problem which was failure to initialize the allocated structures.

**Comment by PaulWessel** [comment]
@seisman please check that my fix deals with your failures.  I am pretty sure it does but just in case.

**Comment by seisman** [comment]
All tests pass except the new test added in #1167.

The positions of the contour annotations "0" are different. Please see the attached gm-highlighted figure.

image

**Pull request closed without merging**
