### PR TITLE
VS isdigit in debug mode has an assert C>=0 && c<= 255. 

### PR DESCRIPTION
**Pull request by joa-quim**
Do that here otherwise it crashes in debug mode.
I still another one like this in ``struct_geo.sh`` but these crashes are damn hard and time consuming to find.

### CODE REVIEW

**Comment by joa-quim** [comment]
Possibly that char is not ascii so we are pushing the situation. Why (int)t[0] is giving a negative number?

**Comment by PaulWessel** [comment]
What is the text that is being checked? Has Euro accented characters?

**Comment by joa-quim** [comment]
From utf8.sh. This line
```
echo 0 1 ø ù ú û ü ý þ ÿ | gmt pstext -R-1/6/0.6/9.6 -Jx0.9i -P -B0  -F+f24p+jBL > lixo.ps
```

**Comment by seisman** [comment]
This PR should be merged into 6.0, right?

**Comment by joa-quim** [comment]
right. Doing to many things at same time.

**Comment by seisman** [comment]
OK. I'll cherry-pick the commit to 6.0 branch.

**Pull request merged**
