### PR TITLE
Address topic http://gmt.soest.hawaii.edu/boards/1/topics/7807

### PR DESCRIPTION
**Pull request by PaulWessel**
While the longitudes where correctly inferred to be pixel registered, disaster struck for latitudes...
Should be a bit more foolproof now.

### CODE REVIEW

**Comment by joa-quim** [comment]
The problem is that we rely on the existence of "node_offset" or "node_offset" or "valid_range" or "valid_min"/"valid_max" to guess if data is grid or pixel but if none exists, we assume data is pixel reg.

**Comment by PaulWessel** [comment]
Given the original grid actually says the x-values are 0.25, .75, ..., 359.75 it is admitting it is pixel registered, which matches the even number of nodes.  Even more so that min = -89.25 so I think only pixel registration makes sense.

**Comment by joa-quim** [comment]
Yes, it has an even number of nodes but that doesn't necessarily make it more pixelated

```
length(0.25:0.5:359.75)
720
```

For this data, why a pixel reg -R[0 360] makes more sense then a grid reg of -R[0.25 359.75]?

```
C:\v>ncdump -h result_ice_repository.grd
netcdf result_ice_repository {
dimensions:
        lon = 720 ;
        lat = 360 ;
        time = 113 ;
```

**Comment by PaulWessel** [comment]
Since we know it is a global grid it should be 360 by 180 degrees.  I would say 0/360/-90/90 as pixel reg make much more sense than 0.25/359.75/-89.75/89.75 as gridline reg.  Same file.

**Comment by joa-quim** [comment]
OK, I by the global argument but the gmt_nc code is not basing its choice on a test for global regions.

**Comment by PaulWessel** [comment]
No, it is basing it on xmin/dx giving a remainder of 0.5 *dx which is normally a good test to guess pixel registration.  It cannot know for sure of course, so a grid form 0.25 to 9.75 with dx 0.5 could be 0/10 pixel or 0.25/9.75 gridline. Hard to know what the user meant without more info in the header, but it is still a reasonable guess.  However, when the adjusted min/max gives a 360 range then I think we can be very sure.  I don't think we would treat these two cases differently but we certainly would be more confident in the latter case and could print a long-verbose message to that effect.

**Comment by PaulWessel** [comment]
Note that the original grid fails to use COARDS convention for longitude attribute: It has "degrees east" instead of "degrees_east".  So it is also seen as a Cartesian grid.
Of course, it should not stop GMT from perhaps still figuring this out that it is geographic.

**Pull request merged**
