### PR TITLE
Improved handling of minus and hyphen in text

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See #1421 for background.  This PR addresses this by replacing hyphens with minus sign _only_ during axes annotations.  For the example in #1421 , we now get this:
isolatin

The implementation is a new PSL function _PSL_settextmode_ that can be used to switch the text machine from replacing hyphens with minus sings (for annotations) or the other way around (for text).  The changes brings 52 test "failures" and I wanted to confirm with you what you thing (please build this PR and run tests).  What I see are these types of failures:

1. Powers of ten (10^-3) now uses the minus symbols whereas in the past those remained hyphens.  This is an improvement; e.g. ex03.sh
2. Lots of basic text and labels that contained hyphens were typeset as minus before (e.g., new_gaps.sh printing GMT option settings and the leading hyphen would become a minus.  This is good. Most of the failures seems to be text with hyphens incorrectly changed to minus.
3. Plotting negative numbers with pstext (e.g., center_bf_g.sh, reduce.sh) now have hyphens. Do we rely on octal codes here (awkward when plotting data tables) or do we check for a single word that is a number and then switch automatically?  Other than -F+z we cannot really know.
4. Sometimes we set an equation and it may contain minus sign, with pstext. We could scan for @~ (switching to symbol font) as an indication of math and use minus.  Thoughts on that one?  Other places we cannot know, e.g., -6x4 labels in geodesy_01.sh.  In some doc scripts we actually use the octal code for a long-dash or minus to force the issue (GMT_-OK.sh).
5. Embedded negative numbers in magnetic rose direction now has minus sign (e.g. rose_map1.sh).
6. Lastly, time axis with primary and secondary annotations (e.g., time_testing_6.sh).  Right now, the labels January-04 uses a minus instead of a hyphen.  This may be a good effect, but it is also easy to turn off minus here since all those numbers are positive, hence we can be reasonably assured that a hyphen is a hyphen.  Shall I force these to be hyphens?

Let me know what you are willing to consider good failures and what you think we need to do further with this PR.

### CODE REVIEW

**Comment by seisman** [comment]
According to the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601): the separator used between date values (year, month, week, and day) is the hyphen. But now it's minus.

**Comment by PaulWessel** [comment]
OK, so we can change annotation status to hyphen when we have a time-axis then, since there won't be any negative dates or hours (and unlikely negative years).

**Comment by PaulWessel** [comment]
After letting pstext -F+z turn on minus mode we are down to 44 failures.  All fall into two categories: Powers of ten where the originals have hyphens for negative powers, and text or titles or labels including GMT option strings, e.g., -JM6i, where the hyphen in correctly is convert to a minus symbol.  I think this PR is ready for prime time and have removed the WIP

**Comment by PaulWessel** [comment]
This PR closes #1421.

**Pull request merged**
