### PR TITLE
Prevent ESRI checking from accepting a .jp2 tile

### PR DESCRIPTION
**Pull request by PaulWessel**
The checks in _gmtlib_is_esri_grid_ were defeated because the file name had some similarities with the special case for *.hgt files in there.  Now we refuse to even look inside *.jp2 files and punt back to GDAL.  Hopefully this will bypass the DarthMac troubles, @meghanrjones.

### CODE REVIEW

**Comment by meghanrjones** [comment]
The original failures (imagepluscpt.sh and viewpluscpt.sh) now pass. But, the same problem now happens with marbles.sh where relative path use for grdinfo on earth_day_01d_p.tif returns a grid file format of gd = Import/export through GDAL while absolute path yields grid file format of ei = Esri ASCII, leading to the test failing with a grid read error.

**Comment by PaulWessel** [comment]
Thanks, will work on that and revise the branch.

**Comment by PaulWessel** [comment]
Perhaps you could try to implement this: Move that last GDAL case up ahead of the esri case as per @joa-quim those may be caught successfully by GDAL anyway.  See if that works for us.

**Comment by meghanrjones** [comment]
That fix works for reading the GDAL grids. I'm getting a segfault in grdimage_img_tif.sh. I'll look into that before moving forward with this solution. 

For completeness, the other failing tests are ex49, apicubeplot, onelayer, and longbasemap but those failures do not seem related.

**Comment by PaulWessel** [comment]
OK, @seisman reported that the apicubeplot and onelayer fails in the CI.  longbasemap fails because it needs 

`add_definitions(-DUSE_COMMON_LONG_OPTIONS) 	# Turn on testing of upcoming long-option syntax for common GMT options`

in the _ConfigUserAdvanced.cmake_ to work. Oh, and happy thanksgiving!

**Comment by PaulWessel** [comment]
In fact, you may wish to set all these:

```
add_definitions(-DDEBUG)
add_definitions(-DMEMDEBUG) # Turn on memory tracking see gmt_support.c for extra info
add_definitions(-DUSE_COMMON_LONG_OPTIONS) 	# Turn on testing of upcoming long-option syntax for common GMT options
add_definitions(-DUSE_MODULE_LONG_OPTIONS) 	# Turn on testing of upcoming long-option syntax for module options

```

The MEM debug stuff will print more info regarding unfreed memory.

**Comment by PaulWessel** [comment]
See if this update to _gmtlib_make_equidistant_array_ takes care of onelayer.sh and other issues, @meghanrjones and @seisman.

**Comment by meghanrjones** [comment]
It's still failing for me with the same output as before.
```
    Start 454: test/grdinterpolate/onelayer.sh

454: Test command: /opt/local/bin/bash "gmtest" "test/grdinterpolate/onelayer.sh"
454: Test timeout computed to be: 10000000
454: Set GMT_SESSION_NAME = 85754
454: grdinterpolate [ERROR]: Grid y increment <= 0.0
454: grdinterpolate (gmt_api.c:1993(gmtapi_init_grdheader)): Please select compatible -R and -I values
454: grdinterpolate [ERROR]: gmt_M_err_trap: -47
454: grdinterpolate (gmt_api.c:5170(gmtapi_export_grid)): NetCDF: NC_UNLIMITED in the wrong index [newlayer.nc]
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: [Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
454: ERROR: gmtest:61
454: memtrack errors: 0
454: exit status: 1
1/1 Test #454: test/grdinterpolate/onelayer.sh ...***Failed    0.09 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by PaulWessel** [comment]
Hm, OK the clue would be that it should not get into _gmtlib_make_equidistant_array_ in this case, and I see inc[GMT_Z] is uninitialized and could have junk.  So now that is initialized too.  Please see if this helps, @meghanrjones and @seisman? Note, @seisman's output has the backtrace while @meghanrjones does not.  Are you using -DNO_SIGHANDLER in the flags? Any tips here?

**Comment by PaulWessel** [comment]
I was able to reproduce the crash by building the no-debug release version and found the uninitialized variables.  Please try now.

**Comment by meghanrjones** [comment]
Onelayer.sh passes now for me

**Comment by PaulWessel** [comment]
Hi all, seems like this branch is ready to be approved? Pinging @meghanrjones @seisman @joa-quim

**Review by seisman — APPROVED** [review]

**Review by meghanrjones — APPROVED** [review]
These changes fix the original problem with .jp2 tiles. Marbles.sh still fails for me after these changes. If I move the gdal case above the esri case, marbles passes but grdimage_img_tif.sh fails. So, I don't think everything is resolved but we could merge this branch and work on that on a different branch.

**Comment by PaulWessel** [comment]
Agreed.

**Comment by PaulWessel** [comment]
@meghanrjones, please open a new issues for the marbles case.

**Pull request merged**
