### PR TITLE
Draw ticks normal to line when a pole plots as a line

### PR DESCRIPTION
**Pull request by PaulWessel**
This only affects the non-oblique regions for Robinson, Winkel-Tripel and the two Eckert projections

There are many (> 10) failures because the default changes.  Please see if you agree than all the ones using these 4 projections look better with this fix, e.g ex46. ex25, ex22, ex20, urlquakes, etc etc.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Here is the list of failures that I attribute specifically to the Winkel, Robinson, Eckert upgrade:

ex46
ex25
ex22
ex20
urlquakes
pssolar_fill
pssolar_fill2
select
closed
GMT_tut_6

There are many other failures that are unrelated to this change in tick-normal.  If you agree then I can update these PS files.

**Comment by meghanrjones** [comment]
> Here is the list of failures that I attribute specifically to the Winkel, Robinson, Eckert upgrade:
> 
> ex46
> ex25
> ex22
> ex20
> urlquakes
> pssolar_fill
> pssolar_fill2
> select
> closed
> GMT_tut_6
> 
> There are many other failures that are unrelated to this change in tick-normal. If you agree then I can update these PS files.

Looking now

**Review by meghanrjones — APPROVED** [review]
I agree that the annotations look better for those scripts. I think that the best appearance would be with slanted ticks and a constant annotation distance from the frame, but perhaps that is not an option.

I'm not sure it's worth updating the PS files until all the issues in #4955 are resolved since they are likely to change again - up to you.

**Comment by PaulWessel** [comment]
Yes, and no.  I worry that if we do not update the PS files but just merge in the fix that it is a bit hard to keep track of what is actually fixed and what is still out there.

**Comment by PaulWessel** [comment]
> I agree that the annotations look better for those scripts. I think that the best appearance would be with slanted ticks and a constant annotation distance from the frame, but perhaps that is not an option.

It cannot work for some since the tick angle is crazy horizontal for some of them, and they we would have to invent some threshold angle instead that would not represent map trends etc.  I think the clean normal is pretty decent and at least is a big improvement over the bumpy lineup with the central meridian sticking down.

**Comment by meghanrjones** [comment]
> > I agree that the annotations look better for those scripts. I think that the best appearance would be with slanted ticks and a constant annotation distance from the frame, but perhaps that is not an option.
> 
> It cannot work for some since the tick angle is crazy horizontal for some of them, and they we would have to invent some threshold angle instead that would not represent map trends etc. I think the clean normal is pretty decent and at least is a big improvement over the bumpy lineup with the central meridian sticking down.

OK, agreed.

**Comment by PaulWessel** [comment]
Looking at ex16 which is master now has missing CPT annotations but running master produces them.  So looks like we merged in some PS files with issues related to CPT annotations but whatever the problem was it is no longer an issue?  E.g., ex16, categoricalcpt.ps.

**Comment by meghanrjones** [comment]
> Looking at ex16 which is master now has missing CPT annotations but running master produces them. So looks like we merged in some PS files with issues related to CPT annotations but whatever the problem was it is no longer an issue? E.g., ex16, categoricalcpt.ps.

Yes, sorry. I fixed in #4957 but did not update PS files.

**Comment by PaulWessel** [comment]
OK, you or me updating those two?
After than I see several with slight differences in map pen thickness (?), and GMT_cassini has a different interval but was not updated? Then GMT_TM looks OK in the failure so update that too?

**Comment by meghanrjones** [comment]
> OK, you or me updating those two?
> After than I see several with slight differences in map pen thickness (?), and GMT_cassini has a different interval but was not updated? Then GMT_TM looks OK in the failure so update that too?

The GMT_cassini is probably related to https://github.com/GenericMappingTools/gmt/pull/4954 and the map pen thicknesses very likely could be related to that as well. I'll go through all the PS files that failed after #4954 and #4957 now and make a PR with the updates.

**Pull request merged**
