### PR TITLE
gmtspatial.rst: fix formatting

### PR DESCRIPTION
**Pull request by anbj**
Fix link to `-W` and formatting in description of ``-W``.

### CODE REVIEW

**Comment by PaulWessel** [comment]
I'm building the docs now

**Review by PaulWessel — APPROVED** [review]
Looks good. You could try to merge - not sure if you have that power - if you get an error just let me know and I will merge.

**Comment by anbj** [comment]
Wow, I thought things went slow in the English countryside

**Comment by anbj** [comment]
The button went green and I pressed it!

Looks OK?

**Comment by PaulWessel** [comment]
Yep, all good, and thanks!

**Comment by anbj** [comment]
Great! Thanks Paul.

**Pull request merged**
