### PR TITLE
Add VPDF for Von Mises PDF to gmtmath

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

This adds a new operator VPDF that creates a PDF for the Von Mises circular (wrapped) normal distribution for periodic data.  I added a test to ensure it works.  I also removed the number of operators listed in the doc since it is always out of sync with reality anyway.

### CODE REVIEW

**Comment by PaulWessel** [comment]
FYI: The **VPDF** and PR was added for several reasons:

1. Given the ability to wrap data into periodic functions (**-w**) the statistics of the wrapped functions as used in **histogram -N** must follow the very different rules of such distribution (see failure in #4992).  Here, von Mises analysis will be required.  Having this capability in gmt **math** is helpful.
2. **psrose** does not have a an option similar to **histogram -N** but it could.  In that case, the curve would be a von Mises fit.
3. I have done quite a bit with these distros as well as the 3-D equivalent (Fisher distribution on a sphere) via my data analysis and book so it is pretty much ready to go apart from implementation.

So **VPDF** may soon show up in grdmath as another PR, as will **IPDF** for Fisher distribution.

**Comment by PaulWessel** [comment]
Might @joa-quim have time to check this branch and approve?  It is pretty isolated and cannot break other things (than itself - but the test works).

**Comment by joa-quim** [comment]
some missing commit?
```
grdmath.c.obj : error LNK2019: unresolved external symbol gmt_vonmises_pdf referenced in function grdmath_VPDF
src\gmt_w64.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by PaulWessel** [comment]
That branch awaits the gmtmath PR first; it is not a PR yet

**Comment by joa-quim** [comment]
OK, wrong branch. This one builds fine

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
