### PR TITLE
Typo. Remove extra )

### PR DESCRIPTION
**Pull request by Esteban82**

### CODE REVIEW

**Review by anbj — APPROVED** [review]

**Comment by joa-quim** [comment]
This type of fixes can be applied directly to master.

**Comment by seisman** [comment]
I believe the master branch is protected so that no one except @joa-quim and me can push directly into master.

**Comment by Esteban82** [comment]
Ok, I will applied directly next time. 
I have permission to do that.

**Comment by anbj** [comment]
I think that was because of me, pushing directly to master by a mistake.

**Pull request merged**
