### PR TITLE
fix typo in batch.rst

### PR DESCRIPTION
**Pull request by mwoot**
Changed "we advice" to "we advise" in batch.rst

**Description of proposed changes**

Fix typo! Thanks!

### CODE REVIEW

**Comment by anbj** [comment]
Thanks! Why can’t this be merged?!

**Comment by Esteban82** [comment]
> Thanks! Why can’t this be merged?!

I think that you have to approve it first.

**Review by anbj — APPROVED** [review]

**Comment by anbj** [comment]
Oh… ops. Thanks.

**Comment by anbj** [comment]
Why have the checks stopped..

**Comment by Esteban82** [comment]
These tests are to check the code. But it is not needed for the documentation.

**Comment by anbj** [comment]
Ok. I don’t know how to get this merged.

**Comment by Esteban82** [comment]
I don't know. Maybe @seisman could help us.

**Pull request merged**
