### PR TITLE
Add a tutorial version in Julia

### PR DESCRIPTION
**Pull request by joa-quim**
As it says, this PR adds a version of the Tutorial translated to Julia.

One reason to submit it here is that converting the RST to Markdown (used in the Julia docs) would be a lot of work.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Looks OK, but I think you should remove all our names from the Julia first page and just cite via link to the CLI tutorial since none of us have contributed to the Julia docs or code, no?

**Comment by PaulWessel** [comment]
Maybe you could also add a link to https://julialang.org/learning/getting-started/ in the first page for those who need to explore this a bit first.

**Comment by joa-quim** [comment]
Added some links and reduced the authors list. Still left you since you since you actually wrote the original tutorial.

**Comment by PaulWessel** [comment]
OK, I guess that is fine for now.  I think I was thinking of just you writing GMT.jl and thus only you need to be listed there.

**Pull request merged**
