### PR TITLE
Add gdalread func list

### PR DESCRIPTION
**Pull request by PaulWessel**
Also rename static local functions to follow GMT standard naming convention.

### CODE REVIEW

**Review by joa-quim — COMMENTED** [review]
They are local funs, what's the interest of making their names longer?

**Comment by joa-quim** [comment]
In my view this only makes the code a bit more difficult read (longer lines that wrap or 'outflow' on the right) with no gain in extra information.

**Comment by PaulWessel** [comment]
Well, what is the point of having a convention and then we start making exceptions here and there.  This is to help future GMT developers better navigate things.

**Comment by PaulWessel** [comment]
If you wish to shorten some of those names, feel free to do so as long as they start as indicated.

**Review by joa-quim — APPROVED** [review]
I am not convinced that this convention helps code navigation. Static local files are only seen when reading the code, and than the GMT_LOCAL prefix already tells reader about their nature without making the fun names longer.

**Comment by PaulWessel** [comment]
Well, true but I am not going back to removing gmtfile_ from all those functions everywhere,  So a bit of inconvenience you will have to endure.

**Pull request merged**
