### PR TITLE
WIP: Debug nearneighbor/nat_nn.sh

### PR DESCRIPTION
**Pull request by seisman**
Address #2721

### CODE REVIEW

**Comment by seisman** [comment]
`grdgdal/gdal_nn.sh` fails on Linux, and `nearneighbor/nat_nn.sh` fails on macOS.

**Comment by seisman** [comment]
Don't know why but `grdgdal/gdal_nn.sh` now passes on Linux.

For macOS `nearneighbor/nat_nn.sh`, the debug messages are:
```

nearneighbor [DEBUG]: Chosen boundary condition for all edges: natural
nearneighbor [INFORMATION]: Cartesian input grid
nearneighbor [DEBUG]: Object ID 1 : Registered Grid Memory Reference 7fa4d7d79b30 as an Input resource with geometry Surface [n_objects = 2]
nearneighbor [DEBUG]: Successfully created a new Grid container
nearneighbor [INFORMATION]: gdal options used: -ot Float32 -txe 0.000000 10.000000 -tye 0.000000 10.000000 -outsize 201 201 -a nearest:radius1=0.000000:radius2=0.000000:nodata=NaN -of MEM
nearneighbor [ERROR]: gdal_grid: failure
nearneighbor [ERROR]: GDAL nearest neighbor returned error -1
nearneighbor [DEBUG]: gmtapi_garbage_collection: Destroying object: C=0 A=1 ID=0 W=Input F=Data Table M=File S=Used P=7fa4d7d30930 N=tridata.txt
nearneighbor (gmt_free_table): tried to free unallocated memory
nearneighbor [DEBUG]: gmtapi_garbage_collection: Destroying object: C=0 A=0 ID=1 W=Input F=Grid M=Memory Reference S=Unused P=7fa4d7d79b30 N=(null)
nearneighbor [DEBUG]: GMTAPI_Garbage_Collection freed 2 memory objects
nearneighbor [DEBUG]: gmtapi_unregister_io: Unregistering object no 0 [n_objects = 1]
nearneighbor [DEBUG]: gmtapi_unregister_io: Unregistering object no 1 [n_objects = 0]
nearneighbor [DEBUG]: GMT memory: Free 3 temporary column arrays, each of length : 2097152
gmt [DEBUG]: Entering GMT_Destroy_Session
ERROR: gmtest:54
memtrack errors: 0
exit status: 1
```

**Comment by PaulWessel** [comment]
Sorry, I fixed gdal_nn.sh earlier - it did not have execute permission set.  I just committed that to master...

**Comment by seisman** [comment]
Yesterday nightly CI job shows that `grdgdal/gdal_nn.sh` fails again on Linux. Maybe some uninitialized variables cause random crashes?

**Comment by seisman** [comment]
Ping @joa-quim. We have `grdgdal/gdal_nn.sh` failed on Linux and `nearneighbor/nat_nn.sh` on macOS.

**Comment by joa-quim** [comment]
I don't know what I can do. That tests passes for all of us when run locally. It did work to in WSL.

**Comment by seisman** [comment]
Could you add some debug statements so that we may know why the gdal call fails?

**Comment by joa-quim** [comment]
Tried that already but
```
gmt grdgdal lixo.csv -R0/10/0/10 -Gjunk.nc -I0.05 -F"-a nearest -co DEBUG=ON"
Warning 6: driver MEM does not support creation option DEBUG
```

**Comment by joa-quim** [comment]
Actually, without the ``-co`` it didn't complain
```
gmt grdgdal lixo.csv -R0/10/0/10 -Gjunk.nc -I0.05 -F"-a nearest CPL_DEBUG=ON"
```
you may try to add that to the test and see if something comes up.

**Comment by seisman** [comment]
Added, but don't see anything useful.
```
grdgdal [INFORMATION]: gdal options used: -ot Float32 -txe 0.000000 10.000000 -tye 0.000000 10.000000 -outsize 201 201 -a nearest CPL_DEBUG=ON -of MEM
grdgdal [ERROR]: gdal_grid: failure
grdgdal [DEBUG]: gmtapi_garbage_collection: Destroying object: C=0 A=1 ID=0 W=Input F=Data Table M=File S=Used P=561ef7519800 N=tridata.csv
```

**Comment by seisman** [comment]
Fixed by #2775. Closing.

**Pull request closed without merging**
