### PR TITLE
Show curl and zlib library in cmake summary page

### LINKED ISSUE #3633: Cmake summary page has a few blanks under macOS
When running cmake, just before it starts compiling, it will report on all the things it found or did not find.  E.g.,

```
*  GDAL library               : /opt/local/lib/libgdal.dylib
*  GDAL include dir           : /opt/local/include
*  GEOS library               : /opt/local/lib/libgeos_c.dylib
*  GEOS include dir           : /opt/local/include
```

However, I notice these two libraries are not listed:

```
*  Curl library               : 
*  Curl include dir           : /opt/local/include
*  ZLIB library               : 
*  ZLIB include dir           : /opt/local/include
```

searching in the CMakeCache.txt file i find entries like

```
CURL_LIBRARY_RELEASE:FILEPATH=/opt/local/lib/libcurl.dylib
ZLIB_LIBRARY_RELEASE:FILEPATH=/opt/local/lib/libz.dylib
GDAL_LIBRARY:FILEPATH=/opt/local/lib/libgdal.dylib
GEOS_LIBRARY:STRING=/opt/local/lib/libgeos_c.dylib
```

Since all the messages uses the strings NAME_LIBRARY and NAME_INCLUDE_DIR, somehow these are not set when we search for the curl and zlib libraries (again on macOS).  It would be nice to complete the picture.

### PR DESCRIPTION
**Pull request by seisman**
Fixes #3633.

Please build and see if it works for you

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel Please try both release and debug builds, again.

**Comment by PaulWessel** [comment]
Dbuild first,  Works

```
*  Curl library               : /opt/local/lib/libcurl.dylib
*  Curl include dir           : /opt/local/include
*  ZLIB library               : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd
*  ZLIB include dir           : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/
```

**Comment by PaulWessel** [comment]
Same for release build. So looks good.

**Comment by seisman** [comment]
The Windows CI gives a weird output for curl. Perhaps @joa-quim can check if it works for him.
```
*  Curl library               : C:/vcpkg/installed/x64-windows/lib/libcurl.lib;wldap32;winmm;ws2_32;advapi32;crypt32;advapi32;ZLIB::ZLIB
*  Curl include dir           : 
*  ZLIB library               : C:/vcpkg/installed/x64-windows/lib/zlib.lib
*  ZLIB include dir           : C:/vcpkg/installed/x64-windows/include
```

**Comment by seisman** [comment]
This PR fixes the cmake summary information on Linux and macOS, not for Windows, but at least it seems harmless to Windows. @joa-quim Can you verify it on your Windows machine, so that we can merge this PR.

**Comment by joa-quim** [comment]
Very bad WiFi quality and only at the restaurant. Go ahead and commit.

**Pull request merged**
