### PR TITLE
Another way to report versions of gm, gdal, ffmpeg

### PR DESCRIPTION
**Pull request by seisman**
Related to #1851.

This PR tries to use a pure CMake way to detect versions of gm, gdal_translate, ogr2org and ffmpeg.
The only external command needed is `head`.

It runs the commands and try to match the version number x.x.x using regex.
A known issue is, if @joa-quim uses GDAL 3.1.0dev, it will reports 3.1.0 instead.

### CODE REVIEW

**Comment by seisman** [comment]
The `string (REGEX MATCH)` function only match the first version number, thus it's safe to remove the `head` command.

For example, `ffmpeg -version` reports
```
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

There are many versions (e.g. 4.2.1, 10.1.1, 1001.0.46), but only the first one is matched. I believe it's safe to assume that the first version number is what we need.

**Comment by PaulWessel** [comment]
Yes, I agree.

**Comment by seisman** [comment]
Don't know why the gm on Ubuntu 16.04 reports `GraphicsMagick 1.4`, which is not released. Besides that, it works as expected.

**Comment by PaulWessel** [comment]
It is the future.

**Comment by seisman** [comment]
Feel free to merge it if @joa-quim is OK with it.

**Comment by PaulWessel** [comment]
OK.  Can I delete #1851 then?

**Comment by seisman** [comment]
I've closed it and deleted the branch.

**Comment by joa-quim** [comment]
With my commit (wrapping ``${answer}`` in quotes) it works on Win too.

**Pull request merged**
