### PR TITLE
Deal with coverity issues of June 14, 2019

### PR DESCRIPTION
**Pull request by PaulWessel**
I did a bunch at once, sorry.

### CODE REVIEW

**Comment by joa-quim** [comment]
We have a conflict in this PR but hitting the ``Resolve conflict`` button goes into an infinite loop

**Comment by PaulWessel** [comment]
Fixed now

**Comment by joa-quim** [comment]
You should have marked them as "Fix Submitted" on the Coverity page so that those not addressed can stand out.

**Comment by PaulWessel** [comment]
I did! and added pwessel@hawaii.edu as who did it.

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa


On June 14, 2019 at 1:26:21 PM, Joaquim (notifications@github.com) wrote:

You should have marked them as "Fix Submitted" on the Coverity page so that
those not addressed can stand out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/gmt/pull/920?email_source=notifications&email_token=AGJ7IX4HPIXQVADBQO33CUTP2QSJZA5CNFSM4HYNQYHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXYKG3A#issuecomment-502309740>,
or mute the thread

**Comment by joa-quim** [comment]
Ok, but not all. I'm looking for example at CID 199089

**Pull request merged**
