### PR TITLE
Update gmt_es.locale

### PR DESCRIPTION
**Pull request by Esteban82**
Change dgo to dom. See discussion in #5201.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
I assume the changes to the characters for Miercoles and Sabado work for you? If so, then you can merge it.

**Comment by Esteban82** [comment]
> I assume the changes to the characters for Miercoles and Sabado work for you? If so, then you can merge it.

Mmmm, strange. In the previous visualization it looks fine but now don't. Also, I don't remember modifying them.

**Comment by PaulWessel** [comment]
OK, shall we close this one and I simply start a new one and fix the spelling of DOM?

**Comment by PaulWessel** [comment]
OK, given time-zones I will close this PR and open one with just that line.

**Pull request closed without merging**
