### PR TITLE
Replace /tmp with $TMPDIR

### PR DESCRIPTION
**Pull request by seisman**
`$TMPDIR` may work well on Windows.

### CODE REVIEW

**Comment by seisman** [comment]
@joa-quim Please check if it works for you.

**Comment by joa-quim** [comment]
Nope. No difference. Same errors.

**Comment by PaulWessel** [comment]
What are the errors?

**Comment by joa-quim** [comment]
Those that I reported in #2715
```
: Invalid argument (many of these)
grep: movie: No such file or directory
```

**Comment by seisman** [comment]
This PR may still not work well on Windows, but at least it's a good improvement for Linux/macOS. Merge it?

**Comment by PaulWessel** [comment]
Yes, clearly better.  If @joa-quim can run the full bash -xv on the script we can see what is going on better - the errors above do not help me.

**Comment by PaulWessel** [comment]
So please merge.

**Pull request merged**
