### PR TITLE
Check if structure exist before accessing its members

### PR DESCRIPTION
**Pull request by PaulWessel**
Hopefully fixes #3510.  Let me know @seisman.

### CODE REVIEW

**Comment by seisman** [comment]
This PR works well for PyGMT, but now there are two new failing tests:
```
	205 - anim04/anim04.sh (Failed)
	249 - genper/east_map_8.sh (Failed)
```
These two tests also fail on the master branch but they're not related to grdimage:
```
grdblend [WARNING]: File @N30W120.earth_relief_02m_p.nc coordinates are phase-shifted w.r.t. the output grid - must resample
grdsample [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
grdsample [ERROR]: Offending option -R275.016666667/290.016666667/30.0166666667/-143165531.517
grdblend [ERROR]: Unable to resample file @N30W120.earth_relief_02m_p.nc - exiting
grdcut [ERROR]: ERROR - Unable to produce blended grid from /var/folders/mz/d3wtwjtx4fg8qlds5lgt1c240000gn/T/=tiled_56_GX.G88AFt
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
grdimage [ERROR]: Cannot find file etopo2-chesapeake.nc
```

**Comment by PaulWessel** [comment]
Will check once done with another branch (... the cpt solution).

**Comment by PaulWessel** [comment]
Did your problem go away? I am just getting the two gdal_nn.sh and grdimage_img_tif.sh failures for master.

**Comment by seisman** [comment]
They're still failing for master.

**Comment by seisman** [comment]
After running the two failing tests, I have these two files in `earth/earth_relief/earth_relief_02m_p`:

1. N30W120.earth_relief_02m_p.jp2
2. S30W120.earth_relief_02m_p.jp2

**Comment by seisman** [comment]
Perhaps something wrong with my GDAL.

I download a tile directly from the GMT server:
```
wget --no-check-certificate https://oceania.generic-mapping-tools.org/server/earth/earth_relief/earth_relief_02m_p/N30E000.earth_relief_02m_p.jp2
```
The md5sum of the tile is the same as the one in the GMT server:
```
271290bad03ccd1679fdcd9232fbc05d  N30E000.earth_relief_02m_p.jp2
```

But gdalinfo doesn't recognize the tile:
```
gdalinfo N30E000.earth_relief_02m_p.jp2
ERROR 4: `N30E000.earth_relief_02m_p.jp2' not recognized as a supported file format.
gdalinfo failed - unable to open 'N30E000.earth_relief_02m_p.jp2'.
```

**Comment by seisman** [comment]
I mistakenly used the gdalinfo from macports (without openjpeg support). Now all tests pass.

**Pull request merged**
