### PR TITLE
gmt.conf.rst: add small table of printf examples

### PR DESCRIPTION
**Pull request by anbj**

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Looks nice, please consider turning the "(C language printf syntax)" at the start of the FORMAT_FLOAT_OUT section into a hyper link to https://en.wikipedia.org/wiki/Printf_format_string, i.e.,

Format (C language `printf syntax <https://en.wikipedia.org/wiki/Printf_format_string>`_) ...

**Comment by Esteban82** [comment]
Very nice anbj!!

**Comment by anbj** [comment]
Any suggestions @Esteban82?
I believe you posted in the forum some time ago about ``printf``.
Anything that was of good help?

**Comment by Esteban82** [comment]
I am afraid I don't know. I couldn't see this issue again.

**Comment by PaulWessel** [comment]
Thanks @anbj !

**Comment by anbj** [comment]
Super!

**Pull request merged**
