### PR TITLE
Let GMT set a better output format for fractional seconds

### PR DESCRIPTION
**Pull request by PaulWessel**
See #4408 for background.  This PR implements it for table output.  If **-V** is used you may see a message like this:

`gmtmath [INFORMATION]: To prevent loss of time-series precision we have changed FORMAT_CLOCK_OUT to hh:mm:ss.xxxxx`

Note this action is only taken if **FORMAT_CLOCK_OUT** has not been changed from its default value.

I am not sure what to do about rec-by-rec tools which have no way of detecting the format.  We should probably

1. Add some more language under the **FORMAT_CLOCK_OUT** documentation as to under what circumstances the user may wish to change this setting (i.e., dense time-series data).
2. Clarify that GMT may override the default format when data-precision loss is likely (and how we do it).

Thoughts on this?

### CODE REVIEW

**Review by joa-quim — APPROVED** [review]

**Comment by joa-quim** [comment]
The rec-by-rec could also analyze the first 20 (or 10) recs and change to ``.xx``. Then only the first 20 recs would have had an eventual loss and issuing a warning.

**Comment by PaulWessel** [comment]
True, but the problem is that test would be run forever since it would go in GMT_Put_Record.

**Comment by PaulWessel** [comment]
Looking at where _GMT_Put_Record_ is used, I can only think of a few modules where this would be an issue:

1. **filter1d**: Filtering time-series and **-I** specifies sub-second interval.
2. **greenspline**: 1-D of interpolating time-series and **-I** specifies sub-second interval.

In those cases we can just check in those modules and update **FORMAT_CLOCK_OUT** if necessary.

Of course, there may be folks who will be running blockmean on (time,distance,value) data and could run into this as well, but I dont see a good way to deal with this, other than improve the **FORMAT_CLOCK_OUT** documentation.

**Comment by PaulWessel** [comment]
Oh, and sample1d as well.

**Comment by PaulWessel** [comment]
Not **sample1d** since it uses _GMT_Write_Data_.  So I only added a check for **filter1d** as the most likely of the modules to deal with time-series.  I think that is a good start - and the docs have been updated to indicate the issue.

**Pull request merged**
