### PR TITLE
Fix bugs in duplication of CPTs

### LINKED ISSUE #3613: makecpt -G on CPTs with custon label info fails
**Description of the problem**

When trying to limit the remote CTP @age_chrons_GTS2012_2020.cpt on z:

```
   0.0  219/30/38        11.06  219/30/38       U       ;5o
 11.06  241/71/28        19.72  241/71/28       U       ;6o
 19.72  245/114/21       33.16  245/114/21      U       ;13y
....
```

I get lots of memory issues and the result has lost all the custom label information:

```
gmt makecpt -C@age_chrons_GTS2012_2020.cpt -G0/164.70 > t.cpt
makecpt (gmt_support.c:1138(gmtsupport_free_range)): Wrongly tries to free item
makecpt (gmt_support.c:1138(gmtsupport_free_range)): Wrongly tries to free item
makecpt (gmt_support.c:1138(gmtsupport_free_range)): Wrongly tries to free item
....
```

```
head -3 t.cpt

0	219/30/38	11.06	219/30/38
11.06	241/71/28	19.72	241/71/28
19.72	245/114/21	33.16	245/114/21
```

Yet, when used by **colorbar** there is no issues:

`gmt colorbar -C@age_chrons_GTS2012_2020.cpt -G0/164.70  -Dn0.015/0.055+jBL+w5.8i/0.12c+h -S+c --FONT_ANNOT_PRIMARY=3.5p -Rd -JQ180/6i -pdf map`

Will require a check and perhaps debug to see why the different behaviors.

### PR DESCRIPTION
**Pull request by PaulWessel**
The API functions to duplicate a CPT had double allocations and freeing of strings using the wrong functions. Also replace mysterious bit-values with named constants for readability. The man ages for **makecpt** and **grd2cpt** did not list the **-h** option (needed if you want to write CPT comments on output) and **grd2cpt** did not list the option (but did support it).  A few minor correction to obscure test scripts that used awk to build cpts from parts.  Closes #3613.

### CODE REVIEW

**Comment by seisman** [comment]
All the CI jobs are failing now. The error is:
```
##[error]TF24668: The following team project collection is stopped: GenericMappingTools. 
Start the collection and then try again. Administrator Reason: abuse
```
See https://developercommunity.visualstudio.com/content/problem/1103605/pipeline-wont-run-administrator-reason-abuse.html

**Comment by PaulWessel** [comment]
What does that mean? I ran the full test locally and only grdgdal failed.

**Comment by seisman** [comment]
It possibly means there are some technical issues in Azure Pipelines. We have to wait for their fix.

**Comment by PaulWessel** [comment]
Shell I change the branch to master for this and then you backport, @seisman ?

**Comment by seisman** [comment]
Yes,

**Comment by PaulWessel** [comment]
Done.

**Comment by PaulWessel** [comment]
I will run all tests on macOS and CentOS first, locally.  MacOs had no failures, awaiting slower laptop...

**Comment by PaulWessel** [comment]
I have merged this branch @seisman

**Comment by joa-quim** [comment]
So this means 6.1 is definitively dead?

**Comment by seisman** [comment]
backport to 6.1 is done.

**Pull request merged**
