### PR TITLE
Tune docs and add a test.

### PR DESCRIPTION
**Pull request by joa-quim**
The test needs an orig PS

### CODE REVIEW

**Comment by seisman** [comment]
@joa-quim You need to run `gmt_make_module_src.sh` again to fix the CI failure.

**Comment by joa-quim** [comment]
I don't understand what the diff is complaining about. The lines are exactly equal.
The ``gmt_make_module_src.sh`` doesn't work on Windows. it has several ``/tmp/...`` and gives lots of errors like
```
: Invalid argument
grep: movie: No such file or directory
```

**Comment by seisman** [comment]
Since you changed "gmtgdal" to "grdgdal", the order of the modules changes.

**Comment by seisman** [comment]
> The `gmt_make_module_src.sh` doesn't work on Windows. it has several `/tmp/...` and gives lots of errors like
> 
> ```
> : Invalid argument
> grep: movie: No such file or directory
> ```

Perhaps we should use `$TMPDIR` instead of `/tmp`.

**Comment by PaulWessel** [comment]
Those scripts certainly were not written with Windows in mind. Maybe you can post the full output of running them with bash -xv ?

**Pull request merged**
