### PR TITLE
Remove two unused scripts and images

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

These two scripts generate images that were used in remote datasets. Since we have moved remote datasets to a new repository, these two scripts are no longer needed and can be deleted.

@meghanrjones How can I remove the two images `GMT_agefig.ps` and `GMT_earthmask.ps` tracked by dvc?

### CODE REVIEW

**Comment by meghanrjones** [comment]
> **Description of proposed changes**
> 
> These two scripts generate images that were used in remote datasets. Since we have moved remote datasets to a new repository, these two scripts are no longer needed and can be deleted.
> 
> @meghanrjones How can I remove the two images `GMT_agefig.ps` and `GMT_earthmask.ps` tracked by dvc?

The workflow below should work. I can add it to the contributing guide if it works for you:

```
dvc pull
rm doc/scripts/images/GMT_agefig.ps doc/scripts/images/GMT_earthmask.ps
dvc diff # Should show that those two figures were removed
dvc add doc/scripts/images
git add doc/scripts/images.dvc
git commit -m "Remove two unused images"
```

**Comment by seisman** [comment]
> The workflow below should work. I can add it to the contributing guide if it works for you:
> 
> ```
> dvc pull
> rm doc/scripts/images/GMT_agefig.ps doc/scripts/images/GMT_earthmask.ps
> dvc diff # Should show that those two figures were removed
> dvc add doc/scripts/images
> git add doc/scripts/images.dvc
> git commit -m "Remove two unused images"
> ```

It works. Thanks.

**Review by meghanrjones — APPROVED** [review]

**Comment by seisman** [comment]
The docs workflow fails with the following error message:
```
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: None, md5: 2d39427741997587c[18](https://github.com/GenericMappingTools/gmt/runs/5472746188?check_suite_focus=true#step:8:18)a28dd25d8[23](https://github.com/GenericMappingTools/gmt/runs/5472746188?check_suite_focus=true#step:8:23)0e.dir
WARNING: No file hash info found for '/home/runner/work/gmt/gmt/doc/scripts/images'. It won't be created.
A       test/baseline/grd2xyz/
A       test/baseline/psxyz/
A       test/baseline/gmtspatial/
A       test/baseline/psclip/
A       test/baseline/grdimage/
A       test/baseline/api/
A       test/baseline/grdtrend/
A       test/baseline/img/
A       test/baseline/grdfft/
A       test/baseline/grdclip/
A       test/baseline/grdgradient/
A       test/baseline/fitcircle/
A       test/baseline/psrose/
A       test/baseline/grdmask/
A       test/baseline/trend1d/
A       test/baseline/mgd[77](https://github.com/GenericMappingTools/gmt/runs/5472746188?check_suite_focus=true#step:8:77)/
A       test/baseline/pssolar/
A       test/baseline/grdmath/
A       test/baseline/gmtvector/
A       test/baseline/grdcontour/
A       test/baseline/gmtconnect/
A       test/baseline/subplot/
A       test/baseline/pscoast/
A       test/baseline/ogr/
A       test/baseline/time/
A       test/baseline/psternary/
A       test/baseline/pslegend/
A       test/baseline/pscontour/
A       test/baseline/grdcut/
A       test/baseline/segy/
A       test/baseline/psxy/
A       test/baseline/movie/
A       test/baseline/gmtmath/
A       test/baseline/sph/
A       test/baseline/grdblend/
A       test/baseline/potential/
A       test/baseline/grdview/
A       test/baseline/gmtbinstats/
A       test/baseline/sph2grd/
A       test/baseline/grdinterpolate/
A       test/baseline/gmtsplit/
A       test/baseline/gmtmex/
A       test/baseline/gmtlogo/
A       test/baseline/gmtselect/
A       test/baseline/grdlandmask/
A       test/baseline/pstext/
A       test/baseline/nearneighbor/
A       test/baseline/x2sys/
A       test/baseline/project/
A       test/baseline/grdpaste/
A       test/baseline/modern/
A       test/baseline/psmask/
A       test/baseline/grdselect/
A       test/baseline/latex/
A       test/baseline/pspolar/
A       test/baseline/greenspline/
A       test/baseline/pshistogram/
A       test/baseline/grdgdal/
A       test/baseline/pswiggle/
A       test/baseline/geodesy/
A       test/baseline/surface/
A       test/baseline/gmtconvert/
A       test/baseline/grdvector/
A       test/baseline/psimage/
A       test/baseline/grdfill/
A       test/baseline/gshhg/
A       test/baseline/grdmix/
A       doc/examples/images/
A       test/baseline/seis/
A       test/baseline/genper/
A       test/baseline/filter1d/
A       test/baseline/blockmean/
A       test/baseline/grdfilter/
A       test/baseline/psevents/
A       test/baseline/makecpt/
A       test/baseline/spotter/
A       test/baseline/psscale/
A       test/baseline/postscriptlight/
A       test/baseline/sample1d/
A       test/baseline/psbasemap/
A       test/baseline/gmtregress/
A       test/baseline/grdedit/
A       test/baseline/trend2d/
A       test/baseline/grdvolume/
A       test/baseline/mapproject/
A       test/baseline/triangulate/
A       test/baseline/gmtsimplify/
A       test/baseline/grdtrack/
A       test/baseline/grdsample/
A       test/baseline/pssac/
A       test/baseline/grd2cpt/
A       test/baseline/spectrum1d/
A       test/baseline/kml/
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
/home/runner/work/gmt/gmt/doc/scripts/images
Is your cache up to date?
<error.dvc.org/missing-files>
[93](https://github.com/GenericMappingTools/gmt/runs/5472746188?check_suite_focus=true#step:8:93) files added and 1 file failed
Error: Process completed with exit code 1.
```
Perhaps I should run `dvc push` before `git push`?

**Comment by seisman** [comment]
Running `dvc push` gives the following error:
```
╰─$ dvc push                                                                                                                                                                                  130 ↵
ERROR: failed to transfer 'md5: 2d39427741997587c18a28dd25d8230e.dir' - 401, message='Unauthorized', url=URL('https://dagshub.com/GenericMappingTools/gmt.dvc/2d/39427741997587c18a28dd25d8230e.dir')
ERROR: failed to push data to the cloud - 1 files failed to upload
```
I think I haven't been added as a collaborator for DAGsHub.

**Comment by meghanrjones** [comment]
> Running `dvc push` gives the following error:
> 
> ```
> ╰─$ dvc push                                                                                                                                                                                  130 ↵
> ERROR: failed to transfer 'md5: 2d39427741997587c18a28dd25d8230e.dir' - 401, message='Unauthorized', url=URL('https://dagshub.com/GenericMappingTools/gmt.dvc/2d/39427741997587c18a28dd25d8230e.dir')
> ERROR: failed to push data to the cloud - 1 files failed to upload
> ```
> 
> I think I haven't been added as a collaborator for DAGsHub.

You may be able to add yourself. If not, I'll try in a bit.

**Comment by meghanrjones** [comment]
> Running `dvc push` gives the following error:
> 
> ```
> ╰─$ dvc push                                                                                                                                                                                  130 ↵
> ERROR: failed to transfer 'md5: 2d39427741997587c18a28dd25d8230e.dir' - 401, message='Unauthorized', url=URL('https://dagshub.com/GenericMappingTools/gmt.dvc/2d/39427741997587c18a28dd25d8230e.dir')
> ERROR: failed to push data to the cloud - 1 files failed to upload
> ```
> 
> I think I haven't been added as a collaborator for DAGsHub.

Also, the [authentication instructions](https://dagshub.com/docs/reference/dagshub_storage/#pushing-files-or-using-a-private-repo) are on a per-repository basis, just in case you do not have that set-up yet for the gmt repository.

**Comment by seisman** [comment]
> Also, the [authentication instructions](https://dagshub.com/docs/reference/dagshub_storage/#pushing-files-or-using-a-private-repo) are on a per-repository basis, just in case you do not have that set-up yet for the gmt repository.

Thanks, now it works.

**Comment by seisman** [comment]
> Also, the [authentication instructions](https://dagshub.com/docs/reference/dagshub_storage/#pushing-files-or-using-a-private-repo) are on a per-repository basis, just in case you do not have that set-up yet for the gmt repository.

Thanks, now it works.

**Pull request merged**
