### PR TITLE
Allow setting BUILD_SHARED_LIBS to false for static build

### PR DESCRIPTION
**Pull request by PaulWessel**
Creating a static GMT failed to produce working executables.  There were several issues to address:

1. The gmt_core_module.c produced by gmt_make_module_src.sh had a function _gmt_core_module_lookup_ that we probably had never tested before.  It was furthermore out of date, not knowing about modern module names.  This has now been addressed and modules are again being found.
2. The other problem was the reliance on a static array in gmt_init.c.  For reasons not entirely clear to me, when supplemental modules were called and these again called functions in the static library, that static array (hash codes to handle parsing of GMT defaults) was reinitialized to zeros and no GMT defaults could be found.  Making it a structure under the API private pointer means it is initialized once by GMT_Create_Session and does not need to me modified again during that session.
3. The problem above is likely related to the fact that only the GMT core collection of modules are in the static library.  The supplemental library (and any other GMT-compatible external modules, such as the MB-system plugins) remain as shared libraries accessed via the plugins (*.so files).

I have build both static and shared and run all tests and all seems well.  It is important to give it a spin under Windows since shared/static behaves differently and I cannot guarantee that my solution works for Windows.  Hence, need feedback from @joa-quim and @seisman on this.

Otherwise, closes issue #2436.

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel Please remove the file "src/init" in this branch.

**Comment by seisman** [comment]
GMT still can't find supplemental modules, and the Linux and Windows builds fail probably due to some inconsistent compiler options. See the CI reports in https://github.com/GenericMappingTools/gmt/pull/2440 for details.

**Comment by joa-quim** [comment]
I’m away from the computer till Tuesday so can’t revisit but I have the impression that the supplements rely exclusively on dlopen and that cannot be made static.  

Sent from my iDedo

**Comment by PaulWessel** [comment]
So I had to delete several builds that had libgmt.dylib and reboot _before_ my static build would run and find the supplements.  It would run fine in Xcode debug but then the same code would report not finding the supplements from the command line...I think the code is correct (for macOS for sure) but boy, Apple really is doing something odd under the hood with shared libraries and links.

**Comment by PaulWessel** [comment]
@joa-quim, the supplemental and all other external libs will remain shared forever.  The static is _just_ about the core.  We have no way of building static with libraries we don't even maintain (e.g., mbsystem.so).

**Comment by PaulWessel** [comment]
Sure this is not OK? All checks passed.

**Comment by seisman** [comment]
The CI in this PR are building shared libraries. See #2440 for static builds.

**Comment by PaulWessel** [comment]
Hi @seisman, I guess this PR can be deleted once #3133 is merged?

**Comment by seisman** [comment]
Yes, we probably need to rethink about it if someone wants a static build in the future.

**Pull request closed without merging**
