### PR TITLE
Update gmtmath.rst

### PR DESCRIPTION
**Pull request by Esteban82**
Fix indentation of examples.

BTW, I noticed that some examples have an indentation and others don't. Should we use them or not?

### CODE REVIEW

**Comment by joa-quim** [comment]
No, better not indent the examples. They are highlighted already.

**Comment by Esteban82** [comment]
> No, better not indent the examples. They are highlighted already.

Ok, I just did it.

**Comment by anbj** [comment]
I think I asked Paul the same once about indentation, and he preferred to have them.

**Comment by anbj** [comment]
Yes; see [here](https://github.com/GenericMappingTools/gmt/issues/7226#issuecomment-1418929932) and response below.

**Comment by Esteban82** [comment]
Ok, so I have to undo all the last changes.  Do you agree @joa-quim ?

 How can I undo the last commit?

**Comment by seisman** [comment]
> I still prefer the non-indented because it may save us to break a command line example. 

I also prefer the non-indented version, because the code blocks are already highlighted with a colorful background. 

> But what we should do is whatever is done in the majority of of other examples.

It seems possible to batch convert all indented code blocks to non-indneted code blocks by replacing `  ::` with `::`.

> How can I undo the last commit?

If you really want to undo the last commit, you can use `git revert 230a7290f1a6cf29e12f45a2973b32aef1c81b7d` in a terminal.

**Comment by Esteban82** [comment]
Ok, I am not sure if I want to undo the last commit. I don't have a strong opinion on indetaction.

BTW, I notice that the table of operator don't fit in the screen. How can I remove the identation of the table? By removing the whitespace at the beginnig of each line?

**Comment by PaulWessel** [comment]
So long as I don’t have to do it I am fine with whatever system is decided

**Comment by joa-quim** [comment]
I also don't care much about this so minor thing but if someone wants to make the change my vote, as I said before, goes to no indentation. The highlighting is more than enough.

**Comment by anbj** [comment]
I care. The appearance of the docs is imporant. Even if it’s a minor thing, consistency gives a good impression and indicates a well-taken-care-of project. Gmt deserves it.

**Comment by PaulWessel** [comment]
True. If you are motivated please do it

**Comment by Esteban82** [comment]
> So no indentation, @Esteban82, @joa-quim?

No indentation. 

So, I think that this PR can be approved.

**Review by anbj — APPROVED** [review]

**Pull request merged**
