### PR TITLE
mapproject.rst: fix code blocks

### PR DESCRIPTION
**Pull request by anbj**
Fix code blocks in mapproject.rst.
See #7694.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]

**Comment by joa-quim** [comment]
But we decided to do exactly the contrary of this. 
No tabs at beginning of examples.

**Comment by PaulWessel** [comment]
@joa-quim is right. I am at too high altitude to be trusted and @jidanni is posting too much

**Comment by anbj** [comment]
But look at the docs (mapproject) now; this is how we want it, yes?

**Comment by anbj** [comment]
You need to indent the stuff that you want inside a code block following the ``::``. This is in the markup (rst) source. The rendered code block (html) will not be indented. I think it is correct now, but please [check](https://docs.generic-mapping-tools.org/dev/mapproject.html#examples).

**Comment by joa-quim** [comment]
No. It is indented.

**Comment by anbj** [comment]
This is what I see. Isn't this the way it is supposed to look?

Screenshot 2023-07-31 152602

**Comment by joa-quim** [comment]
Well I see the same, there is a small indent right?
But this is not important and I’m not near a computer for now and next week.

**Pull request merged**
