### PR TITLE
Create country color

### PR DESCRIPTION
**Pull request by gouldin**
I try pscoast -JQ105/0/23.2c -Rg -Bg15/g90 -D1 -N1 -Sblue -E=NA+p ?out.ps
All works fine.  I get the map after converting to pdf.
Then I append -K, and write
pscoast -R -J -EUS+gyellow -O >>out.ps
and gmt hangs.  Maybe there is something peculiar 
about 105E as center.  When I use 120 E as center, I get the US colored.

**Description of proposed changes**

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Seems to get in trouble when your central longitude means the US is split across the periodic map boundary.

**Comment by PaulWessel** [comment]
But you are raising an issue, not submitting a pull request.  I will close this and move content to a new issue.

**Comment by leouieda** [comment]
For reference, the new issue is #439 

@gouldin please report bugs or make feature requests by creating an Issue at https://github.com/GenericMappingTools/gmt/issues (see the "Issues" tab at the top of this page).

**Comment by gouldin** [comment]
thanks for re-posting.  I will eventually figure out how to manage github.

gtr

________________________________

**Comment by leouieda** [comment]
>  I will eventually figure out how to manage github.

It definitely takes some time (I've been at this for 9 years now). Please feel free to ping me by including @leouieda in your message if you need any help in the future.

**Pull request closed without merging**
