### PR TITLE
Do not use grid coordinates if a memory grid is a subset

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See #3196 for background - this only affects external calls to GMT.  The problem was this: _gmt_grd_project_ does the conversion from a long-lat grid to the Cartesian rectangular projected grid we can plot. In that function we need the x and y coordinates for both original and projected grid.  These are usually available in the header->x and ->y.  However, when a memory grid is passed in we do not have permission to change the memory.  So when a subset is selected, and implemented by a pad change, the x and/or y coordinates are no longer correct.  This is why things screwed, and only if the beginning of the vector was skipped (west, north).  We now check if the pad has been reset, and if so we obtain fresh coordinate arrays.
Also, there was a forced pad reset to 2 when the projected grid was first initialized but that cannot happen when we have external subsets.

Works for me in Matlab.  Needs @joa-quim  to test in Julia.

### CODE REVIEW

**Comment by joa-quim** [comment]
You can test it in Julia. #3196 has the Julia commands too.

**Comment by htyeim** [comment]
I think I have time to test it, but I don't know the workflow. I guest it involves compiling the source code [?]. Setting the environment must be complex.  Is there a way to build a Docker container (may be built upon [gcc](https://hub.docker.com/_/gcc), e.g., [ref](https://blobfolio.com/2018/12/using-docker-as-a-build-environment/)) for compile and test so I can do it?

**Comment by PaulWessel** [comment]
Yes, this means building GMT from master branch.  If you want to test this from Julia then let's have @joa-quim chime in on that.

**Comment by joa-quim** [comment]
Works fine in Julia too.

**Pull request merged**
