### PR TITLE
Add alloc return checks in xyz2grd

### PR DESCRIPTION
**Pull request by PaulWessel**
Might be related to #6739 or not, but fixing a few memory allocations that did not check the return values.

### CODE REVIEW

**Comment by anbj** [comment]
Difficult to review since I'm not able to install on affected system. What should I do?

**Comment by anbj** [comment]
Ok!

**Review by joa-quim — APPROVED** [review]
Easy rev (between two glasses of wine). Traditional check-if-not-enough-mem.

**Comment by PaulWessel** [comment]
I am thinking this might be @anbj problem: It happily allocates the large grid but when it later try to allocate the flag it fails but it does not check that and chaos ensues.

**Comment by anbj** [comment]
Yes Sir; fixed.

**Pull request merged**
