### PR TITLE
Update testgmtshell

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

I added a debug mode so that if you give any arrgument to testgmtshell it will echo out each line it reads in the format
`cmd = [yourcommand>]
`
before it runs it.

### CODE REVIEW

**Comment by seisman** [comment]
This branch was created from the master branch, so it contains many commits which shouldn't be merged into the 6.0 branch. You need rebase this branch onto the 6.0 branch first and force push the branch again.

**Comment by PaulWessel** [comment]
Shit, yes I started in master and moved the changes to 6.0 but not successful or the way I expected it.  Can w3 just delete this branch and I will start over?

**Comment by seisman** [comment]
No need to start over. Try following commands or I can help you with this.

```
git checkout testshell
git rebase -i 6.0 
# this command will open a text editor, which lists all the commits
# you can just delete the entries of irrelevant commits and only keep the one you want to commit
# then close the text editor.
git push -f
```

**Comment by PaulWessel** [comment]
OK, I did the rebase command while having testshell checked out. But must be missing a call after that since

pwessel@macnut:~/GMTdev/gmt-dev-> git push -f
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Do I switch to 6.0 first before the git push -f?

**Comment by seisman** [comment]
No. After rebasing, you should still stay at the testshell branch. Not sure what's wrong with your operations.

**Comment by PaulWessel** [comment]
Me either.  I had testshell checked out when I did the rebase and it listed a dozen or so commits, ending with the one about testgmtshell.c.  So I removed all the others and left it and all the comments in the file, then ran the git push -f.  Are you able to rescue me or give me other instructions?  Or remove things.  I have a copy of what I did so not a problem.

**Comment by seisman** [comment]
I've force pushed this branch. Now it's good.

**Comment by PaulWessel** [comment]
OK, so once checks have passed it can merge?

**Comment by seisman** [comment]
Yes, OK to merge

**Comment by PaulWessel** [comment]
Thanks!

**Pull request merged**
