### PR TITLE
Deprecate psrose -N and use -S+a instead

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See #5064  for background.

This first PR simply frees up option **-N**_mode_[**+p**_pen_] to be used to draw von Mises curves in a later PR by combining the old **-N** with **-S** in a new **-S**[**+a**] option.  The old syntax will still be honored in backwards compatibility.

### CODE REVIEW

**Review by meghanrjones — COMMENTED** [review]
It does not work for me. I tried editing `ex06.sh` to verify that `-S -N` and `-S+a` give the same result. `-S -N` works but `-S+a` gives this error:

```
./ex06.sh 
gmt [WARNING]: Length <unit> a not supported - revert to default unit [cm]
gmt [WARNING]: + not a valid number and may not be decoded properly.
rose [ERROR]: Option -J parsing failure. Correct syntax:
	-Jx<x-scale>|<width>[d|l|p<power>|t|T][/<y-scale>|<height>[d|l|p<power>|t|T]], scale in cm/units
	-Jz<z-scale>[l|p<power>], scale in cm/units
	Use / to specify separate x/y scaling (e.g., -Jx0.5/0.3.).  Not allowed with 1:xxxxx
	Use -JX (and/or -JZ) to give axes lengths rather than scales
rose [ERROR]: Offending option -JX0i
```

Perhaps this is a consequence of the previously deprecated format for **-S**?

**Comment by PaulWessel** [comment]
OK, I see - will fix after meeting.

**Comment by PaulWessel** [comment]
So I tried ex06 to and just ran

`gmt rose @fractures_06.txt -: -A10+r -S+a -Gorange -R0/1/0/360 -Bg -B+glightblue -W1p -JX15c -pdf t`

and it worked as expected.  Did you build the branch? Or did you run another command - let me know what command failed so I can have a look.  I cannot see how it may fail...

**Comment by meghanrjones** [comment]
It seems to be because **-J** is needed for **-S+a**. **-J** should still be optional.

This works:

```
gmt begin ex06_2
	gmt subplot begin 2x1 -A+JTL+o0.8c -Fs15c/9c -M1c
		gmt histogram -Bx+l"Topography (m)" -By+l"Frequency"+u" %" -BWSne+t"Histograms"+glightblue @v3206_06.txt -R-6000/0/0/30 -Gorange -W1p -Z1 -T250 -c0
		gmt rose @fractures_06.txt -: -A10+r -S -Gorange -R0/1/0/360 -Bg -B+glightblue -W1p -c1
	gmt subplot end
gmt end show
```

This also works:

```
gmt begin ex06_2
	gmt subplot begin 2x1 -A+JTL+o0.8c -Fs15c/9c -M1c
		gmt histogram -Bx+l"Topography (m)" -By+l"Frequency"+u" %" -BWSne+t"Histograms"+glightblue @v3206_06.txt -R-6000/0/0/30 -Gorange -W1p -Z1 -T250 -c0
		gmt rose @fractures_06.txt -: -A10+r -S -N -Gorange -R0/1/0/360 -Bg -B+glightblue -W1p -c1
	gmt subplot end
gmt end show
```

This does not work:
```
gmt begin ex06_2
	gmt subplot begin 2x1 -A+JTL+o0.8c -Fs15c/9c -M1c
		gmt histogram -Bx+l"Topography (m)" -By+l"Frequency"+u" %" -BWSne+t"Histograms"+glightblue @v3206_06.txt -R-6000/0/0/30 -Gorange -W1p -Z1 -T250 -c0
		gmt rose @fractures_06.txt -: -A10+r -S+a -Gorange -R0/1/0/360 -Bg -B+glightblue -W1p -c1
	gmt subplot end
gmt end show
```

**Comment by PaulWessel** [comment]
Fixed.  The problem was in gmt_init which did a special check if -S was given with arg (old args) but that caught +a as well.  Now checks for that case as well and your failing example and all tests work.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
