### PR TITLE
Commit the files that should have gone into #8612

### PR DESCRIPTION
**Pull request by joa-quim**
(Fix the variable transparency case that was broken by the #8612 commit.)

### CODE REVIEW

**Comment by seisman** [comment]
The CI jobs tell me that `test/grdimage/transp_mix.sh` still passes, but `test/grdimage/image_vartrans.sh` fails.

**Comment by joa-quim** [comment]
I failed to commit also the modified tests. You should now see the opposite situation. `test/grdimage/transp_mix.sh` fails (because I removed the KNOWN_FAILURE) and `test/grdimage/image_vartrans.sh` passes. What I ask you is to replace the `transp_mix.ps` original by the new one.

**Comment by seisman** [comment]
It's like something different with macOS preview.

Using the Adobe PDF Reader, I've 

image

image

**Comment by joa-quim** [comment]
But what do you get when running the tests? I get
```
C:\v\build>ctest -R image_vartrans
Test project C:/v/build
    Start 523: test/grdimage/image_vartrans.sh
1/1 Test #523: test/grdimage/image_vartrans.sh ...   Passed    3.44 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   3.47 sec

C:\v\build>ctest -R transp_mix
Test project C:/v/build
    Start 536: test/grdimage/transp_mix.sh
1/1 Test #536: test/grdimage/transp_mix.sh ......***Failed    5.17 sec
```

**Comment by joa-quim** [comment]
Dis you update for this PR? I latter added the modified scripts. Note that now to have variable transparency we must now use the option **-Q+t**. _i.e._, `gmt grdimage rgba.tif -Q+t`

**Comment by seisman** [comment]
Here is what I have in my log file:
```
Start testing: Nov 11 22:06 CST
----------------------------------------------------------
532/1186 Testing: test/grdimage/image_vartrans.sh
532/1186 Test: test/grdimage/image_vartrans.sh
Command: "/bin/bash" "gmtest" "test/grdimage/image_vartrans.sh"
Directory: /Users/seisman/OSS/gmt/gmt/build/debug/test
"test/grdimage/image_vartrans.sh" start time: Nov 11 22:06 CST
Output:
----------------------------------------------------------
Set GMT_SESSION_NAME = 70298
/usr/local/bin/gm compare: image difference exceeds limit (0.0140282 > 0.003).
ERROR: gmtest:171
memtrack errors: 0
exit status: 1
test/grdimage/image_vartrans.ps: RMS Error = 0.0140 [FAIL]
memtrack errors: 0
exit status: 1
<end of output>
Test time =  15.60 sec
----------------------------------------------------------
Test Failed.
"test/grdimage/image_vartrans.sh" end time: Nov 11 22:06 CST
"test/grdimage/image_vartrans.sh" time elapsed: 00:00:15
----------------------------------------------------------

End testing: Nov 11 22:06 CST
```

**Comment by joa-quim** [comment]
> /Users/seisman/OSS/gmt/gmt/build/debug

Hmm, my runs were done with a release build. Could it be the reason?

**Comment by seisman** [comment]
> Did you update for this PR? I latter added the modified scripts. Note that now to have variable transparency we must now use the option **-Q+t**. _i.e._, `gmt grdimage rgba.tif -Q+t`

I've updated to the latest version.



> > /Users/seisman/OSS/gmt/gmt/build/debug
> 
> Hmm, my runs were done with a release build. Could it be the reason?

I also tried the release build. The image is still different from the baseline image, so it fails.

**Comment by joa-quim** [comment]
Can't make sense out of this. I am using `GMT_DATA_SERVER static` at compile time (the only one that works for me). And before this PR the variable transparency **had to fail** always because code use completely broken.

**Comment by joa-quim** [comment]
How can we have this in the original PS? It's **impossible**. Nothing in the `image_vartrans.sh` puts a BACKGROUND word as a kind of watermark. And this disappears when we convert the orig in .png or .pdf

image

**Comment by seisman** [comment]
The "BACKGROUND" word is likely added by macOS Preview. I don't see it in the Adobe PDF reader.

**Comment by joa-quim** [comment]
Yes, likely but the SC I posted was taken in my computer as seen from Ghostscript.
The CI's help nothing. `image_vartrans` fails on Linux and passes on Mac & Windows.

**Comment by joa-quim** [comment]
Any reason to not to merge this PR?

**Comment by seisman** [comment]
I've updated the baseline image for `transp_mix.sh` and the image comparison is available at https://github.com/GenericMappingTools/gmt/pull/8613#issuecomment-2472259078. The old and new images seem almost the same, except that the new image looks more blurry than the old one. Is it expected?

**Comment by joa-quim** [comment]
I can’t see a difference between the two. And note that only the second row, first col subplot has changed.

**Comment by seisman** [comment]
What's the dvc version you're using?

**Comment by joa-quim** [comment]
C:\progs_cygw\GMTdev\gmt5\master>dvc --version
3.28.0

But not that all 3 OSs fail this CI test.

**Pull request merged**
