### PR TITLE
Adds longoptions support to mapproject, grdtrack and psxy.

### LINKED ISSUE #6947: longoptions support for mapproject/grdtrack/psxy
**Description of the desired feature**

longoptions support for mapproject/grdtrack/psxy

**Are you willing to help implement and maintain this feature?** Yes/No

Yes

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**

Adds longoptions support to mapproject, grdtrack and psxy.

Fixes #6947 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]

**Comment by PaulWessel** [comment]
Great, I merged in master and approved and merged this branch back into master.

**Comment by anbj** [comment]
Do you have to enable the longoptions to test them? Or should they work out-of-the-box?

**Comment by PaulWessel** [comment]
In cmake you need to set this in ConfigUser.cmake

`set (USE_LONG_OPTIONS TRUE)`

and in ConfigUserAdvanced.cmake

```
add_definitions(-DUSE_COMMON_LONG_OPTIONS) 	# Turn on testing of upcoming long-option syntax for common GMT options
add_definitions(-DUSE_MODULE_LONG_OPTIONS) 	# Turn on testing of upcoming long-option syntax for module options
```

I cannot recall why we need to edit both files...

**Comment by anbj** [comment]
Great, thanks Paul.

**Pull request merged**
