### PR TITLE
Let the -U+t (i.e. without any argument to the +t modifier) plot no stamp at all.

### PR DESCRIPTION
**Pull request by joa-quim**
Now this plots only the GMT logo and nothing else. Before this PR it still plotted the time stamp.
```
gmt plot -R0/3/0/0.1 -Jx1i -U+t -T  -view GMT_-U
```

### CODE REVIEW

**Comment by Esteban82** [comment]
I got this with master

GMT_-U_previo


and this with this branch

GMT_-U

I use this command with `png` (instead of `view`). Is view a thing? I got a weird message. 

`gmt plot -R0/3/0/0.1 -Jx1i -U+t -T  -png GMT_-U`

**Review by Esteban82 — APPROVED** [review]

**Comment by joa-quim** [comment]
I confess I just learnt about the -view in https://docs.generic-mapping-tools.org/latest/reference/options.html#timestamps-on-plots-the-u-option

But yes, the plots you posted correctly show the situation. **+t** is supposed to replace the time stamp but only worked if it has an argument. A trick was to set `+t" "` but that is ugly and hard to discover.

**Comment by rbdavis** [comment]
Hi Roger,

I'm not cc'ing anyone. You are probably receiving these messages because you are (to be confirmed) in the 'core' group that I indeed select for reviewing the PR's I submit.

Cheers

Joaquim
 

-----Original Message-----

**Comment by seisman** [comment]
Yes, Roger is in the core group. I can remove him from the "core" group or maybe we can have a "gmt-core" team for people who'd like to review the GMT C project.

**Comment by joa-quim** [comment]
I just removed Roger (and Paul) from the 'core' group. And yes, we could have a team for reviews, but how different would it be from 'core'?

**Comment by seisman** [comment]
Actually, we already have a "gmt-maintainers" team (https://github.com/orgs/GenericMappingTools/teams). 

image

**Comment by joa-quim** [comment]
Where, curiously, I am not in. Sure I can add me, but I still think the 'core' is the right group for asking/informing about new PR's.

**Pull request merged**
