### PR TITLE
Ensure we close the opened netCDF file in gmt_nc_is_cube

### PR DESCRIPTION
**Pull request by PaulWessel**
The (new) _gmt_nc_is_cube_ function prematurely returned without closing the door. Closes #4745.

### CODE REVIEW

**Comment by seisman** [comment]
I can't test it unless it is merged into master.

**Comment by PaulWessel** [comment]
OK, well, alla tests pass as before and the only real difference is in gmt_nc_is_cube which now simply closes a file.  So I think a harmless PR that will solve your problem once in master.  Perhaps just approve.

**Comment by seisman** [comment]
I just realize that I can test it in PR #4745. Will report back in < 30 minutes.

**Review by joa-quim — APPROVED** [review]
Confirmed that it works. Uf.

**Comment by PaulWessel** [comment]
Did this do the trick, @seisman ?

**Comment by seisman** [comment]
It works for the simple tests in PR #4745, but I need to wait for conda-forge to run the full PyGMT tests.

**Comment by PaulWessel** [comment]
OK, I assume that will work fine since we clearly fixed the bug with the missing close.  But post if any surprises are found.

**Pull request merged**
