### PR TITLE
Let grdinterpolate also do 1-D profiles through the data cube

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

Initially, grdinterpolate was set up to interpolate a 3-D data cube at planes normal to the 3rd axis (usually time or depth), such that the planes could be saved as new grids.  It is also useful to sample such grid along lines that are parallel to the 3rd axis going through the grids at specified (fixed) lon,lat point(s).  This PR adds the new option **-S**_x/y_|_pointfile_[**+h**_header_] to do this.  Because **-S** changes the output type form grid to table I have added the usual common options that accompany table i/o (**-b**, **-i,** etc).  We pass the input points to the given grid layers to grdtrack and thus first just sample the layers at their levels.  If **-T** is used we then interpolate these series via sample1d.

I have tested it on some synthetic data and made sure **-S** works for a fixed point and a list of points, and that **-T** works with this as well.  It would be helpful if Dave and Eric could build this branch and try it out.  If you have a bunch of grids (*.grd), a table with the times (dates.txt), and a file with desired locations of the time-series (points.txt), you can try

`gmt grdinterpolate *.grd -Zidates.txt -Spoints.txt > profiles.txt`

To save to separate profile files you need to add **-G**profile_%d.txt or similar.

### CODE REVIEW

**Comment by PaulWessel** [comment]
As per #2783 I have also implemented a grid slicing through the 3-D cube.  It is limited to a vertical slice but the surface expression (set with **-E**) can be complicated and sampling can be customized.  For 3-D layers with variable spacing you must also sample along the 3rd dimension via **-T**.  Added new modifiers **+p** (force sampling along a parallel if the line is so aligned) and **+g** (report distance as degrees longitude or latitude instead of great circle distances if line is so aligned ); the +g modifier is also added to grdtrack but +p is left off since grdtrack has **-Ap**.  Also, since grdinterpolate does not have **-A** I added modifier **+x** for lo**x**odrome.

Summary: **-S** drills down the cube at the given point(s) and produces a set of time/space series, while -E creates a vertical slice 2D grid from the 3D cube.

**Comment by PaulWessel** [comment]
Hi @seisman, just checking if you are happy with this PR so I can merge it?  We can then finalize the -JP stuff from #2785.

**Comment by seisman** [comment]
I didn't find time to try this PR, but the description of **-E** and **-S** looks good to me. It would be good if you can add a few tests.

**Comment by PaulWessel** [comment]
OK, will do that.

**Comment by PaulWessel** [comment]
The obvious examples are the ones from the seismic data set and I kind of want to fix the crazy #2785 stuff first so I can make tests that does not require awking those grids to make radial distances...  I think I will work on that first, so we can hold this one until ready.

**Comment by PaulWessel** [comment]
Sorry, meant implementing #2791.

**Pull request merged**
