### PR TITLE
doc: Add the interactive GMT color picker tool to the GMT docs

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Add the interactive "Color Picker" web tool to the GMT docs.

Also remove the long table of color lists from the [gmtcolors](http://docs.generic-mapping-tools.org/dev/gmtcolors.html) page.

**Preview**:
image

image

Closes https://github.com/GenericMappingTools/gmt/issues/7875.

---

Just keep a record. Here is the one-time Python script used to generate the long list of color boxes in the HTML page.
```
with open("gmt_color_rgb.h") as fin:
    rgbs = fin.readlines()
with open("gmt_colornames.h") as fin:
    names = fin.readlines()
    
rgbs = [v.strip("\n,'{}") for v in rgbs]
names = [v.strip("\n,\"") for v in names]

count = 0
for i in range(len(rgbs)):
# for i in range(10):
    name = names[i]
    if name.startswith("grey"):
        continue
    if count % 25 == 0:
        print('<div class="color-row">')

    rgbv1 = "/".join(rgbs[i].split(', '))
    rgbv2 = ", ".join(rgbs[i].split(", "))
    # print('    <div class="color-box">')
    print(f"""    <div class="color-box" title="Name: {name} RGB: {rgbv1}" style="background-color: rgb({rgbv2});" onclick="copyToClipboard('{name}', '{rgbv1}', notification)"></div>""")
    if count % 25 == 24:
        print("</div>")

    count += 1
```

### CODE REVIEW

**Comment by PaulWessel** [comment]
I switched to this branch, built from scratch, then built docs.  I cannot see any picker when I click the link?

screen

**Comment by seisman** [comment]
The color boxes on this page is generated by javascript on the fly, so it doesn't work if you open the HTML file directly in your web browser.

To use it locally, you have to start a local web server. For example, you can do:

```
cd /path/to/the/html/directory
python -m http.server
```
then open `localhost:8000` in your web browser.

**Comment by PaulWessel** [comment]
That works. Once it is merged and built and available from www.generic-... will it then just work or do everybody have to start a http server? (shows how little I know about this).

**Comment by seisman** [comment]
> Once it is merged and built and available from [www.generic-](http://www.generic-)... will it then just work or do everybody have to start a http server? (shows how little I know about this).

It'll work smoothly once deployed to the gh-pages branch, because GitHub has started the server for us.

**Comment by seisman** [comment]
@PaulWessel I've updated this PR so that you can see all the color boxes even locally (i.e., directly open it in your web browser). Please give this PR another review.

**Comment by PaulWessel** [comment]
Sorry, was busy with other on-GMT things.  Just switched to your branch and tried to build the docs and got

```
Extension error:
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')
```

I think we had this issue earlier and you gave me a command to include such extensions?

**Comment by PaulWessel** [comment]
Thanks, just did that now but when building again I get the same error as above.  Install the python extensions seems OK?

```
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Installing collected packages: snowballstemmer, zipp, urllib3, sphinxcontrib-jsmath, Pygments, MarkupSafe, imagesize, idna, docutils, charset-normalizer, babel, alabaster, requests, Jinja2, importlib-metadata, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, sphinx, sphinxcontrib-jquery, sphinxcontrib-youtube, sphinx-togglebutton, sphinx_rtd_theme, sphinx-jinja, sphinx-design, sphinx-copybutton
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Pygments-2.16.1 alabaster-0.7.13 babel-2.13.1 charset-normalizer-3.3.2 docutils-0.18.1 idna-3.4 imagesize-1.4.1 importlib-metadata-6.8.0 requests-2.31.0 snowballstemmer-2.2.0 sphinx-7.2.6 sphinx-copybutton-0.5.2 sphinx-design-0.5.0 sphinx-jinja-2.0.2 sphinx-togglebutton-0.3.2 sphinx_rtd_theme-1.3.0 sphinxcontrib-applehelp-1.0.7 sphinxcontrib-devhelp-1.0.5 sphinxcontrib-htmlhelp-2.0.4 sphinxcontrib-jquery-4.1 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.6 sphinxcontrib-serializinghtml-1.1.9 sphinxcontrib-youtube-1.4.1 urllib3-2.0.7 zipp-3.17.0
```

**Comment by seisman** [comment]
> Thanks, just did that now but when building again I get the same error as above. Install the python extensions seems OK?
> 
> ```
> Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
> Installing collected packages: snowballstemmer, zipp, urllib3, sphinxcontrib-jsmath, Pygments, MarkupSafe, imagesize, idna, docutils, charset-normalizer, babel, alabaster, requests, Jinja2, importlib-metadata, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, sphinx, sphinxcontrib-jquery, sphinxcontrib-youtube, sphinx-togglebutton, sphinx_rtd_theme, sphinx-jinja, sphinx-design, sphinx-copybutton
> Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Pygments-2.16.1 alabaster-0.7.13 babel-2.13.1 charset-normalizer-3.3.2 docutils-0.18.1 idna-3.4 imagesize-1.4.1 importlib-metadata-6.8.0 requests-2.31.0 snowballstemmer-2.2.0 sphinx-7.2.6 sphinx-copybutton-0.5.2 sphinx-design-0.5.0 sphinx-jinja-2.0.2 sphinx-togglebutton-0.3.2 sphinx_rtd_theme-1.3.0 sphinxcontrib-applehelp-1.0.7 sphinxcontrib-devhelp-1.0.5 sphinxcontrib-htmlhelp-2.0.4 sphinxcontrib-jquery-4.1 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.6 sphinxcontrib-serializinghtml-1.1.9 sphinxcontrib-youtube-1.4.1 urllib3-2.0.7 zipp-3.17.0
> ```

It's likely that you have multiple `sphinx` installed. Need to make sure you're using the correct one. Check the outputs of following commands:
```
which python
which sphinx-build
```

**Comment by PaulWessel** [comment]
```
(pygmt) pwessel@MacAttack-2:~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev-> which python
/Users/pwessel/miniconda3/envs/pygmt/bin/python
(pygmt) pwessel@MacAttack-2:~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev-> which sphinx-build
/Users/pwessel/miniconda3/envs/pygmt/bin/sphinx-build
```

**Comment by seisman** [comment]
You're in the `pygmt` environment. Maybe that's the problem? What if you run `conda deactivate pygmt` to exit the `pygmt` environment?

**Comment by PaulWessel** [comment]
No difference at first.  Rebooted and reinstalled those requirements and it worked. Picker works great!

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
