### PR TITLE
Improve subplot when MAP_FRAME_TYPE=inside

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See #4235 for context.  This small PR deals with the calculation of panel size and margins in the event **MAP_FRAME_TYPE**=_inside_ before **gmt subplot begin** is run.  Previously we did not check, but with all annotations and ticks inside the panel, the margin is simply what is set via **-M**.  I added a simple 4-panel check to ensure this works.  This PR does not address the desire to have inside basemaps plot on top of the panel content, which will require much more work and changes.

### CODE REVIEW

**Comment by seisman** [comment]
I changed your test to:
```
gmt subplot begin 2x2 -Fs3i -M5p -A -SCb -SRl -Bwstr -R0/80/0/10 -T"Inside annotations" --MAP_FRAME_TYPE=inside
```
and then it doesn't work.

**Comment by PaulWessel** [comment]
Well, --PAR=value only applies to a single command, so when the later basemap calls come there is no such thing, despite us computing the correct spacing during begin. Hm, In the next PR I am adding a new line to the hidden subplotinfo file that remembers that inside was active, and we could use that to add --MAP_FRAME_TYPE=inside when we plot the frame.  That way the par setting will live until subplot end.  I agree this is what a user would want thought.
However, the current PR works correctly if used with gmt set, so lets accept that one and then I can add more along these lines.

**Review by seisman — APPROVED** [review]

**Comment by PaulWessel** [comment]
Thanks, will work on this probably more tomorrow.

**Comment by PaulWessel** [comment]
Question for @joa-quim and @seisman : In **psxy** and possibly other modules, we lay down the basemap _before_ plotting symbols/lines, because we want the latter to overprint any gridlines.  However, if frametype _inside_ is in effect, not only will symbols overprint any gridlines, but they will overprint annotations.  I think we agree that when _inside_ is used we want these things to be on top of the plot.  With the current scheme, even if I figure out a way to add the requested subplot **-B** options to the last plot call in a panel, it may _still_ get obscured by the **plot** module.  I am also not sure if annotations and ticks and gridlines should all be considered at the same level with _inside_.  But I guess they should all go on top?

Solution: Ensure all plot modules switch to calling _gmt_map_basemap_ after all plotting if inside is in effect.  Note some modules, like **grdimage**, only do this at the end anyway.

**Comment by joa-quim** [comment]
Yes, in ``grdimage`` the grid goes on top, otherwise it wouldn't be visible. But for plot they have to go **under** the symbols/lines. We had this discussion when we found that ``plot`` and ``plot3d`` were doing different things.
See this Matlab [example](https://www.mathworks.com/help/matlab/ref/scatter3.html). It would be awful if grids were on top. And we don't want ``plot`` and ``plot3d`` do different things. Inner annotations, though, should preferably go on top of everything.

**Comment by PaulWessel** [comment]
OK, so sounds like many modules should call gmt_map_basemap twice: before and after, but inside there will be tests to only do one or only do part (say gridlines are always on bottom except for images).  Need some temp variable to remember that girdlines were or were not plotted earlier.

**Comment by PaulWessel** [comment]
My first try on this.  Getting 60 failed tests because now gridlines are behind things like psvelo ellipses, histogram bars, etc.
I am guessing we want that, i.e., gridlines on the back except for images (grdimage, psimage, grdview) and pscoast.  ANything else that should have gridlines on top?

**Comment by PaulWessel** [comment]
What about grdcontour and pscontour when we will with color? Kind of like images. no? But just regular contours are like lines, so gridlines on back.

**Comment by joa-quim** [comment]
Yep, those two should display a binary behavior. Grid on top when fill color and bellow when contours only.

**Comment by PaulWessel** [comment]
And histograms should cover up gridlines as well?

**Comment by joa-quim** [comment]
Both Matlab and Matplotlib put the grid lines on top, though our logic would say that they should go under because a bar is a kind of a symbol.
What histogram should have is this ``BarWidth`` option (in Matlab)
```
>> A = [0 0 1 1 1 0 0 0 0 NaN NaN 1 0 0 0 1 0 1 0 1 0 0 0 1 1 1 1];
C = categorical(A,[1 0 NaN],{'yes','no','undecided'});
>> histogram(C,'BarWidth',0.5)
>> histogram(C,'BarWidth',0.5); grid on
```

And the hexagonal binning? It probably has gridlines under but since it makes an image the lines should go on top.

**Comment by PaulWessel** [comment]
We could introduce **-E**_width_[**unit**][**+o**_off_[**unit**]] where _width_ changes the plotted width of each bar.  If units are applied then that is a firm width, else it is assumed to be in x-units.  Optionally the modifier _off_ could shift the bar from its normal position.  That way you could plot more than one histogram for the same binning scheme by shrinking size and offsetting them.

Hexagonal binning are like images so need gridlines on top, but is done via call to plot.  I will need to see how to fix that.

**Comment by PaulWessel** [comment]
hexagonal binning is just a separate plot with hexagon symbols.  So plot cannot know that perhaps you might want gridlines on top.  Users can always override this behavior at any time by adding a basemap call.

**Comment by PaulWessel** [comment]
How about solar? Kind of like pscoast in plotting a large polygon so gridlines on top, @joa-quim ?

**Comment by joa-quim** [comment]
Yes, solar is like pscoast.

**Comment by joa-quim** [comment]
> We could introduce -Ewidth[unit][+ooff[unit]]

The horizontal offset would be useful in bar plots too (``psxy -Sb``)

**Comment by PaulWessel** [comment]
Hm, maybe.  There we have at least -D to do that, for the most common case of shifting by a plot dimension offset.

**Pull request merged**
