### PR TITLE
Add longoptions support for gmtconnect

### LINKED ISSUE #7950: longoption support for gmtconnect
**Description of the desired feature**

longoption support for gmtconnect

**Are you willing to help implement and maintain this feature?** Yes/No

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**
Add longoptions support for gmtconnect

Python differences:

  No Python module

Julia differences:

  linkfile (-L) changed to link_file to match style with list_file (-Q)
    Better to use underscore for both options or neither.

Fixes #7950

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by PaulWessel** [comment]
@joa-quim, what do you think about the difference between **-L** (takes a single file name) and **-Q** (takes a format template from which two file names can be created)?  Is list_file and link_file still reasonable?

**Comment by joa-quim** [comment]
To be thrush I don't like much the `file` suffix. In Julia/MEX we can make it return a GMTdataset. Perhaps `link_info`, `list_names`?

**Comment by PaulWessel** [comment]
I see, yes "file" is not always true.  Maybe just --link and --lists ?

**Comment by joa-quim** [comment]
OK

**Comment by joa-quim** [comment]
But should be `links`, not `link`

**Comment by PaulWessel** [comment]
Well, **-L** only accepts a single destination (ie., one file) with no template for several links (unlike **-Q** which can be one or a template with %c in it)

**Comment by joa-quim** [comment]
Yes, but it stores the _links_ (there are many) not just one as a singular would suggest.

**Comment by PaulWessel** [comment]
Good point. plural it shall be

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
