### PR TITLE
Let -d set starting column via modifier

### PR DESCRIPTION
**Pull request by PaulWessel**
See #5630 for background discussion.  The best solution is to add an optional modifier **+c**_col_ to override the default settings for the starting column, which for backwards compatible reasons shall remain 2 for input and 0 for output.

All tests pass for me since the default remains the same.

Note: I don't understand how to get the modifier to show up in the options.rst file - it works in the explain*.rst_ files.

### CODE REVIEW

**Comment by meghanrjones** [comment]
The remaining files that need to be updated are doc/rst/source/std-opts-classic.rst and doc/rst/source/std-opts.rst.

**Comment by PaulWessel** [comment]
Seems pretty good now, no?

**Review by meghanrjones — APPROVED** [review]

**Comment by meghanrjones** [comment]
Ran into a problem building mbsystem due to the update to ``gmt_input_is_nan_proxy`` in this PR:
```
mbgrd2obj.c:360:46: error: too few arguments to function call, expected 3, have 2
                if (gmt_input_is_nan_proxy(GMT, G->data[ij])) {
                    ~~~~~~~~~~~~~~~~~~~~~~                 ^
/Users/meghanj/Sandbox/gmt-dev/include/gmt/gmt_prototypes.h:335:17: note: 'gmt_input_is_nan_proxy' declared here
EXTERN_MSC bool gmt_input_is_nan_proxy (struct GMT_CTRL *GMT, double value, unsigned int col);
```

**Comment by PaulWessel** [comment]
Thanks, will fix after breakfast

Paul Wessel, Professor
Dept. of Earth Sciences
SOEST, U of Hawaii at Manoa

**Pull request merged**
