### PR TITLE
put the input table under the required arguments for spotter

### PR DESCRIPTION
**Pull request by wangliang1989**
**Description of proposed changes**

Fixes #

**Reminders**

- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] Add tests for new features or tests that would have caught the bug that you're fixing.
- [x] Describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by wangliang1989** [comment]
> Actually, for grdpmodeler, the input grid is optional as you can define a region via -R -I [-r]. So it should remain in the Optional Argument section. Your other two modules are correct, so please just rever the grdpmodeler changes.

revered.

I think the branch is needed to rebased before merging which can be done by Github

**Comment by wangliang1989** [comment]
Why not merge?

**Comment by PaulWessel** [comment]
Well, our CI fails because the gmtserver is still down, but I will merge it anyway since just docs.

**Comment by PaulWessel** [comment]
Thanks!

**Comment by wangliang1989** [comment]
> Thanks!

My another PR need your comment.

I am happy to help

**Pull request merged**
