### PR TITLE
Let movie -A handle addition of audio track

### PR DESCRIPTION
**Pull request by PaulWessel**
Thie enhancement allows users to add a narration (or any sound) track to their animation.  Via **+e** the length of the audio can be stretched to exactly fit the animation length.

@Esteban82, this PR compiles but I have not tested any of it.  If you have time then please do.  The key coding is in movie.c starting around line 2620.

### CODE REVIEW

**Comment by Esteban82** [comment]
Ok, great @PaulWessel. I will test it. 

Will we need to make a test for gmt/test/movie also?

**Comment by PaulWessel** [comment]
Hard to test movies. Maybe eventually we only create master frame pdf and compare with original

**Comment by anbj** [comment]
I tried adding an mp3-file to an mp4 movie. This resulted in the movie containing only the audio, and not any video.

(Sorry  - couldn't wait testing)

**Comment by PaulWessel** [comment]
I just updated movie.c and also the Indiana Jones track with audio and it worked brilliantly.

**Comment by Esteban82** [comment]
I inverse the ratio formula. I test it with the Indiana Jones script. When I reduce length of movie (`animation_duration` ), the audio was strecht. Now works well with my commit.

**Review by Esteban82 — APPROVED** [review]

**Comment by PaulWessel** [comment]
Thanks, good catch.

**Pull request merged**
