### PR TITLE
Update mapproject.rst

### PR DESCRIPTION
**Pull request by jidanni**
Indent to get yellow examples, not white.

### CODE REVIEW

**Comment by joa-quim** [comment]
Nope, no tabs. 
(Better leave this type of things for our self’s no?)

**Comment by anbj** [comment]
Hmmm. @jidanni, you removed the tabs in 3c829abe717.
They should be there. Not sure why this was closed.

**Comment by PaulWessel** [comment]
My fault not paying attention.  On family trip. Iif you have time @anbj feel free to fix.

**Comment by anbj** [comment]
No problem Paul. Enjoy your trip!

**Comment by joa-quim** [comment]
Hmm, replied already but text got lost. 

We decided not long ago to NO TABS in examples.

**Comment by anbj** [comment]
> Hmm, replied already but text got lost.
> 
> We decided not long ago to NO TABS in examples.

I'm confused. It has to be indented (tab or space) to become a code block. We want that, right?

**Pull request closed without merging**
