### PR TITLE
gmt.conf.rst: condense description of FORMAT_CLOCK_IN and FORMAT_CLOC…

### PR DESCRIPTION
**Pull request by anbj**

### CODE REVIEW

**Comment by PaulWessel** [comment]
I think you have the discussion of the purpose of .xxxx under CLOCK_IN but that only applies to CLOCK_OUT.  For in I think it is mostly the crazy stuff about am/pm as well as delimiters that matters (and whether there are minutes and seconds) but decimals should be fine regardless.

**Comment by anbj** [comment]
Indeed. I'll revise when I can.

**Comment by anbj** [comment]
I think I'm going to mess up the git stuff on this one. If it fails I'll just create a new PR.

**Comment by seisman** [comment]
> I think I'm going to mess up the git stuff on this one. If it fails I'll just create a new PR.

No worries. git history in this PR looks good.

**Comment by anbj** [comment]
Really? I rebased the branch against the upstream master and then force pushed. I thought I might have to rebase against master of my _forked repo_ (first getting my forked master up-do-date).

**Comment by seisman** [comment]
> Really? I rebased the branch to the upstream master and then force pushed. I thought I might have to rebase to master of my _forked repo_ (first getting my forked master up-do-date). So I can rebase directly to upstream?

Yes, rebasing to upstream master branch is simpler.

**Comment by anbj** [comment]
> > Really? I rebased the branch to the upstream master and then force pushed. I thought I might have to rebase to master of my _forked repo_ (first getting my forked master up-do-date). So I can rebase directly to upstream?
> 
> Yes, rebasing to upstream master branch is simpler.

Super, thanks @seisman!

**Comment by anbj** [comment]
Between other stuff going on, this was kind of left on the bench. If it looks OK, please merge. Or let me know if anything else should be changed/moved/annihilated.

**Comment by seisman** [comment]
> not sure if I have to bring this up-to-date with master before it can be merged

Not necessary for this PR, because changes in this PR are simple and are not conflict with the main branch.

**Pull request merged**
