### PR TITLE
Let movie and batch use input script mode to decide the OS

### PR DESCRIPTION
**Pull request by PaulWessel**
When running the windows-installer versions of **movie** or **batch** the user may wish to write scripts in bash or batch.  Thus, commands for moving and copying files as well as directory separators should be determined based on the script type and not just the fact it is a windows binary.  Hopefully this PR will address #4821.

Left in WIP mode for now since we need more cross-platform testing for the Windows executables.

### CODE REVIEW

**Comment by joa-quim** [comment]
You forgot to wrap some of these
```
error C2065: 'S_IRWXU': undeclared identifier
```

**Comment by PaulWessel** [comment]
Boy, I forgot to even look for teh #ifndef branches in general...

**Comment by joa-quim** [comment]
Even worse now. I have a lot more of those errors.
You don't need to set executable bit on bash files to run them on Windows.

**Comment by PaulWessel** [comment]
What are the errors? An this is running a batch-script movie on Windows, right? 
OK, I agree I goofed here,  Those are not command line statements but system calls (chmod) and those should be under ifdefs.  It is just the runtime - scripting commands that we need to deal with.

**Comment by joa-quim** [comment]
Compile errors
```
error C2065: 'S_IRWXU': undeclared identifier
```

**Comment by PaulWessel** [comment]
Hopefully getter again.

**Comment by joa-quim** [comment]
OK, it builds now. But I don't find any ``globe.bat`` or any other animation batch

**Comment by PaulWessel** [comment]
https://docs.generic-mapping-tools.org/dev/movie.html#examples

**Comment by joa-quim** [comment]
Batch finish correctly and sh is on its way and mine is dinner table

**Comment by PaulWessel** [comment]
Great.  Dinner sounds good - just had breakfast a few hours ago...

**Comment by PaulWessel** [comment]
Just a comment on your point about

`/* Needs to be "cmd /C" and not "start /B" to let it have time to finish */`

This is for the preflight script which must finish before we launch the frames.  That is why start would be a disaster (the first frame would start right away and try to use data created by the preflight but it has not finished yet...

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
