### PR TITLE
INitialize variables so the cpp checker is happy

### LINKED ISSUE #4205: cppcheck reports many uninitialized variables in gmt_map.c
```
src/gmt_map.c:2095:7: error: Uninitialized variable: x [uninitvar]
  if (x < xmin) xmin = x;
      ^
src/gmt_map.c:2096:7: error: Uninitialized variable: y [uninitvar]
  if (y < ymin) ymin = y;
      ^
src/gmt_map.c:2097:7: error: Uninitialized variable: x [uninitvar]
  if (x > xmax) xmax = x;
      ^
src/gmt_map.c:2098:7: error: Uninitialized variable: y [uninitvar]
  if (y > ymax) ymax = y;
      ^
src/gmt_map.c:2100:7: error: Uninitialized variable: x [uninitvar]
  if (x < xmin) xmin = x;
      ^
src/gmt_map.c:2100:11: error: Uninitialized variable: xmin [uninitvar]
  if (x < xmin) xmin = x;
          ^
src/gmt_map.c:2095:24: note: Assignment 'xmin=x', assigned value is <Uninit>
  if (x < xmin) xmin = x;
                       ^
src/gmt_map.c:2100:11: note: Uninitialized variable: xmin
  if (x < xmin) xmin = x;
          ^
src/gmt_map.c:2101:7: error: Uninitialized variable: y [uninitvar]
  if (y < ymin) ymin = y;
      ^
src/gmt_map.c:2101:11: error: Uninitialized variable: ymin [uninitvar]
  if (y < ymin) ymin = y;
          ^
src/gmt_map.c:2096:24: note: Assignment 'ymin=y', assigned value is <Uninit>
  if (y < ymin) ymin = y;
                       ^
src/gmt_map.c:2101:11: note: Uninitialized variable: ymin
  if (y < ymin) ymin = y;
```

### PR DESCRIPTION
**Pull request by PaulWessel**
Closes #4205.  Also avoid repetition of a random constant 500.

### CODE REVIEW

**Comment by seisman** [comment]
There are plenty of "errors" like this, for example in functions `gmtmap_init_albers` and `gmtmap_init_econic`. 

The full error messages can be found in https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=10505&view=logs&jobId=011e1ec8-6569-5e69-4f06-baf193d1351e&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=6fe8753d-6a09-5e1d-8a3c-02026d6aed54.

**Comment by PaulWessel** [comment]
Let me add a few more before approving.

**Comment by PaulWessel** [comment]
I got most of them but did not touch mergesort.c for instance.  Let's see what remains after this PR.

**Comment by seisman** [comment]
Only three left in gmt_map.c:
```
src/gmt_map.c:6873:10: error: Uninitialized variable: xx [uninitvar]
 return (xx * GMT->current.proj.scale[GMT_X] + GMT->current.proj.origin[GMT_X]);
         ^
src/gmt_map.c:6881:10: error: Uninitialized variable: yy [uninitvar]
 return (yy * GMT->current.proj.scale[GMT_Y] + GMT->current.proj.origin[GMT_Y]);
         ^
src/gmt_map.c:6889:10: error: Uninitialized variable: zz [uninitvar]
 return (zz * GMT->current.proj.scale[GMT_Z] + GMT->current.proj.origin[GMT_Z]);
         ^
```

**Comment by PaulWessel** [comment]
OK, did those three also.

**Review by seisman — APPROVED** [review]

**Pull request merged**
