### PR TITLE
Apprently new VS headers (or other Win .h) drop "#define NAN".

### PR DESCRIPTION
**Pull request by joa-quim**
This PR defines it when it«s not found (Windows only)

### CODE REVIEW

**Comment by seisman** [comment]
NAN is handled in https://github.com/GenericMappingTools/gmt/blob/fa3eda07161f236a039eb68f5791edcb06850316/src/gmt_notposix.h#L335

Perhaps `_Nan._Double` is not a constant?

**Comment by joa-quim** [comment]
I don't know where `_Nan._Double` is coming from, but since my previous fix seems to solve it (the Win CI built fine), I now moved that NAN definition to `gmt_notposix.h`

**Comment by seisman** [comment]
`_Nan` was originally defined in `ymath.h` but was moved to another file in https://github.com/microsoft/STL/pull/2828.

**Review by seisman — APPROVED** [review]

**Comment by joa-quim** [comment]
Deeper than `ymath.h`. There I looked, but it includes others, that include others ...

**Pull request merged**
