### PR TITLE
gmt.conf.rst: fix letter

### PR DESCRIPTION
**Pull request by anbj**
gmt.conf.rst: fix letter

### CODE REVIEW

**Comment by PaulWessel** [comment]
Hi @anbj , since this needs to go into 6.1 and if I change the base on this commit it also want to change other things I have made the fix in 6.1 and will merge it to master.  You can delete this branch.

**Comment by seisman** [comment]
I can help change the base branch to 6.1 and cherry-pick the one commit that should be merged.

**Comment by PaulWessel** [comment]
Sorry, I already went ahead and did my own fix.  SHould have waited for you..

**Comment by seisman** [comment]
OK. Close the PR.

**Comment by seisman** [comment]
Due to the design of our branching model (master and 6.1), I can see that other new contributors are also likely choose the wrong base branch, since master is always the default one.

**Comment by joa-quim** [comment]
Others and me. It was happening all the time when we had a 6.0 branch

**Comment by seisman** [comment]
We may make less mistakes if we develop GMT 6.1.x in the master branch and add new features to **6.2** branch.

**Comment by PaulWessel** [comment]
We could probably determine the statistics on this, but from gut feeling the vast majority of commits are in response to fixing a problem.  So currently, that means every time we have to remember to switch the branch to 6.1.  Since I have 6.1 checked out when I make a PR, it is always surprising that GitHub opens up a PR to be merged with master instead of the branch I am in.  So while we will screw up from time to time with any of these schemes, perhaps less screwups if we made a 6.2 for new things and continued our habit of doing most stuff to master.  That matches the pattern we create a new branch to test new features anyway.

**Comment by seisman** [comment]
> Since I have 6.1 checked out when I make a PR, it is always surprising that GitHub opens up a PR to be merged with master instead of the branch I am in. 

It's possible to set the default branch to "6.1", but we have to remember to update the default branch when we release GMT 6.2.0 and create the 6.2 branch.

image

**Comment by anbj** [comment]
Thanks for sorting my mess. So i did a PR against ``master``, and it should have been against the ``6.1``-branch?

**Comment by seisman** [comment]
> Thanks for sorting my mess out. So I did a PR against `master`, and it should have been against the `6.1`-branch?

Currently yes. The 6.1 branch is for maintaining GMT 6.1.x. PRs that fixes bugs, typos and improves documentations should be merged into 6.1 branch, while all new features should be merged into master branch (for maintaining the next minor release, e.g., 6.2.x).

As discussed above, it seems unfriendly to new contributors and even the core developers, since most commits are for fixing bugs. We may change our branch model in the future.

**Comment by seisman** [comment]
I opened a new issue to discuss our branching model in https://github.com/GenericMappingTools/gmt/issues/3612. Please have more discussions there.

**Comment by anbj** [comment]
Thanks @seisman

**Pull request closed without merging**
