### PR TITLE
Sort modern module names

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel I've finished steps 1, 2, 3 in #1276, but never test it. Feel free to push more commits to this branch.

**Comment by seisman** [comment]
A quick question: does the API care about the `THIS_MODULE_NAME` macros?

**Comment by PaulWessel** [comment]
No, don't think so.  Those defines were added to enable the creation of the info needed for gmt --help etc, but also is passed into gmt_init_module.  I know inside that function we may be calling a modern function to get the modern name and now we could just pass THIS_MODULE_MODERN_NAME as another argument.  Will see if that is useful after dealing with upgrading the structure that holds all this info.

**Comment by PaulWessel** [comment]
I think it is working.  However, one issue is worth discussing, including with @joa-quim.  As it is, the listing looks like this:

> ...
> nearneighbor     Grid table data using a "Nearest neighbor" algorithm
> plot3d           Plot lines, polygons, and symbols in 3-D
> plot             Plot lines, polygons, and symbols on maps
> project          Project data onto lines or great circles, generate tracks, or translate coordinates
> ...

i.e., plot3d is listed before plot (because of how I need to sort to also sort within groups - basically I am sorting strings like 

coreplot|plot   psxy
coreplot3d|plot3d       psxyz

Hence plot3d comes first.

Two suggestions came up in my mind:

1. The plot description should add "in 2-D"
2. Maybe plot should be called plot2d (more radical) or maybe plot2d should be a valid alias
3. Just manually (or via the script) shuffle the order of plot and plot3d

Thoughts?

**Comment by PaulWessel** [comment]
BTW, I fixed things so plot is listed before plot3. Other questions above still remains.

**Comment by seisman** [comment]
> 1. The plot description should add "in 2-D"

Agree.

> 2. Maybe plot should be called plot2d (more radical) or maybe plot2d should be a valid alias

I don't like plot2d. plot is simpler and is also commonly used in other software for 2D plots (e.g. Matlab use plot and plot3). An alias seems fine, but I don't see many benefits.

**Comment by seisman** [comment]
BTW, the output of `gmt --show-modules` is incorrect.

**Comment by PaulWessel** [comment]
Notice this now:

plot             Plot lines, polygons, and symbols on maps in 2-D
plot3d           Plot lines, polygons, and symbols in 3-D

I dont think we need to say "on maps" since a Cartesian x-y plot is not a map anyway.  I will remove "on maps".

**Comment by PaulWessel** [comment]
Lots of "on maps, @joa-quim and @seisman:

```
gmt --help  2>&1 | grep "on maps"
coast            Plot continents, countries, shorelines, rivers, and borders on maps
colorbar         Plot a gray-scale or color-scale on maps
gmtlogo          Plot the GMT logo on maps
grdimage         Project grids or images and plot them on maps
image            Place images or EPS files on maps
legend           Plot legends on maps
plot             Plot lines, polygons, and symbols on maps in 2-D
text             Plot or typeset text on maps
velo             Plot velocity vectors, crosses, and wedges on maps
meca             Plot focal mechanisms on maps
polar            Plot polarities on the inferior focal half-sphere on maps
sac              Plot seismograms in SAC format on maps
```

OK to remove the "on maps" from these? Also, please run gmt --help and let me know if you see room for improvements elsewhere - especially if things a a bit long.

**Comment by joa-quim** [comment]
Yes, ``plot2d`` is clearly a no go.

**Comment by joa-quim** [comment]
And yes, remove the``on maps``

**Comment by joa-quim** [comment]
```
grdfft           Mathematical operations on grids in the wavenumber (or frequency) domain
```
Replace ``the wavenumber (or frequency)`` by ``spectral``

```
project          Project data onto lines or great circles, generate tracks, or translate coordinates
```
remove ``, or translate coordinates``, it's a bit confusing.

```
gpsgridder       Interpolate GPS velocity vectors using Green's functions for a thin elastic sheet
```
remove ``vectors``

**Comment by PaulWessel** [comment]
OK, modern name again used.  Merging this guy in.

**Comment by PaulWessel** [comment]
So @seisman, this function is declared to prevent some modules from being listed in gmt --help.  But that was when we had an initial list of begin, end, figure, etc.  Now they are all among the modules.  Remove the begin, end etc from this test?

```
GMT_LOCAL int skip_this_module (const char *name) {
	if (!strncmp (name, "end", 3U)) return 1;	/* Skip the end module */
	if (!strncmp (name, "docs", 4U)) return 1;	/* Skip the docs module */
	if (!strncmp (name, "begin", 5U)) return 1;	/* Skip the begin module */
	if (!strncmp (name, "clear", 5U)) return 1;	/* Skip the clear module */
	if (!strncmp (name, "figure", 6U)) return 1;	/* Skip the figure module */
	if (!strncmp (name, "gmtread", 7U)) return 1;	/* Skip the gmtread module */
	if (!strncmp (name, "gmtwrite", 8U)) return 1;	/* Skip the gmtwrite module */
	return 0;	/* Display this one */
}

```

**Comment by seisman** [comment]
> Now they are all among the modules. Remove the begin, end etc from this test?

Agree.

**Comment by PaulWessel** [comment]
While the rest of us live in 2019, Apple's default Terminal window size is from 1977 and is 80x24.  This is what the gmt splash screen looks like (I made it long so we can see all but width is 80):

splash

There is much unfortunate wrapping here.  While we can manually format the Note 1 and 2 messages, the rest comes from gmt.c.  There are ways to set the terminal window size via [osascript](https://alvinalexander.com/source-code/mac-os-x/how-size-or-resize-application-windows-applescript) which is how we open the window in the first place.  If I open that window and type

`osascript -e 'tell application "Terminal" to get size of front window'
`
it returns

1050, 722

I suspect this is Retina or screen dependent so not possible to set number of lines.  What do you get on your computers, @seisman.

**Comment by seisman** [comment]
570, 365

**Comment by PaulWessel** [comment]
Not sure how to set a size in pixel which depends on screen size and dpi...

**Comment by PaulWessel** [comment]
Perhaps take the returned number, scale by 120/80 and set it to that?

**Comment by PaulWessel** [comment]
Actually getting it to be about 100 will work after reformatting one of the notes.

**Comment by seisman** [comment]
A few suggestions:

`grdblend         Blend several partially over-lapping grids into one larger grid`
-> 
`grdblend         Blend several partially overlapping grids into one larger grid`

---
`gshhg            Extract data tables from binary GSHHS or WDBII data files`
->
`gshhg            Extract data tables from binary GSHHG or WDBII data files`

---

```
segy             Plot a SEGY file on a map
segy2grd         Converting SEGY data to a GMT grid
segyz            Plot a SEGY file on a map in 3-D
```
->
```
segy             Plot a SEGY file in 2-D
segy2grd         Converting SEGY data to grid
segyz            Plot a SEGY file in 3-D
```

**Comment by PaulWessel** [comment]
Running this

 ```
 dim=(`osascript -e 'tell application "Terminal" to get size of front window' | tr ',' ' '`)
  w=`echo "${dim[0]} 1.25" | awk '{print int($1*$2)}'`
  osascript -e "tell application "Terminal" to set size of front window to {$w, ${dim[1]}}"
```
However, the last osascript needs to be in single quotes to but then my variables are not defined.  WHat do I do? Sorry, need to go to a meeting.

**Comment by seisman** [comment]
@PaulWessel I've pushed more commits to this branch. Please remember to run `git pull` before making more changes.

**Comment by PaulWessel** [comment]
Yep, done

**Comment by PaulWessel** [comment]
Setting the terminal width works now

**Pull request merged**
