### PR TITLE
Address issue in gspline_4.sh

### LINKED ISSUE #4489: Some new failing tests
**Linux:**
```
1/3 Test #423: test/grdgdal/gdal_nn.sh ..........***Failed    0.51 sec
Set GMT_SESSION_NAME = 22582
malloc(): memory corruption
gmtest: line 57: 22635 Aborted                 (core dumped) "$@"
ERROR: gmtest:61
memtrack errors: 0
exit status: 1

2/3 Test #517: test/greenspline/gspline_4.sh ....***Failed    0.72 sec
Set GMT_SESSION_NAME = 22586
grdcontour [WARNING]: No contours within specified -L range
gawk: fatal: cannot open file `dump' for reading (No such file or directory)
ERROR: gspline_4.sh:27
memtrack errors: 0
exit status: 1
```

**macOS**
```
1/3 Test #229: test/api/apicubeplot.sh ...........***Failed    0.32 sec
Set GMT_SESSION_NAME = 48711
gmtest: line 57: 48762 Abort trap: 6           "$@"
ERROR: gmtest:57
memtrack errors: 0
exit status: 1

2/3 Test #454: test/grdinterpolate/onelayer.sh ...***Failed    0.39 sec
Set GMT_SESSION_NAME = 48713
grdinterpolate [ERROR]: Grid x increment <= 0.0
grdinterpolate [ERROR]: Grid y increment <= 0.0
grdinterpolate (gmtapi_init_grdheader): Please select compatible -R and -I values
grdcontour [WARNING]: Grid has wrong registration type. Switching from gridline to pixel registration
Assertion failed: ((wesn[XLO]+GMT_CONV4_LIMIT*header->inc[GMT_X]) >= header->wesn[XLO] && (wesn[XHI]-GMT_CONV4_LIMIT*header->inc[GMT_X]) <= header->wesn[XHI]), function gmtnc_grd_prep_io, file ../src/gmt_nc.c, line 1373.
gmtest: line 57: 48763 Abort trap: 6           "$@"
ERROR: gmtest:57
memtrack errors: 0
exit status: 1
```

**Windows**:
```

4/9 Test #517: test/greenspline/gspline_4.sh .....***Failed    7.89 sec
Set GMT_SESSION_NAME = 42283
grdcontour [WARNING]: No contours within specified -L range
gawk: fatal: cannot open file `dump' for reading (No such file or directory)
ERROR: gspline_4.sh:27
memtrack errors: 0
exit status: 1
```

### PR DESCRIPTION
**Pull request by PaulWessel**
Because we work on a single dump file we must check for its existance.  Hopefully closes #4489.  Need to see if it passes the test on Linux and Windows in the CI before approval.

### CODE REVIEW

**Comment by seisman** [comment]
The gawk error is gone, but the PS images are different. Please see the attached results:
[gspline_4.zip](https://github.com/GenericMappingTools/gmt/files/5640206/gspline_4.zip)

**Comment by PaulWessel** [comment]
Ok, so no grdcontour command gives any output.  Need to think of adding some extra DEBUG outputs.

**Comment by seisman** [comment]
Latest logs attached: [log.txt](https://github.com/GenericMappingTools/gmt/files/5644615/log.txt)

**Comment by PaulWessel** [comment]
So all slices have the same range of 

`3D_09.00.grd: z_min: 5.96488809586 at x = 32 y = 0 z_max: 6.74661970139 at x = 24 y = 3.25`

despite the layer address changing correctly.  This would seem to point to greenspline as not advancing the layer number...

**Comment by PaulWessel** [comment]
Could @seisman add this command to the gspline_4.sh script and send me the all.txt file from the CI Linux:

`gmt greenspline -R$R3D -I$dz @Table_5_23.txt -S${method}${tens} -D5 > all.txt`

**Comment by seisman** [comment]
Please see the attached file: [all.txt](https://github.com/GenericMappingTools/gmt/files/5644839/all.txt)

**Comment by PaulWessel** [comment]
```
gmt info all.txt 
all.txt: N = 42525	<12/32>	<0/6>	<5/10>	<5.96488809586/6.74661970139>
```

While on my mac, I get

```
gmt greenspline -R12/32/0/6/5/10 -I0.25 @Table_5_23.txt -Sr0.85 -D5 > t.txt
gmt info t.txt
t.txt: N = 42525	<12/32>	<0/6>	<5/10>	<1.02685022354/23.2000007629>
```

So x,y,z coordinates look OK but the solution w(x,y,z) is wrong on the CI for both ascii output and grid output.  So whatever this is, it is happening in **greenspline** and not in the _gspline_4.sh script_.  Any ideas will be appreciated, but of course I did do a mini-rewrite of that section when the struct **GMT_CUBE** was introduced.  Perhaps a diff before/after can yield clues.

**Comment by PaulWessel** [comment]
If I add the undocumented -M option to save the Green function coefficients I get this list:

```
# N: 36 S: G-J G: r0.85
# Command : greenspline -R12/32/0/6/5/10 -I0.25 /Users/pwessel/.gmt/cache/Table_5_23.txt -Sr0.85 -D5 -M3dalpha.txt
-0.61017033771
1.46694880711
-0.882580736034
-1.07576346305
0.812389563836
-0.00670698055475
0.851333964995
-0.74554332014
-0.622710347233
1.58585020823
0.40275011302
-0.615654790714
-0.913279107993
-0.554430360451
2.05296227761
0.0312173438119
-0.819854797873
-0.765027933522
2.15063683618
0.524535657852
-1.06468311716
-0.31384326133
-0.486646460576
1.50986124744
0.134466865421
-0.334620840187
-0.89319285195
-0.298025496862
1.77683196508
0.16947840268
-0.779248973539
-0.15558024929
-0.454877569007
0.436457652197
-0.690506668035
-0.711345952461
```

Could @seisman please add that option to the CI script and post what coefficients are returned? If they are different/wrong then that is one clue, if they are the same then there is something odd with the evaluation of the spline, especially the z-level since all z-levels give teh same wrong grid.

**Comment by seisman** [comment]
```
# N: 36 S: G-J G: r0.85
# Command : greenspline -R12/32/0/6/5/10 -I0.25 /home/runner/.gmt/cache/Table_5_23.txt -Sr0.85 -D5 -M3dalpha.txt
-0.61017033771
1.46694880711
-0.882580736034
-1.07576346305
0.812389563836
-0.00670698055475
0.851333964995
-0.74554332014
-0.622710347233
1.58585020823
0.40275011302
-0.615654790714
-0.913279107993
-0.554430360451
2.05296227761
0.0312173438119
-0.819854797873
-0.765027933522
2.15063683618
0.524535657852
-1.06468311716
-0.31384326133
-0.486646460576
1.50986124744
0.134466865421
-0.334620840187
-0.89319285195
-0.298025496862
1.77683196508
0.16947840268
-0.779248973539
-0.15558024929
-0.454877569007
0.436457652197
-0.690506668035
-0.711345952461
```

**Comment by PaulWessel** [comment]
Nice, so then something with the evolution of the solution for different z-levels.

**Review by seisman — APPROVED** [review]
I believe we also need the changes in this PR.

**Pull request merged**
