### PR TITLE
Let grdimage deal also with indexed images sent in by externals.

### LINKED ISSUE #4657: grdimage lost ability to deal with indexed images from externals
That happened in the ``grdimage`` rewrite where, from memory (mine), indexed images are previously expanded to RGB after reading. But now from externals (where the Image object lands), grdimage now does this and doesn't look anymore to the colormap contents. I used to be able to set transparency via colormap but that is lost too.

```
gray_only = (I->header->n_bands == 1);	/* Got a grayscale image */
```

### PR DESCRIPTION
**Pull request by joa-quim**
Rename gmtapi_expand_index_image() to gmtlib_expand_index_image() and export it
Fixes #4657

### CODE REVIEW

**Review by PaulWessel — COMMENTED** [review]
Before I approve this: Should not all of this happen in gmtapi_import_image? Seems like we should always expect indexed images to rgb since we have no operator that just works directoy in the index. Instead of doing it in grdimage.  What about other modules that read images, won't you have to duplicate that step there too? Seems like it needs to be centralized.

**Comment by joa-quim** [comment]
I don't remember if any other module would need this. The problem is that the code flow followed by
```
julia> imshow(It, Vd=1)
        grdimage  -R0/350/0/258 -JX12c/0 -Baf -BWSen -D -P -K > C:\TMP\GMTjl_tmp.ps
```
does not pass in ``gmtapi_import_image``

**Comment by PaulWessel** [comment]
Well, **grdmix** might, for instance; not sure about **grdview**.
Help me understand why in your example, grdimage is getting an image without visiting _GMT_Read_Image_ and hence _gmtapi_import_image_?

**Comment by joa-quim** [comment]
In ``GMT_Read_Data`` it slips through 
```
return (gmtapi_pass_object (API, S_obj, family, mode, wesn));
```
and then directly gets the image with ``gmtapi_get_image_data``

**Comment by PaulWessel** [comment]
So that is where we need to intervene then, I think.  Otherwise we are stuck repeating the same code in other places.

**Comment by joa-quim** [comment]
But we only want to convert to RGB if image is going to be sent to pslib. If I want to save it with gdalwrite for example I don't want it to be converted.

**Comment by joa-quim** [comment]
We can turn this into a function, so the amount of possible repetitions would be negligible.
```
		if (I->header->n_bands == 1 && I->n_indexed_colors > 0) {	/* Indexed image, must convert to RGB */
			struct GMT_IMAGE *Irgb = NULL;
			gmtlib_expand_index_image (GMT, I, &Irgb);	/* true if we have a read-only indexed image and we had to allocate a new one */
			if (GMT_Destroy_Data (API, &I) != GMT_NOERROR)
				Return (API->error);
			I = Irgb;
		}
```

**Comment by PaulWessel** [comment]
OK, that is not too bac.  Please make it a function so that it is good to go elsewhere as needed.  Please add some comments so we remember why it was added and what it does.

**Comment by joa-quim** [comment]
F. It was supposed to have been an easy thing to do.

**Review by PaulWessel — APPROVED** [review]
Seems to not have broken anything, so good!

**Comment by seisman** [comment]
No, it breaks if GDAL is not installed.

**Comment by PaulWessel** [comment]
Thanks for checking that - I used GDAL.  Add some ifdefs, @joa-quim ?

**Comment by joa-quim** [comment]
Yes, it was because of some IFDEFS I had removed. It is silly that we end up requiring GDAL to do this opts that have nothing to do with GDAL.

**Comment by seisman** [comment]
The CI test without GDAL now passes.

**Comment by joa-quim** [comment]
BTW,  ``set (GMT_EXCLUDE_GDAL TRUE)`` doesn't work. Raises error
```
/mnt/c/progs_cygw/GMTdev/gmt5/master/src/gmt_gdalread.h:26:10: fatal error: gdal.h: No such file or directory
```

**Comment by PaulWessel** [comment]
Why? We have

```
#ifdef HAVE_GDAL
#	include "gmt_gdalread.h"      /* GDAL support */
#endif
```

Oh, I think it is your gmt_ogrread.c file that complains.

**Comment by joa-quim** [comment]
Nope, even if I wrap it under a #ifdef HAVE_GDAL I still get the same error.

**Comment by PaulWessel** [comment]
Not reproducible here by turning GMT_EXCLUDE_GDAL true.  Maybe you have some other code in there that gets added and thus complains.  It cannot go into those ifdefs if HAVE_GDAL is not set.

**Comment by PaulWessel** [comment]
Not done yet:

../src/grdimage.c:1296:46: warning: incompatible pointer types passing 'struct GMT_IMAGE **' to parameter of type 'struct GMT_IMAGE *'; remove & [-Wincompatible-pointer-types]
                if (!Ctrl->A.active && gmtlib_ind2rgb(GMT, &I)) {
                                                           ^~
../src/grdimage.c:1106:72: note: passing argument to parameter 'I_in' here
EXTERN_MSC int gmtlib_ind2rgb (struct GMT_CTRL *GMT, struct GMT_IMAGE *I_in);
                                                                       ^

**Comment by joa-quim** [comment]
Shit forgot that change. 
Can't see warnings under the awful flood of GCC warnings nor on Win where all OMP variables show up as unused vars.

**Pull request merged**
