### PR TITLE
WIP Implement support for 3-D grids

### PR DESCRIPTION
**Pull request by PaulWessel**
Addresses steps listed in #2912 to make GMT ready to transparently handle 3-D data grids, such as needed in grdinterpolate or produced by greens line.  There are several step, and we will do one at the time and test to make sure no bad side-effects sneak in.

This initial commute simply extends the GMT_GRID_HEADER with the required parameters.

### CODE REVIEW

**Comment by joa-quim** [comment]
This going to break Julia

**Comment by PaulWessel** [comment]
How can we do things without breaking Julia/GMT?  We have to be able to improve GMT and not be told no can do, right, so how?

**Comment by joa-quim** [comment]
Can we have a different header for 3D?

**Comment by PaulWessel** [comment]
No, since GMT_GRID contains the GMT_GRID_HEADER.  I think this is a version management thing.  You will need to require 6.0 of users of your current Julia release, not master.  So release a Julia4gmt version that requires 6.0 and done with it.  Then, master is always a work in progress and may need to be rebuilt when GMT changes.  Most users are probably installing 6.0 anyway.

**Comment by joa-quim** [comment]
Don't know if this affects julia only or not. If yes, I can always add another ``if version`` but if it affects others than we should probably not put this in 6.1

**Comment by seisman** [comment]
Any schedule for the 6.1.0 release?

**Comment by PaulWessel** [comment]
The 3-D stuff branch can wait for after 6.1.  We should just pick a date since otherwise we keep on adding things and delaying.  How about April 15?

**Comment by joa-quim** [comment]
What else it open that we may want to put in 6.1. If minor things we can do it earlier than A15

**Comment by PaulWessel** [comment]
Not sure.  I think we have fixed a bunch of stuff and added new features worthy of a 6.1 release.
I will fix #2967 problems.  Does not look like the other issues are critical (?).

**Comment by seisman** [comment]
I opened #2968 for tracking the upcoming 6.1.0 release. No critical issues but I expect some final decisions about PR #2013 before the release.

**Pull request closed without merging**
