### PR TITLE
Ensure given distances in gmtvector are positive

### LINKED ISSUE #7769: gmt vector -Tt: negative distances read as positive unless entered via column
```
$ echo 0 0 45 -1111111 | gmt vector -Tt -jg
-7.1016558127   -7.04772447977
$ echo 0 0 | gmt vector -Tt45/-1111111 -jg
7.1016558127    7.04772447977
$ gmt --version
6.4.0
```
Probably related to https://docs.generic-mapping-tools.org/dev/changes.html
> We have a new GMT common option -j that clarifies how to select flat Earth, great circle, and geodesic calculations and thus eliminates awkward, sign-based increments.

### PR DESCRIPTION
**Pull request by PaulWessel**
No such thing as a negative distance.  Closes #7769.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Actually, perhaps it is more user friendly to simply stay that if distance is negative we make it positive and add 180 to the azimuth?

**Review by joa-quim — APPROVED** [review]

**Comment by PaulWessel** [comment]
I am pretty sure the separation of two points on the earth is a positive definite quantity.  But as you mention, one could pick a point as an origin and then one could have a positional coordinate with sign.  Anyway ,as you see above I allow negative distances.

**Comment by jidanni** [comment]
All I know is now I see in the code changes of today a new error message when a person gives a negative distance. Also there's new documentation requiring a positive distance. All I can conclude is negative distance are now "criminalized."

Consider a person who takes two steps forward, and one step back, but never turns around.

Consider an automobile. That drives 150 ft forward and then puts the gear into reverse and drives 50 ft backward.

That is much different than turning the car around 180° and going backward.

**Comment by PaulWessel** [comment]
Those who knows what they are doing will pull the very latest from master which was this morning, about 12 hours ago:

echo 0 0 | gmt vector -Tt45/-1
-0.707106781187	-0.707106781187
echo 0 0 | gmt vector -Tt45/1
0.707106781187	0.707106781187

My patience with you is wearing thin.

**Pull request merged**
