### PR TITLE
A new module: grdselect

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

The **grdselect** module fills a gap in GMT capabilities and simplifies a series of workflows that otherwise require considerable scripting.  The module operates on a series of grids (or data cubes) and then, depending on options, can

- Find a subset of the data sources that satisfies various conditions, such as data range, increment size, registration type, overlap with **-R**, z-range (for cubes only), and number of NaNs. We output the subset of those data sources that passed any of the imposed conditions.
- For the data sources that passed (or all if no conditions were imposed), determine either the _union_ or the _intersection_ of all the data sources regions.  We then report either a single data record with the min/max coordinates (including the data range within the determined region), a `-Rw/e/s/n[/b/t] `string, or the closed bounding box polygon for the region.

I have added two tests so far.  One computes the intersection and union (plus a pad of 2 degrees) of three geographic grids, of which one is off by 360 degrees relative to the others, and another that outputs the list of grids that passed a variety of tests.

Because we are close to 6.3 and this module may well need to add a few more features and/or revise what has been implemented after more discussion, it will remain WIP until after 6.3.  Suggestions for additional capability can be added to this PR.  Here is the image for the new test, showing in bold the determined regions:

region_u_i

See the man page for more details.

### CODE REVIEW

**Comment by anbj** [comment]
Looks very useful. I’m going to play with this as soon as I can. ‘Increment size’ = find grid resolution automatically (x/y inc)?

**Comment by weiji14** [comment]
Hi Paul, just my two cents on this.

> * Find a subset of the data sources that satisfies various conditions, such as data range, increment size, registration type, overlap with **-R**, z-range (for cubes only), and number of NaNs. We output the subset of those data sources that passed any of the imposed conditions.
>
> * For the data sources that passed (or all if no conditions were imposed), determine either the _union_ or the _intersection_ of all the data sources regions.  We then report either a single data record with the min/max coordinates (including the data range within the determined region), a `-Rw/e/s/n[/b/t] `string, or the closed bounding box polygon for the region.

This intersection and union feature reminds me of [`gmtspatial -S`](https://docs.generic-mapping-tools.org/6.2/gmtspatial.html#s). Wondering if this module could be split into a `grdspatial` and a `grdselect`? Specifically, have `grdselect` do the 1st task (subset based on conditions) and have `grdspatial` do the intersection/union and other spatial operations (symmetrical difference, buffer/pad, etc).

That said, maybe there's a good reason to keep it as a single C function, so maybe `grdspatial` could be another naming option?

**Comment by PaulWessel** [comment]
> Hi Paul, just my two cents on this.
> 
> > * Find a subset of the data sources that satisfies various conditions, such as data range, increment size, registration type, overlap with **-R**, z-range (for cubes only), and number of NaNs. We output the subset of those data sources that passed any of the imposed conditions.
> > * For the data sources that passed (or all if no conditions were imposed), determine either the _union_ or the _intersection_ of all the data sources regions.  We then report either a single data record with the min/max coordinates (including the data range within the determined region), a `-Rw/e/s/n[/b/t] `string, or the closed bounding box polygon for the region.
> 
> This intersection and union feature reminds me of [`gmtspatial -S`](https://docs.generic-mapping-tools.org/6.2/gmtspatial.html#s). Wondering if this module could be split into a `grdspatial` and a `grdselect`? Specifically, have `grdselect` do the 1st task (subset based on conditions) and have `grdspatial` do the intersection/union and other spatial operations (symmetrical difference, buffer/pad, etc).
> 
> That said, maybe there's a good reason to keep it as a single C function, so maybe `grdspatial` could be another naming option?

It is a reasonable suggestion.  I think for now we continue to collect ideas and dream up potential features and then we can see if one or two modules are needed and what the most suitable name might be.  I chose select since there are some similarities with what gmtselect does, but while union and intersection are mentioned in gmtspatial those features are actually not implemented!.  

I can see that a grdspatial could do things like return the union or intersection grid rather than a -Rstring, and probably other things too in situations where most GMT modules expects all input grids to have the same region, etc (like grdmath). I would like to have (new) modules only produce one data type and not several, since that adds complexity in the API...

**Comment by anbj** [comment]
Not tested yet, so excuse ignorance;

* Is it possible to print the grid filenames on 1) the map and/or 2) the legend?
* Possible to include other relevant/useful information in legend (thinking about resolution/xy-increment here)?

**Comment by PaulWessel** [comment]
> Not tested yet, so excuse ignorance;
> 
> * Is it possible to print the grid filenames on 1) the map and/or 2) the legend?

I am not sure what you mean here. If **grdspatial** found 10 grids would you want 10 lines of something in a legend? And what would the symbol for any of those grids be?

> * Possible to include other relevant/useful information in legend (thinking about resolution/xy-increment here)?

Seems that is something you do via **grdinfo** and building a legend file directly?

> * grid extent may fool you; possible to trace area of _actual data_ (i.e. exclude NaN's)?

That seems relevant to **grdspatial**.  Perhaps an option could case **grdcut -Z+N** to eliminate rows/cols of NaNs first.

**Comment by anbj** [comment]
> > Not tested yet, so excuse ignorance;
> > 
> > * Is it possible to print the grid filenames on 1) the map and/or 2) the legend?
> 
> I am not sure what you mean here. If **grdspatial** found 10 grids would you want 10 lines of something in a legend? And what would the symbol for any of those grids be?

In your graphical example, there is a colored rectangle with the found of the grid `-R` to the right of it (so that would be the symbol).
I was thinking about a 3rd column with the name of the grid? E.g. in legend:

```
[blue rectangle]    212/242/0/30               my-interesting-grid.nc
[red rectangle]      -135/-105/10/40          partly-overlapping-project.tif
[green ractangle]  127W/121W/5S/45N   data-available.nc
```

In addition, a nice way to label the different grids in the map. If you have, what, > 5 grids, it may become difficult to distinguish the different grids based on the color codes.

> 
> > * Possible to include other relevant/useful information in legend (thinking about resolution/xy-increment here)?
> 
> Seems that is something you do via **grdinfo** and building a legend file directly?
Yes basically, but I thought this module was meant to make things easier? (i.e. reduice need to script)
> 
> > * grid extent may fool you; possible to trace area of _actual data_ (i.e. exclude NaN's)?
> 
> That seems relevant to **grdspatial**. Perhaps an option could case **grdcut -Z+N** to eliminate rows/cols of NaNs first.
Absolutely. Still, eliiminating rows/cols of NaNs would not indicate areas of NaNs in a non-rectangular grid? That was my thought.

**Comment by anbj** [comment]
This module would be well suited to investigate what kind of grids you have, right? "Show me what I have".
Should it be possible to mix geodetic and projected grids? How would you then assign a projection to the projected grids?
And input; only via command line, or also possible to input a textfile with grid listing?

**Comment by anbj** [comment]
Does this module do any plotting, or does it only output stuff that is supposed to be piped to modules that _do_ plot? Could you please post the commands used to generate the included figure in your first post?

**Comment by anbj** [comment]
```
$ gmt grdinfo no1.nc no2.nc 
no1.nc: Title: Produced by grdcut
no1.nc: Command: grdcut -RNO @earth_relief_30m_p -Gno1.nc
no1.nc: Remark: Obtained by Gaussian Cartesian filtering (55.6 km fullwidth) from SRTM15+V2.1.nc [Tozer et al., 2019; http://dx.doi.org/10.1029/2019EA000658]
no1.nc: Pixel node registration used [Geographic grid]
no1.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
no1.nc: x_min: -9.5 x_max: 34 x_inc: 0.5 (30 min) name: longitude n_columns: 87
no1.nc: y_min: 57.5 y_max: 81.5 y_inc: 0.5 (30 min) name: latitude n_rows: 48
no1.nc: v_min: -4271 v_max: 1409.5 name: elevation (m)
no1.nc: scale_factor: 1 add_offset: 0
no1.nc: format: classic

no2.nc: Title: Produced by grdcut
no2.nc: Command: grdcut -RNO @earth_relief_20m_p -Gno2.nc
no2.nc: Remark: Obtained by Gaussian Cartesian filtering (37.1 km fullwidth) from SRTM15+V2.1.nc [Tozer et al., 2019; http://dx.doi.org/10.1029/2019EA000658]
no2.nc: Pixel node registration used [Geographic grid]
no2.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
no2.nc: x_min: -9.33333333333 x_max: 33.6666666667 x_inc: 0.333333333333 (20 min) name: longitude n_columns: 129
no2.nc: y_min: 57.6666666667 y_max: 81.3333333333 y_inc: 0.333333333333 (20 min) name: latitude n_rows: 71
no2.nc: v_min: -5223 v_max: 1605 name: elevation (m)
no2.nc: scale_factor: 1 add_offset: 0
no2.nc: format: classic
```
Problems due to different resolution?:

```
$ gmt grdselect no1.nc no2.nc -Ai -C
grdselect [WARNING]: (w - x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdselect [WARNING]: w reset from -9.33333333333 to -10
grdselect [WARNING]: (e - x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdselect [WARNING]: e reset from 33.6666666667 to 34
grdselect [WARNING]: (s - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdselect [WARNING]: s reset from 57.6666666667 to 57
grdselect [WARNING]: (n - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdselect [WARNING]: n reset from 81.3333333333 to 82
grdselect (gmt_nc_read_grd): Tried to read beyond grid domain [no1.nc]
grdselect (gmtapi_import_grid): (null) [no1.nc]
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
```

**Comment by PaulWessel** [comment]
Yes, and you probably want to report the common region in multiples of the largest grid spacing.  See the -A modifier for this.

**Comment by PaulWessel** [comment]
> Does this module do any plotting, or does it only output stuff that is supposed to be piped to modules that _do_ plot? Could you please post the commands used to generate the included figure in your first post?

The modules does no plotting.  It only returns information in one of two types:

1. List of grid file names
2. A common region, either as data record, string record, or bounding box polygon

The scripts can be found in test/grdselect

**Comment by PaulWessel** [comment]
> [Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
> [Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
> 

When used with grids that have different increments and -C is selected then -A+i is now required to set a compatible rounding increment. This should hopefully prevent such crashes from being possible.

**Comment by gd-a** [comment]
> See the man page for more details.

I don't see the module in doc (dev).

**Comment by PaulWessel** [comment]
You must build it from the branch

**Comment by gd-a** [comment]
> You must build it from the branch

So it's not included using brew (Version 6.3.0_3c0d215_2021.11.10) ?

I'll wait and see !
Thanks Paul

**Comment by PaulWessel** [comment]
I have added three more options to **grdselect**:

1. **-C**_datafile_: Pass data sources that contain one or more of the points in _datafile_
2. **-L**_datafile_: Pass data sources that are traversed by one or more of the lines in _datafile_
3. **-F**_datafile_: Pass data sources that are overlapped fully or partially by one or more of the polygons in _datafile_

The **-F** option also has modifiers **+i** and **+o** for only considering polygons that are fully inside or fully outside the polygon.

Moreover, all options to **grdselect** may individually be inverted via **-I**.  Here is the result of a new test (_plot_CFL.sh_)  exploring these options:

plot_CLF

I think grdselect is shaping up well now and has many counterparts with **gmtselect** (hence the selection of **-C -L -F** options).  I think we should consider adding it to 6.3 to get more feedback on it.

```
gmt grdselect [core] 6.3.0 [64-bit] - Determine common regions from 2-D grids or 3-D cubes

usage: gmt grdselect grid1 grid2 ... [-Ai|u[+il|h|<inc>]] [-C<pointtable>] [-D<inc>] [-E[b]] [-F<polygontable>[+i|o]] [-G] [-ICDFLNRWZr] [-L<linetable>]
  [-M<margins>] [-Nl|h[<n>]] [-Q] [-R<west>/<east>/<south>/<north>[+r]] [-W[<min>]/[<max>]] [-Z[<min>]/[<max>]] [-V[q|e|w|t|i|c|d]] [-f[i|o]<colinfo>]
  [-ho[<nrecs>][+c][+d][+m<segheader>][+r<remark>][+t<title>]] [-o<cols>[,...][,t[<word>]]] [--PAR=<value>]
```

**Comment by meghanrjones** [comment]
When would you want 6.3 to be released to have this included?

**Comment by PaulWessel** [comment]
Since it is a new module and I have tested it quite a bit (including the new tests) I think it is ready to go right now.  Regardless of that module, might be a stretch to get 6.3 out tomorrow? I can start checking boxes.

**Comment by meghanrjones** [comment]
> Since it is a new module and I have tested it quite a bit (including the new tests) I think it is ready to go right now. Regardless of that module, might be a stretch to get 6.3 out tomorrow? I can start checking boxes.


> Since it is a new module and I have tested it quite a bit (including the new tests) I think it is ready to go right now. Regardless of that module, might be a stretch to get 6.3 out tomorrow? I can start checking boxes.

I will prioritize testing this out, but agree with tomorrow being a stretch in general.

**Review by meghanrjones — COMMENTED** [review]
A couple questions about the future of the module:

1. Can this be extended to support images in addition to grids?
2. Can **-W** be extended to support units?

I agree with @anbj's point that selecting regions based on non-NaN values is important and share the interest in whether this could work with a mix of projected and geographic grids.

**Comment by PaulWessel** [comment]
> A couple questions about the future of the module:
> 
> 1. Can this be extended to support images in addition to grids?
> 2. Can **-W** be extended to support units?
> 
> I agree with @anbj's point that selecting regions based on non-NaN values is important and share the interest in whether this could work with a mix of projected and geographic grids.

Thanks for the comments and corrections. My feeling is that given all the things **grdselect** now can do perhaps we should gather some feedback and let it harden a bit before tackling further extensions.  Some specific comments on those suggestions:

1. Also check images: Most of the checks only utilize the grid header which is the same as the image header so apart from reading those properly I think that should be relatively seamless.  It would exclude **-W** probably.
2. Support units in **-W**.  GMT does support a bunch of units in various options but they tend to be limited to geographic or plot distance units.  The **-W** option deals with the data units in grids.  That could be anything, from mGal to meter to whatever.  I am not sure what you had in mind here?
3. Grids with NaNs: Given that we are mostly considering rectangular regions the best we could do would be to shrink a grids boundaries inwards until any NaNs along the margins are gone.  It would be trickier if one would be interested in letting options like **-C -F -L** consider if the overlap involves a part of the grid that has non-NaN values etc.  I think that would require a bit more thinking as to what is useful and practical, i.e., coding effort versus needs.
4. Projected vs geographic grids: Nowhere in GMT do we mix different grid types, so if we were to start doing that (e.g., considering the proj4 strings in projected grids) then that is a issue that would affect lots of GMT modules, probably starting with the plotting modules.  So whatever this would mean for grdselect is not clear to me.

Hence I do not feel taking on any of these suggestions are critical for 6.3.  I see the image option as the most likely one to happen.  I think for multi-band data images (i.e., some geotiffs with data layers) they are read as grids anyway and I could just turn off -W for those by checking `header->n_bands > 1`.

**Comment by meghanrjones** [comment]
> 
>     2. Support units in **-W**.  GMT does support a bunch of units in various options but they tend to be limited to geographic or plot distance units.  The **-W** option deals with the data units in grids.  That could be anything, from mGal to meter to whatever.  I am not sure what you had in mind here?
> 

Ugh, sorry typed the wrong letter. I meant **-M**.

**Comment by PaulWessel** [comment]
AH, -M.  OK, well it currently supports arc units, so -M30m and -M15s/30s works.  There is no support to accept distances in km, for instance, if that is what you where thinking?

BTW, I made minor changes to allow for images.  Basically exclude -W -N for images.

**Comment by meghanrjones** [comment]
> AH, -M. OK, well it currently supports arc units, so -M30m and -M15s/30s works. There is no support to accept distances in km, for instance, if that is what you where thinking?
> 

It's not so much that I really want to be able to specify (e.g.) 10 km margins, but that I would prefer the description for -M specify what types of units are supported and what the default units are for *margins* if not given. Thanks for adding some details.

> BTW, I made minor changes to allow for images. Basically exclude -W -N for images.

Great, thanks! Regarding images, the specific use case that I considered was selecting all images that have <X% of the pixels matching some criteria based on the data values (commonly used to select images with minimal cloud cover based on a bitmask band). I agree that it's better to get the base functionality merged rather than focus on additional features, so I am not requesting that this be included in this PR. But, do you think these types of selections based on values in images would be reasonable feature requests in the future?

**Comment by PaulWessel** [comment]
Thanks, just updated -M description do say d, m, and s units are available for geographic grids.

**Comment by PaulWessel** [comment]
Let me know if you think this one is OK to go.  I added that it is _experimental_ at the top of the RST docs.

**Comment by meghanrjones** [comment]
> Let me know if you think this one is OK to go. I added that it is _experimental_ at the top of the RST docs.

Yes, I think so. I haven't tried out the latest image addition but tested the other features this morning and it seems like a nice addition. My one comment for now is that the module description "Determine common regions from 2-D grids, images or 3-D cubes" doesn't capture the latest features that you've added.

**Review by meghanrjones — APPROVED** [review]
There's some comments from my review this morning still at https://github.com/GenericMappingTools/gmt/pull/5929/files. OK to merge without them if you do not agree we the changes.

**Comment by PaulWessel** [comment]
True.  Maybe

Make selections or determine common regions from 2-D grids, images or 3-D

**Comment by meghanrjones** [comment]
> True. Maybe
> 
> Make selections or determine common regions from 2-D grids, images or 3-D

Sounds good.

**Comment by PaulWessel** [comment]
Strange, I went through a bunch of this hours ago and merged in but not in the repo...they were all suggestions and I accepted them.  Now they are listed as differences - I guess I need to make the edits.

**Pull request merged**
