### PR TITLE
earthtide bug fixes and improvement

### PR DESCRIPTION
**Pull request by mrajner**
**Description of proposed changes**

This series of commit deal with:
- inconsistent documentation vs program
- not working of T.inc+n
- confusing output when T.int is less then 0.5s
- confusing output with y T.unit

Please see extended commit message for more details.

My implementation of bug fixes may be not optimal, so devs could adapt it a little, but I hope that changes are clear enough to see the current problems.

### CODE REVIEW

**Comment by joa-quim** [comment]
Well, still waiting for revision of the void-returning-value issue.

**Comment by PaulWessel** [comment]
Where is this described? I don't see anything but I am known to suffer from blindness.

**Comment by joa-quim** [comment]
Shit. Week finger. It looks like I had not pushed hard enough the "submit review" button.

**Comment by joa-quim** [comment]
Any news on this?

**Comment by PaulWessel** [comment]
@joa-quim, can we use some of the commits? It seems like there are merit in several of the things he pointed out, but that was in February.  We should push this to some logical end point.  Suggestions?

**Comment by joa-quim** [comment]
I think we need to recreate our own version of that PR so we can make the asked modifications.

**Comment by PaulWessel** [comment]
OK, since this is your baby perhaps you should do that, no?

**Comment by joa-quim** [comment]
Yes ... one of these days. Have to do a couple o Mirone things and realizing that I'm getting rusty on it.

**Comment by PaulWessel** [comment]
Yikes, that probably means it is time for me to look at the GSHHG stuff again and relearn how it works...

**Comment by joa-quim** [comment]
Implemented in #811

**Pull request closed without merging**
