### PR TITLE
Pause 1 sec before viewing master frame

### PR DESCRIPTION
**Pull request by PaulWessel**
We do something similar before assembling frmes to video since we cannot be 100% that the image(s) have been finished written and ready to be used.  Before this PR we would sometimes (but not aways) get messages like

`mv: rename 1.png to /Users/pwessel/1.png: No such file or directory`

This waits a second before trying to access the master frame.

Let me know if this works on Linux as wells it does on macOS

### CODE REVIEW

**Comment by Esteban82** [comment]
It is not working for me.

**Comment by PaulWessel** [comment]
Maybe it happens when the master ping is there from a previous run? Please delete and try ahain

**Comment by Esteban82** [comment]
It is trying to open the file in a sub-directory (`title/master/`). Not in the main directory.

image

**Comment by PaulWessel** [comment]
Closing this since the 1-sec wait is no longer needed when we use gmt docs to open files.

**Pull request closed without merging**
