### PR TITLE
Add 6.1.1 to changes.rst

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

Just a simple entry.

### CODE REVIEW

**Comment by seisman** [comment]
I think it should be in master branch, and then backport to 6.1, right?

**Comment by PaulWessel** [comment]
Hm, yes I guess so.  Am I allowed to change the target to master?

**Comment by PaulWessel** [comment]
If I change base I get 371 files updated.  Perhaps you know how to do this?

**Comment by seisman** [comment]
No worries. I will do the git magic.

**Pull request merged**
