### PR TITLE
Adjust offset to work in grdconvert for tiles

### PR DESCRIPTION
**Pull request by PaulWessel**
Because grdconvert always applies z' = z * scale + offset, but our definition in the recpie is z' = (z - offset) * scale, , it turns out we must pass -offset/scale to counter-act this shift.
@seisman, pls delete any *.nc tiles you got earlier so that after trying this branch you will get the JP2 again and this time use the update conversion.

### CODE REVIEW

**Comment by seisman** [comment]
earth_age_06m:
image

earth_age_05m:
image

The NaN color is different.

**Comment by PaulWessel** [comment]
Interesting.  The @age.cpt has N 70 so that is the first (darker version). THe second looks like the background color 180. Clearly the NaN gets lost in the shuffle and ends up negative? WIll check.

**Comment by PaulWessel** [comment]
Still struggling with this.  We apply the scaling by 100 and offset by 10000 to get short ints.  The NaNs remains a Nan in the memory,  The we write a short int netcdf. A NaN in that grid becomes -32767 in a netCDF short grid.  Then we convert to JP2 then I think it survives as -32767.  But instead I find -32887.  That is a difference of 120. Not sure what that is.  I could of courlse build in somthing like if <= -32767 set to NaN, but would be nice to understand why.

**Comment by PaulWessel** [comment]
It looks like it has to do with NaNs and JP2000 [https://www.researchgate.net/publication/252329759_Lossless_coding_of_floating_point_data_with_JPEG_2000_Part_10].  We may have to replace NaNs during tiling with an invalid number (for ages, say -1) and then when we convert the JP2 back out we must replace -1 with NaN on output to netcdf.

**Comment by PaulWessel** [comment]
Very strange.  See if this makes any sense to you, @seisman : This is what my srv_tiler.sh script does.  I'll do one tile manually:

```
gmt grdconvert earth_age_05m_p.grd -R-180/0/-90/90 -Gsubset.nc=ns -Z+s100+o100 -V
gdal_translate -q -of JP2OpenJPEG -co "QUALITY=100" -co "REVERSIBLE=YES" -co "YCBCR420=NO" subset.nc tile.jp2
```

Is tile.jp2 different from the official tile we place on the server?  Let's run diff:

diff tile.jp2 earth_age_05m_p/S90W180.earth_age_05m_p.jp2 

No output, and both files have the same byte count, etc.  These files must be identical. Turn the tile.jp2 back to a netcdf grid:

`gmt grdconvert tile.jp2 -Gnew.nc=ns+s0.01+o100 -fg -V --IO_NC4_DEFLATION_LEVEL=9 -Z+s0.01+o-10000  --GMT_HISTORY=false`

What does grdinfo say?

```
gmt grdinfo new.nc
new.nc: Title: Produced by grdconvert
new.nc: Command: grdconvert tile.jp2 -Gnew.nc=ns+s0.01+o100 -fg -V --IO_NC4_DEFLATION_LEVEL=9 -Z+s0.01+o-10000 --GMT_HISTORY=false
new.nc: Remark: 
new.nc: Gridline node registration used [Geographic grid]
new.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
new.nc: x_min: -179.958333333 x_max: -0.0416666666667 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 2160
new.nc: y_min: -89.9583333333 y_max: 89.9583333333 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2160
new.nc: z_min: 0.00999999999999 z_max: 194 name: z
new.nc: scale_factor: 0.01 add_offset: 100 packed z-range: [-9999,9400]
new.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 9
```

Great, correct range and everything. Now do the same with the official tile:

`gmt grdconvert earth_age_05m_p/S90W180.earth_age_05m_p.jp2 -Gnew.nc=ns+s0.01+o100 -Z+s0.01+o-10000 -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false`

What does grdinfo say for this one?

```
gmt grdinfo new.nc
new.nc: Title: Produced by grdconvert
new.nc: Command: grdconvert earth_age_05m_p/S90W180.earth_age_05m_p.jp2 -Gnew.nc=ns+s0.01+o100 -Z+s0.01+o-10000 -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false
new.nc: Remark: 
new.nc: Pixel node registration used [Geographic grid]
new.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
new.nc: x_min: -180 x_max: 0 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 2160
new.nc: y_min: -90 y_max: 90 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2160
new.nc: z_min: -227.68 z_max: 194 name: z
new.nc: scale_factor: 0.01 add_offset: 100 packed z-range: [-32768,9400]
new.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 9
```

Now the min is -227.68, i.e., see the packed range now has a -32768 in it.  How the hell can the two be different?  I do exactly the same thing to both of them, no? Am I missing something here?

**Comment by seisman** [comment]
> diff tile.jp2 earth_age_05m_p/S90W180.earth_age_05m_p.jp2

Are the md5sum the same?

**Comment by PaulWessel** [comment]
WIll check the mdsums now.  The commit I must made is needed regardless and was in effect during my experiment above.

**Comment by PaulWessel** [comment]
76d46cd4e75cec7a98203d4a25e3f70f3f0d23cf2659574ee24e5e7bcef626ae
76d46cd4e75cec7a98203d4a25e3f70f3f0d23cf2659574ee24e5e7bcef626ae

Exactly the same

**Comment by PaulWessel** [comment]
Ah, but the one just downloaded from server is

ce74ff6fcfca3ebf21c1627c2a1ef32b348dfaf73bd047a62516a3e2432321a2

different.  How can that be? EIther up or download caused trouble?

**Comment by PaulWessel** [comment]
Hold a second.  I removed my .gmt file and ran gmt get -N on that data.  Got the two jp2 tiles for 05m_p.  Idential SHA256 to the original and the ones on the server.  Yet, running the convert on that one gives the -227 min age but not when the same command is run on my original jp2.  This cannot be happneing.

**Comment by seisman** [comment]
I also have `new.nc: z_min: -227.68 z_max: 194 name: z`. Can you share your tile.jp2 file?

**Comment by PaulWessel** [comment]
shasum -a 256 tile.jp2
76d46cd4e75cec7a98203d4a25e3f70f3f0d23cf2659574ee24e5e7bcef626ae  tile.jp2
shasum -a 256  S90W180.earth_age_05m_p.jp2
76d46cd4e75cec7a98203d4a25e3f70f3f0d23cf2659574ee24e5e7bcef626ae  S90W180.earth_age_05m_p.jp2

Gives different netcdf files.  I wonder if the S90W180 tag triggers something in GDAL. The reason I suspect this is then I first created the SRTM tiles from the binary *.hgt file, it knew about that format but only if the proper SRTM file names were used, which has that tag.

**Comment by PaulWessel** [comment]
tile:


Paul Wessel, Professor and Chair
Dept. of Earth Sciences
SOEST, U of Hawaii at Manoa


On July 3, 2020 at 6:41:39 PM, Dongdong Tian (notifications@github.com)
wrote:

I also have new.nc: z_min: -227.68 z_max: 194 name: z. Can you share your
tile.jp2 file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/gmt/pull/3591#issuecomment-653720344>,
or unsubscribe

**Comment by seisman** [comment]
I can't see your attachment if you reply to issues by email.

**Comment by PaulWessel** [comment]
Sorry, I know, forgot.

**Comment by seisman** [comment]
I got the same incorrect z_min with your tile_1.jp2 file:
```
gmt grdinfo new.nc          
new.nc: Title: Produced by grdconvert
new.nc: Command: grdconvert tile_1.jp2 -Gnew.nc=ns+s0.01+o100 -fg -V --IO_NC4_DEFLATION_LEVEL=9 -Z+s0.01+o-10000 --GMT_HISTORY=false
new.nc: Remark:
new.nc: Gridline node registration used [Geographic grid]
new.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
new.nc: x_min: -179.958333333 x_max: -0.0416666666667 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 2160
new.nc: y_min: -89.9583333333 y_max: 89.9583333333 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2160
new.nc: z_min: -227.68 z_max: 194 name: z
new.nc: scale_factor: 0.01 add_offset: 100 packed z-range: [-32768,9400]
new.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 9
```

**Comment by PaulWessel** [comment]
Yet I get the correct result with the same file:
gmt grdconvert tile.jp2 -Gnew.nc=ns+s0.01+o100 -Z+s0.01+o-10000 -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false
gmt grdinfo new.nc 
new.nc: Title: Produced by grdconvert
new.nc: Command: grdconvert tile.jp2 -Gnew.nc=ns+s0.01+o100 -Z+s0.01+o-10000 -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false
new.nc: Remark: 
new.nc: Gridline node registration used [Geographic grid]
new.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
new.nc: x_min: -179.958333333 x_max: -0.0416666666667 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 2160
new.nc: y_min: -89.9583333333 y_max: 89.9583333333 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2160
new.nc: z_min: 0.00999999999999 z_max: 194 name: z
new.nc: scale_factor: 0.01 add_offset: 100 packed z-range: [-9999,9400]
new.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 9

**Comment by PaulWessel** [comment]
This is GDAL 3.1.0

**Comment by seisman** [comment]
I also have GDAL 3.1.0 (brew provides 3.1.1, but I downgraded it to 3.1.0).

**Comment by PaulWessel** [comment]
Rebuilt with 3.1.1, same result for me (works with tile,jp2)

**Comment by PaulWessel** [comment]
Are you using this branch inv-scale-jp2 to run your command?

**Comment by PaulWessel** [comment]
I will reboot then rebuild form this branch.

**Comment by seisman** [comment]
Yes, I'm running this branch.

**Comment by PaulWessel** [comment]
OK, solved the mystery at least: When gdal_translate converts to jp2 it cannot place all the meta data there, so it creates tile.jp2.aux.xml, which we turn off for this work.  But when I did it manually the file survivied.  It contains among other things 
    <MDI key="z#_FillValue">-32768</MDI>
If I delete that file then I get the same as you.
If I just do

gmt grdconvert tile.jp2 -Gnew.nc=ns

then I get

```
 gmt grdinfo new.nc -M
new.nc: Title: Produced by grdconvert
new.nc: Command: grdconvert tile.jp2 -Gnew.nc=ns
new.nc: Remark: 
new.nc: Gridline node registration used [Cartesian grid]
new.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
new.nc: x_min: -179.958333333 x_max: -0.0416666666667 x_inc: 0.0833333333333 name: x n_columns: 2160
new.nc: y_min: -89.9583333333 y_max: 89.9583333333 y_inc: 0.0833333333333 name: y n_rows: 2160
new.nc: z_min: -9999 at x = -127.375 y = 41.5416666667 z_max: 9400 at x = -75.125 y = 35.125
new.nc: scale_factor: 1 add_offset: 0
new.nc: 1956412 nodes (41.9%) set to NaN
new.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 3
```

Note is still says 41.9% are NaNs but it also lets the -32768 be seen as a data value.  I think GDAL does not set a nan but I think the netCDF driver or library detects it since the ncdump -h says

```
		z:_FillValue = -32768s ;
		z:actual_range = -32768., 9400. ;
```

So looks like I might be able to just replace the -32768 with NaNs in grdconvert via a flag.

**Comment by PaulWessel** [comment]
And why does it claim gridline registration? I KNOW I fixed this earlier in gdal_grd*.c...

**Comment by PaulWessel** [comment]
Nevermind the registration.  I impose a specific solution if the file is a tile (with specific names), else I dont override.

**Comment by PaulWessel** [comment]
I think the solution here might be the same I do for the registration.  In gmt_gdalread I call 

```
if (gmtlib_file_is_jpeg2000_tile (GMT->parent, gdal_filename) != GMT_NOTSET && (Ctrl->RasterXsize % 2) == 0 && (Ctrl->RasterYsize % 2) == 0)
		/* PW: Reading GMT server special JP2 tiles: even size implies pixel registration */
		pixel_reg = true;
```

since I know we are dealing with a JP2 tile.  I could also do that to check for -32767 in the shorts returned from GDAL if that is true.

**Comment by PaulWessel** [comment]
OK, so this works well it seems.  I intercept the -32768 integers and make them NaN in the grid.  The nc tiles now say

```
gmt grdinfo S90W180.earth_age_05m_p.nc -M
S90W180.earth_age_05m_p.nc: Title: Produced by grdconvert
S90W180.earth_age_05m_p.nc: Command: grdconvert /Users/pwessel/.gmt/server/earth/earth_age/earth_age_05m_p/S90W180.earth_age_05m_p.jp2 -G/Users/pwessel/.gmt/server/earth/earth_age/earth_age_05m_p/S90W180.earth_age_05m_p.nc=ns+s0.01+o100 -Z+s0.01+o-10000 -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false
S90W180.earth_age_05m_p.nc: Remark: 
S90W180.earth_age_05m_p.nc: Pixel node registration used [Geographic grid]
S90W180.earth_age_05m_p.nc: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
S90W180.earth_age_05m_p.nc: x_min: -180 x_max: 0 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 2160
S90W180.earth_age_05m_p.nc: y_min: -90 y_max: 90 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2160
S90W180.earth_age_05m_p.nc: z_min: 0.0100021362305 at x = -127.375 y = 41.5416666667 z_max: 194 at x = -75.125 y = 35.125
S90W180.earth_age_05m_p.nc: scale_factor: 0.01 add_offset: 100 packed z-range: [-9999,9400]
S90W180.earth_age_05m_p.nc: 1956412 nodes (41.9%) set to NaN
S90W180.earth_age_05m_p.nc: format: netCDF-4 chunk_size: 135,135 shuffle: on deflation_level: 9
```

Just like my old tile.jp2 produced.  However, the image I get is red (as in age = 0) where it is NaN, and the grid does have NaNs.  I think I need dinner.

map

**Comment by PaulWessel** [comment]
Jeez.  My fix here is fine.  The grids have NaN.  However, grdblend is not considering NaNs, so things are left as 0, hence red....

**Comment by PaulWessel** [comment]
OK, this should now work fine: Without the .aux.xml files we deal with NaN via -32768 manually.  The nc grid are now fully recovered with NaNs.  The other issue had to do with how **grdblend** was used to add tiles into the final grid.  This started with only earth relief so there were some settings that only made sense for reliefs with no NaN.  Specifically, I passed **-N**0 to **grdblend** so that empty nodes were set to 0.  But age grids have NaNs and should become NaN...
The slightly longer solution is to avoid using **grdblend** at all.  After all, except for the SRTM 1|3s plus SRTM15 blend, the rest is simply placing the files in the grid - there is no over lap or blending.  So a _grdstitch_ function should be written and called instead.  For a later revision.

All test pass for me and stuff like

`gmt grdimage @earth_age_05m -B -png map -C@age.cpt`

works as expected.  Please check on review.

**Comment by PaulWessel** [comment]
Here is the latest plot of 05m:

map

**Comment by PaulWessel** [comment]
Hoping @joa-quim and @seisman can confirm and approve this one.

**Comment by joa-quim** [comment]
Sorry, I can only give a *blind approve*

**Pull request merged**
