### PR TITLE
Reset subplot row,col|index to start at zero

### PR DESCRIPTION
**Pull request by PaulWessel**
In order to be consistent with all other places in GMT where rows or columns are given, we will set subplot row,col also follow the same convention.  Thus 0,0 is the top left panel.
Implementation changed some unsigned ints to int and several doc and test scripts needed to be updated.  Only failure (for me right now) was anim_08.sh which seems to have to do with NEIC data changes.

### CODE REVIEW

**Comment by seisman** [comment]
The script below works but generate some "error" messages:
```
gmt begin map pdf
gmt subplot begin 3x2 -Fs5c/5c
    gmt basemap -R0/10/0/10 -Baf -c0
    gmt basemap -R0/10/0/10 -Baf -c3
gmt subplot end
gmt end show
```

Error message:
```
gmt [ERROR]: Index 0 goes to (0, 0)
gmt [ERROR]: Index 3 goes to (1, 1)
```

**Comment by seisman** [comment]
`-c-1` also works. Is it a feature?
```
gmt begin map pdf
gmt subplot begin 3x2 -Fs5c/5c -A
    gmt basemap -R0/10/0/10 -Baf -c-1
    gmt basemap -R0/10/0/10 -Baf -c3
gmt subplot end
gmt end show
```

**Comment by PaulWessel** [comment]
oops.  What do you mean it works? It goes to the first panel?
I will add a check that the index is not negative (I think I check that row,col are not negative).

**Comment by seisman** [comment]
> oops. What do you mean it works? It goes to the first panel?

Yes, `-c-1` goes to the first panel.

**Comment by seisman** [comment]
Another issue is the figure is incorrectly cropped at the bottom. To reproduce the issue, run:
```
gmt begin map pdf
gmt subplot begin 3x2 -Fs4c/4c -A
for i in $(seq 0 5); do
    gmt basemap -R0/10/0/10 -Baf -c
done
gmt subplot end
gmt end show
```

image

The cropping is correct if I change `3x2` to `5x2`. Thus the issue may be not related to #195.

**Comment by PaulWessel** [comment]
Gets worse if I extend to 4x2. ghostscript again? I mean, gs is doing the cropping. Doing ps I see we are running off the page, so perhaps not gs.  THis is not related to the new row,col stuff but was there before, right?

**Comment by seisman** [comment]
What's the plot origin for the first panel?

**Comment by PaulWessel** [comment]
I will look into it, but since this problem exists in 6 with old 1-n, 1-m specifications I think we can merge this PR in and then work on this problem.

**Pull request merged**
