### PR TITLE
Add longoption support for filter1d

### LINKED ISSUE #7942: longoption support for filter1d
**Description of the desired feature**

longoption support for filter1d

**Are you willing to help implement and maintain this feature?** Yes/No

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**

Add longoption support for filter1d

Python differences:

  None?

Julia differences:

  Changed symetry (-S) to symmetry (spelling correction)
  Changed equi_space (-T) to equispace (spelling correction)
    equispace is a real English word (with no underscore in the middle).

Fixes #7942

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by joa-quim** [comment]
OK, I changed those two in GMT.jl but the **-T** case is more delicate and will show up in several modules. My preferred one is `range` and the `equispace` (funny, the Github dictionary doesn't know it) comes as alias in this module but not in other where we also have a **-T**. The problem with `range` for Python is that it's a reserved keyword and cannot be used there. They picked `series` but I don't find it a good choice for GMT.

**Comment by PaulWessel** [comment]
True that **-T** appears in many modules and calls the same _gmt_parse_array_ and _gmt_create_array_ machinery.  In many modules you can specify non-equidistant arrays, such as `-T1,5,6,10,100`.  So in that sense _equispace_ is not appropriate.  Even monotonically increasing is not true as `-T1,2,1,50` is accepted. The thing `-T1/100/1`, `-T1,5,6,10,100` and `-T1,2,1,50`have in common is that they are a all series of 1-D time or space coordinates.  Perhaps we can have a discussion of whether

```
--coordinates=
--series=
--nodes=
--times|positions
--abscissae=

```
and perhaps others? Pinging @GenericMappingTools/long-options-review on this one since will affect many modules.

**Comment by PaulWessel** [comment]
BTW, I merged master into this branch to minimise any conflicts since there are > 20 commits to master since this branch was posted as PR.

**Comment by joa-quim** [comment]
I think having -T aliased as `range` and `series` solves all the problems. 
  1) It satisfies both GMT.jl & PyGMT
  2) it's a range when `-T1/100/1` and it's a series when `-T1,2,1,50`.

**Comment by PaulWessel** [comment]
> I think having -T aliased as `range` and `series` solves all the problems.
> 
> 1. It satisfies both GMT.jl & PyGMT
> 2. it's a range when `-T1/100/1` and it's a series when `-T1,2,1,50`.

A Solomonian decision that I can concur with. We should probably identify all modules accepting a -T option and fix them all before we forget.

**Review by PaulWessel — APPROVED** [review]
-T revised, time_column as alias

**Pull request merged**
