### PR TITLE
Check if gm is installed

### LINKED ISSUE #1494: Improve error message if gm isn't found
I uninstalled GraphicsMagick and ran the animation example in the [movie manpage](https://docs.generic-mapping-tools.org/dev/movie.html#examples).

The movie command is:
```
gmt movie globe.sh -Nglobe -T360 -Agif -C6ix6ix100 -Lf -Vd
```

The output information is:
```
movie [DEBUG]: Found file globe.sh
movie [DEBUG]: Found file globe.sh
sh: gm: command not found
movie [INFORMATION]: GraphicsMagick  found.
movie [INFORMATION]: Paper dimensions: Width = 6i Height = 6i
movie [INFORMATION]: Pixel dimensions: 600 x 600
```
gm is not available, but GMT says it's found.

### PR DESCRIPTION
**Pull request by PaulWessel**
See #1494.  Now be more careful in checking the return of the system command output before we say it is found.  Closes #1494.  Not tested yet....

### CODE REVIEW

**Comment by seisman** [comment]
Not working.

**Comment by PaulWessel** [comment]
OK< I will rename gm and test in debug.  Busy with other stuff...

**Comment by seisman** [comment]
ffmpeg --version may have the same problem.

**Comment by PaulWessel** [comment]
OK the gm test now works and I did the same for ffmpeg.

**Pull request merged**
