### PR TITLE
Ensure degenerated Cartesian ellipses get correct azimuth

### LINKED ISSUE #4877: psxy -SE bug when using linear projection
I have been having some issues with using the -SE option with psxy and linear projections. I've specifically been having issues with ellipses, but I think the problem can be best described with this example:

echo "0 0 0.1" | gmt psxy -JX10c/10c -R-0.1/0.1/-1/1 -SE- -Gred -Wthinner,black -Bxa0.05 -Bya0.5 -BSWne > tmp.ps
gmt psconvert -Tf -Z -P -A tmp.ps

This should plot a circle with a diameter of 0.1 units. As you can see from the attached plot, this command isn't working how I would expect. It seems the x and y direction are flipped (i.e. in this case the shape should be rotated by 90 deg).

[tmp.pdf](https://github.com/GenericMappingTools/gmt/files/6062185/tmp.pdf)

**System information**

* Operating system: ubuntu
* GMT version (`gmt --version`): 6.1.1

### PR DESCRIPTION
**Pull request by PaulWessel**
Depending on projection, needed to set the degenerate ellipse azimuth correctly since for Cartesian axes with different scalings it may plot as an ellipse, not a circle, so direction matters even if it is a "circle".

Also, pen, fill was not activated for this particular case, leading to an invisible ellipse (which seems broken since 6.1.1).  With this PR, the following command works:

`echo "0 0 0.1" | gmt plot -JX10c/10c -R-0.1/0.1/-1/1 -SE- -Gred -Wthinner,black -B -BSWne -png t`

and gives the expected thin ellipse stretched in the x-direction given the different ranges:

t

Closes #4877.

### CODE REVIEW

**Comment by meghanrjones** [comment]
Is it worthwhile to add a test for this?

**Comment by PaulWessel** [comment]
Yes, since this case was not covered.  Maybe you can make one that does 2x2 panels of degenerate ellipses for Cartesian projections with different scalings, including equal, to just cover the bases.

**Comment by meghanrjones** [comment]
> Yes, since this case was not covered. Maybe you can make one that does 2x2 panels of degenerate ellipses for Cartesian projections with different scalings, including equal, to just cover the bases.

OK, I will push a new test directly to this branch rather than creating a new PR off it for simplicity.

**Comment by PaulWessel** [comment]
Yep, that is good.

**Pull request merged**
