### PR TITLE
Add call to GMT_Option for -c in all plotting modules

### PR DESCRIPTION
**Pull request by PaulWessel**
In response to #784.  Well, except inset which cannot start a new panel.  Still subject to #777.  Meant to only be listed under modern mode.  Still need to do synopsis.

### CODE REVIEW

**Comment by seisman** [comment]
The rST documentations should also be updated.

**Comment by PaulWessel** [comment]
Yes.  I have to head out for a few hours - if you have time please do it and let me know you are working on it so we don't both do it.

**Comment by seisman** [comment]
OK. I'll open another PR to address the issue of documentations.

**Comment by seisman** [comment]
I tried 
```
gmt coast -
```
and
```
gmt begin map
gmt coast -
gmt end
```
both don't show -c option.

**Comment by PaulWessel** [comment]
Yes, will have to debug - now that I am back.

**Comment by PaulWessel** [comment]
Funny, pscoast was left of my list as I created the list by searching for KEYS with >X} but pscoast.c is a chameleon that may write data...  Now works for me.  So gmt coast - or gmt coast -? works and shows the **-c** and explanation, while gmt pscoast - or -? gives classic usage with **-O -K** but no **-c**. Typing gmt coast with no args give errors about **-R** etc as before.  Please see gmt_report_usage in gmt_init.c for the explanation.

**Pull request merged**
