### PR TITLE
Let GMT recognize MATLAB headers/comments

### PR DESCRIPTION
**Pull request by PaulWessel**
By extending the **IO_HEADER_MARKER** setting to accept a string of possible input-header markers we can set the default to `#%'"` which means either GMT or MATLAB header records as well as quoted text records are automatically recognized.  For output only one marker can be selected `[#]`.

### CODE REVIEW

**Comment by joa-quim** [comment]
A low probability event, but **IO_SEGMENT_MARKER** should not be allowed to be any of the **IO_HEADER_MARKER**'s

**Comment by PaulWessel** [comment]
Good point, I will add that test.

**Comment by PaulWessel** [comment]
This PR is meant to close #3016.  Test described above has been added and works.

**Comment by PaulWessel** [comment]
Please read and comment on the last entry on #3016 first.

**Pull request merged**
