### PR TITLE
Try again to fix the draping issues. It seams to work for the 4 cases.

### LINKED ISSUE #7261: grdview -D is broken in classic but not in modern
```
gmt grdcut  @earth_relief_01m_p -R0/10/0/10 -Gtopo.nc
```
- Classic
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01d_p.tif -Baf -BWSne -Qi100 -P > lixo_classic.ps
```

lixo_classic

- Modern
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01d_p.tif -Baf -BWSne -Qi100 -png lixo_modern
```
lixo_modern

### PR DESCRIPTION
**Pull request by joa-quim**
Hopefully Fix #7261

### CODE REVIEW

**Comment by joa-quim** [comment]
Yes, I run the tests but those on Windows are of limit use (lots of false failures). It has been like that for years.

**Comment by joa-quim** [comment]
Ping.
All these 4 cases work now (only 1 or 2 worked before)
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@wood_texture.jpg -Baf -BWSne -Qi100 -P > lixo.ps
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@wood_texture.jpg -Baf -BWSne -Qi100 -png lixo

gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01m_p.tif -Baf -BWSne -Qi100 -png lixo
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01m_p.tif -Baf -BWSne -Qi100 -P > lixo.ps
```

**Review by PaulWessel — APPROVED** [review]
Can we make this into a better test given the 4 cases work?  Add a second texture3.sh script while you are at it?

**Comment by joa-quim** [comment]
Yeap. I was trying to avoid having to relearn how to *DVC*'it

**Comment by joa-quim** [comment]
DVC it's letting me push
```
/c/progs_cygw/GMTdev/gmt5/master/test> dvc push
ERROR: failed to transfer 'md5: 9764ba6b0093666a74cf2f13e494b8a3' - 401, message='Unauthorized', url=URL('https://dagshub.c
om/GenericMappingTools/gmt.dvc/97/64ba6b0093666a74cf2f13e494b8a3')
ERROR: failed to transfer 'md5: 75b1652777146435901ed04ec1273c25' - 401, message='Unauthorized', url=URL('https://dagshub.c
om/GenericMappingTools/gmt.dvc/75/b1652777146435901ed04ec1273c25')
ERROR: failed to upload 'C:\progs_cygw\GMTdev\gmt5\master\.dvc\cache\d8\4a0d4cd2b921e1bd1782256ed1692a.dir' to 'https://dag
shub.com/GenericMappingTools/gmt.dvc/d8/4a0d4cd2b921e1bd1782256ed1692a.dir'
ERROR: failed to push data to the cloud - 3 files failed to upload

```

**Comment by PaulWessel** [comment]
I forget, does @maxrjones remember any other steps like an account?

**Comment by maxrjones** [comment]
> I forget, does @maxrjones remember any other steps like an account?

Yes, but I thought Joaquim already followed the steps at https://dagshub.com/docs/feature_guide/dagshub_storage/#how-to-set-up-dagshub-storage-locally for setting up the authentication.

**Comment by joa-quim** [comment]
The problem is those instructions are incomprehensible. This is what I see.
And if I'm a collaborator and I'm logged in. What authentication else does it want?
 
image

**Comment by maxrjones** [comment]
That popup definitely could be improved. I've copied the relevant parts in https://github.com/GenericMappingTools/gmt/issues/7280

**Comment by joa-quim** [comment]
And as I commented in that issue, I am now able to commit to DVC.
Thanks

**Pull request merged**
