### PR TITLE
Add a GMT team page and update contributor recognition model

### LINKED ISSUE #2330: Give credits to contributors by adding them to AUTHORS.md
We encourage more contributors to help maintain and improve GMT. For these contributors, I think we should give them credits by adding them to AUTHORS.md. Or they can choose to add themselves to AUTHORS.md when submitting a PR.

We already have a section "Further Acknowledgments" in AUTHORS.md, but it's a long paragraph. Maybe better to change it to a list of names.

### LINKED ISSUE #5567: Add Meghan to AUTHORS.md
@meghanrjones Don't forget to add yourself to AUTHORS.md

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR makes four changes to the GMT documentation:

1. Add a GMT Team page that contains a Distinguished Contributors section which can be used to recognize people's efforts. This is largely based on the project Jupyter distinguished contributors model and the NumPy team page. Suggestions are welcome for the recognition model, in which new distinguished contributors are decided upon by the people listed on the page annually.
2. Change AUTHORS.md to THANKS.md to better reflect the updated contents.
3. Move pages that are in the Developer Resources toctree to the devdocs folder and updates links accordingly.
4. Rename Developer Documentation page to GMT Enhancement Proposals to provide more descriptive information about the contents.

If this is approved, we should change the redirect for https://www.generic-mapping-tools.org/team from https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md.

Fixes #2330
Fixes #5567 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
Preview page: https://gmt-qa2jybumh-gmt.vercel.app/devdocs/team.html

**Comment by seisman** [comment]
For the "Distinguished Contributors" (or Team Members in AUTHORS.md), is it better to sort people by the time they joined the team? I'm a little overwhelmed as I'm currently listed as the first one.

**Comment by meghanrjones** [comment]
> For the "Distinguished Contributors" (or Team Members in AUTHORS.md), is it better to sort people by the time they joined the team? I'm a little overwhelmed as I'm currently listed as the first one.

I can change this to sorted by time :smile: I just went by alphabetical out of habit.

**Comment by meghanrjones** [comment]
> For the "Distinguished Contributors" (or Team Members in AUTHORS.md), is it better to sort people by the time they joined the team? I'm a little overwhelmed as I'm currently listed as the first one.

Done now, thanks for the recommendation.

**Review by PaulWessel — APPROVED** [review]
I guess this may make me update the GitHug pix...

**Review by seisman — APPROVED** [review]

**Comment by meghanrjones** [comment]
@seisman, do you know how I could set the redirect link for https://www.generic-mapping-tools.org/team.html to go to the new page after merging?

**Comment by seisman** [comment]
You need to change the URL in this file:
https://github.com/GenericMappingTools/website/blob/master/team.html

**Comment by meghanrjones** [comment]
> You need to change the URL in this file:
> https://github.com/GenericMappingTools/website/blob/master/team.html

Thanks!

**Pull request merged**
