### PR TITLE
cmake: Rename CMake variable BUILD_EXTRA_DIRS to SUPPL_EXTRA_DIRS

### LINKED ISSUE #2917: EXTRA_MODULES_SUPPL doesn't work as documented
The `cmake/ConfigUserAdvanced.cmake` file documents that the variable contains a list of C codes.

https://github.com/GenericMappingTools/gmt/blob/758119cee25740c7f2cdc43437b7b9c7c697e189/cmake/ConfigUserAdvancedTemplate.cmake#L202-L203

But, in the `src/CMakeLists.txt`, the variable is used in the other way. The `include` directive in CMake expects to load and run a CMake script rather than a C code.

https://github.com/GenericMappingTools/gmt/blob/758119cee25740c7f2cdc43437b7b9c7c697e189/src/CMakeLists.txt#L489-L495

We have another three cmake variables:
- **EXTRA_MODULES**: list of C codes to be included into GMT's core modules. Works as documented.
- **EXTRA_BUILD_DIRS**: list of directories with a CMakeLists.txt file, just like seis. The codes in the directories will be added as GMT's supplemental modules.
- **EXTRA_INCLUDE_NEWSUPPL**: the variable is not documented.

### PR DESCRIPTION
**Pull request by seisman**
Close #2917.

### CODE REVIEW

**Comment by joa-quim** [comment]
Can we please stop renaming variables? I have next to spend hours debugging why my builds break.

**Comment by seisman** [comment]
What you need to do is renaming BUILD_EXTRA_DIRS to SUPPL_EXTRA_DIRS in your own cmake/ConfigUser.cmake file.

**Comment by joa-quim** [comment]
Yes, but before finding that I had to spend time and . trying to figure out why the MB was broken again, and all of that because of a variable rename that was not needed at all. 
It's not fun to find that older mex and julia tests that I don't run so often are broken because used files in the server had been renamed or deleted.

**Comment by PaulWessel** [comment]
Well, that is a good point.  Perhaps when we make changes to things like Cmake files we should require approval from both of us before it is merged.

**Pull request merged**
