### PR TITLE
Document rose -N option in reST files

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR adds the **-N** option to the reST documentation for `rose`. 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
@PaulWessel, the **-N** usage says that it's only valid for **-Sn***radius*, but there is no **n***radius* modifiers listed for **-S** in the html or command-line docs. I can look into the code regarding **n***radius*, or if you know off-hand what those modifiers do then I can add that to the docs.

**Comment by PaulWessel** [comment]
Will look after a zoom that starts in 1 minute...

**Review by PaulWessel — APPROVED** [review]

**Comment by PaulWessel** [comment]
> @PaulWessel, the **-N** usage says that it's only valid for **-Sn**_radius_, but there is no **n**_radius_ modifiers listed for **-S** in the html or command-line docs. I can look into the code regarding **n**_radius_, or if you know off-hand what those modifiers do then I can add that to the docs.

The **-S**[**n**]_radius_ was the old syntax, so this text will have to change.  I see the **-N** requires **-S** basically, so silly to have two options needed to accomplish normalization of radii, then take square root of the normalized radii.  I think this scheme would allow some simplification plus adding a **-N** option like **histogram** has:

1. Let **-N** with no argument be a backwards compatible way to select sqrt(normalized-radii).  This would be marked as a deprecated option.
2. As an alternative to **-N**, introduce **-S**[**+a**] for what presently requires **-S -N,** with **+a** meaning "area normalization"
3. Introduce **-N0**[**+p**_pen_] for drawing the best-fitting Least-squares von Mises pdf fit on top of the polar histogram (there are no robust fits yet for these distros, but if we add those later then best to have the same **-N0**|**1**|**2** syntax as in histogram).

Thoughts?

**Comment by meghanrjones** [comment]
> > @PaulWessel, the **-N** usage says that it's only valid for **-Sn**_radius_, but there is no **n**_radius_ modifiers listed for **-S** in the html or command-line docs. I can look into the code regarding **n**_radius_, or if you know off-hand what those modifiers do then I can add that to the docs.
> 
> The **-S**[**n**]_radius_ was the old syntax, so this text will have to change. I see the **-N** requires **-S** basically, so silly to have two options needed to accomplish normalization of radii, then take square root of the normalized radii. I think this scheme would allow some simplification plus adding a **-N** option like **histogram** has:
> 
>     1. Let **-N** with no argument be a backwards compatible way to select sqrt(normalized-radii).  This would be marked as a deprecated option.
> 
>     2. As an alternative to **-N**, introduce **-S**[**+a**] for what presently requires **-S -N,** with **+a** meaning "area normalization"
> 
>     3. Introduce **-N0**[**+p**_pen_] for drawing the best-fitting Least-squares von Mises pdf fit on top of the polar histogram (there are no robust fits yet for these distros, but if we add those later then best to have the same **-N0**|**1**|**2** syntax as in histogram).
> 
> 
> Thoughts?

Yes, I agree with all three points.

**Pull request merged**
