### PR TITLE
Remove unused structure element in grdinterpolate

### PR DESCRIPTION
**Pull request by PaulWessel**
Left-over from cut/paste probably.

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel Check the output of `gmt grdinterpolate`. Some small issues:

1. -V is missing
2. -Z should be shown before -^

**Comment by PaulWessel** [comment]
Unrelated, the explain_array.rst_ that we use to explain -T in many programs (including grdinterpolate) does not format the examples as I thought.  The trailing :: we use before giving an example results in a single colon being plotted.  Is this normal?

**Comment by seisman** [comment]
Yes, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks.

**Comment by PaulWessel** [comment]
Thanks.

**Pull request merged**
