### PR TITLE
Update some header files and fix typos

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Fix a small typo (`user`-> `used`) in three PS files, and run scripts `gmt_make_PSL_strings.sh`, `gmt_make_module_src.sh` to update the header files.

### CODE REVIEW

**Comment by PaulWessel** [comment]
The psl_fnt stuff looks different and is more than a small typo.  How come they differ so much?

**Comment by seisman** [comment]
I think someone modified the PSL_\*.ps before and didn't run the scripts to re-generate the header files.
I only fixed the `user` typo in these PSL_\*.ps files. GitHub fails to show the changes of the PS files.
You can use following command to view the changes in terminal:
```
$ git checkout master
$ git pull
$ git show 9b3e8ee32fc77c17da3427e45274fe3205e655f0
```

```
diff --git a/src/PSL_label.ps b/src/PSL_label.ps
index 66dbc69d1..8427758c8 100644
--- a/src/PSL_label.ps
+++ b/src/PSL_label.ps
@@ -7,7 +7,7 @@
 %-     The second part is the functions that assist in finding
 %-     out where labels are placed and setting clip paths etc.
 %-
-%- NOTE: No longer user as replaced by static string in PSL_strings.h.
+%- NOTE: No longer used as replaced by static string in PSL_strings.h.
 %-      We keep the file in the repository as it may be simpler to see
 %-      the logic in this file than in the static string.
 %-----------------------------------------------------------------------------
diff --git a/src/PSL_prologue.ps b/src/PSL_prologue.ps
index 9d1eea282..dbed30ac4 100644
--- a/src/PSL_prologue.ps
+++ b/src/PSL_prologue.ps
@@ -1,5 +1,5 @@
 %-----------------------------------------------------------------------------
-%- NOTE: No longer user as replaced by static string in PSL_strings.h.
+%- NOTE: No longer used as replaced by static string in PSL_strings.h.
 %-      We keep the file in the repository as it may be simpler to see
 %-      the logic in this file than in the static string.
 %-----------------------------------------------------------------------------
diff --git a/src/PSL_prologue.ps b/src/PSL_prologue.ps
index 9d1eea282..dbed30ac4 100644
--- a/src/PSL_prologue.ps
+++ b/src/PSL_prologue.ps
@@ -1,5 +1,5 @@
 %-----------------------------------------------------------------------------
-%- NOTE: No longer user as replaced by static string in PSL_strings.h.
+%- NOTE: No longer used as replaced by static string in PSL_strings.h.
 %-      We keep the file in the repository as it may be simpler to see
 %-      the logic in this file than in the static string.
 %-----------------------------------------------------------------------------
```

**Comment by PaulWessel** [comment]
I'd like to run the full tests using this branch but having trouble with remote files from SOEST.

**Comment by seisman** [comment]
I pushed a commit to trigger the full tests temporarily. The build report is available at https://travis-ci.org/GenericMappingTools/gmt/builds/504206621.

**Comment by seisman** [comment]
@PaulWessel If I understand it correctly, `gmt_make_PSL_strings.sh` combines `PSL_label.ps`, `PSL_text.ps` and `PSL_prologue.ps` and generates `PSL_strings.h` automatically.

If you run `gmt_make_PSL_strings.sh`, you would find some changes of `PSL_strings.h`. This PR is generated by running `gmt_make_PSL_strings.sh`, but the tests failed.

**Comment by PaulWessel** [comment]
OK, will build your commit and see if I can figure out what is right.

**Comment by PaulWessel** [comment]
Hi @seisman could you merge changes from master into this branch so that I can compare the results without having to track down others changes due to recent merges?

**Comment by PaulWessel** [comment]
On my system, the same 27 failures I have with master are the same that occurs with your branch (after merging in changes from master).  I thus think it is OK to merge this PR.

**Pull request merged**
