### PR TITLE
Prevent makecpt crash due to lack of nodes

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

If iT is used with _inc_**+n** to indicate we want _inc_ points along the z-axis, we must check that this results in at least 2 nodes since we need that many to form a single CPT slice.  Before this PR, commands like

gmt makecpt -Cjet -Z -T0/100/1+n

would result in a crash because downstream it was assumed there surely would be at least 2 nodes.  I have plugged that crash-site and now added a test in **makecpt** itself to stop right there if n < 2.

### CODE REVIEW

**Review by meghanrjones — COMMENTED** [review]
...so many failures

**Comment by PaulWessel** [comment]
Sorry, you need to update - I fixed a stupid thing.  My test now only gave me one (the new one from earlier today) that may not be relevant.

**Comment by meghanrjones** [comment]
Is the change pushed? git says I'm up to date

**Comment by PaulWessel** [comment]
Ooops. now.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
