### PR TITLE
rename insert to inset

### PR DESCRIPTION
**Pull request by PaulWessel**
In addition, several internal variables and functions changed from using insert to inset as well

I have renamed insert.c to inset.c.  In addition there are lots of internal functions and structures and constants that incorrectly used "insert" as well.  These are now all using inset or INSET.

### CODE REVIEW

**Comment by seisman** [comment]
@PaulWessel Don't forget to change "insert"s in the documentation.

**Comment by PaulWessel** [comment]
Thanks, now did the documentation and scripts.

**Comment by seisman** [comment]
@PaulWessel Please double check following files:
1. src/gmt_constants.h
2. src/gmt_init.c
3. src/gmt_plot.c
4. src/gmt_support.c
5. src/gmt_symbol.h
6. src/gmt_symbol.h
7. doc_classic/examples/ex21/example_21.bat
8. doc_classic/examples/ex44/example_44.bat
9. doc_modern/examples/ex21/example_21.bat
10. doc_modern/examples/ex44/example_44.bat.

**Comment by PaulWessel** [comment]
I've done all those and committed to that branch but perhaps I dont understand how to merge the two commits?

**Comment by leouieda** [comment]
No need to merge. To update the PR, run `git push` from the branch.

**Pull request merged**
