### PR TITLE
Enable greenspline in modern mode to pick up session -R -I -r

### PR DESCRIPTION
**Pull request by PaulWessel**
In modern mode, modules that take **-R -I -r** can fish these from the history.  However, **greenspline** is a bit of an odd duck in that its **-R** option is _not_ parsed as a common option since it may take limits for 1-D, 2-D, or 3-D domains.  So, when no **-R** is given then the things that normally happens for other modules do not happen for **greenspline**.  This PR implements the required steps so that **-R -I -r** can be found if present in the history.

Unfortunately, I also fixed a few documentation errors for batch and movie in this PR: We talked about **MOVIE_TAG**, **BATCH_TAG** but the actual parameters are **MOVIE_ITEM** and **BATCH_ITEM**.

Tests pass with these changes, as does a new movie script that starts this way:

```
gmt begin
	gmt convert -Em10 @geologists.txt -i0,1,2+s-1 -s | gmt blockmedian -R158:00W/156:58W/18:00N/19:40N -I1m > geo.txt
	gmt greenspline geo.txt -Sc -C+feigenvalues.txt+c+i -Ggeo.grd -Z2
	...
```

### CODE REVIEW

**Comment by PaulWessel** [comment]
Hoping one of you could take pity on me and look at the two greenspline-related PRs since I am stuck making progress on anim05 without these merged in.

**Comment by PaulWessel** [comment]
SHould have aded pinging @joa-quim @Esteban82 @seisman @meghanrjones

**Comment by meghanrjones** [comment]
Currently the example below fails with the warning `No output locations specified (use either [-R -I], -N, or -T)`. Does the -R history not translate across plotting/processing modules?
```
gmt begin 2D
  gmt plot -R0/6.5/-0.2/6.5 -JX6i -B -Sc0.1 -Gblack @Table_5_11.txt
  gmt greenspline @Table_5_11.txt -I0.1 -Sc -V -Z1 -GS1987.nc
  gmt grdcontour -C25 -A50 S1987.nc
gmt end show
```

**Comment by PaulWessel** [comment]
I think the rule is that a plotting module will first look for a plot **-R** and if none found it will look for a data processing **-R**, while a data processing module will only accept a data processing **-R** from the history.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
