### PR TITLE
Redesign documentations

### PR DESCRIPTION
**Pull request by seisman**
@leouieda I create the PR so that we can easily track the progress and contribute PRs to the docs-refactor branch.

This PR is related to #805, #816, #851, #870, #871.

### CODE REVIEW

**Comment by leouieda** [comment]
Thanks, Dongdong!

**Comment by leouieda** [comment]
Hi @seisman sorry for the delay. I'm pushing in some changes I made recently. Please don't merge master or 6.0 branches here since it creates a lot of conflicts that need to be resolved. Or at least give me a heads up :wink:

**Comment by seisman** [comment]
It seems @leouieda is busy and have limited time working on the documentations. Maybe I can take over this branch and commit changes directly, so that we can have the new documentation ready when releasing 6.0.0.

**Comment by PaulWessel** [comment]
I know, but I think we need to give @leouieda a chance to resurface on Monday at the latest.  If nothing by Monday night GMT then you can make changes.

**Comment by seisman** [comment]
👌

**Comment by leouieda** [comment]
Hi guys, sorry for the disappearance. It's ok with me if @seisman takes over this PR. A few things that were left unfinished:

- [ ] Break the tutorial document into several documents. I'm thinking one for each chapter and include them separately in the `index.rst` toc table.
- [ ] Add some text to the front page about GMT, how the docs are laid out and where to start if you don't know anything about GMT.
- [ ] A page explaining modern mode (*Modern mode primer*) for people who know GMT. Could be taken directly from the paper.

**Comment by seisman** [comment]
Although the new documentations still needs more improvements, I think it's OK to replace the old documentations. As we have many files renamed or removed in the new documentations, modifying the old documentations may lead to a lot of conflicts which need to be solved. So I think we can merge it into 6.0 branch ASAP, so that we can improve the documentations efficiently.

You can preview the new documentations by [visit this temporary site](https://seisman.github.io/gmt-docs-preview/).

**Comment by leouieda** [comment]
@seisman great job on this! It looks really good. I agree that this can be merged and worked on in later PRs. The only question I have is about the classic mode tutorial and cookbook links. It's a bit strange to me that they go to the GMT 5 docs. I'd rather not have those toctree items and put a note on the tutorial and cookbook pages points to GMT 5 with some explanation why. Like we did in the Core Modules page. Something like:

> Looking for the classic mode tutorial? Since classic mode commands haven't changed since GMT 5, please visit the [GMT 5 tutorial page](https://docs.generic-mapping-tools.org/5.4/GMT_Tutorial.html) instead.

**Comment by joa-quim** [comment]
Sorry, I've not paid much attention to this. I looks very nice.
I note however that we lost the [GMT -J codes](https://docs.generic-mapping-tools.org/dev/proj_codes_GMT.html).

Also, history is round. we came back to GMT3-4 were modules were resented in thematic categories. I'm sorry to disagree here but I always searched in the alphabetic order.

We should have a GMT ``Core Modules - thematic`` and a ``Core Modules - alphabetic`` entries that users can change as bookmarks depending on their preferences.

**Comment by PaulWessel** [comment]
Hi @seisman and @leouieda - this looks very nice; thank you!  I think this looks good enough to publish for GMT 6.0.0.  I do agree with @joa-quim that having alphabetical access is what you want when you know which module you need to look up instead of hunting for it a bit under the categories, but we can add that as he suggests if we find it really is a problem.  The -J codes page: Seems like that could easily be added under the Reference Documentation heading.  Maybe call it "Projection Specifications" and add it just after common options?

**Comment by seisman** [comment]
I've addressed some of the comments above, and the new documentation is available from https://seisman.github.io/gmt-docs-preview/.

**Comment by seisman** [comment]
The core module list (https://seisman.github.io/gmt-docs-preview/modules.html) has the same problem, because we're using multiple tables for thematic categories. Will see how to fix it later.

**Comment by KristofKoch** [comment]
May I show you a problem I just noticed with the theme @seisman chose:

Screenshot

When using the search function the term searched for becomes highlighted and the word containing the search term becomes separated into two words. This surely will lead to errors when user don't use copy&paste but read the docs and type their own code. `pssolar` ≠ `ps solar`

**Comment by joa-quim** [comment]
Hmm, is it a Mac'ish thing? It doesn't happen to me on Win with both Firefox and Epic. But I'm looking at Dongdong's link page where, BTW, there is no ``pssolar`` reference.

**Comment by seisman** [comment]
The new site is online https://docs.generic-mapping-tools.org/latest/ now. @joa-quim

**Comment by seisman** [comment]
I can reproduce it with Chrome and Safari, and just found a solution. If you think it's a problem, then I can fix it in minutes.

**Comment by PaulWessel** [comment]
Looks like pssolar is missing from classic module list?

**Pull request merged**
