### PR TITLE
Make the gmt_mkdir error messages different

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by seisman** [comment]
This PR should also be merged into 6.0 branch, right?

**Comment by PaulWessel** [comment]
Yes.  It is a bit clumsy to do the two steps (6.0 first, then merge 6.0 into master) and apparently easy to forget...

**Comment by seisman** [comment]
OK. I will pick this commit into 6.0 branch.

**Comment by seisman** [comment]
Done. It's also in 6.0 branch now.

**Comment by leouieda** [comment]
I think I could have a bot do the cherry-picking through Travis. I'll research this a bit next week.

**Comment by joa-quim** [comment]
I did create a branch in 6.0 but somehow when I push it wants to merge directly on master and if I forget to change in the Github page to merge on 6.0, it happens what happened.

**Comment by seisman** [comment]
The default base branch is always the master branch.

**Pull request merged**
