### PR TITLE
Add -R to coast example

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

The coast example in the docs did not work as written. This PR adds -R to the example.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by seisman** [comment]
Isn't it a bug?

**Comment by meghanrjones** [comment]
> Isn't it a bug?

This was not clear to me. I skimmed the docs and did not see any mention of an automatic -R determination happening here except when -M is used as well:

> *If -M is used with -E then -R or the +r modifier to -E are not required as we automatically determine the region given the selected geographic entities.*

This quote from -M mentions a +r modifier to -E, but there's no +r modifier documented for -E.

**Comment by PaulWessel** [comment]
This feature evolved from just -E to being applicable in -R, so I think some man pages may have obsolete language.  That +r modifier is no longer relevant since -R sets region.
However, I think @seisman is right to consider it a bug.  We have the -R available via those codes set with -E so we should not have to split it with -R.  I am flagging it as a bug.

**Comment by seisman** [comment]
Actually, the old command without **-R** works well for me:
```
gmt coast -JM6i -Baf -EGB,IT,FR+gblue+p0.25p,red -EES,PT,GR+gyellow -pdf map
```

**Comment by meghanrjones** [comment]
I'm closing this PR and have opened a bug report (https://github.com/GenericMappingTools/gmt/issues/5314) instead.

**Comment by joa-quim** [comment]
> EDIT: Sorry, it doesn't.

It does for me

**Pull request closed without merging**
