### PR TITLE
Option to use build-release no gdal on the macports

### PR DESCRIPTION
**Pull request by PaulWessel**
This PR adds a check to determine if we do not have **GDAL** installed in **macports** (since they screwed that port up) and instead get that library, include files, and executables from a **homebrew** installation.  This seems to work well except of course the new problem of _otool_ not finding a library:

```
 error:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic:
  can't open file: @rpath/libIlmThread-3_1.30.dylib (No such file or
  directory)

```
Since our script always worked before and now fails with this error I can only assume that there is something stupid somewhere else that is causing this @rpath confusion.  Ideas are welcome, but this PR should be straightforward.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Some googling revealed that the missing library is something graphics related developed by Industrial Light and Magic (George Lucas), hence the **Ilm** tag.  Nothing we have relies on it as far as I can tell, but perhaps **ffmpeg**? I noticed earlier that the library is present in /opt/homebrew but was not in macports until I installed it explicitly.  In either case the library is not found due to the `@rpath `issue above.

**Comment by seisman** [comment]
Can you figure out which package relies on `@rpath/libIlmThread-3_1.30.dylib` by 

> This PR adds a check to determine if we do not have **GDAL** installed in **macports** (since they screwed that port up) and instead get that library, include files, and executables from a **homebrew** installation. This seems to work well except of course the new problem of _otool_ not finding a library:

Both GMT and GDAL rely on netCDF. In this case, GMT may be linked to the netCDF library from MacPorts and GDAL from Homebrew is linked to the Homebrew's netCDF library. Will it make a mess?

**Comment by joa-quim** [comment]
> Both GMT and GDAL rely on netCDF. In this case, GMT may be linked to the netCDF library from MacPorts and GDAL from Homebrew is linked to the Homebrew's netCDF library. Will it make a mess?

Potentially yes. netCDF depends on HDF5 and if they were not build with the **exactly** same HDF5 version, shit will follow.

**Comment by seisman** [comment]
@PaulWessel Can you figure out which package rely on `libIlmThread-3_1.30.dylib` by adding more debug message to your `otoolr.c` code?

**Comment by PaulWessel** [comment]
No package depends on the ILM Threads library.  I agree with the HDF5/netcdf/GDAL issue - my experiment was mostly to see if the ILM was something that only happen when using homebrew, but given it is the same error for this hybrid macports setup there is no need to involve macports provided we can fix the ILM library issues that originates in the Xcode command above.

**Comment by PaulWessel** [comment]
Sorry, take that back.  ligdal depends on it via another library:

gdal:

	`/opt/homebrew/opt/openexr/lib/libOpenEXRUtil-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)`

and that one lists this:

	`@rpath/libIlmThread-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)`

So because **GDAL** depends on the _openexr_ library and it has lovely `rpath` statements we get screwed?

**Comment by PaulWessel** [comment]
I dont understand why some entries have full paths and others just have `@rpath `in the libraries from homebrew:

```
/opt/homebrew/opt/openexr/lib/libOpenEXRUtil-3_1.30.dylib:
	/opt/homebrew/opt/openexr/lib/libOpenEXRUtil-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)
	@rpath/libOpenEXR-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)
	@rpath/libOpenEXRCore-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)
	/opt/homebrew/opt/imath/lib/libImath-3_1.30.dylib (compatibility version 30.0.0, current version 30.0.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	@rpath/libIlmThread-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)
	@rpath/libIex-3_1.30.dylib (compatibility version 30.0.0, current version 30.6.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)

```

**Comment by joa-quim** [comment]
I think the @rpath results from the use of a compiling/linking option and different packages do it differently.

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
