### PR TITLE
Check that a custom shared library given has extension

### PR DESCRIPTION
**Pull request by PaulWessel**
See #7086 for background.  Turns out the documentation is corrrect, and one must end a directory entry with trailing slash.  Alternatively, give the full name (or comma-separated list of full names) to shared libraries.

This PR strengthens the parsing by checking that a non-directory argument in fact ends in the valid extension before trying to open it as a shared library and instead yield an informative error.

### CODE REVIEW

**Review by anbj — COMMENTED** [review]
When defining a directory, I'm still getting;

```
$ gmt set GMT_CUSTOM_LIBS /home/anbj/MB-System/build/lib/
ERROR: Caught signal number 7 (Bus error) at
/lib64/ld-linux-x86-64.so.2(+0x15961)[0x7f8699959961]
[0x0]
Stack backtrace:
/home/anbj/gmt/build/lib/libgmt.so.6(sig_handler_unix+0xc0)[0x7f86994c07f0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13140)[0x7f8699344140]
/lib64/ld-linux-x86-64.so.2(+0x15961)[0x7f8699959961]
/lib/x86_64-linux-gnu/libc.so.6(_dl_catch_exception+0x80)[0x7f8699292b50]
/lib/x86_64-linux-gnu/libc.so.6(_dl_catch_error+0x2f)[0x7f8699292c0f]
/lib/x86_64-linux-gnu/libdl.so.2(+0x1a65)[0x7f8696c9ea65]
/lib/x86_64-linux-gnu/libdl.so.2(dlclose+0x24)[0x7f8696c9e374]
/home/anbj/gmt/build/lib/libgmt.so.6(GMT_Destroy_Session+0xda)[0x7f86993d01aa]
gmt(main+0x487)[0x563224235677]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)[0x7f869917fd0a]
gmt(_start+0x2a)[0x5632242365aa]
```

**Comment by PaulWessel** [comment]
OK, probably because my PR only addresses the lack of checking on paths only.  There was no crash on macOS so Cannot test what is going on.  We need a ddd debug session on Linux to see what is happening I think. Also need a Windows check.

**Review by joa-quim — APPROVED** [review]

**Comment by joa-quim** [comment]
I think that on Windows the only documented way should as is now. **All** shared/supplement dlls must go into the ``bin/gmt_plugins`` dir. We don't want that some *clever* users put things in dirs with spaces or, worse, use accent chars and then come to us saying that *it's not working*.

**Comment by anbj** [comment]
(I have no idea what I'm doing).

Installed `ddd` and compiled with *DCMAKE_BUILD_TYPE=Debug*. This is what I've got:
Screenshot from 2022-11-12 21-32-40


Screenshot from 2022-11-12 21-32-14

**Comment by PaulWessel** [comment]
IT has been some years but I think you start it by giving it the argument of the program, i.e.

`ddd gmt &`

and gmt needs to be built in DEBUG mode.  Sorry, at conference at Sundvolden so no access to any Linux.

**Comment by PaulWessel** [comment]
Maybe this [link](http://www.science.smith.edu/~jfrankli/231f13/231/doc/quickstart.html) can get you going?

**Comment by anbj** [comment]
From Hawaii to Sundvolden, love it!

**Comment by anbj** [comment]
Thanks, I'll see what I can do. Have to start learning C soon...

**Comment by anbj** [comment]
PS! Is what I posted from `ddd` of any help? https://github.com/GenericMappingTools/gmt/pull/7089#issuecomment-1312566702

**Comment by PaulWessel** [comment]
Maybe related to bus factor?

**Comment by PaulWessel** [comment]
@anbj the message only says it crashes at line 193 which is the start of the signal handler.  So only hope is to set a stop point and step in until it crashes and hopefully there is something to be learned at that spot.

**Comment by PaulWessel** [comment]
But apart from that, I think this specific PR can be merged, yes? It only adds more checking and better messaging b ut does not address the (for me) non-reproducible crash.

**Comment by anbj** [comment]
Don’t underestimate the power of public transportation.

**Comment by anbj** [comment]
Yes, just merge it. I’ll try digging for crash if time and ability permits. Thanks Paul.

**Comment by joa-quim** [comment]
In what was not meant as a curse but as premonition, I told Andreas "if you had to debug on Linux ..."

**Comment by anbj** [comment]
I remember @joa-quim. We’ll see..

**Pull request merged**
