### PR TITLE
Final version of updates for 6.5: grdimage, colorbar, grdmix

### PR DESCRIPTION
**Pull request by PaulWessel**
This PR takes over the function of the previous PR (#8241) which now has been absorbed and modified into this cleaner PR.  It also makes further adjustments to the placement and pale dimensions related to the enhanced **-Li**|**I**[_gap_] option in **colorbar**.  I also have added a test for this whose plot looks like this:

interval-panel

You can see the older PR for various new test plots that documents the working of grdmix and grdimage.  I get zero failures with this branch, running with or without OpenMP,  Plesae make sure you change to theimg-layout branch, select static as active server (`export GMT_DATA_SERVER=static`) and run all tests.  If you find any issues under Windows or Linux please let me know.

The **colorbar** docs now states this:

L

I believe this is the last item to be merged into master before we release 6.5.

### CODE REVIEW

**Review by seisman — APPROVED** [review]
Looks good, but need to update the copyright year to 2024 to make the "Code Validator" workflow pass.

**Comment by joa-quim** [comment]
Can we merge this? I need to trig a GMT build in the Julia system.

**Comment by PaulWessel** [comment]
Yep, doing it now.

**Comment by PaulWessel** [comment]
Master is now up to date with all those changes and copyright year is now 2024.
Going to bed but will work on building installers and tar balls tomorrow.

**Comment by joa-quim** [comment]
OK, I'll build the Win installer tonight.

**Comment by anbj** [comment]
> OK, I'll build the Win installer tonight.

Please also remember to do a Windows portable.

**Comment by PaulWessel** [comment]
Just fixed a few warnings and updated master. No big deal if you have started building yet.

**Comment by joa-quim** [comment]
If you want one with 1 or 2 weeks old, I have it here.

**Comment by joa-quim** [comment]
I built these 4 guys. Which one should we publish as 6.5?

```
01/01/2024  11:33 PM       203,678,458 gmt-6.5.0-win64_DOCS_MB.exe
01/01/2024  09:00 PM       189,460,313 gmt-6.5.0-win64_DOCS_NO_MB.exe
01/01/2024  11:04 PM       160,435,361 gmt-6.5.0-win64_NO_DOCS_MB.exe
01/01/2024  09:44 PM       146,217,412 gmt-6.5.0-win64_NO_DOCS_NO_MB.exe
```

**Comment by PaulWessel** [comment]
You can choose what you think is useful for Win users and possibly Julia users.

BTW, I fixed a half-dozen or so of warnings that were annoying me.  Probably no need to rebuild your installers.

**Pull request merged**
