### PR TITLE
Add longoptions support for gmtconvert

### LINKED ISSUE #7952: longoption support for gmtconvert
**Description of the desired feature**
longoption support for gmtconvert

**Are you willing to help implement and maintain this feature?** Yes/No

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**
Add longoptions support for gmtconvert

Python differences:

  No python module found.

Julia differences:

  Changed range (-Z) to transpose.
    The gmtconvert manual page -Z documentation says
    nothing about range.

Fixes #7952

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by joa-quim** [comment]
Thanks for the **-Z** catch. A mistake for sure. As I said in another PR `range` is for those **-T**'s

**Comment by PaulWessel** [comment]
What to do about -T[d][h][selection]? We have two directives that both could be set, e.g. -Tdh,  Dont think we can say --suppress=headers,data, or perhaps we can? If not, we could do a backwards compatible syntax change and turn one or both directives into modifiers +d and +h? Also, selection might be better as columns? Comments, @GenericMappingTools/long-options-review ?

BTW, I merged in 21 commits from master.

**Comment by joa-quim** [comment]
`--suppress=headers,duplicates` looks fine to me.

**Comment by PaulWessel** [comment]
> `--suppress=headers,duplicates` looks fine to me.

Done.

**Comment by PaulWessel** [comment]
@rbdavis please check that I did the short and long directives for -T correctly.

**Review by remkos — CHANGES_REQUESTED** [review]
I would suggest to have --select_number as an alias for --select_num.
Same for --select_header as an alias for --select_hdr

**Comment by PaulWessel** [comment]
> I would suggest to have --select_number as an alias for --select_num. Same for --select_header as an alias for --select_hdr

Agreed and done.

**Review by PaulWessel — APPROVED** [review]

**Review by remkos — APPROVED** [review]

**Comment by joa-quim** [comment]
In that sense, I would even drop the ``--select_num`` (I'll change it GMT.jl too). Regarding ``--select_hdr`` this one I think is fine to keep alongside ``--select_header``. Using `hdr` to mean `header` is a very common practice in coding.

**Comment by PaulWessel** [comment]
OK, so just --select_number then?

**Comment by PaulWessel** [comment]
and the two aliases for headers

**Comment by joa-quim** [comment]
For me, yes

**Comment by PaulWessel** [comment]
Wait a minute. Reading **-Q** and it takes about a series or range of segments that should be written. I think `--segments` is much more to the point.  select_num|select_number is not clear that these are segment numbers.  So `--segments=1,2,11` is much clearer, no?

**Comment by joa-quim** [comment]
Yes, clearer.

**Comment by rbdavis** [comment]
> Dont think we can say --suppress=headers,data, or perhaps we can?

We most definitely can **_NOT_** do this with the current parsing code. (I just tested to confirm.)

I have encountered a substantial number of options in various modules with similar structure, i.e., there are attribute-ish flags (i.e., _NOT_ +_x_ modifier flags) where immediately following the short-option the user may specify more than one such attribute flag in any order such as **gmtselect**'s **-I[cflrsz]** option, e.g.,

`% gmtselect -Ircz`

So, I can certainly see how it would be a nice feature to be able to longoptify such choose-any-or-all-type attributes. However, enhancing the longoption translation code is always an adventure in discovering which of the zillion variations in existing GMT option syntax will be broken by doing so. In this case, anything that currently uses a comma character would be at risk, and in fact the comma already has particular importance for longoption translation as a special separator character between option groups in certain cases.

Paul's suggestion to change such option flag sets to a collection of modifiers, e.g.,

`% gmtselect -I+r+c+x`

which could then be longoptified as

`% gmtselect --invert+rectangle+circle+zrange`

would certainly work, although presumably you would want to both preserve the existing syntax, e.g., **-I[cflrsz]** , as well as add the new modifiers.

**Comment by PaulWessel** [comment]
Ok will give this one more thought

**Comment by PaulWessel** [comment]
This needs the new multi-directive scheme I think?

**Comment by rbdavis** [comment]
Yes.

I will be re-examining all longoptified modules completed so far for
possible application of this new translation feature. Probably amount to
maybe one out of every six to ten?

Workplan for this week, probably starting Wednesday (after all outstanding
longoption string group review PRs are closed):

(1) Modify translation tests to accommodate group review of the last batch
of PRs.

(2) Submit one PR for new bitmask field update of all *_inc.h files for
your review only (no string changes). LMK if you would like me to break
this up into multiple PRs due to the number of *_inc.h files, but
preferably no more than 3 or so?

(3) Revisit already-longoptified modules for multi-directive stuff, with
PRs for group review (new strings).

(4) Resume per-module longoptification as before with group reviews.

Roger

**Pull request merged**
