### PR TITLE
Add script for documentation figure for grdblend

### PR DESCRIPTION
**Pull request by PaulWessel**
The figure produced by this script will be added to the **grdblend** man page.  But first it needs to be added to _dvc_ before referencing it in _grdblend.rst_.  Maybe some guidance by @meghanrjones will be needed.

GMT_blend

### CODE REVIEW

**Comment by meghanrjones** [comment]
Yes, I need to update the instructions in the contributing guide for managing the examples and scripts using dvc. For now, do you mind if I just push the update to this branch?

**Comment by PaulWessel** [comment]
No problem.

**Comment by PaulWessel** [comment]
The figure will need to be recreated after the grdblend region fix we just merged.

**Comment by PaulWessel** [comment]
I added the figure and caption so this PR should be OK (and once dvc is updated with revised plot).

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
