### PR TITLE
Implement the documented -N and update the docs

### LINKED ISSUE #5246: Is grdfill -N option available?
The [grdfill documentation](https://docs.generic-mapping-tools.org/dev/grdfill.html#optional-arguments) lists the **-N***nodata* option, but I don't see it in the synopsis or in the source code.

Please verify if **grdfill** has the **-N** option or not.

### PR DESCRIPTION
**Pull request by PaulWessel**
We advertised **-N** but had not code it up; this PR does that.  Also, we stated that **-As** had not been implemented but it has been for a long time. I have now improved the man page to mention all of this.  Closes #5246 but will not be merged until after 6.2.0 has been released, hence WIP.

### CODE REVIEW

**Comment by meghanrjones** [comment]
The docs state that **-A** is required but grdfill without **-A** passes without warning (see below). Is -A required? If not, what is the default?
```
gmt grdclip @earth_relief_05m -R199:30/206/18/23 -Sa0/NaN -Gislands.nc
gmt grdfill islands.nc -Gnew.nc
```

**Comment by PaulWessel** [comment]
I think **-A** should be required.  It is not obvious that anyone would expect a default method in this module.  So I think we should check for it and complain if not given.  Again, the docs are clear while the grdfill synopsis prints it as optional.  I will fix this herein.

**Comment by PaulWessel** [comment]
I will do it in a separate PR.

**Comment by PaulWessel** [comment]
Hm. So **either** -A or -L are required.  If you use -L then -A is not required.  I think when that happens in other modules we list both -A and -L as optional but state that one must be selected, right?

**Comment by meghanrjones** [comment]
> Hm. So **either** -A or -L are required. If you use -L then -A is not required. I think when that happens in other modules we list both -A and -L as optional but state that one must be selected, right?

Yes and usually break with error if neither are provided.

**Comment by PaulWessel** [comment]
Should be OK here now, @meghanrjones.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
