### PR TITLE
Ensure hoels of polygons have correct handedness

### LINKED ISSUE #3135: Polygon holes filling is tricky
It seems that adding **-Ph** to headers is not enough. It needs that the hole polygon has an orientation contrary to its parent. But that's not all, if origin is not at LowerLeft (for rectangles) wholes are painted too regardless if its orientation.

```
cat << EOF > quads.dat
> -Gred CCW
0  0
5  0
5  10
0  10
0  0
> -Ph  CW
2  1
2  3
4  3
4  1
2  1
> -Ph  CCW
2  4
4  4
4  6
2  6
2  4
> -Ph CCW origin TopLeft
2  9
2  7
4  7
4  9
2  9
> CW -Gblue
5  0
5  10
10 10
10 0
5  0
> -Ph  CW
7  1
7  3
9  3
9  1
7  1
> -Ph  CCW
7  4
9  4
9  6
7  6
7  4
EOF
gmt plot quads.dat -JX12c -Ba2f1WSen -R-0.5/10.5/-0.5/10.5 -Gred -W1p -png map
```
map

### PR DESCRIPTION
**Pull request by PaulWessel**
Do not trust the incoming data.  For polygons with holes that need to be filled, we ensure the holes have a different handedness than the parent, reversing the child if needed.  Closes #3135.

### CODE REVIEW

**Comment by joa-quim** [comment]
OK, this works but there is some other bug from externals that probably is not looking for the **-Ph** option.
This paints the whole in blue
```
> -Gred
0  0
5  0
5  10
0  10
0  0
> -Ph -Gblue
2  1
2  3
4  3
4  1
2  1

D = gmtread("quad.dat");
plot(D, J="X12c", B="a2f1WSen", G=:red, W=1, show=1)
```
 but doe not male it transparent when I remove the **-Gblue** from second segment header.

**Comment by PaulWessel** [comment]
Maybe make a mex version of the test?

**Comment by joa-quim** [comment]
Use your Julia. Life is much easier with it
```
D=gmtmex('read quad.dat -Td');
gmtmex('psxy -JX12c -Ba2f1WSen -W1 -R-0.5/10.5/-0.5/10.5 > lixo.ps', D)
```

**Comment by PaulWessel** [comment]
OK, fine.  I just installed/update julia to 1.3.1.  Followed your macOS hint of addint startup.jl.  Then tried ]add GMT and ERROR unexpected ].

**Comment by PaulWessel** [comment]
Am I completely missing any instructions for actuallly installing GMT.jl?.

**Comment by joa-quim** [comment]
Last version is Julia 1.4 but 1.3 is just as good.
You only have to do
``] add GMT``
When you type the ``]`` the prompt immediately turns into ``pkg``. What is your ` `ERROR unexpected``?

**Comment by PaulWessel** [comment]
Seems like your instructions is missing some critical spaces between ] and add.  Works now.

**Comment by joa-quim** [comment]
Ah, because you copy-pasted?

**Comment by PaulWessel** [comment]
Yes, but also the README.md has no space.

**Comment by PaulWessel** [comment]
Now here:
ia> D = gmtread("quad.dat");
ERROR: UndefVarError: gmtread not defined

**Comment by PaulWessel** [comment]
FYI, the adding package seems to work?

```
v1.3) pkg>  add GMT
   Cloning default registries into `~/.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
     Added registry `General` to `~/.julia/registries/General`
 Resolving package versions...
 Installed GMT ─ v0.17.0
  Updating `~/.julia/environments/v1.3/Project.toml`
  [5752ebe1] + GMT v0.17.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [5752ebe1] + GMT v0.17.0
  [de0858da] + Printf 
  [4ec0a83e] + Unicode 
```

**Comment by joa-quim** [comment]
Ok, you should not need it but better to have the master version
``] add GMT#master``
And more thing, you have to do 
``D = gmtread("/path/to/file"); or do a ``cd("/path/to/file)`` first.
But you say ``gmtread`` is not found? Can't be. Try running the tests
``] test GMT``

**Comment by joa-quim** [comment]
Ah sorry, I know. It's like Python. Before using any package you have to import it. So first command per session has to be
``using GMT``

**Comment by PaulWessel** [comment]
D = gmtread("quad.dat");
ERROR: error compiling gmtread: error compiling #gmtread#60: error compiling gmt: could not load library "libgmt"

I put the startup.jp in config with path to my library dir and restarted.

julia
ERROR: LoadError: UndefVarError: Libdl not defined

**Comment by joa-quim** [comment]
Ok the other user that passed through this had to do
``using Libdl`` before the ``push!(Libdl.DL_LOAD_PATH ...``
I have to update this instructions also

**Comment by PaulWessel** [comment]
I added a call to Libdl in startup.jo before the LIB call.  Same error.
Admittedly I am a Julia rookie so this is a very good test - clearly your  README needs some work.  I would think the average rookie would give up by now.

**Comment by PaulWessel** [comment]
OK, using Libdl works.
Plot generated.

**Comment by joa-quim** [comment]
Good. I debugged to confirm that the header is well transmitted to GMT. And mex version confirms the same thing. No hole.

**Comment by PaulWessel** [comment]
So when I debug MEX I have to load in gmtmex.c (compiled for Xcode) into Xcode, set a stop point, start matlab, connect Xcode to MATLAB processes, then run the matlab command.
What do I load into Xcode to set a stop point for Julia???

**Comment by PaulWessel** [comment]
You may need to add a "how to debug" section.

**Comment by PaulWessel** [comment]
Anyway, in the GMT io we do this:

`if (gmt_parse_segment_item (GMT, S->header, "-Ph", NULL)) SH->pol_mode = GMT_IS_HOLE;
`

so the hidden helper structure per segment sets a flag.  When gmt read returns to mablat it has the info:

```
ans = 

  struct with fields:

       data: [5x2 double]
       text: []
     header: '-Gred'
    comment: []
      proj4: []
        wkt: []

>> D(2)

ans = 

  struct with fields:

       data: [5x2 double]
       text: []
     header: '-Ph'
    comment: []
      proj4: []
        wkt: []

```

What does your Julia D data have?

**Comment by joa-quim** [comment]
Ok, dinner time here (still preparing it).
To debug from Julia you should do exactly the same but load the Julia process in Xcode. There is no equivalent in C to gmtmex so you can't debug that part with Xcode (you need VScode).

In Julia you get the same thing as in Matlab . Have a function for display that only shows first segment. To see more you do

```
julia> D[1]
Header: -Gred
5×2 Array{Float64,2}:
 0.0   0.0
 5.0   0.0
 5.0  10.0
 0.0  10.0
 0.0   0.0


julia> D[2]
Header: -Ph -Gblue
5×2 Array{Float64,2}:
 2.0  1.0
 2.0  3.0
 4.0  3.0
 4.0  1.0
 2.0  1.0
```

**Comment by PaulWessel** [comment]
As far as I can tell, when D is passed back into a matlab gmt call the header is extracted and copied into the GMT segment header so it should work - I just need to rebuild gmtmex here.

**Comment by joa-quim** [comment]
I verified that it is indeed like that from Julia, but -Ph makes no effect (tried with both **-Ph -Gblue** and **-Ph**

**Comment by joa-quim** [comment]
Don't want to try a debug from Julia
1. Load the Julia process in XCode
2. Open a GMT source code in XCode and set a breakpoint
3. run the julia command that triggers that breakpoint

Ofc never tried in Mac but that's what I do on Windows.

**Comment by PaulWessel** [comment]
OK, it makes sense to set stop point in the GMT C in Xcode.  I will see - as you know multi-tasking on this end during the day...

**Comment by joa-quim** [comment]
BTW, I updated the installing instructions so you can give a star to the project.

**Pull request merged**
