### PR TITLE
Ad -F+i option to allow setting ffmpeg options that apply to input only.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by Esteban82** [comment]
I think that there is something missing.

I got these messages:
```
movie [WARNING]: Modifier +i detected but not a valid modifier! - ignored
movie [ERROR]: Option -F: Unrecognized format mp4+i-thread_queue_size 4096
movie [ERROR]: Must select at least one output product (-F, -M
```
I think that this issue (#8327) can help.

**Comment by joa-quim** [comment]
Please try again.

**Comment by Esteban82** [comment]
> Please try again.

Ok, I will try.

**Comment by Esteban82** [comment]
Now it works. @joa-quim do you want me to add something in the [docs](https://docs.generic-mapping-tools.org/dev/movie.html#f) ?

**Review by Esteban82 — APPROVED** [review]

**Pull request merged**
