### PR TITLE
Mgd77list with nans

### PR DESCRIPTION
**Pull request by sarzeaud**
**Description of proposed changes**

Allow mgd77list to write out NaNs for non existing columns.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Hi @seisman, how can I build and test this PR?

**Comment by seisman** [comment]
It would be much easier if you have the [GitHub official CLI](https://github.com/cli/cli) installed.

You can run `sudo port install gh` to install it. Then you may need to run `gh auth login` to login your GitHub account in CLI.

After that, checking out a PR is as easy as to run 
```
gh pr checkout 4614
```

**Comment by PaulWessel** [comment]
Wow, works like magic! Thanks.
-p

**Comment by PaulWessel** [comment]
Hi @sarzeaud, sorry this got ignored for so long.  Might you be able to share a file and a command that shows the new behavior so I can do some testing before we merge this in?

**Comment by joa-quim** [comment]
Shell we close this?

**Pull request closed without merging**
