### PR TITLE
Enable longoptions support for grdbarb.

### PR DESCRIPTION
**Pull request by rbdavis**
**Description of proposed changes**

Python differences:

  No Python module.

Julia differences:

  No Julia module.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Maybe @masahigaki would like to opine if these long-options align with his thinking since he is the author of this module (sam when we get to barb)?

**Review by PaulWessel — APPROVED** [review]
I feel -A goes better with --radial and --cartesian and I am going to edit the use message to use those terms.  Same will be true for grdvector (whose -A usage I will also check).

**Comment by PaulWessel** [comment]
Opps, changed my mind since we use words like polar and cartesian so lets use polar instead of radial since we mean polar versus cartesian coordinates.

**Review by joa-quim — APPROVED** [review]

**Comment by masahigaki** [comment]
Sorry for my delayed response.
Basically I agree with the proposed long options for grdbarb.
I am not so familiar with long options of GMT, but if I may comment, --\*_azimuth seems better than --\*_azimuth"s" for consistency with long options of other subcommands.

**Comment by PaulWessel** [comment]
Thanks for your feedback, @masahigaki. Looking more carefully, since **-A** is the same as in **grdvector** we should have the option for these two modules.  I would pick **--polar** for **-A** since we recently updated the documentation to distinguish between Cartesian [Default] and polar coordinates.  That means we don't overabuse the "azimuth" word.  Now, **-T** can be **--adjust_azimuth** and no plural "s" is indeed needed.

FYI, once we complete all 150 or so modules there will be another review to make sure we stay consistent.  The long-option feature won't be released until GMT 7 I think.

**Pull request merged**
