### PR TITLE
Add full in/out options to *ingrid* and *outgrid*

### PR DESCRIPTION
**Pull request by joa-quim**
But we have a problem. As it stands ``grdconvert`` says we need to state ``=ID`` in order to access to **+s**scale, etc. But that's not what we have in https://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#grid-file-format-specifications where ``=ID``  is optional.

### CODE REVIEW

**Comment by joa-quim** [comment]
But have you read the comments in PR body?

**Comment by PaulWessel** [comment]
Sorry, no... What is the problem other than changing the docs to match reality?

**Comment by joa-quim** [comment]
No problem, but not sure anymore what reality is. I remember that we visited this not long ago and I think we made ``=ID`` optional but it has to be provided when read/write native binary formats, so not so optional.

**Comment by PaulWessel** [comment]
Think it says(?) optional if reading the default netCDF grid format.

**Comment by joa-quim** [comment]
The point is. Should in ``grdconvert`` we remove the part that says ``If =id is set (see below),``?
Although true more most cases, that is a contradiction to saying that ``=ID`` is optional.

**Comment by joa-quim** [comment]
This is clearly out of scope of this (closed) PR but since I started it... The CookBook section is badly incomplete as it misses the ``:diver`` option that is used when saving grids in GeoTiff floats or JPK2.

**Pull request merged**
