### PR TITLE
Ensure that the raster has x and y increasing normally

### PR DESCRIPTION
**Pull request by PaulWessel**
See discussion on the [forum](https://forum.generic-mapping-tools.org/t/malloc-error-with-grdview-using-a-draped-tiff-image/2644/10) for background.  Unless we put in efforts to handle odd cases, we now return with error if x or y are not increasing in the expected directions (left to right, bottom to top),

### CODE REVIEW

**Review by joa-quim — COMMENTED** [review]
Hmm, I don't like this. For example these tests are done only when a -R is set. The other case, read it all, will also be upside down but we'll let it go unnoticed.

**Comment by PaulWessel** [comment]
Hm, yes, makes sense.  Will see what to do.

**Comment by PaulWessel** [comment]
What should I check for? Does the adfGeoTransform reflect the upside down settings? Any other parameters we need to consult instead?

**Comment by joa-quim** [comment]
Wait, I'll work on it.

**Comment by joa-quim** [comment]
Managed to avoid the crashes with logic changes, but the UD flipping is resisting to the presumably smart attempts. Will continue after that sport that we practice by dinner time.

Wat happens at the base is that gdalread expects the y-axes to be **always  positive down** but in this case GDAL returns it a positive up ... and shit follows.

**Comment by PaulWessel** [comment]
OK, will leave in your capable hands, especially after filling up with nutrients.

**Comment by joa-quim** [comment]
Many debugs latter, both of this work
```
gmt grdimage drape.tif  -JX14c/0 -Baf -BWSen -n+a -R0/390.2/-49.825549/49.824651 -png lixo

gmt grdimage drape.tif  -JX14c/0 -Baf -BWSen -n+a -png lixo
```

**Comment by PaulWessel** [comment]
Great, I can run all the tests in a bit but have a zoom happening first.

**Comment by PaulWessel** [comment]
All the tests still pass so if you are happy with this then you can approve, etc.  Going exercises for an hour or so.

**Comment by joa-quim** [comment]
Yes, I,m finished here till next trouble.

**Review by joa-quim — APPROVED** [review]

**Pull request merged**
