### PR TITLE
First-record scanning let trailing text be parsed as number

### PR DESCRIPTION
**Pull request by PaulWessel**
The _gmtio_examine_current_record_ failed to distinguish text from numbers.
In an example, the data record

`0 2 -JX8cd/8c`

ended up giving the (harmless but annoying) warning

`-JX8c/8 not a valid number and may not be decoded properly`

because _gmt_scanf_arg_ was fooled.  This tightens the check.

### CODE REVIEW

**Comment by joa-quim** [comment]
I'm still getting a
```
psrose [WARNING]: 12c/8 not a valid number and may not be decoded properly.
```

**Comment by PaulWessel** [comment]
Ok, which test?

**Comment by joa-quim** [comment]
It's a Julia one.
```
julia> data=[20 5.4 5.4 2.4 1.2; 40 2.2 2.2 0.8 0.7; 60 1.4 1.4 0.7 0.7; 80 1.1 1.1 0.6 0.6; 100 1.2 1.2 0.7 0.7; 120 2.6 2.2 1.2 0.7; 140 8.9 7.6 4.5 0.9; 160 10.6 9.3 5.4 1.1; 180 8.2 6.2 4.2 1.1; 200 4.9 4.1 2.5 1.5; 220 4 3.7 2.2 1.5; 240 3 3 1.7 1.5; 260 2.2 2.2 1.3 1.2; 280 2.1 2.1 1.4 1.3;; 300 2.5 2.5 1.4 1.2; 320 5.5 5.3 2.5 1.2; 340 17.3 15 8.8 1.4; 360 25 14.2 7.5 1.3];

julia> rose(data, yx=[], A=20, R="0/25/0/360", B="xa10g10 ya10g10 +t\"Sector Diagram\"", W=1, G="orange", F=1, D=1, S=4, Vd=1)
        psrose  -R0/25/0/360 -JX12c/8c -Bxa10g10 -Bya10g10 -B+t"Sector -BDiagram" -: -A20 -D1 -F1 -S4 -Gorange -W1 -P -K > C:\TMP\GMTjl_tmp.ps
psrose [WARNING]: 12c/8 not a valid number and may not be decoded properly.
```

BTW, this should be a INFO too, no?
```
julia> G = surface(rand(100,3) * 150, R="0/150/0/150", I=1, Ll=-100, upper=100);
surface [WARNING]: Your upper value is < than max data value.
```

**Comment by joa-quim** [comment]
and this
```
julia> gmtsimplify([0.0 0; 1.1 1.1; 2 2.2; 3.3 3], T="3k", Vd=1);
        gmtsimplify  -T3k
gmtsimplify [WARNING]: gmtsimplify only implemented using Flat-Earth calculations.
```

**Comment by PaulWessel** [comment]
OK, please fix - going on hike.

**Comment by PaulWessel** [comment]
Odd to give differernt height and width for a square (circle) plot.  I will look. psrose was the last module to actually tolerate -J.  It had its own -Sradius forever.  I probably am taking some short-cut and did not anticipate your crazy -J argument.

**Comment by joa-quim** [comment]
That's automatic generated code. Must add a check to make it square by default for roses.

**Comment by PaulWessel** [comment]
OK, now that argument will cause an error on the psrose side (same for psternary)

**Comment by joa-quim** [comment]
Why forbid? If user want to deform just let him do that. And what if a  subplot with rectangular subplots want to plot a rose? A warning is fine here, but erroring is is extreme.

**Comment by joa-quim** [comment]
Even if I use ``-JX12c/0``, the complain is the same
```
julia> rose(data, yx=[], A=20, R="0/25/0/360", B="xa10g10 ya10g10 +t\"Sector Diagram\"", W=1, G="orange", F=1, D=1, S=4, Vd=1, show=1)
        psrose  -R0/25/0/360 -JX12c/0 -Bxa10g10 -Bya10g10 -B+t"Sector -BDiagram" -: -A20 -D1 -F1 -S4 -Gorange -W1 -P -K > C:\TMP\GMTjl_tmp.ps
psrose [WARNING]: 12c/0 not a valid number and may not be decoded properly.
```

**Comment by PaulWessel** [comment]
Please update.

**Comment by joa-quim** [comment]
It gives

        psrose  -R0/25/0/360 -JX12c/8c -Bxa10g10 -Bya10g10 -B+t"Sector -BDiagram" -: -A20 -D1 -F1 -S4 -Gorange -W1 -P -K > C:\TMP\GMTjl_tmp.ps
psrose [ERROR]: Option -J: Must specify -JX<diameter>[<unit>]

**Comment by PaulWessel** [comment]
Even if we allowed -JXa/b we are drawing the rose per polar coordinates using a radial scale.  It makes absolutely no sense to give -JXa/b to prose and psternary.  As for subplots, we are supposed to give a -JX? or -Jx? as the projection.  Not sure if we have a test for this with rose and ternaries so that would be a good test.

**Pull request merged**
