### PR TITLE
Clean up end usage

### PR DESCRIPTION
**Pull request by KristofKoch**
**Description of proposed changes**

Changed formatting of usage message as per #5341.

### CODE REVIEW

**Comment by KristofKoch** [comment]
Uh-oh I think I screwed something up. That first commit b50a0c4 is in the wrong branch. Somehow I managed to put my changes in `src/clear.c` into this pull request. Before making things worse: Could someone with more Git-Fu than me kindly solve that problem?

**Comment by meghanrjones** [comment]
You can undo that commit using:
`git revert b50a0c4cecd6cb917cdfc7f9f4f67e74e34a1e34`

**Comment by KristofKoch** [comment]
> You can undo that commit using:
> `git revert b50a0c4cecd6cb917cdfc7f9f4f67e74e34a1e34`

And then push again? Trying not to make matters worse …

**Comment by meghanrjones** [comment]
> > You can undo that commit using:
> > `git revert b50a0c4cecd6cb917cdfc7f9f4f67e74e34a1e34`
> 
> And then push again? Trying not to make matters worse …

Yes, that command makes a new commit that reverts the old commit, which can then be pushed to your end-usage branch. no problem, I understand wanting to check.

**Comment by KristofKoch** [comment]
Aweseome, @meghanrjones! Thank you for your help and your understanding.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
