### PR TITLE
WIP: Simplify documentation for common options

### LINKED ISSUE #4917: Use a list to improve readability of the -R documentation
**Description of the desired feature**

There are many ways to specify a region, from w/e/s/n via country codes to grid files.  However, in the RST docs the option is all one long paragraph.  I suggest we split it into bulleted sections like the recent -F-box upgrade (#4915).

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This (WIP) PR organizes the documentation for -R to increase readability. It also consolidates some information from the [common option page](https://docs.generic-mapping-tools.org/dev/std-opts.html) and the [cookbook common options](https://docs.generic-mapping-tools.org/dev/cookbook/options.html). 

Fixes #4917 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
There's a lot of redundancy in the text of the various doc/rst/source/explain_-\*\_full.rst_ files and doc/rst/source/cookbook/options.rst. For example, I only noticed a couple small differences for **-B** and much of the information for **-R** was repeated (although organized differently). I think it would be better to consolidate these in the doc/rst/source/explain_-\*\_full.rst_ files and then include those files in the cookbook before going on to provide more examples and images. This is a prototype of that organization for the **-R** option. What do you think of this structure @PaulWessel? Is there a reason to keep the cookbook completely isolated from the other source ReST files? (Note: I haven't completed the documentation in explain_-R_full.rst yet; just wanted to discuss the include structure first).

**Comment by seisman** [comment]
Just a quick comment, `explain_-*_full.rst_` are only included in the gmt manpage (`gmt.rst`). They're useful when we provided documentation in the manpage format in GMT 5.

Now, we no longer provide manpages. Perhaps we should just directly link to the cookbook?

**Comment by meghanrjones** [comment]
> Just a quick comment, `explain_-*_full.rst_` are only included in the gmt manpage (`gmt.rst`). They're useful when we provided documentation in the manpage format in GMT 5.
> 
> Now, we no longer provide manpages. Perhaps we should just directly link to the cookbook?

Yes, I think this would be even better for maintenance and would help reduce the knowledge gap between users who know how essential the cookbook is and users who do not (yet).

**Comment by joa-quim** [comment]
I don't think it's a good idea to link **-R** to the CookBook. The CookBook is a heavy page and we should no assume that all users have beefy computers and very fast internet.

**Comment by meghanrjones** [comment]
> I don't think it's a good idea to link **-R** to the CookBook. The CookBook is a heavy page and we should no assume that all users have beefy computers and very fast internet.

But anyone who is concerned about internet usage can use `gmt docs`. It is also possible to block the images from loading if `gmt docs` for some reason doesn't work, which is the main reason for the cookbook being larger. When I build the docs, gmt.html is 123 KB and cookbook/options.html is 147 KB, so the base versions aren't so different.

**Comment by joa-quim** [comment]
Yes, the CookBook page is heavy because of the images. Imagining a trick to make it faster by not loading them seems unreasonable to me. I believe people use internet dos pages more then ``gmt docs`` (and would bet that many don't even know about it).

**Comment by PaulWessel** [comment]
> we should no assume that all users have beefy computers and very fast internet.

We know that not all users have beefy computers and very fast internet.  However, GMT is funded by the NSF to provide scientific software to US scientists, all of whom do have as beefy computers and fas ast internet as they decide to have.  We cannot let lowest-common-demoninator thinking affect how we design and build GMT.  We are building it for people like ourselves, not for folks with low RAM, dial-up, and rubber bands.  And I am sure @joa-quim could have written this paragraph for me if I had asked him to!

**Comment by joa-quim** [comment]
I would understand this if we had any need/gain to do it. Otherwise, I don't.

**Comment by meghanrjones** [comment]
> I would understand this if we had any need/gain to do it. Otherwise, I don't.

The need is that there are hundreds of lines (at least) of redundant documentation that should not need to be updated independently any time a new feature gets added. While the solution in this PR is an option, it is more convoluted than directly linking to the common options descriptions in the cookbook.

**Comment by seisman** [comment]
> I would understand this if we had any need/gain to do it. Otherwise, I don't.

It also means fewer source files in the `doc/rst/source` directory and may make it easier for new contributors to make changes to documentations.

**Comment by meghanrjones** [comment]
I'm closing this PR and will try out the different ways for consolidating the documentation. First, it is necessary to make sure that there isn't information included in the gmt manpage but not in the cookbook (e.g., #4922 for the -R option).

**Pull request closed without merging**
