### PR TITLE
Add Earth crustal age grid as remote dataset description

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

This PR updates the GMT documentation to list the EarthByte seafloor crustal age grid as a new remote dataset, tiled and ready to go once we release 6.1. I have been in touch with them and Maria Seton will add a 1x1 minute pixel registered original on her Monday (our Sunday).  We could just go ahead with what we have once I have placed the files in the server and tested the remote operations locally.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Preview actually can view those jp2 files.

**Comment by PaulWessel** [comment]
Shit, forgot about this one!  What to do?

**Comment by PaulWessel** [comment]
I guess 6.1 branch as bug/omission.

**Comment by seisman** [comment]
🤦‍♂️After merging it to 6.1 branch, users can still view the dataset from the online documentation, but can't see it on the local documentation.

**Comment by PaulWessel** [comment]
Yes, I could mention this in my news item as well, and say 6.1.1 will fix these glitches.

**Pull request merged**
