### PR TITLE
Ensure colorbar uses -S+y when no -B given but -L is given

### PR DESCRIPTION
**Pull request by PaulWessel**
There was some confusion, as documented in this forum [post](https://forum.generic-mapping-tools.org/t/more-colorbar-user-errors-or-bugs/1983). This PR fixes this issue.  All tests still pass.

### CODE REVIEW

**Comment by Esteban82** [comment]
This is correct, right?

`    gmt colorbar -Cseis_pgv.cpt.txt -DjCM+h -F -Q -S+y"cm/s"`


sample_colorbar_issues

**Comment by Esteban82** [comment]
Now I get this figure. In subplot C there is a problem. 

```
    gmt subplot set # c
    gmt colorbar -Cseis_pgv.cpt.txt -DjCM+h -F -Q -S+y"cm/s"
```

sample_colorbar_issues

**Comment by PaulWessel** [comment]
Yep, same here,  I am in the middle of debugging case d.

**Comment by PaulWessel** [comment]
My latest update fixes d but I still need to fix c - but a workshop starts in 10 minutes.

**Comment by Esteban82** [comment]
I get this now: 

sample_colorbar_issues

**Comment by PaulWessel** [comment]
Now all 4 works for me - same for you @Esteban82 ?

**Comment by Esteban82** [comment]
Now I get this:

sample_colorbar_issues

Is it ready to be approved? Or is something missing?

**Comment by PaulWessel** [comment]
No that is it, I think it is all working now.  Thanks! If you agree, please approve.

**Review by Esteban82 — APPROVED** [review]

**Pull request merged**
