### PR TITLE
Ensure automatic y-range works for log counts and log projections

### PR DESCRIPTION
**Pull request by PaulWessel**
See discussion on the [forum](https://forum.generic-mapping-tools.org/t/histogram-with-y-range-not-specified/1384/8).  The **-R**w/e/0/0 option set to determine the y-range automatically cannot become **-R**w/e/0/n when we are doing logarithmic cases.  In those cases it needs to be 1/n.

### CODE REVIEW

**Review by Esteban82 — APPROVED** [review]

**Comment by PaulWessel** [comment]
I changed it to WIP. Although the latest log10 checks will prevent a crash due to a bad w/e/s/n, the automatic w/e/s/n algorithm assumes linear projections.  If log10 then we should do something better, so will work on that later today.

**Comment by PaulWessel** [comment]
OK, this revision handles logarithmic axes as well as -Z settings involving log and tries to come up with better ranges while having safety valves against getting a log10 (0).  No change in testing.

**Review by meghanrjones — COMMENTED** [review]
The y-range minimum at 1 is problematic in some instances for the log cases of **-Z**. For example, much of the data is cut off in this plot:
```
gmt begin Histo png
gmt histogram @v3206_06.txt -T100 -Jx0.002c/1c -Bxaf -By1 -Gblack -Z3 -R-6000/0/0/0
gmt end show
```

**Comment by PaulWessel** [comment]
Thanks, went overboard here.  It should be 0 not 1 since we do log (1+x) in the bins.  Now that I have added a check for **-J** being log the else case does not have to worry about this any more.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
