### PR TITLE
When clobbering the background we only want to plot land on top

### PR DESCRIPTION
**Pull request by PaulWessel**
See issue #2409 for background.  The **pscoast** code would set _clobber_background_ to true (since both land and ocean fill are selected) but then would initialize _start_direction_ and _stop_direction_ to -1 and +1 and select _level_to_be_painted_ as 0 for both directions.  Not sure how this worked before but clearly it fails catastrophically from time to time, like in #2409.
However, after attempting a fix I get several failures related to **pscoast**:

```
	 77 - GMT_hammer.sh (Failed)
	150 - anim08/anim08.sh (Failed)
	151 - ex01/ex01.sh (Failed)
	169 - ex19/ex19.sh (Failed)
	170 - ex20/ex20.sh (Failed)
	551 - pscoast/pscoast_JA.sh (Failed)
	552 - pscoast/pscoast_JE.sh (Failed)
	554 - pscoast/pscoast_JE3.sh (Failed)
	557 - pscoast/pscoast_JS.sh (Failed)
	629 - pssolar/shading.sh (Failed)
```

However, I cannot actually see any real failures. It seems the new PS are the correct one and the old ones had (due to the above bug) drawn some features twice and there are slightly different polygon renders.  So @seisman and @joa-quim, please run tests and see what you think of the "failures" and if you agree that these are not failures but should be PS updates due to the code fix.

### CODE REVIEW

**Comment by seisman** [comment]
I have one more failure (GMT_TM.sh), but all the new PS seem correct to me.

**Comment by seisman** [comment]
BTW, #144 also reported two -JE failings. The second one is also fixed by this PR.

**Comment by PaulWessel** [comment]
Sorry, I left off GMT_TM.sh - I have that one as well.  Since we flagged failing tests we never see them - I think we may have some with -JE that perhaps now work?

**Comment by seisman** [comment]
Yes, that's possible.

**Comment by PaulWessel** [comment]
pscoast/pseudo.sh is the only coastline test flagged with GMT_KNOWN_FAILURE. Would you know how I might run those tests without editing all the tests and (temporarily) removing that tag?  I will do it manually for pseudo for now.

**Comment by seisman** [comment]
I think you can edit the file `test/gmtest.in`, and always set `known2fail` to 0.

**Comment by PaulWessel** [comment]
No, pseudo.ps has other issues not related to pscoast but to **-p** and positioning.
As for this PR perhaps we will wait for @joa-quim to run tests as well and see if he agrees with us that the new PS is the correct one - I can them add those to the PR.

**Comment by joa-quim** [comment]
Curious. Common failing tests I have only

```
        150 - anim08/anim08.sh (Failed)
        551 - pscoast/pscoast_JA.sh (Failed)
        552 - pscoast/pscoast_JE.sh (Failed)
```
I still have several failures like. Don't get it why the same does not happen on CI
```
psxy [ERROR]: Could not find custom symbol C:C:/programs/WinGit/progs_cygw/GMTdev/gmt5/master/test/psxy/comet
```

Regarding the failures, 551 & 552 differ only on the rim (a very thin purple line), so the new PS as as good as the previous. 150 differs in the rim and in some islands. Strange but again, as good as the old one.

**Comment by PaulWessel** [comment]
OK, given that this is clearly a bug in pscoast I think it is reasonable to update the PS following that change.  I will compute the new PS and add to this PR and then ask for your reviews.

**Comment by PaulWessel** [comment]
OK, PS files updated, please approve this PR, @joa-quim or @seisman.

**Pull request merged**
