### PR TITLE
Fix colorbar -Zwidths problems

### PR DESCRIPTION
**Pull request by PaulWessel**
**Description of proposed changes**

See this forum [post](https://forum.generic-mapping-tools.org/t/colorbar-with-zzfile/1982) for background.  There were several problems:

1. The option failed to read the file due to an incorrect GMT_Read_Data call sequence.
2. It did not handle any dimension units appended to the widths.
3. It did not scale the sum of the absolute or relative widths to match the prescribed bar length.

These have been fixed and a test script has been added to the test suite.

### CODE REVIEW

**Comment by PaulWessel** [comment]
With @meghanrjones busy with upcoming workshop, might @joa-quim or @Esteban82 have time to give this a check so that I can move on to the second problem reported for colorbar?

**Comment by Esteban82** [comment]
@PaulWessel do you need me to test the following commands?
```

awk '{print (log($3)-log($1))/log(10)}' seis_pgv.cpt.txt > widths.txt
gmt begin sample_colorbar_Z png
  gmt colorbar -Cseis_pgv.cpt -DJCB+h -R0/1/0/1 -Zwidths.txt 
gmt end show

```

**Comment by Esteban82** [comment]
I get this figure. 


sample_colorbar_Z

Script tested: 

```
gmt begin sample_colorbar_Z png
  gmt colorbar -Cseis_pgv.cpt -DJCB+h -R0/1/0/1 -Zwidths.txt 
gmt end show
```
Files used: widths.txt and seis_pgv.cpt (I removed the trailing ".txt") from the post of the forum. 

So, If a tested the correct issue I think it is fixed. Let me know.

**Comment by Esteban82** [comment]
I also try the test you add it and get the same result.

**Review by Esteban82 — APPROVED** [review]

**Pull request merged**
