### PR TITLE
Fix lack of abs() in scale_down parameter in psscale

### PR DESCRIPTION
**Pull request by PaulWessel**
Somehow I forgot that a color bar can be given with _negative_ length to reverse the positive direction.  The new scale_down variable that adjusts annotation font size and other bar parameters involves taking sqrt of the ratio of two dimensions. One of them was in the form of `MAX (a, b) `and `a` was negative, so it picked the bar width` b` and we got tiny fonts.

This PR does the `fabs()` and revises the wrong PostScript original GMT_App_M_2.ps.

### CODE REVIEW

**Review by joa-quim — APPROVED** [review]

**Comment by seisman** [comment]
@PaulWessel Did you forget to run `dvc push` when working on this PR?

**Comment by PaulWessel** [comment]
It is possible, what do you see?

**Comment by seisman** [comment]
The CI fails with errors like:
```
A       test/baseline/nearneighbor/
A       test/baseline/grdvolume/
A       test/baseline/psmask/
A       test/baseline/psevents/
A       test/baseline/grdpaste/
A       doc/examples/images/
93 files added and 979 files fetched
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
doc/scripts/images
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

I think it means the new baseline images in the `doc/scripts/images` directory were not pushed to the remote. 

Could you please run `dvc push` on your computer?

**Comment by PaulWessel** [comment]
Done, said 2 files pushed.

**Comment by PaulWessel** [comment]
I will run all tests now.

**Comment by PaulWessel** [comment]
MacOS gives 64 failures, in different categories:

1. Most are grdimage/contour of earth_relief that have changed over time.
2. Bunch of colorers are now different
3. LOng-standing bugs yielding failures.

horsclpanel_diff

**Comment by seisman** [comment]
> Done, said 2 files pushed.

The CI now can get the baseline images correctly.

**Comment by PaulWessel** [comment]
I also have a few font(?) issues.  Do you get this for GMT_Defaults_1c?

GMT_Defaults_1c_diff

**Comment by seisman** [comment]
Yes, I have the same failure on Linux with gs 10.02.0

**Comment by PaulWessel** [comment]
Worse, some of teh PS files in DVC are wrong. potential/growth_c and others fail for me, but that is because the original says this (see CPT):

growth_c

**Comment by PaulWessel** [comment]
My dvc pull says everything is up to date so you must have the same bad PS files too?

**Comment by seisman** [comment]
> My dvc pull says everything is up to date so you must have the same bad PS files too?

Yes.

> potential/growth_c

From the git history, I can see that the last change of the `potential/growth_c.ps` baseline image was done in PR #6802, in which you scale the colorbar annotations with colorbar length. But the colorbar in `potential/growth_c.ps` has a negative length, so the baseline image is wrong and should be updated in this PR.

But it seems you only update the baseline images in doc/scripts directory and didn't update any baseline images in tests.

**Comment by PaulWessel** [comment]
I have updated 9 PS files and now down to 55 failures

**Comment by joa-quim** [comment]
I don't understand nothing of our failing tests. I', down to 21 but for example ``equalarea`` fails because
image

or `contours` because
image

This has to be due to un-updated PSs

**Comment by PaulWessel** [comment]
Those changed in the last few hours.  Please do `dvc pull` to get the latest.

**Comment by PaulWessel** [comment]
Note there are still some (including the equlization) who fails due to the grid differences.

**Comment by PaulWessel** [comment]
Also refresh master as well

**Comment by joa-quim** [comment]
All six of these fail because of similar issues with the colorbar bar. None because of a different grid
```
        354 - test/grd2cpt/equalarea.sh (Failed)
        373 - test/grdcontour/contours.sh (Failed)
        424 - test/grdfilter/openmp.sh (Failed)
        426 - test/grdfilter/threads.sh (Failed)
        445 - test/grdimage/grdcyclic.sh (Failed)
        448 - test/grdimage/grdread.sh (Failed)
        527 - test/grdvector/met_uv.sh (Failed)
```
and the ``met_uv.sh`` fails although it has a ``# GMT_KNOWN_FAILURE_WINDOWS``

**Comment by joa-quim** [comment]
This is even more obvious.
image

**Comment by PaulWessel** [comment]
Well, when I run those scripts I get grid image mismatches that dominates the failure. This must either be

1. M1 round off, using the -no-fast-math compiler switched helped but I think there is more here
2. You are running different @earth_relief files.  Can you do a ls -l on one of them and see what you get?

**Comment by PaulWessel** [comment]
Looks like your dvc files are not up to date.  Here is my full cyclic diff:

grdcyclic_diff

I can of course update the PS since mine looks great, but then I think you will get the grdimage failure

**Comment by joa-quim** [comment]
I just did a ``dvc pull`` before running the tests. Different chips can not explain the differences. There are IEEE rules for floating point calculation and chips have to produce de same result. Also, fast-math should never be a default.

**Comment by PaulWessel** [comment]
Could you send me the grid resulting from

`gmt grdcut -R0/10/0/10 @earth_relief_05m_p -Gafr_topo.grd`

and I will compare.  Something is odd here.

**Comment by joa-quim** [comment]
This fails because of the symbols transparency is different from when the *orig* was created. No grids involved
events_diff

**Comment by PaulWessel** [comment]
That one was updated < 30 minutes ago and now passes?

**Comment by joa-quim** [comment]
> gmt grdcut -R0/10/0/10 @earth_relief_05m_p -Gafr_topo.grd

[afr_topo.grd.zip](https://github.com/GenericMappingTools/gmt/files/12684080/afr_topo.grd.zip)

**Comment by PaulWessel** [comment]
Same with the other prevents test.

**Comment by joa-quim** [comment]
Well, it says is very *feshy*
```
C:\progs_cygw\GMTdev\gmt5\master>dvc pull
Everything is up to date.
```

**Comment by PaulWessel** [comment]
Maybe my issue with different grids having been written to .gmt. After deleting the 05m_p dir and rerun I get you grid.  So I will delete earth_relief and rerun tests.

**Comment by joa-quim** [comment]
```
$ ls -l ~/.gmt/server/earth/earth_relief/earth_relief_05m_p
total 11732
-rw-r--r-- 1 j 197121 5952748 Aug 17 14:11 S90E000.earth_relief_05m_p.nc
-rw-r--r-- 1 j 197121 6057780 Aug 17 14:09 S90W180.earth_relief_05m_p.nc
```

An important question is is "What is this test testing"? If it's only the cyclic cpt it shouldn't involve any grid.

**Comment by PaulWessel** [comment]
Yes, for this case sure, but do you feel like editing hundreds of scripts to make it so?

First, we need to get the tests to run from the static.generic-mapping-tools.org service with the idea that those files should not change.  Working on it.

**Comment by joa-quim** [comment]
I just though. If we invent a synthetic Earth we could cut it pieces to use in tests and no need for the static thing.

**Comment by PaulWessel** [comment]
@Esteban82, the oceania server has a gmt_data_server.txt file that lists the new planets.  Did you or I update it by mistake? Says updated Sept 20 (yesterday).  Oh, I see the cronjob copies information/gmt_data_server.txt into oceania etc. But that cron script is outdated; we do not store that in git anymore.  There are no planet data on oceania, only candidate, yet the text file lists all of them.  I will work on that.

**Comment by PaulWessel** [comment]
> I just though. If we invent a synthetic Earth we could cut it pieces to use in tests and no need for the static thing.

If we create GMT_world_topo_15s.nc and tile it we will need to update hundreds of PostScript plots and scripts.  I'm not ready for that for sure.  
I do not understand why my grdcyclic test fails now that we both use the same grid. So your full image looks OK and just the color bars?

**Comment by joa-quim** [comment]
Yes, colorbars are the source of almost all failures I see. That and the events transparency.

**Comment by Esteban82** [comment]
> @Esteban82, the oceania server has a gmt_data_server.txt file that lists the new planets. Did you or I update it by mistake? Says updated Sept 20 (yesterday). Oh, I see the cronjob copies information/gmt_data_server.txt into oceania etc. But that cron script is outdated; we do not store that in git anymore. There are no planet data on oceania, only candidate, yet the text file lists all of them. I will work on that.

No, I didn't touch that file. It must have been the cronjob.

**Comment by PaulWessel** [comment]
Could you try this for me: copy your

-rw-r--r-- 1 j 197121 5952748 Aug 17 14:11 S90E000.earth_relief_05m_p.nc
-rw-r--r-- 1 j 197121 6057780 Aug 17 14:09 S90W180.earth_relief_05m_p.nc

somewhere to safe, then delete those two files from your .gmt dir, then cd to your build dir and try test -R grdcyclic.  Still passes after downloading the grids (are they coming from oceania or Europe?)

**Comment by Esteban82** [comment]
> Could you try this for me: copy your

Are you asking me or joaquim?

**Comment by PaulWessel** [comment]
> > Could you try this for me: copy your
> 
> Are you asking me or joaquim?

Sorry, that was for Joaquim.  And I was a bit hasty declaring the files are the same:

```
gmt grdmath afr_topo_jl.grd afr_topo.grd SUB = d.grd
d.grd: v_min: -176.5 v_max: 132 name: z
```

Because here are the updated min/max after I wiped my earth_relief and got fresh from _oceania_:

```
afr_topo_jl.grd: v_min: -5087 v_max: 2769.5 name: z
afr_topo.grd: v_min: -5071 v_max: 2769.5 name: z
```

So we use different data and hence mine (more recent) differ and the test fails miserably. oceania has the same as candidate [Idid both]

**Comment by PaulWessel** [comment]
And of course it makes sense that the differences only involve the oceans (new SRTM15s data).

**Comment by joa-quim** [comment]
Doing that now the tests fails just like yours (grid's is !=)

**Pull request merged**
