### PR TITLE
Prevent grdcut -D from downloading files

### PR DESCRIPTION
**Pull request by PaulWessel**
When **grdcut -D** is used there is no need to actually access the file that is determined to be the suitable resolution since we just are reporting information.  Closing #5809.

### CODE REVIEW

**Comment by meghanrjones** [comment]
I still get the download notice after building this branch on Linux.

**Comment by PaulWessel** [comment]
OK, will trace in debug

**Comment by PaulWessel** [comment]
Please double-check.  I get no download and I explicitly turn it off in the parse and delete the file name as well.

**Comment by PaulWessel** [comment]
Here is what I get with master:

```
rm -rf ~/.gmt/server/earth/earth_age/earth_age_01m_g
gmt grdcut @earth_age    -Rg -JG15/20/2500/0/0/0/30/30/15c -D -V
grdcut [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]
grdcut [NOTICE]: Earth Seafloor Crustal Age (GTS12 timescale) at 1x1 arc minutes from EarthByte [Seton et al., 2020].
grdcut [NOTICE]:   -> Download grid file [188M]: earth_age_01m_g/
```

while this is what I get with this branch:

```
rm -rf ~/.gmt/server/earth/earth_age/earth_age_01m_g
pwessel@MacAttack-> gmt grdcut @earth_age    -Rg -JG15/20/2500/0/0/0/30/30/15c -D -V
8.23333333333	21.7666666667	13.7833333333	26.0166666667	0.0166666666667	0.0166666666667
```

**Comment by meghanrjones** [comment]
> Please double-check. I get no download and I explicitly turn it off in the parse and delete the file name as well.

I double checked. Here is the script:

```
#!/usr/bin/env bash
gmt --version
gmt grdcut @earth_day -Rg -JG15/20/2500/0/0/0/30/30/15c -D -V
```

and the output:

```
6.3.0_c1c869c_2021.09.27
gmt [INFORMATION]: Spherical approximation used
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.237099959360917/21.76290004063909/13.79659000492764/26.00827117141064.
gmt [INFORMATION]: Map scale is 86.273 km per cm or 1:8.6273e+06.
gmt [INFORMATION]: Given -Rg -JG15/20/2500/0/0/0/30/30/15c, representative distances D_g = 17.6048 degrees, D_m = 21.2132 cm and dpu = 300i (this_n_per_degree = 142.319) we replace @earth_day by @earth_day_30s_p
grdcut [INFORMATION]: Processing input grid
grdcut [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdcut [NOTICE]: Earth Daytime Image at 30x30 arc seconds [NASA image mosaic - Blue Marble].
grdcut [NOTICE]:   -> Download grid file [219M]: earth_day_30s_p.tif
grdcut [INFORMATION]: Downloading file http://oceania.generic-mapping-tools.org/server/earth/earth_day/earth_day_30s_p.tif ...
```

Note that I have never received a download notice on macOS. This is on ubuntu 20.04. Let me know if you want me to try to debug on linux.

**Comment by PaulWessel** [comment]
Yes please do if you can.  I am looking at the sentinel situation.

**Comment by PaulWessel** [comment]
Hm, I did not notice you switched from earth_age (a grid) in the first example to earth_day (an image).  I do get the same as you for the image but the age grid is not downloading.  Please check that - I will debug now that I can reproduce it.

**Comment by meghanrjones** [comment]
> Hm, I did not notice you switched from earth_age (a grid) in the first example to earth_day (an image). I do get the same as you for the image but the age grid is not downloading. Please check that - I will debug now that I can reproduce it.

You are right, I no longer get the download notice with earth_age.

**Comment by PaulWessel** [comment]
Give this version a spin - should fix things.

**Comment by Esteban82** [comment]
When I run` gmt grdcut @earth_age    -Rg -JG15/20/2500/0/0/0/30/30/15c -D -V` and with earth_day I get:


```
gmt [INFORMATION]: Spherical approximation used
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.237099959360917/21.76290004063909/13.79659000492764/26.00827117141064.
gmt [INFORMATION]: Map scale is 86.273 km per cm or 1:8.6273e+06.
gmt [INFORMATION]: Given -Rg -JG15/20/2500/0/0/0/30/30/15c, representative distances D_g = 17.6048 degrees, D_m = 21.2132 cm and dpu = 300i (this_n_per_degree = 142.319) we replace @earth_age by @earth_age_01m_g
gmt [INFORMATION]: Spherical approximation used
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.237099959360917/21.76290004063909/13.79659000492764/26.00827117141064.
gmt [INFORMATION]: Map scale is 86.273 km per cm or 1:8.6273e+06.
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.337099959360916/21.66290004063908/13.89659000492764/25.90827117141064.
gmt [INFORMATION]: Extracted grid region will be 8.33333/21.6667/13.8833/25.9167 for increments 01m/01m
gmt [INFORMATION]: Writing Data Table to Standard Output stream
8.33333	21.66667	13.88333	25.91667	0.01667	0.01667
```

and with `earth_day` I get:



```
gmt [INFORMATION]: Spherical approximation used
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.237099959360917/21.76290004063909/13.79659000492764/26.00827117141064.
gmt [INFORMATION]: Map scale is 86.273 km per cm or 1:8.6273e+06.
gmt [INFORMATION]: Given -Rg -JG15/20/2500/0/0/0/30/30/15c, representative distances D_g = 17.6048 degrees, D_m = 21.2132 cm and dpu = 300i (this_n_per_degree = 142.319) we replace @earth_day by @earth_day_30s_p
gmt [INFORMATION]: Spherical approximation used
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.237099959360917/21.76290004063909/13.79659000492764/26.00827117141064.
gmt [INFORMATION]: Map scale is 86.273 km per cm or 1:8.6273e+06.
gmt [INFORMATION]: A point's inside/outside status w.r.t. polygon(s) will be determined using a spherical algorithm.
gmt [INFORMATION]: gmt_map_setup perimeter search region: 8.337099959360916/21.66290004063908/13.89659000492764/25.90827117141064.
gmt [INFORMATION]: Extracted grid region will be 8.33333/21.6667/13.8917/25.9083 for increments 30s/30s
gmt [INFORMATION]: Writing Data Table to Standard Output stream
8.33333	21.66667	13.89167	25.90833	0.00833	0.00833

```

**Comment by Esteban82** [comment]
If a run autores.sh, the file `fail` should be empty? 
I got this: 

```
0a1,2
> 8.23333	21.76667	13.79583	26.00833	0.00417	0.00417
> 8.23333	21.76667	13.78333	26.01667	0.01667	0.01667
```

**Comment by PaulWessel** [comment]
> Are these ok?

That is the same as I get,

**Comment by PaulWessel** [comment]
> f a run autores.sh, the file `fail` should be empty?
> I got this:
> 
> ```
> 0a1,2
> > 8.23333	21.76667	13.79583	26.00833	0.00417	0.00417
> > 8.23333	21.76667	13.78333	26.01667	0.01667	0.01667
> ```

I get no errors on autores.sh in this branch.  My output file is

```
8.33333	21.66667	13.89583	25.90833	0.00417	0.00417
8.33333	21.66667	13.88333	25.91667	0.01667	0.01667
8.33333	21.66667	13.89583	25.90833	0.00417	0.00417
8.33333	21.66667	13.89167	25.90833	0.00833	0.00833
8.33333	21.66667	13.89167	25.90833	0.00833	0.00833
```

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
