### PR TITLE
Update gmtsimplify.rst

### PR DESCRIPTION
**Pull request by Esteban82**
I add ` to fix the wikipedia link.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]

**Comment by PaulWessel** [comment]
You should have the power to  lick the red box and squash and merge since that failure is unrelated.

**Comment by joa-quim** [comment]
It has been failing consistently
```
D:\a\gmt\gmt\src\gmt_support.c(6338) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
```

**Comment by PaulWessel** [comment]
And staring at that section in gmt_support.c shows nothing I can find that looks odd.

**Comment by Esteban82** [comment]
> You should have the power to lick the red box and squash and merge since that failure is unrelated.

I think I can't. In other cases I saw that it is possible but not in this case.

**Comment by PaulWessel** [comment]
OK, merged.  Not sure why it varies.

**Pull request merged**
