### PR TITLE
Bump sphinx_rtd_theme to from v0.5.1 to v1.0.0

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR bumps [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme) from 0.5.1 to 1.0.0. Locally, this seems to fix https://github.com/GenericMappingTools/gmt/issues/5211 and https://github.com/GenericMappingTools/gmt/issues/5282.

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Blind review, trust that it worked for you.

**Comment by meghanrjones** [comment]
> Blind review, trust that it worked for you.

If you don't mind, it would actually be helpful if you test that https://github.com/GenericMappingTools/gmt/issues/5282 is resolved for you on your arm64 system so we know the docs will look better in the next bundle.

**Comment by PaulWessel** [comment]
OK, give me some time.  At UH but did bring my M1 laptop. Stay tuned.

**Comment by PaulWessel** [comment]
The spacing looks fine to me.  However, I noticed that on the **modules** page the light blue background that used to only be present for the initial Note 1-line message now extends all the way to the end of the pages, to the Previous/Next buttons, i.e., the entire page has light blue background. That is probably not expected?

**Comment by meghanrjones** [comment]
> The spacing looks fine to me. However, I noticed that on the **modules** page the light blue background that used to only be present for the initial Note 1-line message now extends all the way to the end of the pages, to the Previous/Next buttons, i.e., the entire page has light blue background. That is probably not expected?

Can you post a picture? This is what I get (only see blue within the note):

image

**Comment by PaulWessel** [comment]
bad

**Comment by meghanrjones** [comment]
What is your sphinx and docutils version?

**Comment by PaulWessel** [comment]
py-docutils @0.18_1 (python, textproc)
py-sphinx @4.3.0 (python, textproc, devel)
sphinx @2.2.11_1 (textproc, net)

Active python is 3.9.1

**Comment by meghanrjones** [comment]
If you get a chance, could you please check if the latest changes make a difference?

Based on issues in the sphinx and sphinx_rtd_theme repositories, both have made efforts to make the packages compatible with docutils v0.17. So, this PR should fix those issues. But now, docutils v0.18 is out and there are more incompatibilities with sphinx. We may be running into some of those. If these formatting adjustments don't help, I'm not sure what can be done apart from building the bundles in a virtual environment with an older docutils than the latest available from MacPorts.

**Comment by PaulWessel** [comment]
OK, will in a bit.

**Comment by PaulWessel** [comment]
No change.  But if this is a M1 issue we will build on Intel anyway right?

**Comment by meghanrjones** [comment]
> No change. But if this is a M1 issue we will build on Intel anyway right?

For the last release, we did an Intel bundle and M1 bundle. Is the plan different for this release?

**Comment by PaulWessel** [comment]
No, I guess we will do both, and the M1 one will be a bit bluer but that is not big deal - presumably it will go away in the future.

**Pull request merged**
