### PR TITLE
Do not free the PROJ4 pointers at levels > 1.

### PR DESCRIPTION
**Pull request by joa-quim**
With nested calls, as for example pscoast -E, if projections are done with PROJ4 we need those pointers alive when plotting the grid lines that happens only at the end.

### CODE REVIEW

**Comment by anbj** [comment]
Don't know how to test this.

**Comment by anbj** [comment]
I get

``
$ gmt coast -ECA+p0.2 -R-122.913612/36.214964/-9.977657/62.430681+r -J+proj=lcc+lat_0=0+lon_0=-95+lat_1=49+lat_2=77+width=15c/0 -Bpa10g10 -png lixo
ERROR 1: Point outside of projection domain
ERROR 1: Point outside of projection domain
``

But plot is made and looks good.

**Comment by joa-quim** [comment]
But you get that with the `no-free-proj4-at-higher-levels` branch, not `master`, right?

**Comment by anbj** [comment]
Yes, sorry. I get this with ``no-free-proj4-at-higher-levels``. In master there was alot of other stuff output.

**Comment by joa-quim** [comment]
So that means the fix worked for this case (I have no other to test).

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: anbj ***@***.***>
Enviado: Monday, March 4, 2024 2:22:20 PM
Para: GenericMappingTools/gmt ***@***.***>
Cc: Joaquim Manuel Freire Luís ***@***.***>; State change ***@***.***>
Assunto: Re: [GenericMappingTools/gmt] Do not free the PROJ4 pointers at levels > 1. (PR #8390)


Yes, sorry. I get this with no-free-proj4-at-higher-levels.

**Pull request merged**
