### PR TITLE
Update grdgdal usage message

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

Per https://github.com/GenericMappingTools/gmt/issues/5341

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Question for -A: Is the brackets correct here? I.e., both +m and +c must be given or neither?

**Comment by meghanrjones** [comment]
> Question for -A: Is the brackets correct here? I.e., both +m and +c must be given or neither?

From the gdal docs, it seems `+c<cpt_name>` is needed when `+m<method>` is color-relief (unless there's a default cpt, not clear on this). So I suppose it should be `-A<prog>[+m<method>[+c<cpt_name>]]`.

**Comment by PaulWessel** [comment]
Yes, I agree. @joa-quim ?

**Comment by joa-quim** [comment]
Yes, trusting in docs ...

**Pull request merged**
