### PR TITLE
Fix API case for external data passed as vectors

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR adds a version of the bug report from https://github.com/GenericMappingTools/pygmt/issues/1691 to the C API tests. Currently crashes.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
@PaulWessel, I found that this test uses GMT_IS_REFERENCE and crashes as-is but passes if I modify `y` to be `GMT_UINT` (similar to https://github.com/GenericMappingTools/pygmt/issues/1691). Do you think you could use this to debug the issues related to https://github.com/GenericMappingTools/gmt/pull/5953, to circumvent the issues with conda on M1?

**Comment by PaulWessel** [comment]
Yes possibly, I will give it a check tomorrow morning.

**Comment by meghanrjones** [comment]
> Yes possibly, I will give it a check tomorrow morning.

Thanks

**Comment by PaulWessel** [comment]
I had a conceptual error in my thinking when it came to data sets being passed in via vectors and GMT_IS_REFERENCE:  Since we are creating a DATASET container for the input and we set its pointers to the external arrays, we do not need to consult which columns were allocated externally or internally since all of them shall be treated as external so that when the module (here psxy) finishes it does not attempt to free any of them (even one that was allocated by GMT in main) since it will be freed at that level instead.

**Comment by meghanrjones** [comment]
> See if this also fixes the original pyGMT issue, @meghanrjones . That crash is gone for me.

Yes, the PyGMT issue is fixes. Thanks. I will need your approval on the PR before merging.

**Review by PaulWessel — APPROVED** [review]
Oops

**Pull request merged**
