### PR TITLE
Do not let go a -E<non-DCW code> and -M or -R. It would crash.

### LINKED ISSUE #7484: pscoast -E<valid-code-but-not-DCW> crashes
This is worst than the example recently brought by Andreas (pscoast -Ejunk). I made this mistake of passing a non DCW code and it crashed.

```
gmt pscoast -EEUR+p0.5 -REUR -JD28.213/52.993/40.865633333333335/77.24743333333333/15c -Baf -BWSen -P -K > lixo.ps
```

### PR DESCRIPTION
**Pull request by joa-quim**
Fixes #7484

### CODE REVIEW

**Comment by joa-quim** [comment]
Maybe @Esteban82 could give this a more extensive testing.

**Review by Esteban82 — APPROVED** [review]
I got this message with

`gmt pscoast -EEUR+p0.5 -REUR -JD28.213/52.993/40.865633333333335/77.24743333333333/15c -Baf -BWSen -P -K > lixo.ps`

`coast [ERROR]: Passing other than DCW codes to option -E together with -M or -R options is not possible.`

**Comment by joa-quim** [comment]
Yes, that one I know it works. I just don't want to block any valid requests too.

**Comment by Esteban82** [comment]
Great. Should we squash and merge?

**Comment by anbj** [comment]
This causes custom codes from ``dcw.conf`` to fail;

This works:
```
$ gmt pscoast -Enato -pdf test
-R4.650158/31.138197/57.966579/71.18811
```

This gives an error. I would expect a plot with all countries in the 'nato' code to plot as red polygons. And I'm not using ``-E`` together with ``-M`` or `-R``:
 
```
$ gmt pscoast -Enato+gred -pdf test
coast [ERROR]: Passing other than DCW codes to option -E together with -M or -R options is not possible.
```

**Comment by joa-quim** [comment]
But that didn't work before either
```
j@dell-from-hell:~$ gmt pscoast -Enato+gred -pdf test
coast [WARNING]: No country code matching nato (skipped)
psconvert [ERROR]: Unable to decode BoundingBox file /home/j/.gmt/sessions/gmt_session.10/psconvert_42c.bb (maybe no non-white features were plotted?)
```

**Comment by joa-quim** [comment]
Right, I still can do this in WSL that uses an older GMT version
```
gmt coast -EUN021+gred -RUN021 -png lixo
```

What we can't do is
```
gmt pscoast -Enato -pdf test
```

because that's a modern mode command and in modern mode there is no such a thing as **pscoast**. No error about this was issued though.

But in summary, my change restricted what can be used and that's not good. So I need another condition that allows me to distinguish the DCW based regions from those that are purely set by a **-R**. These latter are the ones that we cannot let go into pscoast because they Kaboom it.

**Comment by joa-quim** [comment]
BTW, is there any recommended way of creating custom regions? Do we have to edit the ``dcw-countries.txt`` file or anything else that is seek too?

**Comment by anbj** [comment]
See [coast docs](https://docs.generic-mapping-tools.org/dev/coast.html#dcw-collections). Create a ``~/gmt/dcw.conf`` and populate it with custom codes, like

```
# ~/.gmt/dcw.conf
# Arbitrary comments and blank lines anywhere

# The France-Italian union (2042-45) of gallery example 34.
tag: FRIT Franco-Italian Union
list: FR,IT
# Stay away from those dangerous eels!
tag: SARG Sargasso Sea
region: 70W/40W/20N/35N
```

**Comment by anbj** [comment]
Why can't -E be used with -R or -M? I don't understand.

What about a ``strcmp('list'); then good to go; else no-go``?

**Comment by joa-quim** [comment]
> Why can't -Eregion be used with -R or -M? I don't understand.

That's where this all started. Because in cases where the region is nor supported by a code list it crashes GMT, and I don't have the patience nor time to fix it at the very low level.

**Comment by anbj** [comment]
Ok, thanks. So it *should* work, but it crashes for some reason.

**Comment by anbj** [comment]
Got it, thanks.

**Comment by anbj** [comment]
And now my command works again (plotting custom codes).

**Comment by PaulWessel** [comment]
Not sure what this means:

```
gmt coast -Enato -pdf test
-R1483228800/1514764800/10000/40000
```

**Comment by joa-quim** [comment]
That's some pscoast joke. You don't have the Andreas custom collection where he's is playing that old game that I forgot the name right now.

**Pull request merged**
