### PR TITLE
Fix text manpage

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by seisman** [comment]
Looks good to me. It's not implemented, right?

**Comment by PaulWessel** [comment]
No, busy at the moment with cpt stuff, but I can do this in a bit.

**Comment by PaulWessel** [comment]
Just implemented it (not tested but seems benign enough).  Perhaps you can fix docs?

**Comment by seisman** [comment]
Since this is a breaking change (although backwards compatible), I changed the base branch to master.

**Pull request merged**
