### PR TITLE
Remove animation cmake target

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR removes the animation build step from the docs workflow and fixes the removal of the animations cmake target.

Fixes #

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by meghanrjones** [comment]
@seisman, do you think we still need the animations target or should we remove it completely from `doc/examples/CMAKELists.txt`, `cmake/ConfigUserAdvancedTemplate.cmake`, `doc/examples/animate.in`, and `MAINTENANCE.md`?

**Comment by seisman** [comment]
Considering that running each animation may take hours, I believe no one will run `make animation` to run all animations. So it's safe to remove the animation target.

**Review by PaulWessel — APPROVED** [review]

**Comment by PaulWessel** [comment]
This all looks good to me.  How can I test it locally? Has it been tested by the CI?

**Comment by meghanrjones** [comment]
> This all looks good to me. How can I test it locally? Has it been tested by the CI?

I tested it locally by building gmt and the docs. Usually the CI only runs the docs workflow on merged PRs, if you want I could temporarily edit https://github.com/GenericMappingTools/gmt/blob/cmake-animate/.github/workflows/docs.yml to get the docs workflow to run on this pull request.

**Pull request merged**
