### PR TITLE
Special case to find the gs executable full name from within Julia artifacts

### PR DESCRIPTION
**Pull request by joa-quim**
In Julia when using the precompiled Artifacts, the Ghost is also shipped with but when gmt_init makes calls to psconvert it doesn't set -G with the path to the Ghostscript_jll executable and those processes fail (mostly modern mode stuff). The solution is to try to read the gs path from ~/.gmt/ghost_jll_path.txt

This code should only be executed by binaries created with Julia's BinaryBuilder.

### CODE REVIEW

**Review by PaulWessel — COMMENTED** [review]
I think the add_definition statements all go into cmake/ConfigUsersAdvancedTemplate etc and not in CMakeLists.txt.  That would be very unusual.  Please move it there and update your copy of the template.

**Comment by joa-quim** [comment]
The only other place where the ``add_definition`` statement can go is to ``ConfigDefault.cmake``. The *templates* are just indications and rely on a ``ConfigUser.cmake`` but for builds that don't use a ``ConfigUser.cmake`` like GMT Julia artifact
https://github.com/boriskaus/Yggdrasil-1/blob/4c4171e0c7df698870ffe00403faa6b7c383c97b/G/GMT/build_tarballs.jl
we need something that can be specified on the ``cmake ... `` command line.

Not sure that ``ConfigDefault.cmake`` is particularly more appropriate for this default (non)-setting than ``CMakeLists.txt`` but don't care either.

**Comment by PaulWessel** [comment]
Put it in the Default file then

**Review by PaulWessel — APPROVED** [review]

**Comment by joa-quim** [comment]
OK, but let's not merge this until it proves useful. Creating and testing those *Artifacts* is far from trivial.

**Pull request merged**
