### PR TITLE
Make table for format geo out

### PR DESCRIPTION
**Pull request by anbj**
Make table for format geo out

### CODE REVIEW

**Comment by PaulWessel** [comment]
Hi @seisman, might you be able to cherry-pick the non-6.2 stuff from this commit? I think @anbj built this patch from master.

**Comment by seisman** [comment]
I think I can't. @anbj may not tick the "Allow maintainers to edit" checkbox when he submitted the PR, so I can't make changes to his branch/PR.

**Comment by PaulWessel** [comment]
OK, perhaps @anbj and delete this PR and implement the table in the 6.1 branch and resubmit.

**Comment by seisman** [comment]
He can do a rebase or a cheery-pick if he knows how.

**Comment by anbj** [comment]
I’ll resubmit to the 6.1 branch.

**Pull request closed without merging**
