### PR TITLE
Let mapproject also find encompassing rectangular regions for non-oblique projections

### PR DESCRIPTION
**Pull request by PaulWessel**
See this [forum post](https://forum.generic-mapping-tools.org/t/finding-the-rectangular-domain-that-covers-an-oblique-area/2872) for background.  What is needed is **-We** or **-WE**, hereby implemented.  Now, @anbj can run

`gmt mapproject -JS36/90/30c -R-15/60/68/90 -WE`

and get his

`-R-1.852421104674526/62.33269965938534/126/80.96267731894207+r`

### CODE REVIEW

**Comment by anbj** [comment]
This is great Paul, thanks alot.

I find it strange that I'm the first one(?) to nag enough about this to get it implemented. Guess confusion can sometimes lead to great things.

**Comment by anbj** [comment]
Note to self and a 'fun' observation; I see that the rounding off is different between the two methods

```
-R-1.85242110467/62.3326996594/126/80.9626773189+r             # from gmt mapproject -JS36/90/30c -R-15/60/68/90 -Wn0/0 and gmt mapproject -JS36/90/30c -R-15/60/68/90 -Wn1/1
-R-1.852421104674526/62.33269965938534/126/80.96267731894207+r # from gmt mapproject -JS36/90/30c -R-15/60/68/90 -WE
```

**Comment by PaulWessel** [comment]
Sometimes one finds oneself on a train with nothing to do but hack away.

**Comment by PaulWessel** [comment]
> Note to self and a 'fun' observation; I see that the rounding off is different between the two methods
> 
> ```
> -R-1.85242110467/62.3326996594/126/80.9626773189+r             # from gmt mapproject -JS36/90/30c -R-15/60/68/90 -Wn0/0 and gmt mapproject -JS36/90/30c -R-15/60/68/90 -Wn1/1
> -R-1.852421104674526/62.33269965938534/126/80.96267731894207+r # from gmt mapproject -JS36/90/30c -R-15/60/68/90 -WE
> ```

This is because the -Wn method involves a multiplication of the rectangular extent by the factor "1" which in a computer is not 1 but perhaps 1 + 2e-12 and hence that extra multiplication will mess with insignificant digits down the line.

**Comment by anbj** [comment]
Thanks!

**Pull request merged**
