### PR TITLE
New FindNETCDF.cmake that works with MinGW (ours doesn't)

### PR DESCRIPTION
**Pull request by joa-quim**
This file is in fact from GDAL and lets the building with MinGW ... fail later but from another reason.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Couple of issues I noticed:

1. During the config I got these:

```
CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (NetCDF)
  does not match the name of the calling package (NETCDF).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindNETCDF.cmake:192 (find_package_handle_standard_args)
  src/CMakeLists.txt:139 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

```
2. From yesterday's macro fix I think some parenthesis are in order to avoid this warning:

```
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/src/grdview.c:994:22: warning: '&&' within '||' [-Wlogical-op-parentheses]
                if (Ctrl->G.n == 1 && gmt_M_file_is_image (Ctrl->G.file[0]) || Ctrl->G.is_mem_image) {
                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/src/grdview.c:994:22: note: place parentheses around the '&&' expression to silence this warning
                if (Ctrl->G.n == 1 && gmt_M_file_is_image (Ctrl->G.file[0]) || Ctrl->G.is_mem_image) {
                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

```

**Comment by joa-quim** [comment]
Hmm, I had to rename the file from ``FindNetCDF`` to ``FindNETCDF`` but since Win is case insensitive don't know what really happened. But yes, now that you mention it I also see that message.

Regarding the macro, you can't be on the right branch because the ``G`` member ``is_mem_image`` is gone.

**Comment by joa-quim** [comment]
OK, changed ``NetCDF`` to ``NETCDF`` and the warning is gone.

**Review by PaulWessel — APPROVED** [review]
Possible, but I did pull your PR but if still there we can do later. Bedtime for old folks

**Pull request merged**
