### PR TITLE
Use MAP_SYMBOL_PEN_SCALE instead of MAP_STROKE_WIDTH

### LINKED ISSUE #7788: Treat stroke-symbols as other symbols unless -W is set
**Description of the desired feature**

It has annoyed me for some time that using symbols like cross, dash, etc., i.e., just line features, requires **-W** to set the pen thickness, making it very complicated to have variable pen widths.  Also, color is not set by **-G** as for other symbols but taken from the pen.  That color could come from a z/cpt lookup if **-W+c** is given.  Etc.  So while they are symbols they re second-class citizens in many ways.

Because of history an upgrade needs to be backwards compatible.  I think this is:

- If **-W** is used to set pen with constant color or variable via **-W+c** we honour that as the current solution as backwards compatibility.
- If _no_ **-W** then stroke symbol pen width is` f * symbol_size`, and if **-G** is set we set the pen to that color (same if z/cpt lookup)

This would allow `-Sx14p -Gred` to draw a red cross with pen width `f *size` and `-Sx14p -Ct.cpt` will do the same `f * size` but with pen color set via z/cpt.

So what is a reasonable _f_?  Here are three candidates (ignore the other but reported in #7787)  - I think going beyond this range gets odd:  Please give your votes:

**Note:** As they say, _different strokes for different blokes_, one could also entertain a new GMT defaults **MAP_STROKE_WIDTH** that could default to our preferred choice but the users could override it for some project.

line_symbols_10

line_symbols_15

line_symbols_20

### PR DESCRIPTION
**Pull request by PaulWessel**
See #7788 for discussion at end.  Note the internal variable is _map_stroke_width_. Two questions:

1. Rename _map_stroke_width_ to _map_stroke_factor_
2. Consider SCALE instead of FACTOR?

Not sure what is best but will go with the flow of comments. Closes #7788.

### CODE REVIEW

**Comment by remkos** [comment]
I'm fine with FACTOR.

**Review by remkos — APPROVED** [review]

**Comment by joa-quim** [comment]
Can we drop the `STROKE`? The variable name is very long and will look ugly if used in command with the ``--`` mechanism. And many may think the symbol had and hart attack 😄

**Comment by remkos** [comment]
> Can we drop the `STROKE`? The variable name is very long and will look ugly if used in command with the `--` mechanism. And many may think the symbol had and hart attack 😄

It's true that this would be getting long. But `MAP_SYMBOL_FACTOR` is not very clear, is it? It would suggest some dependent scaling of the whole symbol. If you want to avoid STROKE, it ought probably be `MAP_SYMBOL_PEN_FACTOR`.
But in that case, I start to feel with @PaulWessel that it should be `MAP_SYMBOL_PEN_SCALE`.

Look @joa-quim : I saved just 3 characters 😄. It is shorter than many of the others that we have, e.g.: `MAP_GRID_CROSS_SIZE_SECONDARY`

**Comment by joa-quim** [comment]
I prefer `MAP_SYMBOL_PEN_SCALE` to `MAP_SYMBOL_PEN_FACTOR`, and I definitely prefer `PEN` to `STROKE` and not because it's 3 chars shorter but because the meaning is much more clear (no coronaries involved).

**Comment by seisman** [comment]
Do we really need the new default MAP_SYMBOL_STROKE_FACTOR? It's easy to change the scale via the **-W** option so I feel the new default will be rarely used.

**Comment by remkos** [comment]
@seisman : You can set the pen width with -W, but that would then apply to any size. The thing is that Paul wanted to assure that if someone did not supply -W, some pen width would be set automatically. For example `-Sx30p -Gred` should automatically result in `-Sx20p -Gred -W3p`, assuming a scale factor of 0.15 (15%).

But in any case you are correct: it would be a barely used setting.

**Comment by PaulWessel** [comment]
I aded WIP until we have a solution.  Just so we are on the same page.  Unless MAP_SYMBOL_STROKE_FACTOR is set to 0, we do

`GMT->current.setting.map_stroke_width * S.size_x * PSL_POINTS_PER_INCH`

So the pen thickness does not enter I think, @seisman ? The whole point was to scale the pen to a fraction of symbol size.  Adding -W4p makes all symbols fat.

**Comment by seisman** [comment]
> The whole point was to scale the pen to a fraction of symbol size. Adding -W4p makes all symbols fat.

That makes sense to me now.

> If you want to avoid STROKE, it ought probably be `MAP_SYMBOL_PEN_FACTOR`

My first impression about `MAP_SYMBOL_PEN_FACTOR` is that it is applied to all symbols like circles.

**Comment by PaulWessel** [comment]
Must say **MAP_SYMBOL_PEN_SCALE** is not bad: Avoids cardiac arrests and shaves a few letters.

**Comment by remkos** [comment]
I agree: RTFM.

**Pull request merged**
