### PR TITLE
Let grdimage share -T with grdview

### PR DESCRIPTION
**Pull request by PaulWessel**
This PR is creating a function of out **grdview -T** so it can be called from grdimage as well as **grdview**.  We can consider extending this to handing images (which **grdimage** may be fed) but for **now** it is like **grdview -T.**

Tested on @anbj script and seems to work fine - no test issues.  However, need @joa-quim to try this from Julia and passing memory since it is at least possible that something different needs to be done when I call `goto basemap_and_free` he end.

### CODE REVIEW

**Review by joa-quim — APPROVED** [review]
No problems from the Julia side.

**Comment by anbj** [comment]
Fantastic - thank you Paul!

Just a PS: Skip nodes with NaN/NaN values transparent: ``-Q`` has no effect it ``-T`` is used, and basically replaced with ``T+s``. Worth noting in the docs?

**Comment by anbj** [comment]
One more note: ``-T+oblack+s -t50`` makes the cells transparent, as expected. ``-T+oblack@50+s -t50`` makes nothing transparent ('cancels' the ``-t50``). I don't know if ``-T+oblack`` should even accept a ``@50``. Just testing!

**Comment by PaulWessel** [comment]
You could see if #7322 makes things more stable?

**Comment by anbj** [comment]
``-T+oblack+s -t40`` - works as expected
These do not;
``-T+oblack@20+s -t50``:

tell-antall-jordskjelv-i-noder

``-T+oblack@20+s``:

tell-antall-jordskjelv-i-noder

**Pull request merged**
